### ISSUE TITLE
WebSocket ZMQ gateway architecture recommendations

### ISSUE THREAD

**Issue by chrgrd** [boostorg/beast#1001]
Hi, 

First of all, kudos to @vinniefalco, boost/beast is quite impressive! 

I am looking for recommendations to implement a WebSocket ZMQ gateway using boost/beast.
For starting point, I used [boost/beast 1.66 websocket example](http://www.boost.org/doc/libs/1_66_0/libs/beast/example/websocket/server/async/websocket_server_async.cpp) 

I plan to augment the demo with a zmq socket listener and forward incoming messages to the websocket.   
I am contemplating the following options
- integrate zmq using boost asio library  
- leverage [azmq](https://github.com/zeromq/azmq)

Any recommendations? 

Thanks in advance.

**Comment by rodgert** [comment]
I can't comment on the specifics of Beast, but, as the author of azmq, I
don't know of any reason why it shouldn't work, and I would be happy to
help make it work for this use case.

I have separate, longer term project going on to re-implement zmq's framing
protocol and basic handling for zmq sockets directly on Asio, but it's far
from ready for use.

**Comment by chrgrd** [comment]
Thank you @rodgert, much appreciated. 
Stay tuned.

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by chrgrd** [comment]
Yes. I don't have the specifics at the task has been re-assigned but we were able to integrate ZMQ with Beast
