### ISSUE TITLE
Multiple websocket instances can not exist in a process

### ISSUE THREAD

**Issue by lls2wow** [boostorg/beast#1003]
Hi , @vinniefalco 
      I found that if multiple websocket client instances exist in one process. All instance can write message to server , but only one instance can receive message from server. Is there something I did not notice? 
      Note： Every instance owned a io_service. And I Start ios in a single thread like this ：
      'thr_ = boost::make_shared<boost::thread>(boost::bind(&boost::asio::io_service::run, &ios_));'

      Could you give me some advices thank you?

Br linsong

**Comment by lls2wow** [comment]
I Used the websocket async mode

**Comment by lls2wow** [comment]
I handled read one msg from server and arrange next read task immediately.

```
void wssession::handle_read(const boost::system::error_code& error, size_t bytes_transferred)
{
	//std::cout << "handle_read" << std::endl;
	if (!error)
	{
		boost::ignore_unused(bytes_transferred);

		sig_packet( getStrFromMultiBuffer(), bytes_transferred);

		buffer_.consume(buffer_.size());
		socket_.async_read(buffer_,
			boost::bind(&wssession::handle_read, shared_from_this(),
				boost::asio::placeholders::error,
				boost::asio::placeholders::bytes_transferred));
	}
	else
	{
		do_close();
	}
}
```

**Comment by vinniefalco** [comment]
You can have as many websocket streams in the same process as you like, and they will all be able to send and receive messages. You do not need one `io_service` per stream, you can use a single `io_service` for your process. They will all receive messages, so I'm not sure what problem you're having.

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by vinniefalco** [comment]
It looks like there is nothing actionable here so I'll go ahead and close this issue. If you have another problem or question feel free to open a new issue - thanks!
