### ISSUE TITLE
`basic_flat_buffer` lacks `reserve` method

### ISSUE THREAD

**Issue by LeonineKing1199** [boostorg/beast#1007]
```
    return (std::min<std::size_t>)(
        (std::max<std::size_t>)(512, buffer.capacity() - size),
        (std::min<std::size_t>)(max_size, limit));
```

Buffer capacity is used to decide how much to read by `detail::read_some_op`. As a feature request, it'd be useful to be able to control the capacity of `basic_flat_buffer`.

**Comment by vinniefalco** [comment]
This should be in the master branch now
