### ISSUE TITLE
Example http-server-coro should have or logic not and when validating verb get or head

### ISSUE THREAD

**Issue by jdmairs** [boostorg/beast#1009]
https://github.com/boostorg/beast/blob/908f84cb3c023ed7c5bd19e2e5283d3218a6d820/example/http/server/coro/http_server_coro.cpp#L149

**Comment by vinniefalco** [comment]
You think it should read this way?
```
    if( req.method() != http::verb::get ||
        req.method() != http::verb::head)
```
won't that always be `true`?

**Comment by jdmairs** [comment]
Sorry that's what I thought problem was!!!  Just discovered in debugger I was wrong.  Great stuff here.
