### ISSUE TITLE
how to get peer's certificate when ssl

### ISSUE THREAD

**Issue by mozeat-sun** [boostorg/beast#1017]
hi vinnie
    i develop a https server which needs to store peer's cert and trustchain info when ssl, where i did not find any method to get them from ssl::context ,is there any way to achieve ?

PLEASE DON'T FORGET TO "STAR" THIS REPOSITORY :)

If you rather keep your project secret, feel free
to email the author at `<vinnie.falco@gmail.com>`; any
private correspondence is treated as confidential.

When reporting a bug please include the following:

### Version of Beast

You can find the version number in the file `<boost/beast/version.hpp>`,
or by using the command "git log -1" in the local Beast repository
directory.

### Steps necessary to reproduce the problem

A small compiling program is the best. If your code is
public, you can provide a link to the repository.

### All relevant compiler information

If you are unable to compile please include the type and
version of compiler you are using as well as all compiler
output including the error message, file, and line numbers
involved.

The more information you provide the sooner your issue
can get resolved!

**Comment by vinniefalco** [comment]
If the `ssl::context` interface does not have the functionality you need, there is always the ability to get the native SSL handle and interact directly with OpenSSL.

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by vinniefalco** [comment]
Validation of SSL certificates is the responsibility of Asio not Beast, so I'll go ahead and close this issue. Feel free to open a new one if you have questions or problems!
