### ISSUE TITLE
std::function< response(request) > based on send_lambda from http_server_coro.cpp

### ISSUE THREAD

**Issue by jdmairs** [boostorg/beast#1025]
It appears that the send_lambda that passed into handle_request can accept any response.  Meaning a response with string_body or empty_body or file_body etc.  

I am trying to store a std::functional< beast::response< any body > ( beast::request<http::string_body>)>

I'm calling this std::functional my "request handler".  I'm storing a bunch of them in a tuple and calling it my router.  All this is motivated/inspired from the very fine cppcon2017 "Using Functional Programming Patterns to build a clean and simple HTTP routing API"

Any help or examples on how to write a function, functor, lambda etc that can return "any type of body_type"  response would be appreciated.  

If I should have sent this request through boost mailing list I apologize.

**Comment by vinniefalco** [comment]
>If I should have sent this request through boost mailing list I apologize.

GitHub issues is fine, thanks for asking!

>Any help or examples on how to write a function, functor, lambda etc that can return "any type of body_type" response would be appreciated.

Phew, that's a tall order. I guess you need to type-erase the **Body**. You would need to implement your own **Body** type which stores a type-erased reference to the original body. And you would need to implement a type-erased **BodyWriter** for it. These concepts are well specified:

http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/concepts/Body.html
http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/concepts/BodyWriter.html

There is also my CppCon 2017 presentation which will help you understand these concepts:

https://www.youtube.com/watch?v=WsUnnYEKPnI

Where you will have a bit of trouble is the type-erasing of the **ConstBufferSequence** which the **BodyWriter** returns to the stream algorithm. You'll have to allocate memory for that. In fact you'll have to allocate a few pieces of memory to fully type-erase the body.

I can help if you have specific questions.

**Comment by jdmairs** [comment]
Thanks for the quick response.  I did watch Making Classes great again...I've been mumbling down the hallway, "All problems can be solved by another level of indirection."

Since I'm not sure what type-erase means nor ever done one I'm starting to feel this ship listing to port.  

John

**Comment by vinniefalco** [comment]
Well `std::function` represents a type-erased function. You construct it with a particular type and yet the `std::function` template parameter list does not name that type. Because it is erased :) That help?

**Comment by jdmairs** [comment]
maybe there is a baby step pragmatic way where I return a tuple or variant of "bodies" until I understand type erasure better.

**Comment by jdmairs** [comment]
I realized in the end...all my responses are string responses.  Even the file_body turns into a bunch of bytes which can be stored in string_body.

Thanks again and hope to hear you on cppcast again.

**Comment by zlojvavan** [comment]
what about ::TransmitPackets?

**Comment by vinniefalco** [comment]
>what about ::TransmitPackets?
Interesting, but beast uses `::TransmitFile`

**Comment by zlojvavan** [comment]
I know it does for sending files while TransmitPackets is intended for optimized sending of memory buffers

**Comment by vinniefalco** [comment]
Is there anything actionable in this issue or is it resolved?

**Comment by jdmairs** [comment]
I cannot access github from work right now but it can be closed.

Thanks.

**Comment by vinniefalco** [comment]
Thanks, I'll go ahead. Feel free to open new issues as needed.
