### ISSUE TITLE
Enhansement request to http_server_async.cpp

### ISSUE THREAD

**Issue by carolinebeltran** [boostorg/beast#1040]
This demo demonstrates how to serve files but I would like the modification to handle my own dynamically generated result.

**Comment by vinniefalco** [comment]
Sorry, I pressed Edit instead of Comment. If you could please Open a new issue and repeat your question I will answer it correctly

**Comment by vinniefalco** [comment]
>This demo demonstrates how to serve files but I would like the modification to handle my own dynamically generated result.

The servers already do that by returning error responses, for example:
https://github.com/boostorg/beast/blob/fc187257c300301e616c61d11baaee79072eef6e/example/advanced/server/advanced_server.cpp#L117

To return your own generated content just declare the response to use the `http::string_body` type, fill in the object including the body, call `prepare_payload`, and then write it. Should be very simple.

**Comment by carolinebeltran** [comment]
Thank you for responding Vinnie.  I actually took an approach similar to **http_server_small.cpp** demo; it appears to obtain posted form data correctly:

`	if (req.method() == http::verb::post)
	{
		std::cout << req.body() << std::endl;  // firstname=Mickey&lastname=Mouse

		http::response<http::dynamic_body> res;
		res.result(http::status::ok);
		res.set(http::field::server, BOOST_BEAST_VERSION_STRING);
		res.set(http::field::content_type, "text/html");
		boost::beast::ostream(res.body())
			<< "<html>\n"
			<< "<head><title>HTTP POST response</title></head>\n"
			<< "<body>\n"
			<< "<h1>hello world</h1>\n"
			<< "</body>\n"
			<< "</html>\n";

		res.content_length(res.body().size());

		res.keep_alive(req.keep_alive());
		return send(std::move(res));
	}
`
Then below I use your **http_server_async.cpp** code to handle GET/HEAD methods.  Does this look correct to you?  And secondly, I am assuming that we are completely responsible for handling all form, URL and cookie parsing.  Is this correct?

**Comment by carolinebeltran** [comment]
Thank you for your comments, I have a pretty good understanding how I can handle dynamic content now.
