### ISSUE TITLE
How to send binary data to server

### ISSUE THREAD

**Issue by lls2wow** [boostorg/beast#1045]
Hi ,@vinniefalco
    I`m not familiar how to send the binary data to server.

    I test send a byte array to server like this：

```
    BYTE arrOutput[] = { 0x00, 0x00, 0x00, 0xAA, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7B, 0x22, 0x70, 0x72, 0x6F};

    ......
    ......
    		// Send the message
		ws_.async_write(
			boost::asio::buffer(arrOutput,sizeof(arrOutput)),
			std::bind(
				&session::on_write,
				shared_from_this(),
				std::placeholders::_1,
				std::placeholders::_2));
```

      But always generate the error ： 
      
      **read: websocket connection failed due to a protocol violation**

      Is that I wrap the buffer in a wrong way?

Br
Lv

**Comment by lls2wow** [comment]
I use the websocket async demo. Just modified the send content from string to BYTE array

**Comment by lls2wow** [comment]
```
	explicit
		session(boost::asio::io_context& ioc)
		: resolver_(ioc)
		, ws_(ioc)
	{
		ws_.binary(true);
	}
```

I add this code : 

`ws_.binary(true);`

it works ok .

**Comment by lls2wow** [comment]
and another question how to convet the received buffer data to BYTE array ?

Like this ：

```
	void on_read(
			boost::system::error_code ec,
			std::size_t bytes_transferred)
	{
		boost::ignore_unused(bytes_transferred);

		if (ec)
			return fail(ec, "read");

		std::cout << text_ << " : " << boost::beast::buffers(buffer_.data()) << std::endl;

                BYTE arraydata[] = **SomefunctionToByteArray**(boost::beast::buffers(buffer_.data()) );
         }
```

Br lv

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by lls2wow** [comment]
I want copy these beast::buffers_front(buffer_.data()) `s  data to BYTE output[] ;  How to do it ?

**Comment by vinniefalco** [comment]
Use `boost::asio::buffer_copy`:
http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/buffer_copy.html

**Comment by lls2wow** [comment]
Hi @vinniefalco  ， I`m not familiar  with beast buffer (like flat_buffer multi_buffer). 

I tried these code 
```
char* tempchar = new char[bytes_transferred];
boost::asio::buffer_copy(tempchar, buffer_, bytes_transferred);
```

but the second line can`t compile. 

It notice need 7 parameter.   
buffer_ is flat_buffer type.

**Comment by vinniefalco** [comment]
```
...
boost::asio::buffer_copy(tempchar, buffer_.data(), bytes_transferred);
```

Consider reading the documentation:
http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/overview/core/buffers.html
http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/ConstBufferSequence.html
http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/MutableBufferSequence.html
http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/concepts/DynamicBuffer.html

**Comment by lls2wow** [comment]
Thank you very much . So sorry to trouble you with this simple question. @vinniefalco 

But the  code
`boost::asio::buffer_copy(tempchar, buffer_.data(), bytes_transferred);`

can`t compile either. I `ll study the buffers more from your advised web

**Comment by vinniefalco** [comment]
sorry, `tempchar` is not a **MutableBufferSequence**. It should read:
```
...
boost::asio::buffer_copy(boost::asio::buffer(tempchar, bytes_transferred),
    buffer_.data(), bytes_transferred);
```

**Comment by lls2wow** [comment]
It works good , Thank you @vinnie!

**Comment by Gadamatik** [comment]
Hi @vinniefalco, Thanks so much, this post help me too... 

By the way, you did a great work on boost::beast... In the future, it will be better to make 2 books: 1 for beginners in networking and second for advanced (I mean really advance)... I don't know if my suggestion is welcome...

Thanks again.
