### ISSUE TITLE
websocket::detail::mask_inplace() needs a test for split message

### ISSUE THREAD

**Issue by vchang-akamai** [boostorg/beast#1061]
I stumbled across a weird websocket message corruption issue, and I think there might be a bug in websocket::detail::mask_inplace(). I'm using top of develop branch.

It was triggered when my server was reading an incoming message that was fragmented in multiple parts. The first part was 291 bytes, which when modulo'd 4, is 3.  

This first fragment was masked properly, but subsequent fragments were mangled. (I also had another nearly identical incoming message, but it was fragmented differently and was not mangled.)

The original mask key was: b7 00 bb 51

The last 3 bytes were XOR'd against b7 00 bb.  Therefore, the next fragment should be masked starting with 51, so the modified key should be 51 b7 00 bb.

However, instead, the modified key was 00 bb 51 b7

I made this modification:

    {
        for(std::size_t i = 0; i < n; ++i)
            p[i] ^= mask[i];
        rol(key, /*4 - */ n);
    }

and it seemed to work.  Or I suppose you could also substitue rol() with ror().

**Comment by vinniefalco** [comment]
This code is supposed to work on both big-endian and little-endian platforms. I am investigating.

**Comment by vinniefalco** [comment]
`rol(key, n)` is correct, thanks for finding this (and just before a release!).

I'll keep this issue open as a reminder to add a test for a split message.
