### ISSUE TITLE
Document requirement of building Boost libraries for CMake on Windows

### ISSUE THREAD

**Issue by mloskot** [boostorg/beast#1064]
The README says:

> To build the documentation, examples, tests, and benchmarks it is necessary to first
> obtain the boost "superproject" along with all of the boost libraries.
> Instructions for doing so may be found on the Boost Wiki. 

The wording _obtain the boost "superproject" along with all of the boost libraries_  is insufficient in the context of using the CMake configuration on Windows which does not build any of the Boost libraries, dependencies required by Boost.Beast, unlike the Boost.Build setup.

The "boost libraries" does not necessarily mean building the binary libraries.

My suggestion is to complete the sentence this way:

> first obtain the boost "superproject" along with sources of all of the Boost libraries, then run `b2` command to build the Boost libraries.

BTW, boost should read Boost, it's a name.

**Comment by vinniefalco** [comment]
Seems reasonable, have you considered submitting a pull request?

**Comment by mloskot** [comment]
Yes, of course, here it goes #1067
