### ISSUE TITLE
get ec.message() variable from another class

### ISSUE THREAD

**Issue by Ludea** [boostorg/beast#1066]
Hello,

I follow the http over ssh examples.
But, for my app, I have to get the value returned by the fail function.
So I change a little the code, I add `fail` into request class (public), and a std::string variable.
The std string get the error message. 
When I call the string into another class:
```
request* req;
printf(req->mystringvalue); 
```
, there are no values. 
So can I get the error message from another class ?

Thanks !

**Comment by vinniefalco** [comment]
I'm going to need a little more information than that, do you have an example program which I can run that exhibits the behavior you are describing?

**Comment by Ludea** [comment]
Yes sorry .

request cpp
```
void request::fail(boost::system::error_code ec, char const* what)
{
    std::cerr << what << ": " << ec.message() << "\n";
    std::cout<<ec.message()<<std::endl;
    respond = ec.message() ;
}

void request::start_request(char const* host, char const* port, char const* target, int version, std::tring method, std::string body)
{
    boost::asio::io_context ioc;
    ssl::context ctx{ssl::context::sslv23_client};
    std::make_shared<request>(ioc, ctx)->run(host, port, target, version, method, body);
    ioc.run();
}
```

request .h
```
public:
std::string respond;
void fail(boost::system::error_code ec, char const* what);
```

my class which call respond
void connection::server_connect(std::tring host, std::string port, std::string target, int version, std::string method, std::string body)
{
    http->start_request(host, port, target, version, method, body);
}

std::string connection::getHttpResponseBody()
{
    std::cout<<"test : "<<http->respond<<std::endl;
    return (http->respond);
}
```

.h
```
private:
    request *http;
````

**Comment by Ludea** [comment]
If I initialize my string var into constructor, i can get his values.
But no ec.message() values

**Comment by vinniefalco** [comment]
Are you linking dynamically to Boost.System? Perhaps this is a problem with a mismatch between the shared library version and the header file version. Try linking everything statically.
