### ISSUE TITLE
How to connect to server using IP address not by domain name?

### ISSUE THREAD

**Issue by lls2wow** [boostorg/beast#1072]
Hi @vinniefalco ,

     I tried the websocket sync demo using the domain name 'echo.websocket.org' it works ok. 

    I tried the IP address '174.129.224.73' (It`s domain echo.websocket.org `IP address ).  And it failed for reason : hand shake failed.
   

    I want to know how to connect to server using websocket by (ip address, port , target)

**Comment by vinniefalco** [comment]
Has this been resolved?
