### ISSUE TITLE
websocket cannot connect to www.bitmex.com

### ISSUE THREAD

**Issue by kylejan** [boostorg/beast#1081]
bitmex websocket api: https://www.bitmex.com/app/wsAPI

use the websocket_client_async_ssl example to start the connection to www.bitmex.com

but it always handshake failed. it returns "unknown protocol" or "wrong version number" error message

**Comment by kylejan** [comment]
how  to get the http headers before async_handshake in beast?

**Comment by vinniefalco** [comment]
Use the overload of `async_handshake` which fills out the response:
http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/using_websocket/handshaking_clients.html#beast.using_websocket.handshaking_clients.filtering
http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/async_handshake/overload2.html

**Comment by kylejan** [comment]
oh sorry. i am not describe the problem clearly. i fail on the websocket::stream::next_layer_type::async_handshake, which use to do the ssl handshake.
finally i fail on the ssl handshake

**Comment by vinniefalco** [comment]
Oh...well, I have no idea why that would fail. Perhaps contact BitMEX? Or look up common reasons why SSL handshakes produce those errors:
http://blog.techstacks.com/2010/03/3-common-causes-of-unknown-ssl-protocol-errors-with-curl.html

**Comment by kylejan** [comment]
gotcha, thx!
