### ISSUE TITLE
Does beast integrate with boost::fibers?

### ISSUE THREAD

**Issue by randian** [boostorg/beast#1085]
I haven't seen any examples using Beast with fibers. I've used Beast with coroutines, and the fibers API is pretty similar. A different future type though so the use_future tag to make the Beast/asio APIs return futures can't work with fibers and the fibers documentation offers little help on how to write your own tag (or really, help on anything related to asio and fibers). Fibers use a different yield type too (boost::asio::fibers::yield instead of boost::asio::yield_context).

**Comment by LeonineKing1199** [comment]
Fibers and Asio are tricky. The Fiber docs contain this example: https://www.boost.org/doc/libs/1_66_0/libs/fiber/doc/html/fiber/callbacks/then_there_s____boost_asio__.html
