### ISSUE TITLE
Minor change to example comment

### ISSUE THREAD

**Issue by carolinebeltran** [boostorg/beast#1088]
This is so insignificant but I thought that I'd mention it anyway.  I believe that the comment should read 'relative', not 'absolute'.

```
// Request path must be absolute and not contain "..".
if( req.target().empty() ||
    req.target()[0] != '/' ||
```
The last line of code validates a 'relative' path and fails when an 'absolute' path is received.

Relative path:
/whatever.html

Absolute path:
http://www.example.com/whatever.html

**Comment by vinniefalco** [comment]
The path refers to the filesystem path not the request target. Relative paths are those which either depend on the current directory or have ".." in one or more places. Such paths could be used to escape the configured html root directory and access files to which clients should not have permission.

**Comment by carolinebeltran** [comment]
Thank you for the clarification!
