### ISSUE TITLE
compiler error under advanced_server.cpp:

### ISSUE THREAD

**Issue by bnadem** [boostorg/beast#1090]
wenn compile programm advanced_server.cpp bekom error.n  unter version 1.66
"advanced_server.cpp:254:39: error: no matching function for call to ‘boost::beast::websocket::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp> >::control_callback(std::_Bind_helper<false, void (websocket_session::*)(boost::beast::websocket::frame_type, boost::basic_string_view<char, std::char_traits<char> >), websocket_session*, const std::_Placeholder<
1>&, const std::_Placeholder<2>&>::type)’
                 std::placeholders::_2));"

**Comment by vinniefalco** [comment]
Where did you get the advanced_server.cpp file?

**Comment by bnadem** [comment]
oh thanks fro replay,
i get it from https://github.com/boostorg/beast/tree/develop/example/advanced/server
and have compiled from normal Makefile.

**Comment by vinniefalco** [comment]
You are trying to use the **develop** version of advanced_server.cpp with the Boost 1.66 release, which are two different versions. Please use the advanced_server.cpp which matches the version of Boost you are using: 
https://github.com/boostorg/beast/blob/boost-1.66.0/example/advanced/server/advanced_server.cpp

**Comment by bnadem** [comment]
thanks. for replay es ist work. program run under defined port and docroot (http) , and who is websocket port running!

**Comment by vinniefalco** [comment]
It looks like this issue has been resolved so I'll go ahead and close it, feel free to open new issues as needed!
