### ISSUE TITLE
Autobahn chapter 12.4 fails

### ISSUE THREAD

**Issue by alexhultman** [boostorg/beast#1095]
Many tests of chapter 12.4 fails:

https://vinniefalco.github.io/boost/beast/reports/autobahn/boost_beast_128_async_case_12_4_5.html

Do you have any idea why?

**Comment by vinniefalco** [comment]
Yeah, see: https://github.com/crossbario/autobahn-testsuite/issues/77

**Comment by alexhultman** [comment]
Thanks
