### ISSUE TITLE
Server-sent Events (SSE) with boost/beast as HTML client

### ISSUE THREAD

**Issue by smipi1** [boostorg/beast#1097]
Do you have examples on how to use boost/beast as an HTML client to receive HTML5 Server-sent Events (SSE)?

P.S. @vinniefalco, I could not find any information on this, so I am logging an issue (at least for posterity).

**Comment by vinniefalco** [comment]
I have no idea, it sounds like it is beyond the scope of Beast and has to do with the specifics of HTML5 (which is not covered by the library).

**Comment by smipi1** [comment]
I think it should be doable with an async_read_some with delimiter.

In essence it is an http request that never completes. You get from the event provider target with a Content-Type: text/event-stream. The response has the headers, followed by each event preceded with the text string 'data:'. Events are separated with '\n\n' and are flushed via the socket on a per-event basis. The best explanation (be-it a bit dated) is here: https://www.html5rocks.com/en/tutorials/eventsource/basics/

Do you forsee any problems using boost/beast this way on the client side?

**Comment by vinniefalco** [comment]
>Do you forsee any problems using boost/beast this way on the client side?
It should be possible, read the HTTP header first and then read the body yourself.

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by smipi1** [comment]
You can close it. I will ask the developers to add a writeup to this ticket so others can find the information. It might be interesting to add an example server and client at some point as well.

**Comment by bcs-cmorell** [comment]
> You can close it. I will ask the developers to add a writeup to this ticket so others can find the information. It might be interesting to add an example server and client at some point as well.

Hello, Any update on this type of events and how to handle them(Server/Client Sample). I am currently trying to read data from an open stream and found this thread.

**Comment by dragahassan** [comment]
Finally you can use Beast WebSocket instead of SSE.
