### ISSUE TITLE
HTTP 2.0 support

### ISSUE THREAD

**Issue by smipi1** [boostorg/beast#1098]
Is there work in the pipeline to add HTTP 2.0 support?

**Comment by vinniefalco** [comment]
Eventually

**Comment by smipi1** [comment]
Let me know when, and if you need help.

**Comment by vinniefalco** [comment]
Well we need a header-only codec for decompressing the header fields

**Comment by TechnikEmpire** [comment]
@smipi1 HPACK

**Comment by vinniefalco** [comment]
I no longer believe that Beast will be supporting HTTP/2. It hasn't really been popular, and Google looks like it doesn't support it. Instead they have supported their SPDY and now QUIC, which has been renamed to HTTP/3.

It very much looks like HTTP/2 is dead.
