### ISSUE TITLE
Possible bug in read.ipp read_some_op::operator()

### ISSUE THREAD

**Issue by bebuch** [boostorg/beast#1099]
In very rare cases I run into this BOOST_ASSERT:

https://github.com/boostorg/beast/blob/b4cb4f1fd3d9d1eca90f44e59e1ca0b5260d0c13/include/boost/beast/websocket/impl/read.ipp#L628

`ws_.status` is `status::failed` and I come from:

https://github.com/boostorg/beast/blob/b4cb4f1fd3d9d1eca90f44e59e1ca0b5260d0c13/include/boost/beast/websocket/impl/read.ipp#L422

`ws_.status` was in `L422` and at the beginning of `.operator()` (`L172`) already `status::failed`.

I'm not completely sure it is a bug in Beast or in my own code.

### Version of Beast

```
$ git log -1
commit b4cb4f1fd3d9d1eca90f44e59e1ca0b5260d0c13
Author: Vinnie Falco <vinnie.falco@gmail.com>
Date:   Thu Mar 22 20:14:16 2018 -0700

    Set version to 167
```

### Steps necessary to reproduce the problem

The bug is trigged by a penetration test of my library based on Beast. I create a WebSocket Server and after that 50 threads every creating a client that connects to the server. Client and Server start to ping pong text messages and the clients a destroyed after a random time in the range of 0 to 100 ms.

This process is repeated in a loop. I run into the bug around every 10 minutes, so it is very rarely and not simple to reproduce. I hope you can give clear a statement (bug in my code or in Beast) by looking into `L422` of `read.ipp`. If not I will provide more information how to compile and debug my code.

### All relevant compiler information

```
$ g++ --version
g++ (GCC) 8.0.1 20180410 (experimental)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

With `BOOST_ASIO_HAS_STD_CHRONO` and `-std=c++14`.

**Comment by vinniefalco** [comment]
Thank you for the detailed report. I am investigating.

**Comment by adrianimboden** [comment]
@bebuch Have you found any workaround in your case?

I think I'm facing the exact same thing. The status is failed also.
It happens since I refactored some server side code.

I use async_read on the reader side and the assert is happening in a test where the client closes the websocket connection. When i use tsan, the error happens almost always.
I added some output to look into it. The socket goes into error state after during the async_read call. Just before calling, the state is open.

@vinniefalco If you have any place where should put some log output, I would be happy to provide you with the output.

My configuration:
* Clang 6.0
* Boost 1.67
* C++17

**Comment by vinniefalco** [comment]
I have studied the code and concluded that the assert is simply wrong. If you remove the assert in your beast implementation file, it should work correctly.

**Comment by adrianimboden** [comment]
I just found out, that the error occurs because i use async_read and async_write without a strand.
Is that basically supported or not?

Are the internals of async_read and async_write supposed to be interleavable?

**Comment by vinniefalco** [comment]
> Are the internals of async_read and async_write supposed to be interleavable?

Far from it! You need either an implicit strand (only one thread calling `io_context::run`) or explicit strand.

The same goes for asio sockets - they are not Thread Safe. Don't confuse thread safety with asynchronous. You cannot access I/O objects like sockets (and correspondingly, websocket streams) from more than one thread simultaneously.

**Comment by adrianimboden** [comment]
I have only one thread calling io_service::run. But the async_write and async_read functions did interleave anyway.

**Comment by vinniefalco** [comment]
> the async_write and async_read functions did interleave anyway.

What does that mean, interleave?

**Comment by adrianimboden** [comment]
Can't the methods interleave, because the coorutine-parts can interleave?

**Comment by adrianimboden** [comment]
I did debug the following scenario:
1. Call async_read
2. Call async_write
3. async_write has an error (broken_pipe, because client disconnected)
4. async_write completion handler reports broken pipe
5. async_read throws the assertion

All of that happens in the same thread.

**Comment by vinniefalco** [comment]
The assertion not valid, you should remove the line from read.ipp.

**Comment by vinniefalco** [comment]
>1. Call async_read
> 2. Call async_write

Are you making these calls from the same thread that is invoking `io_context::run`?

**Comment by adrianimboden** [comment]
Yes, exactly.

**Comment by vinniefalco** [comment]
That should work.

**Comment by adrianimboden** [comment]
Yes, it probably will when I remove the assert. I'll try that now

**Comment by adrianimboden** [comment]
Ok, allright. When I apply the patch from above, everything works as expected. Perfect :smile:

**Comment by vinniefalco** [comment]
This fix will go into 171
