### ISSUE TITLE
How to read post request body as std::string

### ISSUE THREAD

**Issue by snahmad** [boostorg/beast#1106]
### Version of Beast
167

### Steps necessary to reproduce the problem

void process_request(http::request<request_body_t, http::basic_fields<alloc_t>> const& req)
		{
			std::string str = req.
			switch (req.method())
			{
			case http::verb::post:
                                
                              std::string post_body = req.?
				break;
			default:
				break;
			}
		}

**Comment by knejadfard** [comment]
What is the body type of this request?

If the request is of type `http::request<http::string_body>`, then calling the `body()` member function of the request will return a `std::basic_string`:
```std::string body = req.body();```

A more real-world scenario would be to read the header of the request first, determine its content type, and then read the body accordingly. I found [this example](https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/more_examples/change_body_type.html) to be quite useful for scenarios like this.

**Comment by vinniefalco** [comment]
The type of  `string_response_->body();` will be `std::string`.

**Comment by snahmad** [comment]
I am talking about request body not response body.

**Comment by vinniefalco** [comment]
```
using request_body_t = std::string;
```

**Comment by snahmad** [comment]
Changing the example
//using request_body_t = http::basic_dynamic_body<boost::beast::flat_static_buffer<1024 * 1024>>;
using request_body_t = std::string;

break compilation.

Do you have any example C++ class Http Server with thread to handle both http get file and post

**Comment by vinniefalco** [comment]
No, and if you don't post the output of the compiler which shows the error, I can't help you.

**Comment by snahmad** [comment]
c:\boost_1_67_0\boost\beast\http\parser.hpp(57): error C2338: BodyReader requirements not met
1>c:\boost_1_67_0\boost\type_traits\is_nothrow_move_constructible.hpp(27): note: see reference to class template instantiation 'boost::beast::http::parser<true,http_worker::request_body_t,http_worker::alloc_t>' being compiled
1>c:\boost_1_67_0\boost\optional\optional.hpp(187): note: see reference to class template instantiation 'boost::is_nothrow_move_constructible<T>' being compiled
1>        with
1>        [
1>            T=boost::beast::http::parser<true,http_worker::request_body_t,http_worker::alloc_t>
1>        ]
1>c:\boost_1_67_0\boost\optional\optional.hpp(831): note: see reference to class template instantiation 'boost::optional_detail::optional_base<T>' being compiled
1>        with
1>        [
1>            T=boost::beast::http::parser<true,http_worker::request_body_t,http_worker::alloc_t>
1>        ]
1>c:\users\naeem\documents\visual studio 2017\projects\boost_beast\boost_beast\boost_beast.cpp(110): note: see reference to class template instantiation 'boost::optional<boost::beast::http::parser<true,http_worker::request_body_t,http_worker::alloc_t>>' being compiled
1>c:\boost_1_67_0\boost\asio\use_future.hpp(138): note: see reference to class template instantiation 'boost::asio::use_future_t<std::allocator<void>>::std_allocator_void' being compiled
1>c:\boost_1_67_0\boost\asio\use_future.hpp(146): note: see reference to class template instantiation 'boost::asio::use_future_t<std::allocator<void>>' being compiled
1>c:\boost_1_67_0\boost\beast\core\string.hpp(87): note: see reference to class template instantiation 'boost::basic_string_view<char,std::char_traits<char>>' being compiled
1>c:\boost_1_67_0\boost\beast\http\parser.hpp(66): error C2039: 'reader': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.11.25503\include\xstring(4079): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>c:\boost_1_67_0\boost\beast\http\parser.hpp(66): error C3646: 'rd_': unknown override specifier

**Comment by snahmad** [comment]
Any idea about these compiler errors.

**Comment by snahmad** [comment]
I cannot find any working example Http server which handle http post. get post body as std::string and send back reply.

**Comment by vinniefalco** [comment]
I am so sorry...I gave you incorrect code. This is the correct version:
```
using request_body_t = http::string_body;
```
I tested this in MSVC and it compiled.

**Comment by snahmad** [comment]
ok. working thanks.

**Comment by vinniefalco** [comment]
Glad it works! I'll go ahead and close this since it is resolved, feel free to open new issues as needed - Thanks.

**Comment by Shoaib-Raza** [comment]
Hi,

I am using Boost beast 1.67 version, example Http Server 3.
My problem is that, body variable is missing in Request struct in request.hpp.
How can I get the body as string in Http Server 3 example?

**Comment by vinniefalco** [comment]
That's because you're looking at the Asio examples not the Beast examples.
