### ISSUE TITLE
Workaround for ssl::stream write and async_write slowdown

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1108]
This issue:
https://stackoverflow.com/questions/50026167/performance-drop-on-port-from-beast-1-0-0-b66-to-boost-1-67-0-beast

Could be resolved with an overload of `write` and `async_write` which flattens the serialized message header to a single dynamically allocated piece of memory instead of passing buffer sequences with length greater than one to the underlying SSL stream.

Alternatively, new functions can be provided with different names. Or both.

**Comment by djarek** [comment]
What about a special tag type that wraps the message and allows calling the flattening overload, e.g.
`boost::beast::http::async_write(stream, boost::beast::http::flatten(message), token);`
