### ISSUE TITLE
Emptying thg buffer queue sync

### ISSUE THREAD

**Issue by shovalyechiel** [boostorg/beast#1111]
Hi. I need a websocket use in a not some common way. i need to read SYNC all the messages process each one of them ( individually) and then after the queue is empty do some logic. the problem is a can't find a way to do some read the only block if there is some data. is there a way to set a timeout, or perform a non blocking read?
thanks!

**Comment by vinniefalco** [comment]
Non blocking reads are accomplished by using the asynchronous interfaces. If you want a timeout, use one of the Asio deadline or steady timers.

**Comment by shovalyechiel** [comment]
ok thanks you!
so just to make sure I got it, I can do some BLOCKING read until some multiple message arrives and then set the Asio timeout to zero ?

**Comment by vinniefalco** [comment]
No that's not what I said, you need to use the asynchronous interfaces.

**Comment by shovalyechiel** [comment]
ok I will explore some more. 
thank you !
