### ISSUE TITLE
Recommendations on how to write unit-tests for a beast based server.

### ISSUE THREAD

**Issue by trivigy** [boostorg/beast#1115]
Nothing else to add. Just wanted to start a thread for people to share their structure for writing unit-tests for a beast based server.

**Comment by knejadfard** [comment]
Nicely timed question and answer! I was wondering the exact same thing yesterday!

**Comment by trivigy** [comment]
@vinniefalco any example on how to use that when combining [http_client_async](https://www.boost.org/doc/libs/1_67_0/libs/beast/example/http/client/async/http_client_async.cpp) and [http_server_async](https://www.boost.org/doc/libs/1_67_0/libs/beast/example/http/server/async/http_server_async.cpp). Not to be tooooo specific. :D

Honestly I am just looking for some example of how people actually organize this kind of testing in a `Boost.Units` context

**Comment by vinniefalco** [comment]
What do I for Beast is as follows:

1. Decompose higher level abstractions into their individual parts which use stream algorithms

2. Express stream algorithms using templates and the Asio stream concepts **SyncReadStream**, **SyncWriteStream**, **AsyncReadStream**, **AsyncWriteStream**

3. In a test, invoke the stream algorithm using a `test::stream`:
https://github.com/vinniefalco/beast/blob/f48b9780448d091ffe22f17783143facdfec82e0/include/boost/beast/experimental/test/stream.hpp#L37

4. To exercise all branches in the implementation being tested, instantiate the `test::stream` using a `test::fail_count`:
https://github.com/vinniefalco/beast/blob/f48b9780448d091ffe22f17783143facdfec82e0/include/boost/beast/experimental/test/fail_count.hpp#L21

5. Exercise the implementation inside a loop where the fail counter is incremented until it reaches some upper limit (indicating that the code being tested is incorrect) or until the operation succeeds. Example:
https://github.com/vinniefalco/beast/blob/f48b9780448d091ffe22f17783143facdfec82e0/test/beast/http/write.cpp#L354

6. At this point I look at the code coverage report and write individual functions which exercise any parts of the code that were not reached by the looping approach above. I aim for 100% coverage:
https://codecov.io/gh/vinniefalco/beast/src/v170/include/boost/beast/websocket/impl/close.ipp
