### ISSUE TITLE
http::request docs show some non-request methods

### ISSUE THREAD

**Issue by vchang-akamai** [boostorg/beast#1120]
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/ref/boost__beast__http__request.html

This page shows methods reason(), result(), result_int().  Each of their docs indicate "only available when isRequest == false. ".    Should suppress these non-request methods when generating docs for http::request.

Hmm.. I just checked http::response and saw similar issue with request-only methods (like "target()") showing up in those docs.

**Comment by vinniefalco** [comment]
>Should suppress these non-request methods when generating docs for http::request

Easier said than done. How can I do that?

**Comment by vchang-akamai** [comment]
I don't have any ideas either :-)  I see some of the difficulties involved. This is probably the best compromise in the situation.

**Comment by vinniefalco** [comment]
I agree :)
