### ISSUE TITLE
Add "short read" explanation to documentation

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/beast#1123]
Beast: closing websocket stream throws "short read" exception

Moved from https://svn.boost.org/trac10/ticket/13483

**Comment by vinniefalco** [comment]
In an ideal world, every client and server would gracefully end the SSL session by following the shutdown handshake procedure. Unfortunately, certain companies (cough, Google) can't be bothered with this polite behavior. There are many documented cases of programs which intentionally do not follow the SSL shutdown (such as Chrome). You will need to just ignore this error, or something similar.

The documentation should explain this.

**Comment by vinniefalco** [comment]
This might be fixable actually:
https://github.com/boostorg/beast/issues/38

See also:
https://stackoverflow.com/questions/25587403/boost-asio-ssl-async-shutdown-always-finishes-with-an-error

**Comment by ashtum** [comment]
Addressed in https://github.com/boostorg/beast/commit/094f5ec5cb3be1c3ce2d985564f1f39e9bed74ff
