### ISSUE TITLE
Examples isn't compiling

### ISSUE THREAD

**Issue by yuyaryshev** [boostorg/beast#1130]
### Version of Beast
#define BOOST_BEAST_VERSION 167

### Steps necessary to reproduce the problem
Trying to compile http_server_small.cpp

### All relevant compiler information
The example don't compile. It gives three errors in header files.

The first error - d:\boost\boost\beast\core\detail\ostream.hpp(263)
doesn't seem to be able compile in any C++ environment, because it's really missing template arguments and I just fixed it locally by adding them.

Visual studio 2017 - v171 x64
1>------ Build started: Project: test, Configuration: Debug Win32 ------
1>stdafx.cpp
1>d:\boost\boost\beast\core\detail\ostream.hpp(263): error C2955: 'boost::beast::detail::ostream_helper': use of class template requires template argument list
1>d:\boost\boost\beast\core\detail\ostream.hpp(234): note: see declaration of 'boost::beast::detail::ostream_helper'
1>d:\boost\boost\beast\core\detail\ostream.hpp(264): error C2244: 'boost::beast::detail::ostream_helper<DynamicBuffer,CharT,Traits,true>::ostream_helper': unable to match function definition to an existing declaration
1>d:\boost\boost\beast\core\detail\ostream.hpp(262): note: see declaration of 'boost::beast::detail::ostream_helper<DynamicBuffer,CharT,Traits,true>::ostream_helper'
1>d:\boost\boost\beast\core\detail\ostream.hpp(264): note: definition
1>d:\boost\boost\beast\core\detail\ostream.hpp(264): note: 'boost::beast::detail::ostream_helper<DynamicBuffer,CharT,Traits,true>::ostream_helper(boost::beast::detail::ostream_helper &&)'
1>d:\boost\boost\beast\core\detail\ostream.hpp(264): note: existing declarations
1>d:\boost\boost\beast\core\detail\ostream.hpp(264): note: 'boost::beast::detail::ostream_helper<DynamicBuffer,CharT,Traits,true>::ostream_helper(boost::beast::detail::ostream_helper<DynamicBuffer,CharT,Traits,true> &&)'
1>d:\boost\boost\beast\core\detail\ostream.hpp(264): note: 'boost::beast::detail::ostream_helper<DynamicBuffer,CharT,Traits,true>::ostream_helper(DynamicBuffer &)'

**Comment by snahmad** [comment]
Try removing use of stdafx.h from your .cpp file properties.
