### ISSUE TITLE
std::string_view option

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1133]
It should be possible for users to define BOOST_BEAST_USE_STD_STRING_VIEW or some such, and have beast use `std::string_view` (and `std::basic_string_view`) in `<boost/beast/core/string.hpp>`

**Comment by BitonicEelis** [comment]
Yes, that would be really great!

**Comment by raidenluikang** [comment]
Hi, 

Why std::string_view is not automatic detected ?

https://en.cppreference.com/w/cpp/string/basic_string_view

Standard required [__cpp_lib_string_view >= 201606L ](https://en.cppreference.com/w/cpp/feature_test#Library_features)
