### ISSUE TITLE
More tolerant parsing of CRLF characters in http headers

### ISSUE THREAD

**Issue by beast-lenient-parsing** [boostorg/beast#1138]
In using the beast http handler on a project, we've noticed the tolerance for unrecognized control characters to be rather strict. Specifically, we're seeing the \001 character embedded in some cookies arriving from certain parties, resulting in `bad value` reads from beast.

Other similar http libraries seem to handle these responses.

While it's clear that these characters are not in fact allowed per the RFC for HTTP, I'm curious if there's any plans to make beast more tolerant in it's header parsing?

Here is the relevant code in question, specifically the flow resulting in the `goto found_control`

```
    static
    char const*
    parse_token_to_eol(
        char const* p,
        char const* last,
        char const*& token_last,
        error_code& ec)
    {
        for(;; ++p)
        {
            if(p >= last)
            {
                ec = error::need_more;
                return p;
            }
            if(BOOST_UNLIKELY(! is_print(*p)))
                if((BOOST_LIKELY(static_cast<
                        unsigned char>(*p) < '\040') &&
                    BOOST_LIKELY(*p != '\011')) ||
                    BOOST_UNLIKELY(*p == '\177'))
                    goto found_control;
        }

**Comment by vinniefalco** [comment]
No plans to make the parser relaxed, but you can simply filter the input before passing it to Beast.

**Comment by vinniefalco** [comment]
LOL, what is this, an account just for reporting one issue?
