### ISSUE TITLE
the demo “websocket-client-async-ssl” to get data from  "wss://stream.binance.com:9443/ws/bnbeth@depth"

### ISSUE THREAD

**Issue by weiweiloong** [boostorg/beast#1144]
hello;
        I learn to use “websocket-client-async-ssl” to get data from  "wss://stream.binance.com:9443/ws/bnbeth@depth"

I get the correct data using other websocket client tool but I get nothing form webserver as my code like this:

	auto const host = "wss://stream.binance.com";//
	auto const port = "9443";
	auto const text = "/ws/bnbeth@depth";
    // The io_context is required for all I/O
    boost::asio::io_context ioc;
    // The SSL context is required, and holds certificates
    ssl::context ctx{ssl::context::sslv23_client};
    // This holds the root certificate used for verification
    load_root_certificates(ctx);
    // Launch the asynchronous operation
    std::make_shared<session>(ioc, ctx)->run(host, port, text);

    // Run the I/O service. The call will return when
    // the socket is closed.
    ioc.run();

**Comment by vinniefalco** [comment]
`host` should be `"stream.binance.com"`

**Comment by weiweiloong** [comment]
I did it as your way ,but it output "handshake: The WebSocket handshake was declined by the remote peer";
ws_.async_handshake is faild;
i debug the code find it run this pos..
 void on_handshake(boost::system::error_code ec)
    {
        if(ec)
            return fail(ec, "handshake");
        
        // Send the message
        ws_.async_write( boost::asio::buffer(text_), std::bind( &session::on_write, shared_from_this(), std::placeholders::_1, std::placeholders::_2));
    }

**Comment by weiweiloong** [comment]
I did it as your way ,but it output "handshake: The WebSocket handshake was declined by the remote peer";
ws_.async_handshake is faild;
i debug the code find it run this pos..
void on_handshake(boost::system::error_code ec)
{
if(ec)
return fail(ec, "handshake");

    // Send the message
    ws_.async_write( boost::asio::buffer(text_), std::bind( &session::on_write, shared_from_this(), std::placeholders::_1, std::placeholders::_2));
}

**Comment by weiweiloong** [comment]
hello , i refer to the example: beast\example\websocket\client\sync-ssl
this is my request
I use websocket request "wss://stream.binance.com:9443/ws/bnbbtc@depth"
add certificate or not add a certificate always error : WebSocket upgrade handshake failed
code :

		auto host = "stream.binance.com";
		auto port = "9443";
		auto text = "ws/bnbbtc@depth";
        // The io_context is required for all I/O
        boost::asio::io_context ioc;
        // The SSL context is required, and holds certificates
        ssl::context ctx{ssl::context::sslv23_client};
		std::string filename = "./cacert.pem";
		ctx.set_verify_mode(ssl::verify_none);
		//ctx.load_verify_file(filename);
		
        tcp::resolver resolver{ioc};
        websocket::stream<ssl::stream<tcp::socket>> ws{ioc, ctx};

        // Look up the domain name
        auto const results = resolver.resolve(host, port);

        // Make the connection on the IP address we get from a lookup
        boost::asio::connect(ws.next_layer().next_layer(), results.begin(), results.end());

how could i do ?

**Comment by vinniefalco** [comment]
You did not post all the code, where is the call to `ws.handshake(...)`?

**Comment by weiweiloong** [comment]
:)

**Comment by Rohan0993** [comment]
@weiweiloong You should post your work around to this problem here or some leads for the people who read your post. Could you please post the answer?

**Comment by sergey-at-ark** [comment]
One of the reasons when "The WebSocket handshake was declined by the remote peer" could happen is when request target in async_handshake() is not setup correctly. In Vinnie's demo request target is hard-coded to "/". For the this case it should be "/ws" or something more elaborated depending on the rules set out by stream.binance.com.

**Comment by vinniefalco** [comment]
funds are safu

**Comment by sergey-at-ark** [comment]
I don't know what "funds are safu" means :-)

**Comment by vinniefalco** [comment]
Oh seriously? You're connecting to binance.com and you never heard of "funds are safu?" Check out this video: https://www.youtube.com/watch?v=DelF6zEHXpE

**Comment by sergey-at-ark** [comment]
Cool. Thank you for the link. No, I never used binance.com... It's just I had the same issue with other exchange.

**Comment by ThomasP1988** [comment]
for the people who might come by like me, the problem is (as sergey said) the "/" when you do your handshake, binance doesn't seem to like it. You should add an endpoint here, example: ws_.async_handshake(host_, "/ws/bnbbtc@depth",
                            beast::bind_front_handler(
                                &session::on_handshake,
                                shared_from_this()));
