### ISSUE TITLE
I want to read the data continuously, but error : Error: WebSocket connection closed normally.

### ISSUE THREAD

**Issue by weiweiloong** [boostorg/beast#1152]
hello, first thank you , The previous question is Ok . 
new question:
I want to read the data continuously, but error :
Error: WebSocket connection closed normally.

code: beast/example/websocket/client/sync-ssl/websocket_client_sync_ssl.cpp

		auto host = "stream.binance.com";
		auto port = "9443";
		auto text = "ws/bnbbtc@depth";
        // The io_context is required for all I/O
        boost::asio::io_context ioc;
        // The SSL context is required, and holds certificates
        ssl::context ctx{ssl::context::sslv23_client};
		std::string filename = "./cacert.pem";
		ctx.set_verify_mode(ssl::verify_none);
		//ctx.load_verify_file(filename);
		
        tcp::resolver resolver{ioc};
        websocket::stream<ssl::stream<tcp::socket>> ws{ioc, ctx};

        // Look up the domain name
        auto const results = resolver.resolve(host, port);
		boost::asio::connect(ws.next_layer().next_layer(), results.begin(), results.end());

        // Perform the SSL handshake
        ws.next_layer().handshake(ssl::stream_base::client);

        // Perform the websocket handshake
        ws.handshake(host, "/ws/bnbbtc@depth");

        // Send the message
        ws.write(boost::asio::buffer(std::string(text)));

        // This buffer will hold the incoming message
        boost::beast::multi_buffer b;

        // Read a message into our buffer
        while( 1 )
        {
        	sleep(1);
        	ws.read(b);
        	if( b.size() > 0 )
        	{
        		std::cout << boost::beast::buffers(b.data()) << std::endl;
        	}
        }

**Comment by vinniefalco** [comment]
It looks like the other end is sending a WebSocket close frame, hence the error `beast::websocket::error::closed`.

**Comment by yongs2018** [comment]
but use libwebsocket request  wss://stream.binance.com:9443/ws/bnbbtc@depth is ok , or web page test is ok.

**Comment by yongs2018** [comment]
Thank you very much , you are a superman of boost.beast technology,  all perfect. !!!!

**Comment by yongs2018** [comment]
this issue Has been resolved. tks

**Comment by vinniefalco** [comment]
Great!
