### ISSUE TITLE
Crash in function ssl3_write with websocket ssl connection

### ISSUE THREAD

**Issue by nguoithichkhampha** [boostorg/beast#1153]
### Version of Beast
Beast 79

### Steps necessary to reproduce the problem
Hi @vinniefalco , We implemented beast library on our product and got some crash reports from customer.
Many crash from function ssl3_write of openssl library. Can you give some suggestion for root cause of this issue ?
I attached stack call and local variable related to beast library
![Figure 1-1](https://scontent.fhan5-1.fna.fbcdn.net/v/t1.0-9/34584750_10210007320018038_2741275628429901824_n.jpg?_nc_cat=0&oh=d21920a6f3d8180df787592017e832d8&oe=5BBE622F "Figure 1-1")

This is variable from frame stack 02
![Figure 1-1](https://scontent.fhan5-1.fna.fbcdn.net/v/t1.0-9/34815555_10210007319898035_6780135063951507456_n.jpg?_nc_cat=0&oh=e92a6cb97ccd969e19d43146b7e36f5e&oe=5BC11BD1 "Figure 1-1")

**Comment by vinniefalco** [comment]
I would suggest using Boost 1.66.0 or Boost 1.67.0 and the version of Beast that comes with it. Beast version 79 is quite old and contains bugs.

**Comment by nguoithichkhampha** [comment]
after update beast this issue will be resolved ? I'm not sure this issue from beast library or we are using the library wrong way.

**Comment by vinniefalco** [comment]
Version 79 is a beta version and contains known crashing defects, so it is very possible that simply updating will resolve your issue. However, if the issue is not resolved upon updating I would be happy to look at your code to see if I can find the problem.

**Comment by nguoithichkhampha** [comment]
Great, thanks for your support.

**Comment by TechnikEmpire** [comment]
If upgrading doesn't resolve this, are IO calls 
(which I assume are async) completion handlers on the encrypted stream wrapped in an explicit strand?
