### ISSUE TITLE
Crash while serializing http response

### ISSUE THREAD

**Issue by hoditohod** [boostorg/beast#1158]
Hi Vinnie,
I'm seeing a crash (segfault) in beast in an HTTP server while writing the HTTP response. The issue is not deterministic, it occurs roughly 1 out of 50000 requests. The beast version is quite old (120), I'm not even sure if it's a beast issue. 

What I would like to know if you have seen a similar issue that's already fixed in beast. If so I'll update versions, if not I'll start digging deeper. I tried to go through github issues, but the list is looong...

Here's the stacktrace I got:

    Program terminated with signal 11, Segmentation fault.
    #0  buffer_size<boost::beast::http::basic_fields<std::allocator<char> >::reader::field_range> (b=<optimized out>) at /import/boost_1_62_0/include/boost/asio/buffer.hpp:394
    #1  boost::beast::buffers_cat_view<boost::asio::const_buffers_1, boost::asio::const_buffers_1, boost::asio::const_buffers_1, boost::beast::http::basic_fields<std::allocator<char> >::reader::field_range, boost::beast::http::chunk_crlf>::const_iterator::construct<3ul> (this=<optimized out>, this=<optimized out>) at /import/beast-120/include/boost/beast/core/impl/buffers_cat.ipp:121
    #2  0x00000000004bdc0f in increment<2ul> (this=<optimized out>) at /import/beast-120/include/boost/beast/core/impl/buffers_cat.ipp:275
    #3  increment<1ul> (this=<optimized out>) at /import/beast-120/include/boost/beast/core/impl/buffers_cat.ipp:277
    #4  boost::beast::buffers_cat_view<boost::asio::const_buffers_1, boost::asio::const_buffers_1, boost::asio::const_buffers_1, boost::beast::http::basic_fields<std::allocator<char> >::reader::field_range, boost::beast::http::chunk_crlf>::const_iterator::increment<0ul> (this=<optimized out>) at /import/beast-120/include/boost/beast/core/impl/buffers_cat.ipp:277
    #5  0x00000000004ca2fe in operator++ (this=<optimized out>) at /import/beast-120/include/boost/beast/core/impl/buffers_cat.ipp:428
    #6  increment<0ul> (this=0x7ff404099f38) at /import/beast-120/include/boost/beast/core/impl/buffers_cat.ipp:270
    #7  operator++ (this=0x7ff404099f38) at /import/beast-120/include/boost/beast/core/impl/buffers_cat.ipp:428
    #8  boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffers_1, boost::asio::const_buffers_1, boost::asio::const_buffers_1, boost::beast::http::basic_fields<std::allocator<char> >::reader::field_range, boost::beast::http::chunk_crlf> >, boost::asio::const_buffers_1> >::consume (this=this@entry=0x7ff404099f20, amount=86) at /import/beast-120/include/boost/beast/core/impl/buffers_suffix.ipp:222
    #9  0x00000000004cea7c in boost::beast::http::serializer<false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, boost::beast::http::basic_fields<std::allocator<char> > >::consume (this=0x7ff404099ea8, n=n@entry=103) at /import/beast-120/include/boost/beast/http/impl/serializer.ipp:294
    #10 0x00000000004d9ed9 in boost::beast::http::detail::write_some_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::beast::http::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::beast::http::detail::write_msg_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, http::HttpSession<http::ZmqClient, http::WebsocketSession>::sendResponse()::{lambda(boost::system::error_code, unsigned long)#1}, false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, boost::beast::http::basic_fields<std::char_traits<char> > >, boost::beast::http::detail::serializer_is_done, false, std::allocator<char>, boost::beast::http::basic_fields>, false, std::allocator<char>, boost::beast::http::basic_fields>::operator()(boost::system::error_code, unsigned long) (this=this@entry=0x7ff421252290, ec={m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, bytes_transferred=103) at /import/beast-120/include/boost/beast/http/impl/write.ipp:166
    #11 0x00000000004da018 in operator() (this=0x7ff421252290) at /import/boost_1_62_0/include/boost/asio/detail/bind_handler.hpp:127
    #12 asio_handler_invoke<boost::asio::detail::binder2<boost::beast::http::detail::write_some_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_msg_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, http::HttpSession<HttpPolicy, WebsocketSession>::sendResponse() [with HttpPolicy = http::ZmqClient; WebsocketSession = http::WebsocketSession]::<lambda(boost::system::error_code, std::size_t)>, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::system::error_code, long unsigned int> > (function=@0x7ff421252290: {handler_ = {s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, h_ = {state_ = 2, s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, bytes_transferred_ = 0, h_ = {d_ = {p_ = 0x7ff404109d80}}}}, arg1_ = {m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, arg2_ = 103}) at /import/boost_1_62_0/include/boost/asio/handler_invoke_hook.hpp:69
    #13 asio_handler_invoke<boost::asio::detail::binder2<boost::beast::http::detail::write_some_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_msg_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, http::HttpSession<HttpPolicy, WebsocketSession>::sendResponse() [with HttpPolicy = http::ZmqClient; WebsocketSession = http::WebsocketSession]::<lambda(boost::system::error_code, std::size_t)>, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::system::error_code, long unsigned int>&> (op=<optimized out>, f=@0x7ff421252290: {handler_ = {s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, h_ = {state_ = 2, s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, bytes_transferred_ = 0, h_ = {d_ = {p_ = 0x7ff404109d80}}}}, arg1_ = {m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, arg2_ = 103}) at /import/beast-120/include/boost/beast/http/impl/write.ipp:384
    #14 asio_handler_invoke<boost::asio::detail::binder2<boost::beast::http::detail::write_some_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_msg_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, http::HttpSession<HttpPolicy, WebsocketSession>::sendResponse() [with HttpPolicy = http::ZmqClient; WebsocketSession = http::WebsocketSession]::<lambda(boost::system::error_code, std::size_t)>, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::system::error_code, long unsigned int>&> (op=<optimized out>, f=@0x7ff421252290: {handler_ = {s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, h_ = {state_ = 2, s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, bytes_transferred_ = 0, h_ = {d_ = {p_ = 0x7ff404109d80}}}}, arg1_ = {m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, arg2_ = 103}) at /import/beast-120/include/boost/beast/http/impl/write.ipp:263
    #15 asio_handler_invoke<boost::asio::detail::binder2<boost::beast::http::detail::write_some_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_msg_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, http::HttpSession<HttpPolicy, WebsocketSession>::sendResponse() [with HttpPolicy = http::ZmqClient; WebsocketSession = http::WebsocketSession]::<lambda(boost::system::error_code, std::size_t)>, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::system::error_code, long unsigned int>&> (op=<optimized out>, f=@0x7ff421252290: {handler_ = {s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, h_ = {state_ = 2, s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, bytes_transferred_ = 0, h_ = {d_ = {p_ = 0x7ff404109d80}}}}, arg1_ = {m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, arg2_ = 103}) at /import/beast-120/include/boost/beast/http/impl/write.ipp:119
    #16 invoke<boost::asio::detail::binder2<boost::beast::http::detail::write_some_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_msg_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, http::HttpSession<HttpPolicy, WebsocketSession>::sendResponse() [with HttpPolicy = http::ZmqClient; WebsocketSession = http::WebsocketSession]::<lambda(boost::system::error_code, std::size_t)>, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::system::error_code, long unsigned int>, boost::beast::http::detail::write_some_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::beast::http::detail::write_msg_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, http::HttpSession<HttpPolicy, WebsocketSession>::sendResponse() [with HttpPolicy = http::ZmqClient; WebsocketSession = http::WebsocketSession]::<lambda(boost::system::error_code, std::size_t)>, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::http::detail::serializer_is_done, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > >, false, boost::beast::http::basic_string_body<char>, boost::beast::http::basic_fields<std::allocator<char> > > > (context=@0x7ff421252290: {s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, h_ = {state_ = 2, s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, bytes_transferred_ = 0, h_ = {d_ = {p_ = 0x7ff404109d80}}}}, function=@0x7ff421252290: {handler_ = {s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, h_ = {state_ = 2, s_ = @0x7ff404054680, sr_ = @0x7ff404099ea8, bytes_transferred_ = 0, h_ = {d_ = {p_ = 0x7ff404109d80}}}}, arg1_ = {m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, arg2_ = 103}) at /import/boost_1_62_0/include/boost/asio/detail/handler_invoke_helpers.hpp:37
    #17 boost::asio::detail::reactive_socket_send_op<boost::beast::detail::buffers_ref<boost::beast::buffers_prefix_view<boost::beast::buffers_suffix<boost::beast::buffers_cat_view<boost::beast::detail::buffers_ref<boost::beast::buffers_cat_view<boost::asio::const_buffers_1, boost::asio::const_buffers_1, boost::asio::const_buffers_1, boost::beast::http::basic_fields<std::allocator<char> >::reader::field_range, boost::beast::http::chunk_crlf> >, boost::asio::const_buffers_1> > const&> >, boost::beast::http::detail::write_some_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::beast::http::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::beast::http::detail::write_msg_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, http::HttpSession<http::ZmqClient, http::WebsocketSession>::sendResponse()::{lambda(boost::system::error_code, unsigned long)#1}, false, boost::beast::http::basic_string_body<char, std::char_traits<char>, std::allocator<char> >, boost::beast::http::basic_fields<std::allocator<char> > >, boost::beast::http::detail::serializer_is_done, false, std::char_traits<char>, boost::beast::http::basic_fields<std::allocator<char> > >, false, std::char_traits<char>, boost::beast::http::basic_fields<std::allocator<char> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0x7ff404000910, base=<optimized out>) at /import/boost_1_62_0/include/boost/asio/detail/reactive_socket_send_op.hpp:107
    #18 0x000000000050eeaf in complete (bytes_transferred=0, ec=@0x7ff421252390: {m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, owner=@0x7ff404000910: {<boost::asio::detail::service_base<boost::asio::detail::task_io_service>> = {<boost::asio::io_service::service> = {<boost::asio::detail::noncopyable> = {<No data fields>}, _vptr.service = 0x8264c0 <vtable for boost::asio::detail::task_io_service+16>, key_ = {type_info_ = 0x828308 <typeinfo for boost::asio::detail::typeid_wrapper<boost::asio::detail::task_io_service>>, id_ = 0x0}, owner_ = @0x7ff421252380, next_ = 0x0}, static id = {<boost::asio::io_service::id> = {<boost::asio::detail::noncopyable> = {<No data fields>}, <No data fields>}, <No data fields>}}, one_thread_ = false, mutex_ = {<boost::asio::detail::noncopyable> = {<No data fields>}, mutex_ = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, wakeup_event_ = {<boost::asio::detail::noncopyable> = {<No data fields>}, cond_ = {__data = {__lock = 0, __futex = 2, __total_seq = 1, __wakeup_seq = 1, __woken_seq = 1, __mutex = 0x7ff404000940, __nwaiters = 0, __broadcast_seq = 0}, __size = "\000\000\000\000\002\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000@\t\000\004�\177\000\000\000\000\000\000\000\000\000", __align = 8589934592}, state_ = 1}, task_ = 0x16e3e70, task_operation_ = {<boost::asio::detail::task_io_service_operation> = {next_ = 0x0, func_ = 0x0, task_result_ = 0}, <No data fields>}, task_interrupted_ = true, outstanding_work_ = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 33}, <No data fields>}, op_queue_ = {<boost::asio::detail::noncopyable> = {<No data fields>}, front_ = 0x7ff40411de30, back_ = 0x7ff4040009a8}, stopped_ = false, shutdown_ = false}, this=0x7ff40409a040) at /import/boost_1_62_0/include/boost/asio/detail/task_io_service_operation.hpp:38
    #19 do_run_one (ec=@0x7ff421252390: {m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, this_thread=@0x7ff421252410: {<boost::asio::detail::thread_info_base> = {<boost::asio::detail::noncopyable> = {<No data fields>}, reusable_memory_ = 0x7ff40409a040}, private_op_queue = {<boost::asio::detail::noncopyable> = {<No data fields>}, front_ = 0x0, back_ = 0x0}, private_outstanding_work = 0}, lock=@0x7ff4212523a0: {<boost::asio::detail::noncopyable> = {<No data fields>}, mutex_ = @0x7ff404000940, locked_ = false}, this=0x7ff404000910) at /import/boost_1_62_0/include/boost/asio/detail/impl/task_io_service.ipp:372
    #20 run (ec=@0x7ff421252390: {m_val = 0, m_cat = 0x8345c0 <boost::system::system_category()::system_category_const>}, this=0x7ff404000910) at /import/boost_1_62_0/include/boost/asio/detail/impl/task_io_service.ipp:149
    #21 run (this=0x7ff421252380) at /import/boost_1_62_0/include/boost/asio/impl/io_service.ipp:59
    #22 http::IOServicePool::<lambda()>::operator()(void) const (__closure=<optimized out>) at /src/main/src/ioServicePool.cpp:81
    #23 0x00007ff424c07c80 in ?? ()
    #24 0x0000000000000000 in ?? ()

### Version of Beast
120

### Steps necessary to reproduce the problem
Uh... not deterministic... Occurrence rate 1:50000.

### All relevant compiler information
Boost 1.62, GCC 5.4.0, Ubuntu 16.04, 64bit

**Comment by vinniefalco** [comment]
Version 120 is older than the first official release so I would update...

**Comment by hoditohod** [comment]
Ok, thanks!
