### ISSUE TITLE
Http server support browser folder

### ISSUE THREAD

**Issue by snahmad** [boostorg/beast#1159]
Hi,

Does beast support browser folder?

I tried few HTTP server examples. I cannot browser my root folder?

Thanks,
Naeem

**Comment by vinniefalco** [comment]
> Does beast support browser folder?

No. The examples are intended to demonstrate the usage of Beast interfaces. Iterating a directory (Boost.Filesystem or std:: filesystem) and rendering the contents in HTML has nothing to do with HTTP or WebSocket, and is out of scope for Beast.
