### ISSUE TITLE
Get Headerdata without consume stream...

### ISSUE THREAD

**Issue by ngohr** [boostorg/beast#1161]
I try to extract header data before accepting a ssl websocket connection.
But no luck since two days...

If i do something like:

		std::cout << "Read out Headers\n";
		boost::asio::streambuf header;
		boost::asio::read_until(_stream, header, "\r\n\r\n");
		std::ostringstream strsresult;
		strsresult << boost::beast::buffers(header.data());
		std::cout << strsresult.str() << "\n";

After etablishing the stream, but before the standard read process....
I cannot read the bytes before and give them to accept, because the full ssl handshake must happen before.
Couldt i read the headers from stream without consuming the bytes, so the standard functions couldt work anyway?
I need the cookie data, before a wss connection will etablished.

**Comment by vinniefalco** [comment]
This is all explained in the documentation. For clients:
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket/handshaking_clients.html#beast.using_websocket.handshaking_clients.filtering

And for servers:
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html

**Comment by ngohr** [comment]
Thank you, but 

ws.accept(buffer.data());

does not work because the http headers appears in the buffer after

stream.handshake(ssl::stream_base::server, ec);

but before ws_.next_layer().async_handshake

(or something else)

so handshake fails and i never came to ws.accept();

My best tries ends up without handshake functions but with fails(): accept: uninitialized

**Comment by ngohr** [comment]
The documentation does not include how http::request< Body, http::basic_fields< Allocator >> const& req shouldt be passed on ssl streams.
In the advanced_server_flex you initiate _req at line and dont touch it since ssl_httpsession calls doRead()
But that does not work in my simple code:
`boost::beast::error_code ec;
boost::asio::streambuf header;
boost::beast::flat_buffer buffer;

// Block until we get a connection
acceptor.accept(socket);

// I dont know where i have to place that i tried it often...
http::request<boost::beast::http::string_body> req;

// Construct the stream around the socket
ssl::stream<tcp::socket&> stream{socket, ctx};
stream.handshake(ssl::stream_base::server, ec);

boost::asio::read_until(stream, header, "\r\n\r\n", ec);
std::ostringstream strheader;
strheader << boost::beast::buffers(header.data());
std::cout << strheader.str() << "\n";

// req = {};

/*
 * This Blocks completly and the prog doesnt reach the next lines
 * std::cout << "Try to read from request\n";
 * boost::beast::http::read(socket, buffer, req, ec);
 * std::ostringstream strsresult;
 * strsresult << boost::beast::buffers(buffer.data());
 * std::cout << strsresult.str() << "\n";
 *
 */

// See if its a WebSocket upgrade request
if(websocket::is_upgrade(req)) {
	// Returns true with Plain ws and without the handshake above
	std::cout << "Here in upgrade\n";
} else {
	// With the read_until above this returns false, i think because the header line was allready read
	// Without the ssl handshake above it returns false, because i think the headers are encrypted
	std::cout << "Handle HTTP\n";
}`

With the read_until after the handshake, i get the expected result, but not a ::read a ::handshake neither ::is_upgrade works.
So i think i abuse the buffer behind the stream. THE Stream that imho does not have any relation to the request element.
I am so sorry but i dont understand in which case i can use the request element in an ssl stream, neither where i a have to instance it.

**Comment by ngohr** [comment]
This:

`		std::cout << "------------------------------------------------\n";
		boost::beast::flat_buffer header;
		boost::system::error_code ec;
		boost::beast::http::read(ws_.next_layer(), header, req);
		std::ostringstream strsresult;
		strsresult << boost::beast::buffers(header.data());
		std::cout << strsresult.str() << "\n";
		std::cout << "------------------------------------------------\n";`

Placed anywhere, after ssl handshake in advanced flex server, blocks the whole application.
Allready tried with moved sockets, sslstream, websocketstream layers and so on...

My first try was to Place it before 

derived().ws().async_accept

with 

derived().ws().next_layer()

**Comment by vinniefalco** [comment]
Beast requires an understanding of Boost.Asio. You are performing a synchronous operation in an asynchronous context, thus blocking the server. I suggest you take some time to first study and understand Asio's execution models, and then revisit Beast once you are more familiar with it.
