### ISSUE TITLE
websocket server : how get request all URL example "wss://192.168.0.11:443/path?random=8" 

### ISSUE THREAD

**Issue by yongs2018** [boostorg/beast#1164]
hello.
on websocktet server , how get client  request all url .
for example 
wss://192.168.0.11:443/path?random=8
I want get the url , call witch function ?

**Comment by vinniefalco** [comment]
See: https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html
