### ISSUE TITLE
how do i change this asio code into beast?boost::asio::async_read(m_Socket, boost::asio::buffer(m_Packet.acHeader)

### ISSUE THREAD

**Issue by opengpu** [boostorg/beast#1171]
`
#define HeaderLength 8
	union
	{
		char           acHeader[HeaderLength];
		struct { int32 iMsgID, iMsgLength; };
	};
	std::vector<char> vcBody;

void TcpSession::do_read_header()
{
	auto self(shared_from_this());
	**boost::asio::async_read(m_Socket, boost::asio::buffer(m_Packet.acHeader),**
		[this, self](const boost::system::error_code& error, std::size_t bytes_transferred)
	{
		if (!error)
		{
			**ASSERT(bytes_transferred == Packet::HeaderLength);**
			int32 iMsgID = ntohl(m_Packet.iMsgID);
			int32 iMsgLength = ntohl(m_Packet.iMsgLength);
			if (IS_VALID(iMsgID))
			{
				if (iMsgLength > 0)
				{
					**m_Packet.vcBody.resize(iMsgLength);**
					do_read_body(iMsgID);
				}
...
}
void TcpSession::do_read_body(int32 iMsgID)
{
	auto self(shared_from_this());
	**boost::asio::async_read(m_Socket, boost::asio::buffer(m_Packet.vcBody),**
		[this, self, iMsgID](const boost::system::error_code& error, std::size_t bytes_transferred)
	{
		if (!error)
		{
			**ASSERT(bytes_transferred == m_Packet.vcBody.size());**
			google::protobuf::Message* pMsg = CreateMessage(iMsgID);
			if (pMsg)
			{
				if (pMsg->IsInitialized())
				{
					//if (pMsg->ParseFromString())
					//if (pMsg->ParseFromIstream())
					if (pMsg->ParseFromArray(m_Packet.vcBody.data(), m_Packet.vcBody.size()))
					{
					}
...
}
`
////////////////////////////////////////////////////////////////////////////////////

can i change this asio code into beast like this as following?
////////////////////////////////////////////////////////////////////////////////////
`
protected:
	boost::beast::websocket::stream<boost::asio::ip::tcp::socket> ws_;
	boost::asio::strand<boost::asio::io_context::executor_type> strand_;
	//boost::beast::multi_buffer buffer_;
	Packet m_Packet;
	int32 m_iMsgID;`

void session::do_read_header()
{
	// Read a message into our buffer
	**ws_.async_read_some(
		boost::asio::buffer(m_Packet.acHeader),**
		boost::asio::bind_executor(
			strand_,
			std::bind(
				&session::on_read_header,
				shared_from_this(),
				std::placeholders::_1,
				std::placeholders::_2)));
}
void session::on_read_header(boost::system::error_code ec, std::size_t bytes_transferred)
{
	// This indicates that the session was closed
	if (ec == boost::beast::websocket::error::closed)
	{
		std::cout << "INFO: @on_read_header, (ec == websocket::error::closed)" << std::endl;
		return;
	}
	if (!ec)
	{
		**ASSERT(bytes_transferred == Packet::HeaderLength);**
		int32 iMsgID = ntohl(m_Packet.iMsgID);
		int32 iMsgLength = ntohl(m_Packet.iMsgLength);
		if (IS_VALID(iMsgID))
		{
			if (iMsgLength > 0)
			{
                                **m_Packet.vcBody.resize(iMsgLength);**
				do_read_body(iMsgID);
			}
...
}
void session::do_read_body(int32 iMsgID)
{
	m_iMsgID = iMsgID;
	// Read a message into our buffer
	**ws_.async_read_some(
		boost::asio::buffer(m_Packet.vcBody),**
		boost::asio::bind_executor(
			strand_,
			std::bind(
				&session::on_read_body,
				shared_from_this(),
				std::placeholders::_1,
				std::placeholders::_2)));
}
void session::on_read_body(boost::system::error_code ec, std::size_t bytes_transferred)
{
	// This indicates that the session was closed
	if (ec == boost::beast::websocket::error::closed)
	{
		std::cout << "INFO: @on_read_body, (ec == websocket::error::closed)" << std::endl;
		return;
	}
	if (!ec)
	{
		**ASSERT(bytes_transferred == m_Packet.vcBody.size());**
		google::protobuf::Message* pMsg = CreateMessage(m_iMsgID);
		if (pMsg)
		{
			if (pMsg->IsInitialized())
			{
				//if (pMsg->ParseFromString())
				//if (pMsg->ParseFromIstream())
				if (pMsg->ParseFromArray(m_Packet.vcBody.data(), m_Packet.vcBody.size()))
				{//FIXME!
				}
...
}
`

**Comment by opengpu** [comment]
sorry, first time issue, so i dont know whether here is like forum that can ask questions.

**Comment by vinniefalco** [comment]
Are you trying to use WebSocket?

**Comment by opengpu** [comment]
yes,the asio code is for TCP. and the beast code is for WebSocket. i am using beast as my server network module.

**Comment by opengpu** [comment]
ok,great! thank you!
so what is the usage of async_read_some?is it equal to devide one async_read into two or more async_read_some? eg. 1st async_read_some read 8 bytes, 2nd async_read_some read the left bytes.
