### ISSUE TITLE
in beast, is websocket stream or ws.async_read() will get all the data ws.send()?

### ISSUE THREAD

**Issue by opengpu** [boostorg/beast#1172]
in beast, is websocket stream or ws.async_read() will get all the data ws.send()? no matter how big the dataSize is...
thank you

**Comment by vinniefalco** [comment]
`websocket::stream::async_read` can read any size message, but the default limits messages to 16 megabytes, see:
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/read_message_max/overload1.html

**Comment by opengpu** [comment]
so for WebSocket, one ws.async_read() will read the entire data of the ws.send() by other client?

**Comment by vinniefalco** [comment]
> one ws.async_read() will read the entire data of the ws.send() by other client?
Yes

**Comment by opengpu** [comment]
ok,great! thank you!
so what is the usage of async_read_some?is it equal to devide one async_read into two or more async_read_some? eg. 1st async_read_some read 8 bytes, 2nd async_read_some read the left bytes.

**Comment by vinniefalco** [comment]
> so what is the usage of async_read_some?is it equal to devide one async_read into two or more async_read_some

Yes
