### ISSUE TITLE
Kindly Request for Websocket Connection over Proxy example

### ISSUE THREAD

**Issue by abeydemir23** [boostorg/beast#1173]
Hi, I look inside the beast library and it's examples about Websocket connection over a proxy but no chance up to the present my actual intention could be explanied using below image please have a look at.

https://user-images.githubusercontent.com/12622800/42079517-94912a3a-7b88-11e8-987f-879939874c43.png

Since I'm a newbie in both C++ and boost/beast i kindly request a websocket client example over proxy.

**Comment by vinniefalco** [comment]
> I'm a newbie in both C++ and boost/beast

You are going to have a very difficult time using Beast successfully without a grasp of C++ and Boost.Asio. I suggest you take a step back and first become proficient in C++, and then learn Boost.Asio. Then the Beast documentation will be more approachable, and you will be able to understand the examples.

**Comment by abeydemir23** [comment]
Hi @vinniefalco actually I've managed to compile and run examples on repository My only need is proxy enhancement or any code change set that provide proxy support.

**Comment by vinniefalco** [comment]
Okay, well I suggest you read the documentation or specification on the type of proxy support you need, and then add the necessary code.

**Comment by abeydemir23** [comment]
Hi @vinniefalco i read the documentation which is below https://www.boost.org/doc/libs/develop/libs/beast/doc/html/index.html 
and found out that proxy support seems not supported by beast

About specification of proxy type it can be any outgoing explicit HTTP proxy for regular and secure websockets.
