### ISSUE TITLE
is_done() for response

### ISSUE THREAD

**Issue by asvald** [boostorg/beast#1187]
BOOST_BEAST_VERSION 167

Hello! How to deal with such responses, for ex.
from ebay.com

> HTTP/1.1 301 Moved Permanently
> Location: https://www.ebay.com
> \r\n\r\n

or from apple.com

> HTTP/1.1 301 MOVED PERMANENTLY
> Server: Apache 
> Date: Thu, 12 Jul 2018 13:43:28 GMT
> Location: https://www.apple.com/
> Content-type: text/html
> Connection: close
> \r\n\r\n

I omitted \r\n at the end of fields.
is_done() for
```
boost::beast::http::response_parser<
			boost::beast::http::string_body>>
```
returns false for such responses.

**Comment by vinniefalco** [comment]
Are you asking how to handle a 301 status code? You need to inspect the Location field and resubmit the request using a new connection to the indicated host, possibly over SSL (the "https").

**Comment by asvald** [comment]
I corrected my first post. I mean is_done() false for this responses.

**Comment by vinniefalco** [comment]
Well, the behavior of `parser` is correct in this case. There is no Content-Length, so the end of the message body is determined by receiving a FIN or SSL shutdown handshake. The server should close the connection, which will make the parser return `true` for `is_done`. If you want to speed this up you can check if the response is a 301, and then call `is_header_done` instead, to break early.
