### ISSUE TITLE
Unable to build example project, advanced - server.cpp

### ISSUE THREAD

**Issue by ChristopherO1** [boostorg/beast#1188]
This more likely down to my limited experience, rather than a bug.

I can't compile the project found here 
https://github.com/boostorg/beast/blob/develop/example/advanced/server/advanced_server.cpp

My issue is in class queue within class http_session :

template<bool isRequest, class Body, class Fields>
void operator()(http::message<isRequest, Body, Fields>&& msg)
{
struct work_impl : work
            {
               http_session& self_;  - **_line the compiler is grumbling about_**
                http::message<isRequest, Body, Fields> msg_;

                work_impl(
                    http_session& self,
                    http::message<isRequest, Body, Fields>&& msg)
                    : self_(self)
                    , msg_(std::move(msg))
                {
                }                
            };
}

**_Error	C2530	'self_': references must be initialized	WebSocket_**

Using
Windows 7 
VS 2017 community
I have BOOST 1.67.0 and the vc141 libraries

I have limited experience with Templates, so not honestly sure what I need to do to resolve this.

Any help gratefully received

Thank you

Chris

**Comment by vinniefalco** [comment]
Are you using `/permissive-` ?

**Comment by ChristopherO1** [comment]
I'm guessing not, would that be a properties option?
Where would I need to set it?

**Comment by ChristopherO1** [comment]
It's OK I found it.
Added it.
No change unfortunately

**Comment by vinniefalco** [comment]
What I mean is that `/permissive-` seems to cause the problem. You should try un-setting it (not sure how to do that).

> Apparently it's set by default in VS 2017 Version 15.7.5

How do you turn it off?

**Comment by ChristopherO1** [comment]
Found it. it's in the properties
C/C++
All Options - Conformance Mode: Set to No

Build succeeded :)

Thanks for the pointers, much appreciated

**Comment by ChristopherO1** [comment]
Yes. Sorry
Now closed
