### ISSUE TITLE
Check type connection

### ISSUE THREAD

**Issue by Ludea** [boostorg/beast#1189]
Hello, 

I have a tcp server, using boost asio (1.67).
I have a tcp client, which communicate with the server by tcp. 
I have another client, a browser, using js and websocket. 
I try to connect and send message to the tcp server. 
But how to check if the message is sent by tcp or websocket on server.?

I see the function is_upgrade(), which do the difference between http request and websocket. But I know, websocket is a full duplex communication using tcp. 
I don't know if it is possible to check tcp and websocket. 

Thanks.

**Comment by Ludea** [comment]
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html

I see this, it is the answer to my question!

**Comment by vinniefalco** [comment]
Glad to hear that the documentation has resolved your issue!

**Comment by Ludea** [comment]
```if(websocket::is_upgrade(req))
{
    // Construct the stream, transferring ownership of the socket
    stream<boost::asio::ip::tcp::socket> ws{std::move(sock)};

    // Clients SHOULD NOT begin sending WebSocket
    // frames until the server has provided a response.
    BOOST_ASSERT(buffer.size() == 0);

    // Accept the upgrade request
    ws.accept(req);
}
else
{
    // Its not a WebSocket upgrade, so
    // handle it like a normal HTTP request.
}
```
I use this to check if the connection use websocket. 
```
void
    on_resolve(
        boost::system::error_code ec,
        tcp::resolver::results_type results)
    {
        if(ec)
            return fail(ec, "resolve");

        // Make the connection on the IP address we get from a lookup
        boost::asio::async_connect(
            ws_.next_layer().next_layer(),
            results.begin(),
            results.end(),
            std::bind(
                &session::on_connect,
                shared_from_this(),
                std::placeholders::_1));
    }
```
I use this to connect from a websocket connection. 

But the connection example from asio is different 
```
void do_accept()
  {
    acceptor_.async_accept(
        [this](boost::system::error_code ec, tcp::socket socket)
        {
          if (!ec)
          {
            std::make_shared<chat_session>(std::move(socket), room_)->start();
          }

          do_accept();
        });
  }
```
It is possible to merge the 2 ways of connection and test the websocket and tcp connection?

**Comment by vinniefalco** [comment]
> It is possible to merge the 2 ways of connection and test the websocket and tcp connection?

I believe you are asking "how can I process normal HTTP requests and WebSocket upgrade handshakes on the same connection?" That is explained in the documentation:
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html#beast.using_websocket.handshaking_servers.passing_http_requests

The Advanced server examples also show how to do this:
https://github.com/boostorg/beast/blob/develop/example/advanced/server/advanced_server.cpp#L607
https://github.com/boostorg/beast/blob/develop/example/advanced/server/advanced_server.cpp#L659

**Comment by Ludea** [comment]
I try to use websocket over ssl.
I see in include file experimental folder, with ssl_stream class.
So you support this in boost 1.67 ?

**Comment by vinniefalco** [comment]
> I try to use websocket over ssl.

The advanced-server-flex example allows SSL over websocket:

https://github.com/boostorg/beast/blob/develop/example/advanced/server-flex/advanced_server_flex.cpp

**Comment by Ludea** [comment]
#include <boost/beast/experimental/core/ssl_stream.hpp> file not found

**Comment by vinniefalco** [comment]
`ssl_stream` will be in the next release (Boost 1.68). You don't need it though, as the advanced-server-flex from 1.67 illustrates:
https://github.com/boostorg/beast/blob/boost-1.67.0/example/advanced/server-flex/advanced_server_flex.cpp

**Comment by vinniefalco** [comment]
Use **websocket-server-async-ssl**

https://github.com/boostorg/beast/tree/develop/example/websocket/server/async-ssl

**Comment by Ludea** [comment]
I must use the template derived() into ssl websocket class?

**Comment by vinniefalco** [comment]
I don't understand what you are asking. You want a server that can handle both HTTP requests and the WebSocket upgrade?

**Comment by Ludea** [comment]
Only Websocket and simple tcp socket

**Comment by Ludea** [comment]
I replace io_service with io_context, follow tutorial from asio. But I can not connect with curl. 

```
tcp_server::tcp_server(boost::asio::io_context& ioc,
      const tcp::endpoint& endpoint)
    : acceptor_(io_context, endpoint)
tcp::endpoint endpoint, std::shared_ptr<std:$
: acceptor(ioc, endpoint),
doc_root(doc_root),
m_room(new chatroom(*this))
{
        wait_for_connection();
}

void do_accept()
  {
    acceptor_.async_accept(
        [this](boost::system::error_code ec, tcp::socket socket)
        {
          if (!ec)
          {
            std::make_shared<chat_session>(std::move(socket), room_)->start();
          }

          do_accept();
        });
  }
```
main.cpp
```
 boost::asio::io_context io_context;
std::shared_ptr<std::string const> const&doc_root = std::make_shared<std::string>("/");
tcp::endpoint endpoint(tcp::v4(), 4000);
tcp_server(ioc, endpoint, doc_root);
io_context.run();
```
I use curl 127.0.0.1:4000 and I have connection refused

**Comment by vinniefalco** [comment]
Does the unmodified example server with with curl?

**Comment by Ludea** [comment]
I try to add connection_ptr new_connection(new tcp_connection(acceptor.get_executor().context()));
But i never success to add it into do_accept()

**Comment by vinniefalco** [comment]
I can't really help without a clearly articulated statement of the problem, so my general advice is as follows: start by compiling one of the examples which operates similarly to your desired use-case, to confirm that it works (they do). Then modify the example in small increments to achieve the required functionality. Along the way, if the program malfunctions, then it is highly likely that your last change is the culprit.

**Comment by Ludea** [comment]
It was an syntax issue.
I success to check if the socket is tcp or websocket
