### ISSUE TITLE
correctly close websocket

### ISSUE THREAD

**Issue by quazeeee** [boostorg/beast#1195]
It's more a question then issue, but i need help. I implement in my code websocket client part with async read, but all other operations in sync style (connect, write, close). io_service run in separate thread and call event on message. Question: it's correct action when i close socket while in parallel thread async_read can read message from server? When i call close connection from client, server side connection closed successfully but client async_read fail with error (WebSocket connection failed due to a protocol violation). Should i stop iocontext before close or after call close? The same question for async_close, should i stop iocontext in onClose handler?

**Comment by vinniefalco** [comment]
Hmmm... you can't mix asynchronous and synchronous websocket operations. I suggest you only use asynchronous.

**Comment by quazeeee** [comment]
thank, your answer was confirms my experiments !
