### ISSUE TITLE
Serializer operator= documentation is misleading

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#1200]
This suggests that serializer is copyable:
https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/ref/boost__beast__http__serializer/operator_eq_.html

**Comment by vinniefalco** [comment]
Needs "(Deleted)" in the javadoc, or we can use `#ifndef BEAST_DOXYGEN` to remove it from the docs.

**Comment by alandefreitas** [comment]
`http::serializer::operator=` is already being rendered as

```cpp
serializer&
operator=(
    serializer const&) = delete;
```

Is there anything else we need to do here?

Do we want to remove `operator=` completely from the table of `http::serializer` member functions?

**Comment by vinniefalco** [comment]
Looks good
