### ISSUE TITLE
sslv3 alert handshake failure - cloudflare

### ISSUE THREAD

**Issue by arminnaderi** [boostorg/beast#1206]
### Version of Beast

BOOST_BEAST_VERSION 144

### Steps necessary to reproduce the problem

Use the websocket client SSL example to connect to a cloudflare-enabled websocket server.

### Relevant Information

After being able to successfully connect to multiple websocket servers without problems, I simply tried changing the server I connected to to one with cloudflare enabled. It keeps throwing a runtime error with the message:

```
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >: handshake: sslv3 alert handshake failure
```

I tried passing different TLS/SSL versions to the `boost::asio::ssl::context` but the error message would not change. Also tried calling `set_options` on the context to disable sslv3 from being used, but it didn't change the output as well.

[https://github.com/chriskohlhoff/asio/issues/262](https://github.com/chriskohlhoff/asio/issues/262) may be related but its fixes were only applied to HTTP examples, not sure how to apply them to websockets since the websocket API is not the same.

Any ideas on how to solve this problem?

**Comment by vinniefalco** [comment]
> not sure how to apply them to websockets since the websocket API is not the same.

Anything having to do with SSL would be applied to the `boost::asio::ssl::stream`, before any websocket handshaking takes place. So the use of WebSocket should not affect your fix.

> Any ideas on how to solve this problem?

None at all; this is strictly related to `ssl::stream` (OpenSSL in particular) and not Beast, and I am not an expert on TLS.

**Comment by arminnaderi** [comment]
Yea you're right, it's not a Beast problem. Do you know how I can access the underlying `ssl::stream` in this line of the example? 

```
websocket::stream<ssl::stream<tcp::socket>> ws_;
```

**Comment by vinniefalco** [comment]
When you upgrade to the latest Beast you might want to use these declarations:
```
#include <boost/beast/experimental/core/ssl_stream.hpp>
...
boost::beast::websocket::stream<boost::beast::ssl_stream<tcp::socket>> ws;
```

**Comment by arminnaderi** [comment]
Ah it seems to have a `native_handle`. Pretty neat, I will consider it thanks

**Comment by vinniefalco** [comment]
Well it also performs much better since it provides a work-around for a limitation in `asio::ssl::stream`.
