### ISSUE TITLE
websocket async server 

### ISSUE THREAD

**Issue by yongs2018** [boostorg/beast#1207]
when I send buffer 

Assertion failed: ! base_, file e:\sdkroot\boost_x64\include\boost-1_66\boost\beast\websocket\detail\pausation.hpp, line 213

**Comment by vinniefalco** [comment]
When you call `websocket::stream::async_write`, you must wait until the operation completes (your completion handler is invoked) before calling `async_write` again. This is explained here:
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket/notes.html#beast.using_websocket.notes.thread_safety

If you want to send more than one message at a time, you need to implement your own write queue. An example may be found here:
https://github.com/vinniefalco/CppCon2018/blob/8fc8528571561d2acee5c05f4b7a51861d1d496d/websocket_session.cpp#L87

**Comment by yongs2018** [comment]
thank you , super man .  Your eyes are like Chairman Mao

**Comment by yongs2018** [comment]
this code Cause the same problem： 
bool Msession::send_msg(const std::string & msg)
{
	bool write_pending = false;
	{
		std::lock_guard<std::mutex> lock(mtx_);
		write_pending = !m_sendQueue.empty();
		m_sendQueue.emplace_back(msg);
	}

	if (!write_pending)
	{
		async_write();
	}
	return true;
}

void Msession::async_write()
{
	std::string msg;
	{
		std::lock_guard<std::mutex> lock(mtx_);
		if (m_sendQueue.empty())
			return;
		msg = m_sendQueue.front();
	}
	auto sp = std::make_shared<std::string>(msg);
	//auto b = boost::asio::dynamic_buffer(*sp);
	
	ws_.async_write(
			boost::asio::buffer(*sp), boost::asio::bind_executor(strand_,
				[sp, self = shared_from_this()](boost::beast::error_code ec, std::size_t bytes_transferred)
		{
			self->on_write(ec, bytes_transferred);
		}));
}

void
Msession::on_write(
	boost::system::error_code ec,
	std::size_t bytes_transferred)
{
	boost::ignore_unused(bytes_transferred);

	if (ec)//error
	{

		std::lock_guard<std::mutex> lock(mtx_);
		m_sendQueue.clear();
		SendBuffer* sq = SendBuffer::getInstance();
		auto p = shared_from_this();
		sq->del_fd(p);
		std::cout << "write close" << std::endl;
		return;
	}

	if (!ec)
	{
		std::lock_guard<std::mutex> lock(mtx_);
		std::cout << "m_sendQueue.size()" << m_sendQueue.size() << std::endl;
		m_sendQueue.pop_front();

	}
	async_write();
}

Assertion failed: ! base_, file e:\sdkroot\boost_x64\include\boost-1_66\boost\beast\websocket\detail\pausation.hpp, line 213

**Comment by vinniefalco** [comment]
I would try using a more recent Boost, 1.66.0 has a few websocket bugs that were fixed in later versions

**Comment by yongs2018** [comment]
1.68 version ok ?  for this bug .

**Comment by vinniefalco** [comment]
Yes

**Comment by yongs2018** [comment]
Assertion failed: id_ != T::id, boost\beast\websocket\detail\stream_base.hpp, line 91  ？

**Comment by vinniefalco** [comment]
If you are getting assertions, it almost certainly means that your code is violating one or more preconditions. This is often the result of accessing I/O objects and the streams that wrap them (like `websocket::stream`) in ways that are disallowed by the interface. I can't really help without clearly articulated statements of the problem, so my general advice is as follows: start by compiling one of the examples which operates similarly to your desired use-case, to confirm that it works (they do). Then modify the example in small increments to achieve the required functionality. Along the way, if the program malfunctions, then it is highly likely that your last change is the culprit.
