### ISSUE TITLE
Contradictory documentation

### ISSUE THREAD

**Issue by RedDwarf69** [boostorg/beast#1213]
In https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket/notes.html it says `this code is well-formed`:

```
ws.async_read(b, [](error_code, std::size_t){});
ws.async_write(b.data(), [](error_code, std::size_t){});
ws.async_ping({}, [](error_code){});
ws.async_close({}, [](error_code){});
```

In https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/async_close.html it says `The program must ensure that the stream performs no other write operations (such as websocket::stream::async_ping, websocket::stream::async_write, websocket::stream::async_write_some, or websocket::stream::async_close) until this operation completes. `

Which seems a contradiction to me. Can `async_write` and `async_close` be pending at the same time or not?

**Comment by RedDwarf69** [comment]
Just so I get it right. If I do this:

```
ws.async_read(b, [](error_code, std::size_t){});
ws.async_write(b.data(), [](error_code, std::size_t){});
ws.async_ping({}, [](error_code){});
ws.async_close({}, [](error_code){});
```

What would happen is:
- Maybe the async_read will complete, maybe it will not
- Maybe the async_write will actually write something to the network, maybe it will not
- Mayve the async_ping will actually write something to the network, maybe it will not
- When `async_close` returns `is_open()` will be still true.

Now... I suppose that, if they have not completed before, `async_read`, `async_write and `async_ping` will return "operation cancelled" whenever the websocket::stream stops being `is_open()`, right?

Then, the async_close documentation says
```
The asynchronous operation will continue until one of the following conditions is true:
    * The close frame finishes sending. 
```
Does this mean the websocket::stream stops being `is_open()` when `async_close()` returns? Or it will stop being `is_open()` only when it receives a close frame back from the other endpoint? If it's the later, does this mean that the only way to close the Websocket connection correctly AND taking into account timeouts (never receiving the close frame back) is to:
* set a `control_callback()`
* set a timer when calling async_close()
* close the lowest_layer() if the timer expires
?

**Comment by vinniefalco** [comment]
>  If it's the later, does this mean that...

Yes. Your analysis is 100% correct. I bet you would write great docs :) These tests address the scenario you described:

https://github.com/boostorg/beast/blob/develop/test/beast/websocket/close.cpp#L455

I am working on a new class `timed_socket` which contains an `asio::basic_stream_socket` and installs a service which handles timeouts on reads automatically. If you would like to provide feedback on it, that would be great. It might address your use-case:

https://github.com/vinniefalco/beast/blob/timed_stream/include/boost/beast/experimental/core/timed_socket.hpp#L25

**Comment by RedDwarf69** [comment]
If I got it right that would set a single read timeout for all the websocket::stream operations, right?

In my use-case I am waiting for the other endpoint to send me instructions, not to reply to requests I send. These instructions can come every 10 ms or once every 2 hours. I don't really want to timeout on async_read. The places where I want to timeout are only when waiting for a "pong" or a "close".

On the other hand I could make use of that timed_socket as it is. I would just need to call `async_read()` again if it completes with a timed-out error.

On the yet other hand, it would not handle "bad" peers that could potentially ignore my close frame.
* I async_close()
* The other side ignores it and keeps sending me other messages
* The socket never timeouts, even if I never receive the close frame, because the other messages keep resetting the timeout timer.

**Comment by vinniefalco** [comment]
Hmm... you are right. Perhaps `basic_timed_socket` can expose additional interface to give you control over the timeout process:
```
template <class Protocol>
class basic_timed_socket
{
    ...
public:
    ...
    /** Arm the timer.
        This function activates the timer. If the timer expires before
        the member function `reset` is called, then on_timeout() will
        be invoked.
    */
    void set();

    /** Reset the timer.
        If the timer is active, this will reset it, otherwise does nothing.
    */
    void reset();

    /// Called when the timer expires
    virtual void on_timeout() = 0;
};
```

**Comment by RedDwarf69** [comment]
How exactly would this look?

```
ws.async_close();
ws.lowest_layer().set(std::chrono::seconds(10));

...

ws.control_callback(
    [&ws](frame_type kind, string_view)
    {
	if(kind == frame_type::close) {
	    ws.reset();
	}
    });

...

// Making it look like spawn without spawn for clarity purposes
while(ws.is_open()) {
    ws.async_read(..., handler_ec);
    if(handler_ec == error::timedout) {
        break;
    }
}
```

?

It would certainly make it easier.

You could argue something like this is easier to use

```
ws.async_close();
ws.set_close_timeout(std::chrono::seconds(10));
// ws.set_ping_timeout(std::chrono::seconds(10));

...

while(ws.is_open()) {
    // Beast internally resets the timer only if a close frame arrives
    ws.async_read(..., ec);
    if(ec == error::timedout) { // "error::close_timeout"?
        break;
    }
}
```

But it may go against the whole ASIO philosophy of getting out of the way letting the user implement it as he sees best. It looks like the easy vs flexible thing is difficult to get right, happy not to be the one who has to design these things :-p

**Comment by vinniefalco** [comment]
Your proposed interface would certainly work, but it would require a separate timer per timed socket. But like you said it would be making a choice on behalf of the user. Getting the timer behavior right is very tricky. In fact the advanced-server and advanced-server-flex examples are wrong, and fixing them is non-trivial. This is not ideal and I think it needs to be simplified.

**Comment by Eelis** [comment]
To be clear: is the documentation still incorrect in Boost 1.69? Thanks

**Comment by vinniefalco** [comment]
The Javadocs (the description above each function) are probably still wrong, e.g.
https://github.com/boostorg/beast/blob/06efddd8b851610b5b3a5832ac87f1c52b838d9b/include/boost/beast/websocket/stream.hpp#L1758

Fixing these docs is non-trivial...suggestions welcomed.

**Comment by vinniefalco** [comment]
I'm working on this now, I'll see what I can do for 1.70 !

**Comment by vinniefalco** [comment]
Please have a look at this and let me know if it is sufficient or containers errors?
https://github.com/vinniefalco/beast/commit/fd959990ed184f4d71950e798ffcd6533df65e48

Thanks!

**Comment by vinniefalco** [comment]
@RedDwarf69 there is new information regarding timeouts in websocket streams:

> I am working on a new class `timed_socket`

This class is almost finished, but it is not appropriate for websocket for precisely the reasons that you specified. However, I am taking the lessons learned from writing this class and applying it to making the `websocket::stream` timeout enabled (with appropriately configurable user settings). It can automatically send the ping and handle the pong for you. Basically you set an option and forget about it, and everything Just Works. This is rather complicated but it will eventually arrive. I've been laying the foundations for it with some of the other changes (like `close_socket`, needed for timeouts).

**Comment by Eelis** [comment]
Very nice!

A minor nit: the Thread Safety notes talk about code that's "well-formed" and "ill-formed" presumably to suggest when UB may be expected, but the standard uses "well-formed" to [mean](http://eel.is/c++draft/defns.well.formed):

> constructed according to the syntax rules, diagnosable semantic rules, and the one-definition rule

**Comment by vinniefalco** [comment]
> the Thread Safety notes talk about...

I'm not seeing this, do you have a link? Here's the file:

https://github.com/vinniefalco/beast/blob/v212/include/boost/beast/websocket/stream.hpp

(or maybe you meant a different file?)

**Comment by Eelis** [comment]
I meant the Thread Safety notes at https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket/notes.html from the opening post in this issue
