### ISSUE TITLE
Documentation for BodyReader

### ISSUE THREAD

**Issue by computerquip-streamlabs** [boostorg/beast#1219]
I noticed when I was implementing a custom BodyReader that when put was called, it wasn't obtaining new data on subsequent calls. I couldn't figure out how the hell to accomplish this until I started searching for alternative ways of parsing the body. Turns out the documentation for this is in [here](https://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/ref/boost__beast__http__basic_parser/put.html) despite being unrelated to BodyReader in practice, especially when it barely mentions the two on any given page

If the two have the same behavior, perhaps a concept abstracting that interface could be created and then the documentation be unified for the two.

**Comment by vinniefalco** [comment]
**BodyReader** and `basic_parser` are quite different although they have similarly named members (`put`). The documentation you linked is something that users rarely need to call, if ever. Why aren't you simply using one of the overloads of `read` or `async_read`? Can you please describe the problem you encountered in a little more detail, so I can determine what changes need to be made, if any? Thanks.

**Comment by computerquip-streamlabs** [comment]
I'm using the Body concept for the purpose of parsing and serialization of a simple text file where a full entry is delimited by a newline. I see [async_read_some](https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/ref/boost__beast__http__async_read_some.html) but it seems to require I pass a parser. I can pass the default parser (base_parser) and parse the message out of the buffer each time the read handler is called, then consume only the bytes parsed. I also appear to be able to pass my own "derived" parser implementation. So there's to be three ways to do the same thing and upon looking into it, I still can't decide which one is best. I'm inclined to keep my Body concept implementation simply because I've already written it. 

I'd also like to mention how hard it is to navigate the documentation in general. For instance, just finding the signature for `async_read_some`, being a free standing function, is actually hard to find and seems to be behind a hidden page (which is one reason I didn't use it, given I didn't think it existed). I actually found that in the headers and then used google to find the page. Am I just not looking in the right place? Perhaps an overall reference page like asio has would be useful.

**Comment by computerquip-streamlabs** [comment]
I don't mean to be nitpicky but really, this is some of the most difficult documentation I think I've ever seen. I feel like it's basically unusable until I understand everything about the entire library else there's good chance I'm going to do something wrong which is just weird. It's not explained where parsers are given, except on the basic_parser page. If I don't know to look for basic_parser, I'm not going to find async_read_some. The [custom parser page](https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/using_http/custom_parsers.html) doesn't explain where to give the custom parser or how it fits into the pipeline. If I don't know that async_read_some is what takes a parser (and can't be used by async_read apparently?) and the only example is using a synchronous read function which is unrelated to what I want, I'm not sure what's expected here.

**Comment by computerquip-streamlabs** [comment]
I don't mean to be nit picky. This documentation is some of the hardest to navigate in my opinion. It doesn't clearly connect the concepts I feel and it's easy to get led astray. It's not clear how to use `async_read_some` or that it even exists. It's also not clear how work with a derived parser using an asynchronous parser. It's also hard to figure out where you would use the differing concepts. Some of the frustration I can't really explain very well but it's worse than the usual Boost documentation and I've been led down the rabbit hole I feel like every single turn I've made in this library. Once everything works, it has worked well. But it's just the initial learning curve, where apparently you can implement an entire concept for parsing without realizing it's not necessary. This documentation, where some pages are behind hidden pages for some reason and others are behind weird padded pages. For instance, why is `async_read_some` not documented in [Stream Operations](https://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/using_http/message_stream_operations.html) when it's actually important?

**Comment by computerquip-streamlabs** [comment]
Not sure how I missed that reference at the bottom there so many times. I even used the index there (though far less useful in navigation when you're not already associated with everything). 

> I'm not sure what you mean by "default parser" or "base_parser". Neither of those are found in Beast.
By base parser / default parser, I meant basic_parser. 

Body Implementation (writer still missing):
```
template <class Map>
class basic_manifest_body {
public:
	using value_type = Map;

	class reader;
};

//####################################
//# Manifest Body Parser/Reader
//####################################
template <class Map>
class basic_manifest_body<Map>::reader {
	value_type &body;
	Map map{ 1024 * 2 };

public:
	template<bool isRequest, class Fields>
	reader(http::header<isRequest, Fields> &h, value_type &body);

	void init(
	  boost::optional<std::uint64_t> const &content_length,
	  boost::system::error_code &ec
	);

	template<class ConstBufferSequence>
	size_t put(
	  ConstBufferSequence const &buffers,
	  boost::system::error_code &ec);

	template <class ConstBuffer>
	size_t handle_buffer(
	  ConstBuffer const &buffer,
	  boost::system::error_code &ec);

	size_t handle_matches(boost::cmatch &type);

	void finish(boost::system::error_code& ec);
};

template <class Map>
template <bool isRequest, class Fields>
basic_manifest_body<Map>::reader::reader(
  http::header<isRequest, Fields>& header,
  value_type& body
) : body(body) {
	boost::ignore_unused(header);
}

template <class Map>
void basic_manifest_body<Map>::reader::init(
  boost::optional<std::uint64_t> const& content_length,
  boost::system::error_code& ec
) {
	boost::ignore_unused(content_length);

	ec.assign(0, ec.category());
}

template <class Map>
size_t basic_manifest_body<Map>::reader::handle_matches(boost::cmatch &matches)
{
	std::string checksum(matches[1].first, matches[1].length());
	std::string file(matches[2].first, matches[2].length());
	
	/* Yo dawg, I heard you like move semantics. */
	map.emplace(move(std::make_pair(move(checksum), move(file))));

	return matches.length();
}

template <class Map>
template <class ConstBuffer>
size_t basic_manifest_body<Map>::reader::handle_buffer(
  ConstBuffer const &buffer,
  boost::system::error_code &ec
) {
	/* Parse line by line until we can't parse no more.
	 * TODO: Hardcoded for SHA-256 checksums. */
	static const boost::regex manifest_regex("([A-Fa-f0-9]{64}) ([^\r\n]+)\r?\n");

	boost::cmatch matches;

	bool regex_result;
	size_t accum = 0;
	
	for (;;) {
		regex_result = boost::regex_search(
			(const char *)buffer.data() + accum,
			(const char *)buffer.data() + buffer.size(),
			matches, manifest_regex);

		if (!regex_result) break;

		accum += handle_matches(matches);
	}

	if (buffer.size() != accum)
		ec = http::error::need_more;

	return accum;
}

template <class Map>
template<class ConstBufferSequence>
size_t basic_manifest_body<Map>::reader::put(
  ConstBufferSequence const &buffers,
  boost::system::error_code &ec
) {
	size_t accum = 0;

	for (
	  auto buffer_it = boost::asio::buffer_sequence_begin(buffers);
	  buffer_it != boost::asio::buffer_sequence_end(buffers);
	  ++buffer_it
	) {
		accum += handle_buffer(*buffer_it, ec);
	}

	return accum;
}

template <class Map>
void basic_manifest_body<Map>::reader::finish(boost::system::error_code &ec)
{
	ec = {};
}

using manifest_body = basic_manifest_body< std::unordered_map<std::string, std::string> >;
```

I then have some handling code that looks like this:
```
	auto &socket = request_ctx->socket;
	auto &response_buf = request_ctx->response_buf;
	auto &response = request_ctx->response;

	auto read_handler = 
	[&client_ctx, request_ctx]
	(auto i, auto e) {
		handle_manifest_response(i, e, client_ctx, request_ctx);
	};

	http::async_read(socket, response_buf, response, read_handler);
```

where `resopnse_buf` is of type `beast::flat_buffer` and response is of type `http::response<manifest_body>`.

**Comment by vinniefalco** [comment]
> why is async_read_some not documented in Stream Operations when it's actually important?

You wrote "Stream Operations" but the docs actually state "Message Stream Operations:"

<https://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/using_http/message_stream_operations.html>

Those functions form the message-oriented interfaces, since they transact entire messages at once. `async_read_some` obviously does not transact a complete message per call. You can find it in the "Parser Stream Operations" section:

<https://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/using_http/parser_stream_operations.html>
