### ISSUE TITLE
Is it possible to set up an IP for a websocket connection?

### ISSUE THREAD

**Issue by litwr2** [boostorg/beast#1226]
I use the next code for this task.

        boost::asio::io_context ioc;
        ssl::context ctx{ssl::context::sslv23_client};
        load_root_certificates(ctx);
        tcp::resolver resolver{ioc};
        websocket::stream<ssl::stream<tcp::socket>> ws{ioc, ctx};
        auto const results = resolver.resolve(host, port);
        /* start of the setting of IP address */
        ws.next_layer().next_layer().open(boost::asio::ip::tcp::v4());
        ws.next_layer().next_layer().bind(boost::asio::ip::tcp::endpoint(
                        boost::asio::ip::address::from_string("51.52.10.5"), 0));
        /* end of the setting of IP address */
        boost::asio::connect(ws.next_layer().next_layer(), results.begin(), results.end());
        ws.next_layer().handshake(ssl::stream_base::client);
        ws.handshake(host, dir);

It works but not the way required for me.  I want to use two websocket connections using two different IP addresses but the code when it is called for the second connection overwrites IP address set for the first connection.  Is there a way to use beast in the way required for me?  A lot of thanks in advance for any hint.

**Comment by vinniefalco** [comment]
The issue is with Asio not Beast. You are trying to use the free function `boost::asio::connect` with a range of addresses. This will not work, because as you noted the binding is lost each time `connect` visits a new item in the range of results. Instead, you should simply write out the loop manually and call `ws.next_layer().next_layer().connect` yourself.

**Comment by litwr2** [comment]
Thanks! The next line does the trick.

ws.next_layer().next_layer().connect(*results);

**Comment by vinniefalco** [comment]
That works too!
