### ISSUE TITLE
Question about concurrent reads/writes.

### ISSUE THREAD

**Issue by aspartamed** [boostorg/beast#1229]
I am trying to understand the boundaries of thread safety. I had some trouble working with the async calls trying to create a continuous read and write. What I have done is create 3 threads one that manages reads and one that manages writes and on that is the business logic

I am using the synchronous calls to read and write. So is it thread safe to concurrently call a synchronous read at the same time as a write? what about close?

**Comment by vinniefalco** [comment]
None of the algorithms in Beast are thread-safe (i.e. safe to call concurrently). However, `websocket` does allow one of each operation (read, write, ping/pong, close) to be active at the same time:
https://www.boost.org/doc/libs/1_68_0/libs/beast/doc/html/beast/using_websocket/notes.html
