### ISSUE TITLE
Does Beast Provide a Way to Get IP Address From Domain Name?

### ISSUE THREAD

**Issue by DragonOsman** [boostorg/beast#1234]
My question is as the title suggests: Is there a way in Beast to get an IP address from a domain name, or do I have to find out how to do this manually?  Thanks in advance for replies.

**Comment by vinniefalco** [comment]
Beast doesn't know anything about TCP/IP or domain names. You should already be familiar with Boost.Asio, the class you are looking for is `boost::asio::ip::tcp::resolver`. Also, the Beast examples demonstrate how to perform DNS lookups:
https://github.com/boostorg/beast/blob/1da229a27c6f0539d422bcedbcf47cfe2517164a/example/http/client/sync/http_client_sync.cpp#L57
