### ISSUE TITLE
Upgrading HTTPS requests to WebSocket

### ISSUE THREAD

**Issue by firewave** [boostorg/beast#1235]
I have existing working code which upgrades a HTTP request to a WebSocket one based on the code as found under _Passing HTTP Requests_ at https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html

Now that code has to be updated to do the same for HTTPS. That seems to be problematic as it is not possible to use an existing ```boost::asio::ssl::stream<tcp::socket>``` when creating a ```websocket::stream<boost::asio::ssl::stream<tcp::socket>>```. I checked various implementation and all of those start out with a ```websocket::stream``` already and access the ssl one via ```next_layer()```. So I was wondering if that was the way to do this or if there also exists an easy way to do the upgrade as there is for HTTP.
 
I am using Boost 1.67.

**Comment by vinniefalco** [comment]
> it is not possible to use an existing boost::asio::ssl::stream<tcp::socket> when creating a websocket::stream<boost::asio::ssl::stream<tcp::socket>>

That's what `beast::ssl_stream` is for, it makes the thing movable, allowing the websocket stream to be move-constructible . See:
https://www.boost.org/doc/libs/1_68_0/libs/beast/doc/html/beast/ref/boost__beast__ssl_stream.html
https://github.com/boostorg/beast/blob/1da229a27c6f0539d422bcedbcf47cfe2517164a/example/advanced/server-flex/advanced_server_flex.cpp#L548
https://github.com/boostorg/beast/blob/1da229a27c6f0539d422bcedbcf47cfe2517164a/example/advanced/server-flex/advanced_server_flex.cpp#L559

Note: You might need Boost 1.68 for these to be available to you.

**Comment by vinniefalco** [comment]
1.67 also has it, but it is in the examples/ directory instead:
https://github.com/boostorg/beast/blob/b4cb4f1fd3d9d1eca90f44e59e1ca0b5260d0c13/example/common/ssl_stream.hpp

**Comment by firewave** [comment]
I was able to do the upgrade using the class from the 1.67 examples for now. Thanks for pointing that out!
