### ISSUE TITLE
How do I initialize a response_parser<file_body>?

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/beast#1239]
I know reading to a file with a `response<file_body>` will get the "body limit exceeded".

However, when I change my `file_parser_` from `response<file_body>` to `response_parser<file_body>` I can no longer use `file_parser_.body().open(this->filename_, boost::beast::file_mode::write, ec_file)` to open the file so I get:

```
Assertion failed: (body_.file_.is_open()), function init, file /usr/local/include/boost/beast/http/basic_file_body.hpp, line 465.
```

This is because `file_parser_.body()` doesn't exist for `response_parser`. 

Is there another function to open the file the `response_parser` will use? 

Or do I have to incrementally read to another `parser<string_body>` and manually save it into the file little by little?

**Comment by vinniefalco** [comment]
You can access the messaged stored in the parser by calling `parser::get`:

```
file_parser_.get().body().open(
    this->filename_, boost::beast::file_mode::write, ec_file);
```

**Comment by alandefreitas** [comment]
Thanks!
