### ISSUE TITLE
About NetWrok Blocking problem by using beast

### ISSUE THREAD

**Issue by lls2wow** [boostorg/beast#1246]
Hi , @vinniefalco 
      Trouble you again , Rencently I use beast write many net tools from my work. Like websocket, http , using ssl or not. but every program has a same problem . When I run much instances of my program. Sometimes later , the entire local area network will be blocked.(with very small flow) Either the web browser can`t work. But I closed my program all , network get to work. Reflected to my code , for some reason I always create the websocket or http client frequently. 

       Like the http sync , 
```
CHttpClient::~CHttpClient()
{
	boost::system::error_code ec;
	sock.shutdown(tcp::socket::shutdown_both, ec);
}
```

 Or websocket code ：
```
void wssession::on_close(boost::system::error_code ec)
{
// 	boost::system::error_code ecc;
// 	socket_.next_layer().shutdown(boost::asio::socket_base::shutdown_both, ecc);
// 	socket_.next_layer().close();

	async_teardown(role_type::client, socket_.next_layer(), std::bind(
		&wssession::on_teardown,
		shared_from_this(),
		std::placeholders::_1));
}

void wssession::on_teardown(boost::system::error_code ec)
{
	state_ = state_close;
	sig_close();
}

```

I always remember to close the socket resource , But it seems not work good. 

when there`s many Network requests, net will be blocked.
Is there something wrong from my code, or any other resources I did not handle?

**Comment by lls2wow** [comment]
Only shallow, I think I did not describe the problem correctly, could you help me ?

**Comment by vinniefalco** [comment]
I have no ideas
