### ISSUE TITLE
Connection reset by peer error

### ISSUE THREAD

**Issue by bcc791** [boostorg/beast#1248]
I am using the latest version of the boost::beast library (i.e version: 1.68)

I was trying the `sync websocket ` client with ssl (very similar to the provided example) and after many hours of correctly receiving data from the server my code terminated with the following error:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
what(): Connection reset by peer
```
What is  causing this error? If this is unavoidable, should I catch the exception in my read loop and reconnect if it happens?

**Comment by vinniefalco** [comment]
It means that the remote peer forcibly closed the connection:
https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean

There is nothing you can do about it, and you should either catch the exception or handle the error by using the interfaces which have `error_code&` parameters.

**Comment by vinniefalco** [comment]
That could mean that the remote host closed the connection non-gracefully.
