### ISSUE TITLE
Changing file position is advised in http::file_body but no methods provided for it

### ISSUE THREAD

**Issue by krasnorutsky** [boostorg/beast#1260]
http::file_body has a good and convenient way for downloading large files by opening them with file_mode = append_existing. In the documentation (file_base.hpp) It is also advised to change file position:
"The current file position shall be set to the end of
        the file prior to each write."
But I can't see any methods for accomplish this using basic_file_body<File>::value_type class. Moreover, I see that "File file_" is private (not protected) - so I cannot add this functionality by overriding the class. I have to completely rewrite the class to accomplish the desired behavior.

Please add the necessary method (or an additional file_mode) for conveniently downloading large files.

**Comment by kaptenhonek** [comment]
I stumbled upon this as well, I solved it by manually creating a file object. Something like this:

```c++
boost::beast::http::response_parser<boost::beast::http::file_body> parser;
boost::system::error_code ec;
boost::beast::file file;
file.open("/path/to/file", boost::beast::file_mode::append_existing, ec);

//Seek to the end of the file
auto size(file.size(ec));
if (size > 0) {
    file.seek(size, ec);
}

//Put the file into the body
parser.get().body().reset(std::move(file), ec);

//...continue with read/async_read
```

**Comment by nickolasrossi** [comment]
For now, is there any harm in adding an accessor for the File to basic_file_body?

`File& basic_file_body<File>::value_type::file() { return file_; }`

I am trying to customize the File itself - computing a hash during the download - and need to get the hash out of my File object. To do this I have to return out a shared_ptr to internal state that I can access after the reset() move, among other complications.

If safe, I can pull-request this change, it's simple.

**Comment by nickolasrossi** [comment]
For now, is there any harm in adding an accessor for the File to basic_file_body?

`File& basic_file_body<File>::value_type::file() { return file_; }`

I came upon a need for this as well, trying to customize the File type and needing the reference to it without resorting to passing along a shared_ptr to internal state.

If it's safe, I can pull-request this change, it's simple.

**Comment by vinniefalco** [comment]
Yes I think we can add that safely

**Comment by mika-fischer** [comment]
This would also help with #1810. Any progress on this?
