### ISSUE TITLE
Boost.Coroutine is now deprecated

### ISSUE THREAD

**Issue by bcc791** [boostorg/beast#1262]
This is a question not a bug:

I was trying to build the websocket co-routine example, but I get the Boost.Coroutine deprication warning. I am using Boost 1.68. Is it because `asio` still using the old  co-routine library?

```
 #  warning                  "Boost.Coroutine is now deprecated. Please switch to Boost.Coroutine2. To disable this warning message, define BOOST_COROUTINES_NO_DEPRECATION_WARNING."
    ^~~~~~~
```

**Comment by vinniefalco** [comment]
> I am using Boost 1.68. Is it because asio still using the old co-routine library?

Yes. This is a sore subject, lol! That warning can be safely ignored. If the author of Boost.Coroutine removes the old coroutine library completely (which works perfectly fine and doesn't need to be fiddled with) then the author of Asio will likely just inline the relevant code into the Asio project itself. 

In other words, Keep Calm and Carry On.
