### ISSUE TITLE
bad_version error with boost::beast::http::async_read_some

### ISSUE THREAD

**Issue by Maratk1n** [boostorg/beast#1264]
Hello!

I am trying to read data asynchronously and write it to a file.
The sequence is as follows:
1. Read the header
2. Read the target using the function `boost::beast::http::async_read_some`.
But I get an error `boost::asio::error::bad_version` when trying to read the target. I have not found a single example of using the function `async_read_some`. How to use it correctly?

My implementation:

```
void AsyncHttpClient::onReadHeader(boost::system::error_code ec, std::size_t bytes_transferred)
{
  boost::ignore_unused(bytes_transferred);

  if(ec) {
    return fail(ec, "read header");
  }
  std::cout << res_.get().base() << std::endl;

  if (file_.is_open()) {
    file_ << res_.get().body();
  }

  // If we read the header, we can start reading content chunk by chunk.
  if (https_mode_) {
    // Receive the HTTP response
    boost::beast::http::async_read_some(stream_, buffer_, chunk_res_, std::bind(&AsyncHttpClient::onRead, this, std::placeholders::_1, std::placeholders::_2));
  }
  else {
    // Receive the HTTP response
    boost::beast::http::async_read_some(socket_, buffer_, chunk_res_, std::bind(&AsyncHttpClient::onRead, this, std::placeholders::_1, std::placeholders::_2));
  }
}
void AsyncHttpClient::onRead(boost::system::error_code ec, std::size_t bytes_transferred)
{
  boost::ignore_unused(bytes_transferred);

  if(ec && ec.value() != boost::asio::error::eof) {
    return fail(ec, "read content"); // here I get error "bad version"
  }

  if (ec.value() != boost::asio::error::eof) { // continue loading
    if (file_.is_open()) {
      file_ << chunk_res_.get().body();
    }

    if (https_mode_) {
      // Receive the HTTPS response
      boost::beast::http::async_read_some(stream_, buffer_, chunk_res_, std::bind(&AsyncHttpClient::onRead, this, std::placeholders::_1, std::placeholders::_2));
    }
    else {
      // Receive the HTTP response
      boost::beast::http::async_read_some(socket_, buffer_, chunk_res_, std::bind(&AsyncHttpClient::onRead, this, std::placeholders::_1, std::placeholders::_2));
    }
  }
  else {
    file_.close();
    std::cout << std::endl;
    std::cout << "Download completed." << std::endl;
    if (https_mode_) {
      // Gracefully close the stream
      stream_.async_shutdown(std::bind(&AsyncHttpClient::onShutdown, this, std::placeholders::_1));
    }
    else {
      // Gracefully close the socket
      socket_.shutdown(boost::asio::ip::tcp::socket::shutdown_both, ec);
      // not_connected happens sometimes so don't bother reporting it.
      if(ec && ec != boost::system::errc::not_connected) {
          return fail(ec, "shutdown");
      }
      // If we get here then the connection is closed gracefully
    }
  }
}
```
Variables types:
```
boost::beast::flat_buffer buffer_;
boost::beast::http::response_parser<boost::beast::http::string_body> res_;
boost::beast::http::response_parser<boost::beast::http::string_body> chunk_res_;
```
Thanks for any help!

**Comment by vinniefalco** [comment]
What do the incoming bytes look like?

**Comment by Maratk1n** [comment]
> What do the incoming bytes look like?

In `AsyncHttpClient::onReadHeader` I get:
```
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.6.6
Date: Mon, 08 Oct 2018 17:04:04 GMT
Content-type: image/jpeg
Content-Length: 60241
Last-Modified: Mon, 08 Oct 2018 11:39:51 GMT
```
but in `AsyncHttpClient::onRead` `bytes_transferred=0`

**Comment by vinniefalco** [comment]
Are you trying to use the `response_parser` more than once?

Also, you might want to use `http::file_body` if you are writing to a file.

**Comment by Maratk1n** [comment]
> Are you trying to use the `response_parser` more than once?

No. I'm using `boost::beast::http::response_parser<boost::beast::http::string_body> res_;` for parse header, and using `boost::beast::http::response_parser<boost::beast::http::string_body> chunk_res_;` for parse parts of content with `async_read_some`. 

> Also, you might want to use `http::file_body` if you are writing to a file.

I tried to do it:
`boost::beast::http::response_parser<boost::beast::http::file_body> chunk_res_;`, but get error in this place:
`file_ << chunk_res_.get().body();`
`/usr/include/c++/7/ostream:682: error: no type named ‘type’ in ‘struct std::enable_if<false, std::basic_ostream<char>&>’`

**Comment by vinniefalco** [comment]
You should not be using two different parsers. Just use `res_` for both the header and the body. And if you want to re-use the parser you have to destroy it and reconstruct it. You can do that easily by putting it inside an `optional` and calling `emplace` every time you need to reuse it.

**Comment by Maratk1n** [comment]
> You should not be using two different parsers. Just use `res_` for both the header and the body. And if you want to re-use the parser you have to destroy it and reconstruct it. You can do that easily by putting it inside an `optional` and calling `emplace` every time you need to reuse it.

Thank for your answer! Can you give me short example, please? 
I tried do as well as [there](https://www.boost.org/doc/libs/1_66_0/libs/beast/example/http/server/fast/http_server_fast.cpp), but it can't help me.
And how I can set max buffer size when work with `async_read_some`?

**Comment by vinniefalco** [comment]
Use
```
boost::optional<boost::beast::http::response_parser<boost::beast::http::string_body>> res_;
```

And then, to reset the parser for reuse, do:
```
res_.emplace();
```

**Comment by vinniefalco** [comment]
Also, this is wrong:
```
if (ec.value() != boost::asio::error::eof) { // continue loading
```
Because you are bypassing the category check. Instead, you should write:
```
if (ec != boost::asio::error::eof) { // continue loading
```
Not only is this correct, but it is also simpler. A double win!

**Comment by Maratk1n** [comment]
> Also, this is wrong:
> 
> ```
> if (ec.value() != boost::asio::error::eof) { // continue loading
> ```
> Because you are doing a simple integer comparison instead of going through the proper `operator==` overload which also checks the error category. Instead, you should write:
> 
> ```
> if (ec != boost::asio::error::eof) { // continue loading
> ```
> Not only is this correct, but it is also simpler. A double win!

**Comment by Maratk1n** [comment]
> Also, this is wrong:
> 
> ```
> if (ec.value() != boost::asio::error::eof) { // continue loading
> ```
> Because you are doing a simple integer comparison instead of going through the proper `operator==` overload which also checks the error category. Instead, you should write:
> 
> ```
> if (ec != boost::asio::error::eof) { // continue loading
> ```
> Not only is this correct, but it is also simpler. A double win!

Excellent answers! But this trick can't help resolve previous problem. I get same error.

And what about buffer size as in Boost?
[There](https://www.boost.org/doc/libs/1_61_0/doc/html/boost_asio/reference/buffered_read_stream/async_read_some.html) we can configure buffer and its size. Is there such a possibility in a Beast?

**Comment by vinniefalco** [comment]
> Assertion! parser.is_done()' failed

This is fixed by putting the parser in an `optional` and constructing it again via `emplace` after you are done with each message.

> And what about buffer size as in Boost? There we can configure buffer and its size. Is there such a possibility in a Beast?

What is the question?

**Comment by Maratk1n** [comment]
> What is the question?
In Boost we can do 
`socket.async_read_some(boost::asio::buffer(data, size), handler);`
So, can we do something like this?
Now Beast read content after every 512 bytes part by part. Can I increase this limit?

**Comment by vinniefalco** [comment]
See:
https://www.boost.org/doc/libs/1_68_0/libs/beast/doc/html/beast/using_http/buffer_oriented_parsing.html
