### ISSUE TITLE
async_read_some trick to reduce instantiations

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1266]
Instead of using `post`, a composed operation can use `async_read_some` with a zero-length buffer sequence. This will reduce the number of template instantiations, resulting in smaller code, for the case where the composed operation is already calling `async_read_some` elsewhere.

**Comment by vinniefalco** [comment]
We aren't doing this anymore

**Comment by sehe** [comment]
I'm glad. It seemed like a leaky hack that could throw off certain kinds of streams (think of decompressing streams)
