### ISSUE TITLE
websocket::stream is not really AsyncStream, DynamicBuffer, SyncStream, is it?

### ISSUE THREAD

**Issue by RedDwarf69** [boostorg/beast#1268]
According to the bottom of https://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream.html `websocket::stream` is `AsyncStream`, `DynamicBuffer` and `SyncStream`.

I may be missing something obvious. But how can it be a `DynamicBuffer`?
Then it certainly is `AsyncReadStream`/`SyncReadStream`. But since `write_some`/`async_write_some` have the initial `bool fin` parameter they don't meet the requirements of `AsyncWriteStream` and `SyncWriteStream`, do they? And without `AsyncWriteStream`/`SyncWriteStream` they are not `AsyncStream`/`SyncStream`.

**Comment by vinniefalco** [comment]
"Concepts" just means the concepts that you should be familiar with to understand the class. It does not mean that it models those concepts.

**Comment by RedDwarf69** [comment]
Oh, in such a case feel free to close the issue. Unless... do you think somebody else may misread that part of the documentation?

**Comment by djarek** [comment]
@RedDwarf69 websockets deal in frames, while AsyncStreams, as the name suggests, deal in octet streams. You can easily write an adapter that enables stream like operation for a websocket stream, should you need it (e.g. if you were to create a TCP tunnel that works over websocket).
