### ISSUE TITLE
std::logic_error instance thrown -- can't tell what line or where from

### ISSUE THREAD

**Issue by DragonOsman** [boostorg/beast#1276]
When I tried to run my app from my Ubuntu VM after re-building it there, it crashed with the following error message:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```
I've added line numbers to my code to document where errors came from, but this doesn't show line numbers.  So it can't be from my own code.  How do I find out if it's from Beast or from Asio, and what line of code it's from?  And how do I fix the error?

Just in case, I'll also give a link to my own code here: https://gist.github.com/DragonOsman/d00ea7ec3d49c128ad7789293f156a09 .  Any help is appreciated.  Thanks in advance.

**Comment by vinniefalco** [comment]
See: https://markheath.net/post/effective-debugging-with-divide-and-conquer

**Comment by DragonOsman** [comment]
I'll try running it through GDB on CodeBlocks (though when I last tried it on the command line, the program wasn't running when I tried to set a breakpoint and step through the code).
