### ISSUE TITLE
Support work on top of other network libraries.

### ISSUE THREAD

**Issue by kotbegemot** [boostorg/beast#1278]
I have a number of projects that use a lot of boost(1.66-1.68).
Projects are not all on asio as a network layer .
Some Projects are using the implementation of network layer is a combination of libraries: libev + libcurl.
Offer:
Support other network libraries if possible: libev and libuv.

**Comment by vinniefalco** [comment]
> Support other network libraries if possible: libev and libuv.

Hmm....I don't think that's a good idea. Beast is written to work with Networking TS, which will become part of the standard library. One that happens, there is really little reason to use other network libraries since C++ will finally have a standard way to network.

**Comment by kotbegemot** [comment]
Not all developers can use the latest standard.
Developers often use boost(and the latter 1.66-1.xx).
There is a decrease in the audience of developers who use boost .

**Comment by kotbegemot** [comment]
I suggest we return to this issue later and close the task.

**Comment by vinniefalco** [comment]
Support for other networking libraries is considerably out-of-scope for Beast and will likely never happen. However, the `http::message` container, and the `parser` and `serializer` classes should still be usable (with <boost/asio/buffer.hpp>). You would just have to implement the stream algorithms.
