### ISSUE TITLE
Explicit instantation of websocket::stream fails

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#1279]
https://wandbox.org/permlink/NhmB6f9y3wanpVdz

**Comment by djarek** [comment]
@vinniefalco I believe that if `open_pmd` used SFINAE, this problem would go away, because the compiler wouldn't try to instantiate both.

**Comment by vinniefalco** [comment]
it has to instantiate both, how does it know ahead of time which one it will need?

**Comment by djarek** [comment]
https://godbolt.org/z/QltKnm
