### ISSUE TITLE
boost::beast::http::verb::delete_ instead of boost::beast::http::verb::delete?

### ISSUE THREAD

**Issue by lingtjien** [boostorg/beast#1282]
Is there a specific reason why the delete verb has an underscore while all the others don't? It seems rather inconsistent to me, so I assume there is a good reason for that, that I'm currently unaware of?

**Comment by vinniefalco** [comment]
LOL.... think about it carefully :) If you haven't figured it out by tomorrow then I'll give you the answer.

**Comment by lingtjien** [comment]
Oh... reserved keywords... derp my bad 

(I was converting my project from a different REST library which had all capital case for the http verb so it would be GET, POST, PUT, DELETE and I wrote a script to convert all those occurrences from capital to lowercase and stumbled upon this inconsistency, hence the question, thanks)

**Comment by vinniefalco** [comment]
That didn't take long!
