### ISSUE TITLE
Boost Beast CppCon2018 Websockets example - runaway infinite loop on socket close

### ISSUE THREAD

**Issue by forresttales** [boostorg/beast#1284]
Vinnie,
Per the example here,
https://github.com/vinniefalco/CppCon2018/blob/master/websocket_session.cpp

void
websocket_session::
on_read(error_code ec, std::size_t)
{
    // Handle the error, if any
    if(ec)
        fail(ec, "read");

    // Send to all connections
    state_->send(beast::buffers_to_string(buffer_.data()));

    // Clear the buffer
    buffer_.consume(buffer_.size());

    // Read another message
    ws_.async_read(
        buffer_,
        [sp = shared_from_this()](
            error_code ec, std::size_t bytes)
        {
            sp->on_read(ec, bytes);
        });
} 

From the browser, upon 'Disconnect' or closing the web page, the above will toggle, quickly eating up memory and cpu. 
websocket_session::on_read
websocket_session::fail - read: Operation canceled
websocket_session send
websocket_session::on_read
websocket_session::fail - read: Operation canceled
websocket_session send
websocket_session::on_read

As the other functions have it, it looks like you just forgot the "return" ...
    // Handle the error, if any
    if(ec)
        return fail(ec, "read");

**Comment by vinniefalco** [comment]
You're right!! Also this should have gone into the other repo but no prob I will link it. Thanks!

**Comment by forresttales** [comment]
i thought about that. But the other repo has 0 issues. I didn't want to be the "1" ))

**Comment by vinniefalco** [comment]
ROFL... I feel you
