### ISSUE TITLE
Websocket assertion during read() when close() is called

### ISSUE THREAD

**Issue by dmpriso** [boostorg/beast#1289]
### Version of Beast
144
### Steps necessary to reproduce the problem
We are using the synchronous methods to read and write from/to a websocket stream. Specifically, one thread spends most of the time waiting for data in `boost::beast::websocket::stream<Types::Socket&>::read()`, waiting for incoming data.
We then want to initiate closing of the websocket connection by calling `close` on the same stream (but from another thread obviously). As a result, the server answers with a close frame, and we would expect our `read` method to return after having read the response's close frame.

However, sometimes we run into a debug assertion instead: `read.ipp:1072 BOOST_ASSERT(! wr_close_);`

I don't really look through the beast implementation, but the doc states that `close` *sends a close stream ... blocks until ... The close frame finishes sending.*. However, looking at the implementation, `close` also reads the close response and tries to finish the close handshake. My best bet is that something is getting messy cause of the waiting `read` and the reading `close` both trying to read?

**Comment by vinniefalco** [comment]
Like all I/O objects.  `websocket::stream`  objects are not thread-safe. Member functions may not be called concurrently.

**Comment by dmpriso** [comment]
According to the docs, albeit not thread-safe, one may have one `read` and one `write` or `close` operation at a given time:
https://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/using_websocket/notes.html

If not it would be hardly possible to shutdown a websocket in synchronous mode.

**Comment by vinniefalco** [comment]
> one may have one read and one write or close operation at a given time:

Those are asynchronous operations

**Comment by dmpriso** [comment]
OK this renders the synchronous operations useless for our application (and possibly for most others). We will switch to the async calls.

**Comment by vinniefalco** [comment]
Well, that is normal. Synchronous operations are applicable for a smaller range of domains than the asynchronous ones.
