### ISSUE TITLE
The WebSocket handshake was declined by the remote peer

### ISSUE THREAD

**Issue by jingliming** [boostorg/beast#1295]
hello,
i use this command ./websocket-client-sync 10.103.101.158 13578 "hello"
and one error occured "The WebSocket handshake was declined by the remote peer" 
i capture http package, wbesocket server responed "http/1.1 404 not found"
websocket server is unuse beast websocket server
how to fixed it?
tks

**Comment by jingliming** [comment]
the question is solved

**Comment by vinniefalco** [comment]
"Not Found" means that the URI was not recognized by the server

**Comment by jingliming** [comment]
> "Not Found" means that the URI was not recognized by the server

that's true,tks
