### ISSUE TITLE
Beast library gives a lot of warnings in Xcode on macOS

### ISSUE THREAD

**Issue by runesig** [boostorg/beast#1297]
I have used this library for a couple of projects on Windows and I love it. Now I am trying to get it to work on Mac OS. And It does work. However, it gives me a lot of warnings when I try to compile one of the http Beast examples. It is probably me doing something wrong but I can't figure out what it is. 

1. Empty paragraph passed to '@see' command
2. Possible misuse of comma operator here
3. Implicit conversion loses integer precision: 'std::size_t' (aka 'unsigned long') to 'socklen_t' (aka 'unsigned int')

<img width="1512" alt="screen shot 2018-11-11 at 22 11 24" src="https://user-images.githubusercontent.com/2069630/48318345-84aab000-e5ff-11e8-9c62-3b365f9fcca8.png">
<img width="1512" alt="screen shot 2018-11-11 at 22 15 38" src="https://user-images.githubusercontent.com/2069630/48318346-8c6a5480-e5ff-11e8-96d6-6449dc96114c.png">
<img width="1512" alt="screen shot 2018-11-11 at 22 15 47" src="https://user-images.githubusercontent.com/2069630/48318348-92603580-e5ff-11e8-987f-775964796d01.png">

**Comment by runesig** [comment]
Thanks Vinnie. I was able to suppress the comment by setting the warnings "Suspicious Comma" and "Documentation Comments" to "No". From your comments I do think those are safe to ignore. That leaves me with the "Implicit Conversion" warning. That is coming from ASIO as you mentioned. So I reported it there instead.

**Comment by vinniefalco** [comment]
Those "suspicious" commas though... lol

**Comment by runesig** [comment]
Yep, very suspicious, but they have probably not committed a crime.
