### ISSUE TITLE
Does beast already support HTTP2?

### ISSUE THREAD

**Issue by pengweichu** [boostorg/beast#1302]
I would like to use beast to send the push notifications to Apple Push Notification Service, it requires the HTTP2(https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1) support, my question is does beast is support HTTP2 now ?

Thanks!

**Comment by vinniefalco** [comment]
No

**Comment by vinniefalco** [comment]
It is unlikely that Beast will ever support HTTP/2, as there is now a published HTTP/3 specification (based on QUIC).

**Comment by rustyx** [comment]
The proposed HTTP/3 can't be the reason for not wanting to support HTTP/2 (which works today in all major browsers already).
What is the real reason?

**Comment by vinniefalco** [comment]
HTTP/2 (and to some extent HTTP/3) is difficult and complex to implement, probably more difficult than it was to write all of beast in the first place. The amount of value that comes out of implementing a new HTTP version is relatively low compared to the other things I could be working on now (such as automatic websocket timeouts or more multi-threaded server examples).

It would very likely take over a year of focused effort to have HTTP/3, so I have to carefully choose what to work on in order to generate the most value since I am just one person working on this. Now, it doesn't mean that HTTP.Next will never happen, but I have other more high priority things to take care of.

**Comment by ckaminski** [comment]
If you're not partial to windows (where it won't build natively yet), nghttp2 already provides libnghttp2_asio.  

I've built it with cygwin and in docker containers on Windows.   Works great on Linux and Mac.  *shrug*

**Comment by patlecat** [comment]
> 
> 
> If you're not partial to windows (where it won't build natively yet), nghttp2 already provides libnghttp2_asio.
> 
> I've built it with cygwin and in docker containers on Windows. Works great on Linux and Mac. _shrug_

It seems this lib has C++ already integrated and ready to use as you can see here in this file: https://github.com/nghttp2/nghttp2/blob/master/src/nghttpd.cc

**Comment by patlecat** [comment]
> It is unlikely that Beast will ever support HTTP/2, as there is now a published HTTP/3 specification (based on QUIC).
So you planned to add HTTP/3 soon? Do you have a timeline for this?

**Comment by madmongo1** [comment]
I don’t think we have plans to include http3 into beast.
I don’t think we’ve seen a compelling motivation yet.

**Comment by patlecat** [comment]
@madmongo1 Then could nghttp2 be adapted to be used with Beast? It seems they also use asio but do not require it. Have you looked at this option?

**Comment by madmongo1** [comment]
I haven’t looked into nghttp2 as I’m not a maintainer of it. Happy to offer help if the maintainers would like to use beast.

**Comment by jeff-martens** [comment]
Compelling reasons are:
- talking to services that only support HTTP/2+ 
- improving performance by largely removing connection setup time

The lack of support for HTTP/2+ and the lack of support for connection pooling makes Beast irrelevant for use in many microservice architectures.  From my perspective Beast should be considered as an end of life maintenance project at this point.    Fine for existing uses, but should not be considered for new projects.

**Comment by nqf** [comment]
Now Rust's HTTP libraries support http2 and 3, and I sincerely hope that Beast can also support them

**Comment by nqf** [comment]
> [@nqf](https://github.com/nqf) I gave up hope years ago. Better use nghttp2 for this if you need modern protocol support.

I found this simple packaging https://github.com/fantasy-peak/simple_http#
