### ISSUE TITLE
Reduce dependencies of test::stream

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#1308]
`test::stream` has a dependency on a small part of websockets and also transitively pulls in `tcp.hpp` from ASIO. I believe this can be resolved with forward declarations.

**Comment by vinniefalco** [comment]
teardown.hpp is pretty harmless except for the tcp.hpp part

**Comment by vinniefalco** [comment]
I think we're allowed to forward declare stuff from other boost libs, after all they are frozen at the same version so the source is predictable.
