### ISSUE TITLE
Still in CONNECTING state

### ISSUE THREAD

**Issue by Ludea** [boostorg/beast#1324]
Hello, 

I use the websocket server example : https://www.boost.org/doc/libs/1_68_0/libs/beast/example/websocket/server/async/websocket_server_async.cpp

For clients side I use a browser, so I create a javascript app with https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

I can connect to the server, but when I try to send a message, I have the message : `Still in CONNECTING state`.
So I can not read the websocket message.
I use boost 1.68.
Any idea what is wrong?

**Comment by Ludea** [comment]
I use Chrome with plain.
Here my js code : ```socket = new WebSocket('ws://localhost:4000');
socket.onopen = () =>
socket.send("here client");```

I modified the websocket server, to print the message :
```
void websocket_session::on_read(boost::system::error_code ec, std::size_t bytes_transferred)
        boost::ignore_unused(bytes_transferred);

        // This indicates that the session was closed
        if(ec == websocket::error::closed)
            return;

        if(ec)
           fail(ec, "read");
     
        ws.text(ws.got_text());
        std::cout << "message : " << boost::beast::buffers(buffer.data()) <<  std::endl;
        do_read();
}```

**Comment by vinniefalco** [comment]
When you launch the server, are you launching it on port 4000?

**Comment by Ludea** [comment]
```int main()
{                                                                                                 
        try
        {                                                                                          boost::asio::io_context ioc;
                tcp::endpoint endpoint(tcp::v4(), 4000);
                std::shared_ptr<std::string const> const&doc_root = std::mak      $
                tcp_server server(ioc, endpoint, doc_root);
                ioc.run();
        }
        catch (std::exception& e)
        {
                std::cerr << e.what() << std::endl;
        }

        return 0;
}```
I can see the accepted message 
```
void websocket_session::run()
{
        // Accept the websocket handshake
        std::cout <<"Accepted! "<< std::endl;
        ws.async_accept(
            boost::asio::bind_executor(
                strand,
                std::bind(
                    &websocket_session::on_accept,                                                                    shared_from_this(),
                    std::placeholders::_1)));
}
```

**Comment by vinniefalco** [comment]
It works on my end, and no one else has reported this. So the problem must be unique to your configuration. You will need to debug it to figure out why it isn't working.

**Comment by Ludea** [comment]
Sometimes, 'message` is screen into a loop, with empty variable. 
It happens with a websocket tester application (not browser)

**Comment by Ludea** [comment]
Ok, I found where is the issue :
`accept: The WebSocket stream was gracefully closed at both endpoints`

**Comment by Ludea** [comment]
I fix the issue.
It was a client side issue
