### ISSUE TITLE
Use of invalidated allocator in flat_stream::write_op

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#1329]
If flat_stream::write_op is dropped, the Handler is destroyed before the allocated buffer (owned by `unique_ptr`) which may result in the use of an invalidated Allocator.

https://github.com/boostorg/beast/blob/develop/include/boost/beast/_experimental/core/impl/flat_stream.ipp#L60

**Comment by vinniefalco** [comment]
Isn't fixing this as easy as changing the order of the data members?

**Comment by djarek** [comment]
Yes, it would fix this particular issue, but:
- I don't think the Handler's associated allocator is appropriate for use as an allocator for large buffers.
- You still can end up with weird allocator states if the handler throws during move construction and the memory resource is owned by the handler.

**Comment by vinniefalco** [comment]
We need these questions answered, possibly in a paper.

**Comment by vinniefalco** [comment]
Is there any sane way to handle an exception when moving a handler?

**Comment by djarek** [comment]
Assuming the handler owns the memory resource, you have no way of knowing whether the memory resource is valid or not if the move throws.

**Comment by vinniefalco** [comment]
The new implementation no longer uses the associated allocator, have you had a look?

**Comment by djarek** [comment]
Yep, looks fine, too bad there's no way to fix the issue in ssl stream's inability to do proper scatter/gather.

**Comment by vinniefalco** [comment]
> too bad there's no way to fix the issue in ssl stream's inability to do proper scatter/gather.
OpenSSL has a scatter/gather API, asio just needs to use it.
