### ISSUE TITLE
echo-op example does not set SO_REUSEADDR

### ISSUE THREAD

**Issue by octobanana** [boostorg/beast#1335]
The echo-op example does not set the SO_REUSEADDR socket option. It would match the other examples well if it also set it.

**Comment by vinniefalco** [comment]
not a bad idea

**Comment by octobanana** [comment]
See #1336

**Comment by vinniefalco** [comment]
I don't mind if you create an issue before submitting a pull request, but it also isn't necessary. Up to you though, there are pros and cons either way.

**Comment by octobanana** [comment]
I wasn't entirely sure if an issue was required for a pull request, so that's good to know, thanks!
