### ISSUE TITLE
Document flat_stream, ssl_stream, make them public

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1343]
The documentation should include a note about the performance issues with `asio::ssl::stream`

**Comment by vinniefalco** [comment]
`flat_stream` is public now

**Comment by vinniefalco** [comment]
We aren't doing this anymore

**Comment by sehe** [comment]
I strongly remember seeing that Chris added buffer flattening to the ssl::stream implementation in Asio proper.

That might make beast's flat_stream redundant (?), but at the very least means that this issue was actually resolved.

**Comment by vinniefalco** [comment]
Yes it does make it redundant
