### ISSUE TITLE
how to get headers in the websocket server?

### ISSUE THREAD

**Issue by kylejan** [boostorg/beast#1385]
how to get headers in the websocket server?

**Comment by vinniefalco** [comment]
The docs explain it

**Comment by kylejan** [comment]
cannot find the corresponding doc page, could you please post the link? thank u!

**Comment by kylejan** [comment]
is this doc (https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/async_accept_ex.html)?

**Comment by vinniefalco** [comment]
For clients:

https://www.boost.org/doc/libs/1_69_0/libs/beast/doc/html/beast/using_websocket/handshaking_clients.html#beast.using_websocket.handshaking_clients.filtering

For servers:

https://www.boost.org/doc/libs/1_69_0/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html#beast.using_websocket.handshaking_servers.passing_http_requests

The advanced servers demonstrate how to receive the websocket HTTP Upgrade request:

https://www.boost.org/doc/libs/1_69_0/libs/beast/example/advanced/server/advanced_server.cpp

Here:
https://github.com/boostorg/beast/blob/f00237cb35bcb0d3d544db4b80de38f1aba78ab0/example/advanced/server/advanced_server.cpp#L664

**Comment by kylejan** [comment]
it seems that i have to set up a http server before websocket session, is that right?

**Comment by vinniefalco** [comment]
You don't need an "HTTP server" you just need to call `http::async_read` to read the request, inspect the headers, before passing it to `websocket::stream::async_accept`.

**Comment by kylejan** [comment]
thank u! it works on server without ssl now. is that i have to use http ssl::stream to do the ssl handshake before http::async_read in the case of async_ssl_websocket_server?

**Comment by kylejan** [comment]
yes, it works! thanks a lot!

**Comment by vinniefalco** [comment]
> The advanced servers demonstrate how to receive the websocket HTTP Upgrade request:

https://github.com/boostorg/beast/blob/f00237cb35bcb0d3d544db4b80de38f1aba78ab0/example/advanced/server/advanced_server.cpp#L263

**Comment by kylejan** [comment]
i had tried it, the error code will be "uninitialized".

**Comment by vinniefalco** [comment]
Have you compiled and run the advanced server? Does it work for you?

**Comment by kylejan** [comment]
oh i know why i get this error code, because i am not use the same ssl::stream layer in http read and websocket accept. now it works, thanks a lot!
