### ISSUE TITLE
How to efficiently use boost beast web sockets with Angular socket.io?

### ISSUE THREAD

**Issue by nknadim1** [boostorg/beast#1388]
I have developed a simple application to communicate between angular client and Boost Beast server using raw web-sockets. Now I am trying to use socket.io and custom event names but not sure how I can identify those events in the beast server. Currently I am parsing the message sent from Angular client to identify particular event/action in my Beast server.

**Comment by vinniefalco** [comment]
I have no idea about Angular or socket.io, have you tried looking at the documentation for those things?

**Comment by nknadim1** [comment]
I was referring to custom event name which can be specified while sending messages. Seems not possible to use with beast as it is raw web socket.

**Comment by xkungfu** [comment]
hi, is there a solution today?
