### ISSUE TITLE
buffers_suffix max size

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1395]
There should be a way to ask for a prefix of the buffers_suffix, like this:
https://github.com/boostorg/asio/blob/a6008b6427ddfc3222f83c53030c34c802c53b59/include/boost/asio/detail/consuming_buffers.hpp#L96

**Comment by klemens-morgenstern** [comment]
Can you elaborate?

**Comment by vinniefalco** [comment]
Since this is a feature and there is no motivating use-case we should close the issue
