### ISSUE TITLE
add bandwidth measurement

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1397]
to `beast::basic_stream_socket`:

Throughput, total sent/received, etc

**Comment by madmongo1** [comment]
Two methods I would find useful:

```
/// @brief return total bytes sent through the socket since the last reset
std::size_t bytes_sent() const;

/// @brief reset the total-bytes-sent counter and return the current value  
std::size_r reset_bytes_sent(std::size_t = 0);  
```

**Comment by vinniefalco** [comment]
The bandwidth / traffic shaping feature in `basic_stream` is merged, but still needs documentation. The feature requested here, calculating throughput, can be implemented as a user-defined _RatePolicy_ associated with the stream. This should be provided as a complete example in the documentation.

**Comment by vinniefalco** [comment]
This is done https://www.boost.org/doc/libs/1_70_0/libs/beast/doc/html/beast/using_io/layered_streams/counted_stream_example_new.html
