### ISSUE TITLE
Using Beast with a CGI library?

### ISSUE THREAD

**Issue by DragonOsman** [boostorg/beast#1413]
Hi, everyone.  I just wanted to ask if I could use a C++ CGI library with Boost.Beast client code, or if I have to use either one or the other.  And if Boost.Beast client code can be used in a CGI application at all, whether I use an actual library for the CGI part or not.  

Thanks in advance for any replies.

**Comment by vinniefalco** [comment]
This question is overly broad, has nothing to do with Beast, and could be easily answered yourself.
