### ISSUE TITLE
Use `numeric_limits` in `to_static_string`

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#1421]
The max size of the static string should be computed based on `numeric_limits`  rather than `sizeof`.

**Comment by vinniefalco** [comment]
I don't understand. The max size is measured in characters, and the size of the internal storage is N characters (not including the null) so how can this possibly be wrong:
```
    size_type constexpr
    max_size() const
    {
        return N;
    }
```

unless you are thinking of some absurd case where `N == pow(2, 64)-1` ? I could make `N` an unsigned short if you think that would help...

**Comment by djarek** [comment]
What I meant was that `sizeof()` doesn't necessarily determine the max value that can be stored in an integral type. This is quite esoteric and I doubt these kind of architectures would use boost anyway.

Doing the "proper" max size requirement computation in C++11 in constexpr time seems not worth the cost of compilation time (it would need recursion, most likely).

**Comment by vinniefalco** [comment]
To be honest I still do not understand this problem

**Comment by djarek** [comment]
https://github.com/boostorg/beast/blob/develop/include/boost/beast/core/impl/static_string.hpp#L621

The number of digits needed to store an integer as a `static_string<N>` are computed based on `sizeof(Integer)`. On some platforms, `sizeof(char) == sizeof(int) && std::numeric_limits<int>::max() == 65535` is true. On such a platform there would be `int` values that would not fit into the result of `to_static_string()`.

A proper solution would be to compute the size based on `log10(std::numeric_limits<T>::max()) + 2`, which requires recursion (or an approximation of  `log10`). TBH, this is probably way too much of an esoteric problem to handle.

**Comment by vinniefalco** [comment]
OHHHH... `to_static_string`! I read the title as "Use `numeric_limits` in `static_string`"

**Comment by vinniefalco** [comment]
Now that I look at it, `to_static_string` return type should be `__implementation_defined__` or `__see_below__`

**Comment by vinniefalco** [comment]
not worth fixing
