### ISSUE TITLE
Add buffers_empty

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1440]
`buffers_empty(b)` can produce a result faster than `buffer_size(b) == 0`

**Comment by djarek** [comment]
Will this be a customization point?

**Comment by vinniefalco** [comment]
I'd rather not have a customization point. I'm not sure if `buffers_empty` is even a good idea.

**Comment by vinniefalco** [comment]
I see what you mean about a customization point. I have `detail::buffers_empty` now, but I am hesitant to make it public.
