### ISSUE TITLE
How to convert http::request or http::response to string?

### ISSUE THREAD

**Issue by ziwu14** [boostorg/beast#1478]
NT

**Comment by vinniefalco** [comment]
use `operator<<` to `std:;stringstream`

**Comment by ziwu14** [comment]
thx for such a quick reply, it works

**Comment by ziwu14** [comment]
wait, it compiles successfully but print out empty string.

**Comment by vinniefalco** [comment]
Did you do `std::cout << ss.str()` where `ss` is the stringstream?

**Comment by vinniefalco** [comment]
Printing messages works, as this example demonstrates:
https://github.com/boostorg/beast/blob/develop/example/http/client/sync/http_client_sync.cpp#L83

**Comment by ziwu14** [comment]
because I am writing a proxy server being a daemon, so I have to use syslog() to do logging in /var/log, which gets me to convert the request and response to string first.

and the problem is fixed, just like what you said.
