### ISSUE TITLE
How to get the request line

### ISSUE THREAD

**Issue by ziwu14** [boostorg/beast#1479]
GET http://www.google.com/ HTTP/1.1^M
Host: www.google.com^M
User-Agent: curl/7.58.0^M
Accept: */*^M
Proxy-Connection: Keep-Alive^M

I know how to use the iterator and [] operator to extract values for corresponding fields but if there is any member function that extract the request line"GET http://www.google.com/ HTTP/1.1"?

**Comment by vinniefalco** [comment]
https://www.boost.org/doc/libs/1_69_0/libs/beast/doc/html/beast/ref/boost__beast__http__message/target.html
https://www.boost.org/doc/libs/1_69_0/libs/beast/doc/html/beast/ref/boost__beast__http__message/method.html
https://www.boost.org/doc/libs/1_69_0/libs/beast/doc/html/beast/ref/boost__beast__http__message/method_string.html
https://www.boost.org/doc/libs/1_69_0/libs/beast/doc/html/beast/ref/boost__beast__http__message/version.html
