### ISSUE TITLE
revisit http::error::bad_alloc

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1490]
I dont think catching bad_alloc and turning it into an error_code is a great idea

**Comment by djarek** [comment]
This error code is no longer used: https://github.com/boostorg/beast/search?l=C%2B%2B&q=bad_alloc

**Comment by Bak-Jin-Hyeong** [comment]
What about adding `field_limit` like `header_limit` or `body_limit`?

Catching `bad_alloc` in code that calls `io_context::run` makes it difficult to limit memory for certain `basic_parser` instance only.

**Comment by vinniefalco** [comment]
There is no `field_limit`...
