### ISSUE TITLE
Document: master and develop beast require master and develop asio

### ISSUE THREAD

**Issue by xinthose** [boostorg/beast#1492]
OS: Ubuntu 18.04 LTS
Version: latest

I am having compile issues.  Don't you just copy the boost folder to your boost folder?

`git clone https://github.com/boostorg/beast.git`
`cp -r beast/include/boost/* /usr/include/boost`

Then I get compile errors like this:
```
/usr/include/boost/beast/core/detail/stream_base.hpp:15:10: fatal error: boost/core/exchange.hpp: No such file or directory
 #include <boost/core/exchange.hpp>
```
I installed boost like this: `apt install libboost-all-dev`.
This command: `locate exchange.hpp` yields this: `/usr/include/boost/context/detail/exchange.hpp`

How do I get this file: `boost/core/exchange.hpp`?  Is it outside of the .deb package?

**Comment by vinniefalco** [comment]
If you want to use the **develop** or **master** branch of Beast (as it seems like you are doing in your git command) then you also need the develop or master branch of Boost.

**Comment by xinthose** [comment]
OK.  The current version of `[libboost-all-dev](https://packages.ubuntu.com/bionic/libboost-all-dev)` on Bionic (18.04) is 1.65.1.  So, I need to upgrade to at least `1.66.0`?  You do not have any releases before this version?

**Comment by vinniefalco** [comment]
The first version of Boost in which Beast appears is Boost 1.66.0. However, it is suggested that you use the latest version, which contains bug fixes and security fixes.

**Comment by xinthose** [comment]
OK.  I see.  Thank you sir.  Perhaps a note in Requirements should say as such.

**Comment by vinniefalco** [comment]
Okay
