### ISSUE TITLE
Getting extraneous bytes with GET request in aync HTTP SSL example

### ISSUE THREAD

**Issue by Xeverous** [boostorg/beast#1501]
I'm running the https://www.boost.org/doc/libs/1_69_0/libs/beast/example/http/client/async-ssl/http_client_async_ssl.cpp example against [this API](https://poe.watch/api) and **sometimes** getting extraneous bytes in the returned response body.

Note: I removed loading certificates and used `ctx.set_verify_mode(ssl::verify_none);`.

Boost version: 1.69
OpenSSL version: 1.1
Compiler: GCC 8.3.1
Build flags: `-std=c++17 -O3 -pedantic -Wall -Wextra -c -fmessage-length=0 -ffast-math`
OS: Windows 10

Example run:
```
> .\beast_http_client_async_ssl.exe "api.poe.watch" 443 "/leagues"
HTTP/1.1 200 OK
Date: Tue, 05 Mar 2019 21:11:42 GMT
Server: Apache/2.4.29 (Ubuntu)
Cache-Control: max-age=60
Expires: Tue, 05 Mar 2019 21:12:42 GMT
Access-Control-Allow-Origin: *
X-Cache: MISS from api.poe.watch
Transfer-Encoding: chunked
Content-Type: application/json

1d2
[{"id":1,"name":"Hardcore","display":"Hardcore","hardcore":true,"upcoming":false,"active":true,"event":false,"challenge":false,"start":"2013-01-23T21:00:00Z","end":null,"duration":{"total":null,"elapsed":192845502,"remaining":null}},{"id":2,"name":"Standard","display":"Standard","hardcore":false,"upcoming":false,"active":true,"event":false,"challenge":false,"start":"2013-01-23T21:00:00Z","end":null,"duration":{"total":null,"elapsed":192845502,"remaining":null}}]
0
```

What can be the source of `1d2` and `0`? The sequence is sometimes different, usually few extra bytes at the beginning and at the end. The extra bytes are not always present.

I have also found that the existence of extra bytes comes together with absence of X-Cache HIT and Content-Length.

Example correct run:
```
> .\beast_http_client_async_ssl.exe "api.poe.watch" 443 "/leagues"
HTTP/1.1 200 OK
Date: Tue, 05 Mar 2019 21:13:56 GMT
Server: Apache/2.4.29 (Ubuntu)
Cache-Control: max-age=60
Expires: Tue, 05 Mar 2019 21:14:48 GMT
Access-Control-Allow-Origin: *
Age: 7
X-Cache: HIT from api.poe.watch
Content-Length: 466
Content-Type: application/json

[{"id":1,"name":"Hardcore","display":"Hardcore","hardcore":true,"upcoming":false,"active":true,"event":false,"challenge":false,"start":"2013-01-23T21:00:00Z","end":null,"duration":{"total":null,"elapsed":192845628,"remaining":null}},{"id":2,"name":"Standard","display":"Standard","hardcore":false,"upcoming":false,"active":true,"event":false,"challenge":false,"start":"2013-01-23T21:00:00Z","end":null,"duration":{"total":null,"elapsed":192845628,"remaining":null}}]
```

I run the api against few online REST test services, no errors in any of them. Also tried `curl` and issue is not present there either. I have also asked API's author/owner to test it and there is no error on the owner's side.

**Comment by vinniefalco** [comment]
Well those "extraneous bytes" are part of the chunked encoding as indicated in your response header:
```
Transfer-Encoding: chunked
```
Chunked encoding of course omits the Content-Length which explains your other observation.

Did you modify the client? Because the example code is not capable of printing the chunked-encoding delimeters (the `"1d2\r\n"` and the `"0\r\n\r\n"`), those are removed during parsing and never land inside the message object.

**Comment by Xeverous** [comment]
The only modifications I have made is disabling SSL verifying.

**Comment by vinniefalco** [comment]
SSL verification should not have an effect on the interpretation of the body. I am investigating.

**Comment by vinniefalco** [comment]
Ah yes, this is working as designed! `operator<<` merely serializes the message to the output stream. Because the header specifies the chunked transfer encoding, you will see chunked output. The body of course does not contain this, so if you print `res_.body()` you should see only the JSON. The `operator<<` really is there for debugging, to make it easy to see a message.

**Comment by vinniefalco** [comment]
If you simply must have `operator<<` print the message without the chunked encoding, you can edit the message first. Call this function before printing the message:
```
res_.prepare_payload();
```
This will remove the chunked encoding, and insert a Content-Length field with the correct size. Then when you print it with `operator<<` it will not have the chunked output.

**Comment by Xeverous** [comment]
Initially `res_.body()` did not worked for me either, but now I have found the bug in my code:

```cpp
		std::future<boost::beast::http::response<boost::beast::http::string_body>> request =
			async_http_get(ioc, ctx, poe_watch_api::target, poe_watch_api::port, "/leagues");

		ioc.run();

		const std::string& result = request.get().body(); // calls .body() on rvalue
```
