### ISSUE TITLE
Doc Issues

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1502]
`async_base` needs the temporary storage example

**Comment by vinniefalco** [comment]
Omit headings like Description when no text

**Comment by ashtum** [comment]
With the addition of [async_compose](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/async_compose.html) to Asio, I believe there is no reason for users to utilize this type for creating composed operations anymore.
@vinniefalco Should we close this?
