### ISSUE TITLE
Http server with websocket server on same ip with 2 different port 

### ISSUE THREAD

**Issue by Ludea** [boostorg/beast#1507]
Hello, 

I try to setup a websocket server (from https://www.boost.org/doc/libs/1_69_0/libs/beast/example/websocket/server/async/websocket_server_async.cpp) and add an http server (from https://www.boost.org/doc/libs/1_69_0/libs/beast/example/http/server/async/http_server_async.cpp)
The http is an api endpoint. 
I need to start them into localhost, on different port. 
```
tcp::endpoint endpoint(tcp::v4(), 4000);
                tcp::endpoint apiEndpoint(tcp::v4(), 7000);
                tcp_server server(ioc, endpoint);
                listener api(ioc, apiEndpoint, doc_root);
```
The websocket start ( on 5000 port) but not the http server (on 8080 port). 

I try to add some options :

```
acceptor.set_option(boost::asio::socket_base::reuse_address(true), ec);
        if(ec)
        {
            std::cout<< "set_option : "<< ec.message()<<std::endl;
            return;
        }
```
 on both websocket and http server, I still can not start both in same time.
Any idea why?

**Comment by djarek** [comment]
Perhaps you already have something running on port 8080?

**Comment by Ludea** [comment]
I try some ports, like 7000, and nothing change.
I also use netstat to verify the open ports. 
No applications use http server port

**Comment by Ludea** [comment]
It seems an issue port.
I open 2 port, 1 for websocket, 1 for http server. 
The http port is 6000, but, when I do `netstat - tuplen` i see an another port (38882).
If I reboot the http server, a random port is open. 
I specify port 6000 but random port is assigned. 
Is it a bug?

**Comment by djarek** [comment]
It's likely a bug in your code. Note, that if an acceptor is assigned port `0` it will listen on a random port. 
BTW: This isn't a Beast-related issue, but rather an ASIO-related one.

**Comment by Ludea** [comment]
Yes, it is not a beast issue.
I will investigate on the random port
