### ISSUE TITLE
stronger contract on flat_buffer, flat_static_buffer

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1513]
Instead of:

> Buffer sequences returned by basic_flat_buffer::data and basic_flat_buffer::prepare will always be of length one.

We can make a stronger statement:

> The type of buffer sequence returned will be `net::const_buffer` or `net::mutable_buffer`

**Comment by klemens-morgenstern** [comment]
^ This should also take into account the dynamic_buffer developments in boost .asio

**Comment by vinniefalco** [comment]
We have tried to update Beast's usage of dynamic buffers to match the style in Asio and the result has only been extreme pain and breakage. I think I have just accepted that Beast's dynamic buffers are going to be different than the ones in Asio. If anything, we should make this more clear in the documentation.

In my new HTTP library, I am avoiding the use of dynamic buffers entirely, so this becomes a non-problem.
