### ISSUE TITLE
Disable vulnerable versions of SSL/TLS

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#1519]
Anything below TLS1.1 should be considered unsafe:
https://www.globalsign.com/en/blog/disable-tls-10-and-all-ssl-versions/

Usages:
https://github.com/boostorg/beast/search?q=sslv23&unscoped_q=sslv23

**Comment by vinniefalco** [comment]
Pull request?

**Comment by djarek** [comment]
Merged in V233
