### ISSUE TITLE
Port zlib develop branch changes

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#153]
There are a few commits that look like they should be applied to Beast's port of zlib:
https://github.com/madler/zlib/commits/develop

**Comment by xsacha** [comment]
Curious, why has Beast ported zlib? It is only used for tests, correct?

**Comment by vinniefalco** [comment]
Beast provides a public interface to zlib that is header-only C++11! It needs it internally because it supports the WebSocket permessage-deflate extension. There is a full copy of original zlib (in C form) in the tests directory to use for comparison to make sure that Beast's version contains no bugs.

**Comment by alandefreitas** [comment]
#2444 already updated whatever changed in zlib. Is there anything else we should do here?

**Comment by vinniefalco** [comment]
No
