### ISSUE TITLE
Does Beast works with standalone Asio?

### ISSUE THREAD

**Issue by Rowandjj** [boostorg/beast#1535]
use macro ASIO_STANDALONE

**Comment by vinniefalco** [comment]
No

**Comment by swex** [comment]
Are there any plans to making it possible? I see that json, url libs are having standalone mode from beginning. It would be great to have a standalone beast also!

**Comment by madmongo1** [comment]
I actually agree that it would be nice to have. 
@vinniefalco what do we think about this?

**Comment by vinniefalco** [comment]
No can do

**Comment by ecorm** [comment]
Is it just a matter of manpower? Or are there Boost dependencies other than Asio that would be difficult to decouple?

**Comment by ecorm** [comment]
I see now that Kohlhoff uses a [Perl script](https://github.com/chriskohlhoff/asio/blob/master/asio/boostify.pl) to generate a "boostified" version of Asio, and the differences between the two are not trivial.
