### ISSUE TITLE
Feature request: forward declarations for http request/response types

### ISSUE THREAD

**Issue by Eelis** [boostorg/beast#1543]
Suppose a header declares:

    namespace http = boost::beast::http;
    void handle(http::request<http::string_body> const &);

This doesn't require the types to be complete, and so forward declarations for them would suffice. Unfortunately, there doesn't appear to be a Beast header that contains such forward declarations. So in order to be able to declare `handle` above, one currently needs to:

    #include <boost/beast/http/message.hpp>
    #include <boost/beast/http/string_body.hpp>

These two headers combined are almost a hundred thousand lines of code.

**Comment by vinniefalco** [comment]
The correct file for this is `include/boost/beast/http/message_fwd.hpp`

**Comment by tcraigtyler** [comment]
> 
> 
> The correct file for this is `include/boost/beast/http/message_fwd.hpp`

I don't find this file in the repository. Is there a replacement?

**Comment by vinniefalco** [comment]
No

**Comment by klemens-morgenstern** [comment]
is this resolved?

**Comment by ashtum** [comment]
Addressed in #2940.
