### ISSUE TITLE
How to handle HTTP/2 upgrade request?

### ISSUE THREAD

**Issue by brjoha** [boostorg/beast#1547]
I need to build a server that supports both HTTP/1.1 and HTTP/2.  My hope is to leverage Beast and nghttp2 for this purpose, where Beast is HTTP/1.1 only and nghttp2 is HTTP/2 only, and use the Beast message classes in either case.

Where I need some guidance is on how to best handle upgrade to HTTP/2.  My understanding is that upgrade is negotiated with the HTTP upgrade header on an unsecured connection, and TLS ALPN on a secured connection.  Beast documentation on WebSocket upgrade here...

https://www.boost.org/doc/libs/1_69_0/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html

...would seem to suggest an unsecured HTTP/2 upgrade request could be handled similarly.  What about the secured upgrade case?

**Comment by vinniefalco** [comment]
> What about the secured upgrade case?

Hmm... my understanding is that TLS ALPN puts the upgrade request into the ClientHello, which is the first "message" sent on a TLS connection. When using Boost.Asio it is OpenSSL which processes this message (via the `asio::ssl::stream`). This happens in the function `ssl::stream::async_handshake`. By the time Asio or Beast get back control from OpenSSL, the message is already processed.

Therefore, you would have to either inspect the ClientHello yourself to see if an upgrade request is tucked away inside, or use some OpenSSL interface which lets you get at it (I am unfamiliar with OpenSSL, so this interface may or may not actually exist).

The beast `detect_ssl` algorithm does limited parsing of this ClientHello message so you could use that code as a starting point if you want to parse it yourself:
https://github.com/boostorg/beast/blob/5154233350d13a08d70f0a3a46c73bb1093225dd/include/boost/beast/core/detect_ssl.hpp#L96

**Comment by djarek** [comment]
You should set up nginx as a reverse proxy that forwards requests to your Beast backend, something like this:
```upstream https_backend {
server 127.0.0.1:8080;

keepalive 16;
}

server {
listen 443 ssl http2;

location /https/ {
proxy_pass https://https_backend;
proxy_http_version 1.1;
}
}```

Note: I haven't tested this so I'm not sure if it works, might need some tweaking. Also, make sure you have OpenSSL 1.0.2 or higher and that the nginx build you use supports HTTP/2.

**Comment by vinniefalco** [comment]
**NOICE!!!**

**Comment by brjoha** [comment]
Dropping in a proxy is, unfortunately, not practical for my application.  We have the option to defer upgrade, and used fixed HTTP/1.1 or HTTP/2 on a given port for now.  However, it would be nice if Beast were to support an upgrade hooks in the secured case if possible.

**Comment by vinniefalco** [comment]
Surely you can't expect Beast to do any OpenSSL heavy lifting...

**Comment by brjoha** [comment]
I can't argue with preserving the clean separation of session and transport, but the HTTP/2 working group thought otherwise for some reason.

**Comment by vinniefalco** [comment]
Well you can still use Beast to parse the HTTP Upgrade request, but you would be responsible for extracting the serialized HTTP message from the TLS ClientHello record.

**Comment by vinniefalco** [comment]
is this issue actionable?

**Comment by brjoha** [comment]
In the regular upgrade request case, we can follow the websocket example to handle HTTP/2.0.  It's just the SSL/ALPN upgrade request case that is problematic, but there's nothing actionable by Beast.

nghttp2 provides client and server side examples of the ALPN negotiation, so I think we abstract that process and switch to Beast or nghttp2 accordingly...

https://nghttp2.org/documentation/tutorial-client.html
https://nghttp2.org/documentation/tutorial-server.html

**Comment by nqf** [comment]
https://github.com/fantasy-peak/simple_http
