### ISSUE TITLE
Missing ssl.hpp (brew)

### ISSUE THREAD

**Issue by benstadin** [boostorg/beast#1552]
I've installed Boost 1.69.0 on OS X with brew, but it's missing <boost/beast/ssl.hpp>. Is it possible to install it separately, or should I rather build boost from sources?

**Comment by djarek** [comment]
`boost/beast/ssl.hpp` has been added in 1.70.

**Comment by benstadin** [comment]
Thanks for the explanation, this issue can be closed then.
