### ISSUE TITLE
Example not working.

### ISSUE THREAD

**Issue by csm10495** [boostorg/beast#1565]
http_client_sync.cpp example doesn't compile on the latest boost 1.69.

Error	C1083	Cannot open include file: 'boost/beast/core/tcp_stream.hpp': No such file or directory	

Did beast::tcp_stream move?

**Comment by vinniefalco** [comment]
If you want to use the examples from **develop** or **master** then you have to use the corresponding version of Beast. You can't compile the latest examples with the older release.

**Comment by csm10495** [comment]
Ahh. That makes so much sense. Thanks!
