### ISSUE TITLE
support std::byte in vector_body

### ISSUE THREAD

**Issue by maddanio** [boostorg/beast#1567]
### Version of Beast

248

### Steps necessary to reproduce the problem

try to construct a `http::response<http::vector_body<std::byte>>`

### All relevant compiler information

Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix

It would be kinda nice not to have to use uint8_t or similar for receiving raw binary data.

**Comment by vinniefalco** [comment]
Well what is the error?
