### ISSUE TITLE
any tests for "async_write_header", i get an error when use it

### ISSUE THREAD

**Issue by wangjiangw** [boostorg/beast#1584]
i am using beast to implement http chunk demand, in the code, when i use http::wirte_header, the program can work well, but if i replace it with http::async_write_header, the program will crash. next is my code
![image](https://user-images.githubusercontent.com/7013043/56486672-01c14600-650b-11e9-8be9-0f14f70bd51b.png)

**Comment by vinniefalco** [comment]
This issue is lacking the requested information. Please edit the issue to include the information listed above (and delete the text from the template).

**Comment by wangjiangw** [comment]
> This issue is lacking the requested information. Please edit the issue to include the information listed above (and delete the text from the template).

sorry about that, i have post issues above, the code by comments works well, but the async_write_header can cause program crash, thank you for answering my question !

**Comment by wangjiangw** [comment]
> > This issue is lacking the requested information. Please edit the issue to include the information listed above (and delete the text from the template).
> 
> sorry about that, i have post issues above, the code by comments works well, but the async_write_header can cause program crash, thank you for answering my question !

an error occurs in field.ipp, next is the problem 
![image](https://user-images.githubusercontent.com/7013043/56486831-a5aaf180-650b-11e9-9666-cf49a7130f02.png)

**Comment by wangjiangw** [comment]
> This issue is lacking the requested information. Please edit the issue to include the information listed above (and delete the text from the template).

another question, when i send header with chunk setting, can i use a http::response<http::string_body> ? in my case, when i use http::response<http::string_body>, client can not receive the response body string

**Comment by vinniefalco** [comment]
> the async_write_header can cause program crash
Do the examples work for you?

**Comment by wangjiangw** [comment]
> > the async_write_header can cause program crash
> 
> Do the examples work for you?

i have not find enough examples for http::async_write_header，https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/using_http/chunked_encoding.html，this link just show the http::write_header

**Comment by LeonineKing1199** [comment]
Hi wangjiangw, I use Boost too.

`http::async_write_header` does work as advertised. Example passing test here:
https://github.com/LeonineKing1199/foxy/blob/develop/test/session_test.cpp#L150-L185

**Comment by wangjiangw** [comment]
> Hi wangjiangw, I use Beast too.
> 
> `http::async_write_header` does work as advertised. Example passing test here:
> https://github.com/LeonineKing1199/foxy/blob/develop/test/session_test.cpp#L150-L185
> 
> That code does a lot but here is the Beast call the `session` uses:
> https://github.com/LeonineKing1199/foxy/blob/develop/include/foxy/impl/session/async_write_header.impl.hpp#L45-L57

thx, i will read it today to check if helpful for me, thank you!
