### ISSUE TITLE
Query builder

### ISSUE THREAD

**Issue by soroshsabz** [boostorg/beast#1585]
ITNOA

Hi,

Is there any plan to write some facility like `query builder` ? something like [cpprestsdk uri builder](https://github.com/Microsoft/cpprestsdk/blob/master/Release/include/cpprest/uri_builder.h)

thanks for write great library

**Comment by vinniefalco** [comment]
Yes.

**Comment by soroshsabz** [comment]
@vinniefalco Thanks a lot, so this issue mark as feature?

**Comment by vinniefalco** [comment]
Duplicate of https://github.com/boostorg/beast/issues/787
