### ISSUE TITLE
Socket5 proxy in beast

### ISSUE THREAD

**Issue by allen2015555** [boostorg/beast#1604]
Can beast::websocket set socket5 proxy ?
I used to use beast::http set LoaclHost:8888 proxy for check http connect in Fiddler . Now, I need 
use beast::websocket client set Socket5 proxy in my project. I checked the doc of Socket5 proxy and few samples, but I still have no idea how to set Socket5 proxy for beast::websocket client. 
Has anyone implemented it ?
I apologize my English is poor.

**Comment by vinniefalco** [comment]
No.
