### ISSUE TITLE
Library headers use deprecated `buffers` calls

### ISSUE THREAD

**Issue by sehe** [boostorg/beast#1607]
Whe compiling code like:
```
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <iostream>

int main() {
    boost::beast::http::response<boost::beast::http::dynamic_body> res;
    std::cout << res.base() << std::endl;
}
```
With 1.70.0+ without `BOOST_BEAST_ALLOW_DEPRECATED` defined, you static asserts:

```
"The function buffers() is deprecated, use make_printable() instead, or define BOOST_BEAST_ALLOW_DEPRECATED to silence this error."
```

These originate e.g. https://github.com/boostorg/beast/blob/d1dabebd8352ce0e854474837ed11a27cb688edc/include/boost/beast/http/impl/write.hpp#L906

Looks like those uses of `buffers` should be replaced with `make_printable` indeed. (It does work with my test)

**Comment by djarek** [comment]
Should be fixed in v256.

**Comment by Poojabhagat1** [comment]
The function buffers() is deprecated, use make_printable() instead 
   how to find the version in which this change happen?

**Comment by ashtum** [comment]
It happened in Boost 1.70: https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/release_notes.html#beast.release_notes.boost_1_70
This is the specific commit that made the change: https://github.com/boostorg/beast/commit/0006ab3b2bbb2478254eb490679d58a5613c7b0c

**Comment by sehe** [comment]
@Poojabhagat1  and to answer the actual question, this is how you can find the version in which this change happens:

![image](https://github.com/boostorg/beast/assets/324097/3b44e9a6-6e0f-493e-b5ec-82cc86dae776)

```bash
git log -Smake_printable --oneline
git tag --contains 0006ab3b --column 
```

To try that yourself.
