### ISSUE TITLE
Port sharing on Windows using websockets

### ISSUE THREAD

**Issue by blayet** [boostorg/beast#1609]
Is it possible to configure beast and asio to allow port sharing with an independent HTTP library (to which I have source)?
I would like to use beast to add websocket support to an existing application.
Any pointers appreciated.
many thanks
ben

**Comment by vinniefalco** [comment]
What is port sharing?

**Comment by blayet** [comment]
From https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/net-tcp-port-sharing:
"The HTTP.SYS model in which traffic for many different HTTP applications is multiplexed onto a single TCP port has become standard on the Windows platform." etc
So in my case I want my web app to make http and websocket connections (latter using beast) to port 80. I know that a websocket connection can be made by upgrading an http connection so maybe this can work with beast? But I see in the simple websocket server example that a tcp::acceptor is configured with an ip address and port. In this case the "port sharing" I want doesn't happen. Either the http library or beast gets sole access to the port.
We could upgrade our http library to handle the http upgrade to websockets and handle the ws protocol  itself - but I was hoping for an easier route by using beast  (I'm far from being an expert in this area...)
thanks
ben

**Comment by vinniefalco** [comment]
Beast doesn't handle ports or listening sockets, that's up to Asio. So I would suggest you look to Asio to answer your question.
