### ISSUE TITLE
how can i reference the header parameter in reader's constructor of body while its finish being invoked

### ISSUE THREAD

**Issue by yiivon** [boostorg/beast#1624]
I really want to how can i reference the parameter **h**(_header<isRequest, Fields>_) in reader's constructor of body while its finish being invoked:
`
class reader
  | {
  | value_type& body_;
  |  
  | public:
  | template<bool isRequest, class Fields>
  | explicit
  | reader(header<isRequest, Fields>& /**  h **/, value_type& b)
  | : body_(b)
  | {
  | }

`

Thanks so much!

**Comment by vinniefalco** [comment]
Well first you need to give it a name. `h` seems prudent, perhaps remove those comments. Then access it the same way you would access any other variable.

**Comment by yiivon** [comment]
> Well first you need to give it a name. `h` seems prudent, perhaps remove those comments. Then access it the same way you would access any other variable.

So surprised and touched my header so much! Thank you a lot! but i need to visit that variant **h** later in reader's member finish, so maybe i need to hold the reference of **h** inner class reader, but don't know the finall type of header<isRequest, Fields> , and the reader of body is checked in the parser with `static_assert(is_body_reader<Body>::value, "BodyReader type requirements not met");`, i don't know how to hold **h** in class reader so that it can be used later?

Thanks again, and maybe this question take your times, then so sorry about that and just ignoring, i am thankful so much still!

**Comment by vinniefalco** [comment]
>  i need to visit that variant h later in reader's member finish, so maybe i need to hold the reference of h inner class reader, but don't know the finall type of header<isRequest, Fields>

Yeah, this is a problem / limitation with the current API.
