### ISSUE TITLE
Custom data struct for each acceptor thread

### ISSUE THREAD

**Issue by benstadin** [boostorg/beast#1629]
I'm experimenting with the async example and create an io_context with 2x number of CPU cores. 

For performance reasons within my own code, I want to keep some data for each of those threads (e.g. I thereby avoid to maintain an object pool which I require at the moment). 

Does beast offer an option to attach custom data to the acceptor threads?

**Comment by vinniefalco** [comment]
No. I would use `thread_local`.

**Comment by benstadin** [comment]
The problem with thread_local is that it will also initialize the storage unnecessarily for each session. Or can this be avoided?
