### ISSUE TITLE
Http::Verb eq Missing

### ISSUE THREAD

**Issue by FBaumeister** [boostorg/beast#1636]
Hi,
I just came across these lines:
'eq' is not used for comparison of of "CL" and "IND" in Lines 133 and 138, or is this intentional?
Am I missing the point here? :-)

https://github.com/boostorg/beast/blob/6af4c01e5662926372a7e43f3194fe01846a28dd/include/boost/beast/http/impl/verb.ipp#L133
https://github.com/boostorg/beast/blob/6af4c01e5662926372a7e43f3194fe01846a28dd/include/boost/beast/http/impl/verb.ipp#L138

**Comment by vinniefalco** [comment]
That is odd.. investigating! Thanks

**Comment by vinniefalco** [comment]
Verbs must be uppercase, so this is technically not a bug (it works correctly as written). But it looks weird, and preliminary benchmarks suggest using a simple `operator==` performs better.

**Comment by FBaumeister** [comment]
Thank you!
