### ISSUE TITLE
buffer_body issues on binary responses

### ISSUE THREAD

**Issue by leobelen** [boostorg/beast#1637]
I am using the excellent beast api to implement a pseudo micro service but I am facing a problem that I don't see covered on the documentation or examples, as far as I can tell: how to use it to expose a binary object (namely a png image, produced by an OpenCv mat) using a buffer instead of an string or file body. 

So far, I have came up with the following code, based on the http sync server, however although it works, I have my doubts it is on the correct beast idiom. Developed on macOs, with Boost 1.70.0, on Safari, latest incarnations. I have tried to use vector_body for this but without success. 

Now, from this on, how can read the binary from a beast client side? Is there a proper way to do it? So far I have been experimenting directly with a browser, but the idea is to have both ends based on beast on a machine-to-machine system. In this case I was able to use vector_body, however, I am failing to get the std::vector after the response. How should I do that?

Another thing that I am not seeing is who frees the memory allocated by the buffer... 

Server: 
``` cpp
cv::Mat image(2000,4000, CV_8UC3, cv::Scalar(255,255,0));
 std::vector<uchar> *imgBuf = new std::vector<uchar>();
 cv::imencode(".png", image, *imgBuf);

 http::response<http::buffer_body> res{http::status::ok, req.version()};
 res.set(http::field::server, BOOST_BEAST_VERSION_STRING);
 res.set(http::field::content_type, "image/png");
 res.keep_alive(req.keep_alive());
 res.body().data = imgBuf->data();
 res.body().size = imgBuf->size();
 res.prepare_payload();
 return send(std::move(res));
```

Client:
``` cpp
cv::Mat outputImage;
    try
    {
      boost::asio::io_context ioc;

      // These objects perform our I/O
      tcp::resolver m_resolver{ioc};
      tcp::socket m_socket{ioc};

      // Look up the domain name
      auto const results = m_resolver.resolve(this->m_host, std::to_string(this->m_port));

      // Make the connection on the IP address we get from a lookup
      boost::asio::connect(m_socket, results.begin(), results.end());

      // Set up an HTTP GET request message
      http::request<http::string_body> req(http::verb::get, target.c_str(), this->m_version);
      req.set(http::field::host, this->m_host);
      req.set(http::field::user_agent, BOOST_BEAST_VERSION_STRING);

      // Send the HTTP request to the remote host
      http::write(m_socket, req);

      // This buffer is used for reading and must be persisted
      boost::beast::flat_buffer buffer;

      // Declare a container to hold the response
      http::response<http::vector_body<uchar>> res;

      // Receive the HTTP response
      http::read(m_socket, buffer, res);

      // Gracefully close the socket
      boost::system::error_code ec;
      m_socket.shutdown(tcp::socket::shutdown_both, ec);

      // not_connected happens sometimes
      // so don't bother reporting it.
      //
      if (ec && ec != boost::system::errc::not_connected)
        throw boost::system::system_error{ec};

      //.the next two are invalid statements!!!
      std::vector<uchar> imgBuffer(res.body().data(), res.body().size());
      outputImage = cv::imdecode(res.body().data(), cv::IMREAD_UNCHANGED);
   
```
Best in advance, 
Leo.

**Comment by djarek** [comment]
Try
```
cv::imdecode(res.body(), cv::IMREAD_UNCHANGED);
```

BTW: This is not related to Beast, seems more like a question about OpenCV...

**Comment by leobelen** [comment]
Well, in a sense the issue was with Beast... but yes, looking it at it is, you are right. Now, this worked like a charm. However, there is a issue with the server part. It prints a "write: need buffer" and I am almost sure that it is leaking memory. Now, I have tried to switch it to vector_body, but I dont find a way to move my vector to the message body... as res.body().data does not seem to be  assignable... do you know if there is there a way or documentation or example to look at?

**Comment by vinniefalco** [comment]
```
std::vector<char> v;
...
res.body() = v;
```
?

**Comment by badaix** [comment]
Just stumbled upon this issue, while I was searching for the "need_buffer" error, that I got when delivering a `jpg` using a `http::buffer_body`. For me it worked to add 
```
res.body().more = false;
```

Hope that helps.

**Comment by liuziangexit** [comment]
Nice post, but what if i wanna to use boost::beast::http::async_write to send the response asynchronouslly? 
In that case, we need to put the data we are sending on heap, and free it after the send was done, how to do this?
I didn't find any example code about this.

**Comment by vinniefalco** [comment]
can't you put it in the same place you put the `socket`?

**Comment by liuziangexit** [comment]
> can't you put it in the same place you put the `socket`?

ah yes, thats a easier solution
