### ISSUE TITLE
strand/executor issue

### ISSUE THREAD

**Issue by randomcoder91** [boostorg/beast#1639]
Hi,

I used to create strands for my sockets like this.

```
class Test
{
public:
	Test(const asio::ip::tcp::socket& socket) : strand(socket.get_io_service()) {}

private:
	asio::io_context::strand strand;
}
```

With the latest version boost 1.70, how do I create a strand from the asio::ip::tcp::socket. ?
The following doesn't seem to work.

```
class Test
{
public:
	Test(const asio::ip::tcp::socket& socket) : strand(socket.get_executor().context()) {}

private:
	asio::io_context::strand strand;
}
```
Thanks

**Comment by vinniefalco** [comment]
```
boost::asio::io_context ioc;
boost::asio::tcp::socket sock(boost::asio::make_strand(ioc.get_executor()));
```
It is no longer necessary to maintain a separate `strand` object, or to use `bind_executor`.

**Comment by djarek** [comment]
Note that the reason that `.get_executor().context()` doesn't work is that it doesn't necessarily return a type that satisfies the ExecutionContext concept (e.g. `asio::io_context` or `asio::thread_pool`).
This function can also return `asio::execution_context&`, which, counterintuitively, does not satisfy the ExecutionContext concept.

**Comment by randomcoder91** [comment]
Thank you both for your replies. So I must have a boost::asio::io_context object here to init the socket with make_strand.

**Comment by randomcoder91** [comment]
I captured errors using the strand.wrap() handler. What is the way to do it without the strand ?

`asio::async_write(socket, asio::buffer(buf, buflen), strand.wrap(...) { }`

Is it like this ?

`boost::asio::async_write(socket_, reply_.to_buffers(), boost::bind(&connection::handle_write, shared_from_this(), boost::asio::placeholders::error));`

**Comment by djarek** [comment]
`strand.wrap` has been deprecated for some time now. In order to avoid the need for `bind_executor`, you need to construct the socket using the strand:
```
asio::io_context ioc;
asio::ip::tcp::socket s{asio::make_strand(ioc)};
```

**Comment by randomcoder91** [comment]
Thanks you very much. I will try that.
