### ISSUE TITLE
Is it possible in Beast to know the IP address of the client who sends POST request?

### ISSUE THREAD

**Issue by Rabahjamal** [boostorg/beast#1642]
I'm using Beast to implement a RESTful web service, but I want my service to accept POST requests from specific IP only as a kind of authentication. So, does Beast provide a way to know the IP address of the client? Thanks in advance.

**Comment by vinniefalco** [comment]
Beast doesn't know about sockets, that's part of Asio. And yes, Asio sockets can report the IP address of both the remote and local hosts.

**Comment by djarek** [comment]
Note that IP addresses can be spoofed, so this kind of authentication isn't very useful and is, in fact, about as secure as sending passwords over in plain-text.
