### ISSUE TITLE
Unable to use the HTTP SSL example to send a GET request

### ISSUE THREAD

**Issue by haashirashraf** [boostorg/beast#1646]
Hey Vinny,

I'm currently using beast 1.70.0 with clang 8.0.0, im using the asynchronous http ssl example to connect to an endpoint to aggregate FX data, unfortunately you wont be able to reproduce the issue as your ip wont be whitelisted. However the example compiles fine and I use the beast library for other things, the issue is running the following command from terminal works fine:
$ curl "https://tools.dxfeed.com/wintermute/rest/events.json?events=Quote&symbols=EUR/USD:AFX&indent" -D -
however when I try to run the asynchronous HTTP example to send the get request it timesout on async_connect, I am passing the following arguments to the binary generated by your example exactly as is: tools.dxfeed.com 7831 /wintermute/rest/events.json?events=Quote&symbols=EUR/USD:AFX&indent
I am sure I am doing something very simple wrong, I would appreciate your help.

**Comment by haashirashraf** [comment]
Actually Ive just realised that the format of the endpoint is totally wrong.
I'll close the issue!

**Comment by haashirashraf** [comment]
Actually the issue isnt in the request format, which is wrong as stated as the connection cant even be made, sorry for the spamming!

**Comment by vinniefalco** [comment]
Based on your command line, **curl** is using port 443 (the default HTTP/S port), since you did not specify an alternate port. But your Beast command line specifies port 7831. Try using port 443 with Beast.
