### ISSUE TITLE
How to deal with two type of post

### ISSUE THREAD

**Issue by brokensword2018** [boostorg/beast#1654]
I want to write a server with beast,  sometimes the request is http::request<http::string_body>, sometimes is http::request<http::file_body>. the example of server show that the request  can only be defined one type.

**Comment by vinniefalco** [comment]
Yes: https://www.boost.org/doc/libs/1_70_0/libs/beast/doc/html/beast/more_examples/change_body_type.html

**Comment by brokensword2018** [comment]
> Yes: https://www.boost.org/doc/libs/1_70_0/libs/beast/doc/html/beast/more_examples/change_body_type.html

thanks a lot.
