### ISSUE TITLE
string_view returned from the request headers has extra \r\n chars

### ISSUE THREAD

**Issue by oAly** [boostorg/beast#1658]
Hey there,

So whenever I send an HTTP request to my beast server and request the headers from request.base(), the function returns a string_view and appends a /r/n at the end. Is there a reason for that?

I am using the 1.69 Beast version

**Comment by vinniefalco** [comment]
A `string_view` representing an HTTP field name or HTTP field value does not contain a CRLF at the end. Perhaps you are looking past the end of the string? Please provide an example where CRLF (`"/r/n"`) appears at the end of a returned `string_view`. Make sure you also include the value returned by calling `string_view::size()`, in addition to all of the bytes pointed to by `string_view::data()`.
