### ISSUE TITLE
Add verbosity option for unit tests

### ISSUE THREAD

**Issue by bachase** [boostorg/beast#166]
Consider adding a verbosity level to determine when `testcase` identifiers are printed.  Since `BEAST_EXPECT` reports the file/line number, those identifiers are not typically needed.  But if you have multiple pathways to `BEAST_EXPECT` for different test cases, the file/line number are not sufficient to disambiguate the test.

**Comment by vinniefalco** [comment]
I believe this has been addressed - if not, please open a new issue!
