### ISSUE TITLE
Wiki instructions on how to build the tests on Macosx do not work

### ISSUE THREAD

**Issue by dmorilha-twilio** [boostorg/beast#1660]
Wiki instructions on how to build the tests on Macosx do not work:

```
$ echo $OPENSSL_ROOT
/usr/local/opt/openssl
$ time b2 -j2 libs/beast/test cxxstd=11
...
./boost/asio/ssl/detail/openssl_types.hpp:23:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^~~~~~~~~~~~~~~~
1 error generated.

    "clang++" -x c++ -std=c++11 -fvisibility-inlines-hidden -fPIC -m64 -O0 -fno-inline -Wall -g -fvisibility=hidden  -DBOOST_ALL_NO_LIB=1 -DBOOST_ASIO_DISABLE_BOOST_ARRAY=1 -DBOOST_ASIO_DISABLE_BOOST_BIND=1 -DBOOST_ASIO_DISABLE_BOOST_DATE_TIME=1 -DBOOST_ASIO_DISABLE_BOOST_REGEX=1 -DBOOST_ASIO_NO_DEPRECATED=1 -DBOOST_ASIO_SEPARATE_COMPILATION -DBOOST_BEAST_ALLOW_DEPRECATED -DBOOST_BEAST_SEPARATE_COMPILATION -DBOOST_BEAST_TESTS -DBOOST_CHRONO_DYN_LINK=1 -DBOOST_CONTEXT_DYN_LINK=1 -DBOOST_COROUTINES_DYN_LINK=1 -DBOOST_COROUTINES_NO_DEPRECATION_WARNING=1 -DBOOST_FILESYSTEM_DYN_LINK=1 -DBOOST_THREAD_BUILD_DLL=1 -DBOOST_THREAD_POSIX -DBOOST_THREAD_USE_DLL=1 -I"." -I"libs/beast" -I"libs/beast/test/extern" -c -o "bin.v2/libs/beast/test/beast/ssl.test/clang-darwin-10.0/debug/cxxstd-11-iso/threadapi-pthread/threading-multi/visibility-hidden/ssl.o" "libs/beast/test/beast/ssl.cpp"
...
$ find /usr/local/opt/openssl -follow -name conf.h
/usr/local/opt/openssl/include/openssl/conf.h
```

**Comment by djarek** [comment]
Try the instruction from the readme: https://github.com/boostorg/beast#mac-os

**Comment by vinniefalco** [comment]
I don't see any wiki instructions. Do you have a link?

**Comment by dmorilha-twilio** [comment]
@vinniefalco https://github.com/boostorg/beast#mac-os

**Comment by dmorilha-twilio** [comment]
I "solved" by linking `/usr/local/opt/openssl/include/openssl` into `/usr/local/include`

**Comment by dmorilha-twilio** [comment]
to be fair, this sounds more like a problem on **ASIO** than on **BEAST**

**Comment by djarek** [comment]
Hmm, this should be working regardless of where you put OpenSSL, as long as you set the root variable correctly. Maybe some weird caching issues with b2?

**Comment by dmorilha-twilio** [comment]
Yeah, eventually complexity piles up and boost, which is suppose to help, starts creating more problems. I am not sure why **b2** even exists given its weak adoption and the presence of solid alternatives. As I solved my side of things, feel free to close this one if you don't think it belongs in here.

**Comment by snoe925** [comment]
The OS X instructions need to add
```
cp ./libs/beast/tools/user-config.jam $HOME
```
in order for OPENSSL_ROOT to be read from the environment.  Then the brew installed openssl can be found.

**Comment by vinniefalco** [comment]
Feel free to edit the wiki? Let me know if it is not editable (it should be writable)
