### ISSUE TITLE
ssl_stream works unexpectedly when moved from

### ISSUE THREAD

**Issue by mitchellwong** [boostorg/beast#1665]
PLEASE DON'T FORGET TO "STAR" THIS REPOSITORY :)

If you rather keep your project secret, feel free
to email the author at `<vinnie.falco@gmail.com>`; any
private correspondence is treated as confidential.

When reporting a bug please include the following:

### Version of Beast

248

### Steps necessary to reproduce the problem

ssl_stream first{next_stream, ctx};
ssl_stream second{move(first)};

auto next_layer = first.next_layer(); //return reference to nullptr

The standard says in 20.5.3.1 a moved from object must still meet the requirements of the library that's using it.

**Comment by vinniefalco** [comment]
> The standard says in 20.5.3.1 a moved from object must still meet the requirements of the library that's using it.

Yes, that applies to objects **provided by the standard**. `beast::ssl_stream` is not provided by the standard, and so does not need to follow that rule.

**Comment by mitchellwong** [comment]
But `beast::ssl_stream` says that it satisfies [MoveConstructible](http://eel.is/c++draft/concept.moveconstructible), so isn't it opting into being constrained by that rule?

**Comment by djarek** [comment]
> rv's resulting state is valid but unspecified

Valid means the user can either destroy the object or that he can perform any operation that has no precondition,

**Comment by mitchellwong** [comment]
If not being moved from is a prerequisite to all of the members, it'd be helpful if that were documented. I was very surprised on finding this when debugging.

**Comment by vinniefalco** [comment]
I agree, it could have better docs, would you like to make an addition? It could be added to this javadoc comment:
https://github.com/boostorg/beast/blob/develop/include/boost/beast/ssl/ssl_stream.hpp#L33

**Comment by mitchellwong** [comment]
Sorry, I've been busy at work lately. Should I also add that to `websocket::stream`? https://github.com/boostorg/beast/issues/1566
