### ISSUE TITLE
permessage-deflate not working in version 1.70.0

### ISSUE THREAD

**Issue by vcouvert** [boostorg/beast#1666]
Hi,

I'm using version 1.70.0 and it seems that websocket compression does not work even when setting the right options before calling async_accept:
    boost::beast::websocket::permessage_deflate opt;
    opt.client_enable = true;
    opt.server_enable = true;
    opt.compLevel = 3;
    ws.set_option(opt);

I use Wireshark to check compression and the only way I found to make compression work was to force wr_compress to true in stream_impl.hpp (Line 102).

Did I miss anything?

Thanks for your help and your work on Beast!

**Comment by djarek** [comment]
Does the client offer that it supports compression in the upgrade request?

**Comment by vcouvert** [comment]
Hi,

The client is Google Chrome so I think it supports compression but perhaps I'm wrong.
What I don't understand is the fact that I need to modify the code of Beast to enable compression.

**Comment by vinniefalco** [comment]
> What I don't understand is the fact that I need to modify the code of Beast to enable compression

That sounds weird, I am investigating.

**Comment by vinniefalco** [comment]
Big bug, thanks for the report!

**Comment by vcouvert** [comment]
Thanks for your work and this fix!
