### ISSUE TITLE
Performance issue on Websocket

### ISSUE THREAD

**Issue by vcouvert** [boostorg/beast#1667]
Hi,

I try to use Beast to stream images over network using websockets (no compression, no SSL).
Images are 1.2Mb and sending them (using write or async_write) takes more than 2 secondes.

Do you think I made something wrong with my configuration? Or this kind of timing seems quite normal?

Thanks for your help.

**Comment by vcouvert** [comment]
My bad, actually, compression was enabled...

**Comment by vinniefalco** [comment]
How is the performance with compression off?

**Comment by vcouvert** [comment]
Hi Vinnie,

Without compression, it takes about 12 to 13 ms (30% more than my other test based on https://gitlab.com/eidheim/Simple-WebSocket-Server).

Vincent

**Comment by vinniefalco** [comment]
Hmm... that's a a little bit faster :)

**Comment by pdimov** [comment]
2 seconds for compressing 1.2 Mb sounds a bit too much.

**Comment by pdimov** [comment]
```
-- timing: gzip -c -9 test.tga >test.9.gz
-- 482 ms

-- timing: gzip -c -8 test.tga >test.8.gz
-- 413 ms

-- timing: gzip -c -7 test.tga >test.7.gz
-- 403 ms

-- timing: gzip -c -6 test.tga >test.6.gz
-- 372 ms

-- timing: gzip -c -5 test.tga >test.5.gz
-- 365 ms

-- timing: gzip -c -4 test.tga >test.4.gz
-- 361 ms

-- timing: gzip -c -3 test.tga >test.3.gz
-- 300 ms

-- timing: gzip -c -2 test.tga >test.2.gz
-- 303 ms

-- timing: gzip -c -1 test.tga >test.1.gz
-- 324 ms
```

```
26.07.2019  17:51         3,861,485 test.1.gz
26.07.2019  17:51         3,818,402 test.2.gz
26.07.2019  17:51         3,761,652 test.3.gz
26.07.2019  17:51         3,835,921 test.4.gz
26.07.2019  17:51         3,816,168 test.5.gz
26.07.2019  17:51         3,809,486 test.6.gz
26.07.2019  17:50         3,807,957 test.7.gz
26.07.2019  17:50         3,806,475 test.8.gz
26.07.2019  17:50         3,805,892 test.9.gz
21.07.2016  15:27         6,220,818 test.tga
```

**Comment by vinniefalco** [comment]
@vcouvert were optimizations turned on in your build?

**Comment by vcouvert** [comment]
@vinniefalco my code is built with gcc and -O2 flag.

**Comment by vinniefalco** [comment]
> I try to use Beast

Which version of Beast?

**Comment by vcouvert** [comment]
@vinniefalco Beast 1.70.0

**Comment by vinniefalco** [comment]
That is interesting because we just found a bug that causes compression not to happen for outgoing messages. Can you please describe exactly what client/server setup you are using including software, versions, and behavior?

**Comment by vinniefalco** [comment]
> @vinniefalco Beast 1.70.0 With #1666 workaround (wr_compress forced to true)

That's not 1.70.0, that's 1.71.0 beta. If you look `<boost/beast/version.hpp>` what number do you see there?

**Comment by vcouvert** [comment]
When I reported this issue, I used 1.70.0 version and edited stream_impl.hpp to force compression.

**Comment by vcouvert** [comment]
One more information, when using secured Websockets (WSS), it takes 25ms (instead of 13ms) to transfer the same 1.2Mb image. I hoped switching from WS to WSS would not have such impact on performances.

**Comment by vinniefalco** [comment]
When you use WSS, what is the exact declaration you are using for the websocket stream?

**Comment by vinniefalco** [comment]
> If you look <boost/beast/version.hpp> what number do you see there?

You never answered this

**Comment by vcouvert** [comment]
> When you use WSS, what is the exact declaration you are using for the websocket stream?

boost::beast::websocket::stream<boost::beast::ssl_stream<boost::beast::tcp_stream>, true> stream_;

**Comment by vcouvert** [comment]
> > If you look <boost/beast/version.hpp> what number do you see there?
> 
> You never answered this

Sorry :-)

#define BOOST_BEAST_VERSION 248

**Comment by vinniefalco** [comment]
Going from 13ms to 25ms when switching to SSL is actually quite good. Encryption is not cheap.

**Comment by vcouvert** [comment]
> Going from 13ms to 25ms when switching to SSL is actually quite good. Encryption is not cheap.

Yes you're right! But as I will increase images size in future versions I try to get the best :-) I switched to -O3 so I fear I can no more improve the timings. Next step: trying with clang...

**Comment by vinniefalco** [comment]
Unless you are compiling OpenSSL yourself, changing the optimization settings won't affect the code that performs TLS.
