### ISSUE TITLE
[feature request] Internal Logging

### ISSUE THREAD

**Issue by dmorilha-twilio** [boostorg/beast#1670]
Our SDK uses boost beast 248 and we are very satisfied with the library!

Please, correct me if I am wrong but I after a quick investigation, I could not find wether boost beast / asio does log its internal events.

We would be interested in exposing any possible and useful internal detail to our consumers through our logging facilities.

Any suggestions or guidance on this area would be highly appreciated as well.

Thanks and keep up the great work!

**Comment by vinniefalco** [comment]
> I could not find wether boost beast / asio does log its internal events.

What internal events do you want to log?

Asio has this:
https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/overview/core/handler_tracking.html

**Comment by dmorilha-twilio** [comment]
This was super useful start! Thanks @vinniefalco!

**Comment by dmorilha-twilio** [comment]
We realized the macro expansion doesn't work nicely if other components of your software happen to include boost asio without the same expanded macro. Advices?

**Comment by vinniefalco** [comment]
Hmm... I am not sure. You could write your own stream layer that logs, see:
https://www.boost.org/doc/libs/1_71_0/libs/beast/doc/html/beast/using_io/layered_streams.html

You might also implement your own executor that supports logging.
