### ISSUE TITLE
Question: 'streaming' large files

### ISSUE THREAD

**Issue by redeemarr** [boostorg/beast#1680]
The task is to receive large files piece-by-piece over HTTP with specific portion size (say 4KB).
Using raw asio it would be done this way:
```C++
char buffer[4096];
async_read_some(io::buffer(buffer, sizeof(buffer)), ...
```
But I'm not sure how to implement this approach in Beast and which body and buffer types would be efficient for this task.

I've tried using incremental reads with ```buffer_body```, ```flat_buffer``` and static array, as explained [here](https://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/using_http/parser_stream_operations/incremental_read.html).
It does work, every ```async_read_some``` call reads 512 bytes or less. But I found no way how to change this value.
Also I'm confused about why we need extra static buffer, while we already have flat_buffer.

Thanks.

**Comment by vinniefalco** [comment]
The dynamic buffer used in HTTP parsing is an implementation detail, it has to copy the data to the buffer you provide. A future version of Beast will likely hide this implementation detail. If you want more than 512 bytes, make the static array larger, e.g. `char buf[1024];`.

**Comment by redeemarr** [comment]
Ah, I didn't mention that static buffer was already 4k size. And ```async_read_some``` gave only 512 bytes. I suppose, this is OS and implementation specific.
But when I changed ```async_read_some``` to just ```async_read```, it would work. 'Need buffer' error happened though, but it was expected since all the data couldn't fit into 4k.

**Comment by vinniefalco** [comment]
The way that `buffer_body` works, after the read, it will subtract from body.size the amount that it wrote, and it increments the body.data pointer by the number of bytes that it wrote. The code to do so is here:
https://github.com/boostorg/beast/blob/6d614cf9a8c6d81258e309682621286bf9d74ec3/include/boost/beast/http/buffer_body.hpp#L133

Are you taking this into account in your calculations?

**Comment by redeemarr** [comment]
Yes, calculating ```m_data.size() - body.size``` gives actual number of bytes received.
In other words, ```capacity - free_space = bytes_received```.
But the odd thing is value of ```std::size_t size```, passed to lambda, which should be equal to ```bytes_received```, but it does not. Not always.

[This](https://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/using_http/parser_stream_operations/incremental_read.html) example uses synchronous calls and therefore does not have ```size``` that comes from the library, but calculates it instead. I use the same calculations for the same purpose in asynchronous call.

**Comment by redeemarr** [comment]
I suspect that ```size``` given by ```http::async_read``` call is not always correct, but it could be ignored and calculated instead.
