### ISSUE TITLE
BOOST_ASSERT(! b_)

### ISSUE THREAD

**Issue by leleftheriades** [boostorg/beast#1682]
Being beginners with using the library and not understanding the full implications of issuing a second async_write on the same websocket/stream before the first one finishes we noticed that our program crashed at 

[BOOST_ASSERT(! b_) of stream_base.hpp](https://github.com/boostorg/beast/blob/develop/include/boost/beast/core/detail/stream_base.hpp#L73)

It would be helpful if a more descriptive error would show up, or at least a comment in the code to indicate the probable causes of this error

**Comment by vinniefalco** [comment]
I agree! This was an oversight.
