### ISSUE TITLE
Using client authentication certificate

### ISSUE THREAD

**Issue by amir-ahmed-ansari** [boostorg/beast#1692]
In Boost 1.70, I cannot find any way to specify a client authentication certificate, so the server can authenticate the client in addition to the client verifying the server's certificate. This is possibly a documentation issue since I am sure OpenSSL supports this. Unfortunately, I do not have enough experience with OpenSSL to determine the best course of action.

**Comment by vinniefalco** [comment]
> I do not have enough experience with OpenSSL to determine the best course of action.
Me neither.

**Comment by djarek** [comment]
@amir-ahmed-ansari you can either use this function: https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_client_cert_cb.html and an appropriate callback to set the certificate when the server asks for one (e.g. you can show a prompt for a certificate to the user). Alternatively, you can also just set the certificate upfront using the `use_certificate` family of functions: https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/ssl__context/use_certificate.html or https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/ssl__context/use_certificate_file.html
