### ISSUE TITLE
Example: long-lived TLS Websocket subscriber

### ISSUE THREAD

**Issue by kyle-downey** [boostorg/beast#1693]
I am currently using IXWebSocket and experimenting with websocketpp as a replacement for my C++ Websocket clients, but ideally I'd like to use Beast! The client examples are clear but am looking for something more advanced:

* issue a subscription message and then receive a very long-lived stream of updates; the current TLS example just writes a message, reads a message, and exits
* reconnect whenever a connection drops on server side, ideally policy-based (e.g. an exponential back-off and retry policy)

Here's what the simplified client code wrapper I wrote for websocketpp looks like, which I'd want to rewrite to use Beast instead:

https://github.com/cloudwall/libcrypto-mktdata/blob/master/include/cloudwall/crypto-mktdata/websocket_client.h
https://github.com/cloudwall/libcrypto-mktdata/blob/master/src/websocket_client.cpp
https://github.com/cloudwall/libcrypto-mktdata/blob/master/src/print_client_tls.cpp

Beast: 1.69 (requested 1.71 from Conan repository)
OS: Linux - Debian "Stretch"
Compiler: gcc 9.2.0

**Comment by vinniefalco** [comment]
For the pub/sub have a look at the `channel` implementation in this other project I am working on which uses Beast websockets: https://github.com/vinniefalco/BeastLounge

**Comment by vinniefalco** [comment]
> reconnect whenever a connection drops on server side, ideally policy-based (e.g. an exponential back-off and retry policy)

Boost.Beast doesn't manage sockets or connections, this is handled in Boost.Asio, so your solution is going to rely on Asio interfaces exclusively. There's no secret sauce here, you can implement your reconnection logic any way that you like.
