### ISSUE TITLE
Coroutines handlers and object lifespans

### ISSUE THREAD

**Issue by brjoha** [boostorg/beast#1700]
I'm running into an intermittent crash with a less then helpful stacktrace.  My suspicion is that a given socket object has gone out of scope, but a previously queued event is attempting to work with it.  My understanding is that this is a common scenario in ASIO that is handled by the use of a shared pointer in the callback handler.  But how can this be addressed when using a coroutine handler?  For example...

```
beast::ssl_stream<beast::tcp_stream> my_sock;
// connection setup happens
// coroutine is spawned for io

// inside the coroutine loop
beast::http::async_write(my_sock, my_request, yield[ec]);
if (ec && ec.value() == ECANCELED) {
   return;  // exit coroutine
}
// continue working
```

Before my_sock goes out of scope, I can invoke cancel() which will terminate the async_write() operation with an ECANCELED result.  However, if there is already an event queued for completion of the operation, it will execute without an ECANCELED result.

Is the right way to handle this by maintaining a shared pointer for the lifespan of the coroutine, rather than the handler, and checking both the result and the state of the socket on return from async_write()?

**Comment by vinniefalco** [comment]
Instead of `if (ec && ec.value() == ECANCELED)` you can write `if(ec == net::error::operation_aborted)`. This won't answer your question but it is idiomatic.

> Before my_sock goes out of scope, I can invoke cancel()

This is a red flag. How can you call `cancel` if your coroutine is blocked in the call to `async_write`? And if your coroutine is not blocked, then there is no I/O to cancel. The only way you can meaningfully call `cancel` is from a *second coroutine* which uses the *same strand* as the socket. And in this scenario, the lifetime issue will become obvious since they will both need to access the same socket variable.

**Comment by brjoha** [comment]
"This is a red flag. How can you call cancel if your coroutine is blocked in the call to async_write?"

In my case, cancel() is being called from another coroutine (associated with a different object) on the same thread.  The coroutine of the object I'm trying to cleanup runs in a loop where it performs an async_pop on a queue (using a net::posix::descriptor around a Linux event_fd) and then an async_write on a socket.  Both the queue and socket are canceled to trigger the coroutine to exit.  But as I said, my suspicion is that there is already an event in the underlying ASIO queue for which the cancel has no effect.

**Comment by vinniefalco** [comment]
> In my case, cancel() is being called from another coroutine (associated with a different object) on the same thread.

How do you know it is on the same thread? Do you have an implicit strand (only one thread calling `io_context::run`)?

**Comment by vinniefalco** [comment]
> In my case, cancel() is being called from another coroutine (associated with a different object)

Then you have shared-ownership of the socket in question. The only way to sanely manage the lifetime is with a reference count (for example, using `shared_ptr`).

**Comment by brjoha** [comment]
Yes, it's an implicit strand.
Yes, I agree a shared pointer will be involved in the solution.  My understanding is that the typical approach involves a shared pointer in the async handler.  This ensure the object stays around as long as there are pending events.  But when using coroutines, the yield context is the handler.  So it seems the lifecycle now has to be managed externally, which then decouples pending events from the lifespan of the object.  Does that make the issue any clearer?

**Comment by vinniefalco** [comment]
> Does that make the issue any clearer?

Kind of. Any coroutine that wants to access the same socket needs to have ownership of a `shared_ptr` to that socket. How you accomplish that is up to you.

**Comment by vinniefalco** [comment]
> when using coroutines, the yield context is the handler

This is not correct. The yield context is the **CompletionToken**. The handler is the coroutine. Putting a `shared_ptr` in the coroutine is as easy as simply making it a local variable in the coroutine's stack frame. You will have to acquire the value from somewhere of course (perhaps a synchronized data structure).
