### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by dk1013** [boostorg/beast#1705]
I have a rather general question regarding backward compatibility (Not sure if this is the best place to raise it though).
So if I have some code using an older version of beast, is it guaranteed that the old code will run correctly with newer versions?
If not, will there be any performance improvement if I adapt my code to the newer version?
BTW, thanks for the amazing library!

**Comment by vinniefalco** [comment]
In terms of protocol compatibility, any version of Beast can talk to any other version of Beast using the HTTP or WebSocket protocols. If you're asking about API compatibility, I try not to break things but sometimes it is not avoidable. For example, Asio made changes which do require a code update. In general, newer versions of Beast are better than older versions, in one or more ways:
- Faster compilation
- Smaller code generation
- Better performance
- More functionality
- Increased security
- Bug fixes
It is in the best interests of programs which use Beast, to use the latest version of the library, to take advantage of bug fixes and security improvements.

**Comment by dk1013** [comment]
Thanks @vinniefalco , the response is really fast.
Well noted, will try to migrate to latest version.
