### ISSUE TITLE
Example websocket_server_async.cpp question

### ISSUE THREAD

**Issue by gladiacxtylish** [boostorg/beast#1706]
I was reading the boost 1.66 websocket example [here](https://www.boost.org/doc/libs/1_66_0/libs/beast/example/websocket/server/async/websocket_server_async.cpp). In the listener class, it initializes the socket_ object. And after the listener accepted the connection, in the on_accept function the socket_ is being **std::move** to the session object. I didn't see any logic to recreate the socket_ object. When the listener accepts another connection, would it be an issue for the next on_accept?

**Comment by djarek** [comment]
Sockets are guaranteed to be left in a usable state after they're moved-from(it's the same state as if the socket was just constructed with the 1-argument constructor).
