### ISSUE TITLE
thread library is not linked on ubuntu 16.04

### ISSUE THREAD

**Issue by fcaponetto** [boostorg/beast#1711]
Hi guys!
I tried to compile  the source code based on the commit  **55fd67b**
Unfortunately the linker was not able to link the "thread library" properly to the examples executable.
In particular, just for test, i built _http-server-small_

On the root CmakeLists.txt you have:
> set (THREADS_PREFER_PTHREAD_FLAG ON)
   find_package (Threads)
   set( CMAKE_CXX_FLAGS
   "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Wextra -Wpedantic -Wno-unused-parameter")
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wrange-loop-analysis")
    endif ()

For fixing this problem i had to introduce the -**pthread** option on _CMAKE_CXX_FLAGS_ flags:
> set( CMAKE_CXX_FLAGS
     "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Wextra -Wpedantic -Wno-unused-parameter -**pthread**")

**Comment by vinniefalco** [comment]
The CMakeLists.txt only supports Windows. Try the Jamfile?

**Comment by fcaponetto** [comment]
In the root CMakeLists.txt there is the if/else condition:

>if (MSVC)
...
else()
    set (THREADS_PREFER_PTHREAD_FLAG ON)
    find_package (Threads)
    set( CMAKE_CXX_FLAGS
      "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -Wextra -Wpedantic -Wno-unused-parameter")
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wrange-loop-analysis")
    endif ()
endif()

... so i thought that cmake is also compatible for Linux.

However, adding that flags mentioned in my first message (-pthread) in Linux system cmake works.

**Comment by vinniefalco** [comment]
I guess I can add it, but does this break other environments? I simply copied and pasted the `else` part. Or perhaps someone else contributed it, I can't recall. Since this file is not tested except on Windows, there's no way to evaluate the change.
