### ISSUE TITLE
What is the websocket's state if async_close fails?

### ISSUE THREAD

**Issue by leleftheriades** [boostorg/beast#1714]
Beast Version 1.70
OpenSSL version 1.1.1a

We use Websocket over SSL. A great number of times when calling `async_close`, the operation fails with error code 1 and message "stream truncated".

We are wondering what the state of the websocket is after the `async_close` has failed.
is it open, closed or undefined?

We found that in some instances a pending `async_read` operation was not cancelled after the `async_close` was run and failed. In some other instances the `async_read` operation was indeed cancelled.

**Comment by vinniefalco** [comment]
Reproducing this in a live run is practically impossible, so we will need to figure out how to make it happen reliably in a test scenario. I would advise that you look at the existing websocket tests to see how they work, and look at the websocket implementation to find where you think that the async read is not being canceled on a failure. Then set up a test that reproduces this situation.

When an async operation fails, the function `check_stop_now` is called which inspects the error and triggers an early exit from the operation. For the async close operation you can see that here:
https://github.com/boostorg/beast/blob/develop/include/boost/beast/websocket/impl/close.hpp#L109

**Comment by vinniefalco** [comment]
The status of the websocket should be `status::closed` or `status::failed`:
https://github.com/boostorg/beast/blob/0ca107bb5c2c1d25fd9b1cd3b44a548afbfd121d/include/boost/beast/websocket/impl/stream_impl.hpp#L329

**Comment by leleftheriades** [comment]
To be honest we are not sure if async_close completed with an error, or it never completed after 10 minutes. Our logs are mixed in the same file. We have improved our logging and will post an update if we have more data.

**Comment by vinniefalco** [comment]
Try giving this a spin? https://github.com/boostorg/beast/pull/1754

**Comment by leleftheriades** [comment]
Hello, it just happened again today. According to our logs we called async_close and it never completed (after 5 minutes). Our versions are beast 1.71 and OpenSSL 1.1.1d.
We did not have any calls to set_option, so we never set a timeout on the websocket. We also called expires_never() before upgrading out httpsession to websocket. So we don't believe it is related to a timeout.

**Comment by vinniefalco** [comment]
There is no guarantee that `async_close` will complete. If the peer never closes the connection, then the completion handler is never invoked, beast will wait patiently forever. That's why you need a timeout. This is explained in the websocket RFC, see 5.5.1: https://tools.ietf.org/html/rfc6455

**Comment by leleftheriades** [comment]
What is the difference between async_close and async_teardown? Which one(s) should we use to close the websoket gracefuly?

**Comment by vinniefalco** [comment]
`stream::async_close`

**Comment by leleftheriades** [comment]
We came across this note:
To receive the error::closed error, a read operation is required.
in [control_frames](https://www.boost.org/doc/libs/1_71_0/libs/beast/doc/html/beast/using_websocket/control_frames.html) document.
Does that mean we have to have a pending async_read operation active, or is that handled by beast?

**Comment by vinniefalco** [comment]
It seems the doc is a tiny bit misleading. If you call `async_close` and there is no read pending, beast will read for you. The note in the doc refers to the scenario where you are not calling `async_close`, and the peer sends a close frame.

**Comment by leleftheriades** [comment]
Thank you so much for your help!
