### ISSUE TITLE
ReadHandler does not do what it did in Boost 1.68's Beast

### ISSUE THREAD

**Issue by dascandy** [boostorg/beast#1717]
### Version of Beast

from Boost 1.71

### Steps necessary to reproduce the problem

https://www.boost.org/doc/libs/1_71_0/libs/beast/doc/html/beast/ref/boost__beast__http__async_read/overload2.html

Documentation indicates "bytes transferred from stream". This is not the amount of data entered into the buffer and cannot be used as such. This is a change from 1.68 as far as I can tell.

### All relevant compiler information

Checked on clang 9 and gcc 7.4

**Comment by vinniefalco** [comment]
What do you think the read algorithms should return?

**Comment by dascandy** [comment]
I expect the argument to my read call to return the number of bytes "read" into my buffer.

**Comment by vinniefalco** [comment]
Which buffer do you mean, the _DynamicBuffer_ parameter? What if there is so much data in this buffer, that the HTTP read operation can complete without reading any additional bytes from the socket? Would you be okay with 0 being returned in this case?

**Comment by klemens-morgenstern** [comment]
@dascandy We're on 1.80 now, how's this issue looking?
