### ISSUE TITLE
boost/beast/ssl.hpp not included in installed version of vcpkg

### ISSUE THREAD

**Issue by illera88** [boostorg/beast#1730]
Hi,

I'm trying to use beast after installing it with vcpkg:
`vcpkg.exe install boost:x86-windows-static`

Unfortunately it seems that it does not include the header `boost/beast/ssl.hpp` which is needed to compile a ssl websocket server. 

Is this an expected behavior?

**Comment by vinniefalco** [comment]
No idea why that file is not there for you. What version is vcpkg installing?

**Comment by illera88** [comment]
`boost-beast:x86-windows-static                     1.69.0           Boost beast module`

**Comment by vinniefalco** [comment]
Are you using the 1.71 examples with the 1.69 package? You have to use the examples from 1.69. You can get them using the tagged release:
https://github.com/boostorg/beast/tree/boost-1.69.0/example

However I suggest you use 1.71 if possible, it has some great features like built-in websocket timeouts and various improvements. But 1.69 will still work well for you.

**Comment by illera88** [comment]
You are right. I was mixing versions. It seems that the vcpkg boost version is 1.69 and I was using that boost against beast examples from the 1.71 version.

Thanks
