### ISSUE TITLE
compile error C2668 with vs2017

### ISSUE THREAD

**Issue by zaley2000** [boostorg/beast#1742]
In "buffer_traits.cpp"  line 123, a C2668 error appear. " Ambiguous call to overloaded function net::buffer_sequence_begin ". In vs2015 there is no similar errors.

using buffers_iterator_type =
    decltype(net::buffer_sequence_begin(
        std::declval<BufferSequence const&>())); 

BOOST 1.71  Beast 266

**Comment by vinniefalco** [comment]
I develop on VS2017 and I have not seen this error. Appveyor also has no trouble building it:
https://ci.appveyor.com/project/vinniefalco/beast/history

Does this error occur when you compile the tests? Can you provide a small program which reproduces the error?

**Comment by zaley2000** [comment]
When changing IDE to vs2017 (15.9), everything is OK now.
