### ISSUE TITLE
How to receive RAW data from WebSocket server

### ISSUE THREAD

**Issue by alorver** [boostorg/beast#1743]
We need to receive raw data from WebSocket server, including non printable chars. We faced with case when WebSocket server as responce uploads json-file, but it is not equal to source json-file, as we have noticed without some chars like "\n" (probably anything else). 

We use simple code:

#Dest: Windows Dll (Win7/32)
#WebSocket Sync
beast::flat_buffer buffer;
str::stringres res= _strdup(beast::buffers_to_string(buffer.data()).c_str());
Boost ver: 1.71

Is there any way to receive absolutly equal json-file to source one from WebSocket server?

Best regards,
Andrey

**Comment by RedDwarf69** [comment]
As long as you set the stream to send binary messages (https://www.boost.org/doc/libs/1_70_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/binary/overload1.html) you can send whatever you want and will receive absolutely equal data.

The "simple code" you included doesn't show either how you send or receive data, so it's not specially useful. If you need help with your code you are going to need to include a self-contained full example. You can easily create one using https://www.boost.org/doc/libs/1_71_0/libs/beast/doc/html/beast/ref/boost__beast__test__stream.html to avoid the connection boilerplate.

**Comment by alorver** [comment]
Thank you, we need to do some checks regarding JSON-parsing (using node.js/JSON.stringify(...)) on our WebServer(WebSocket). According to your reply,  everything rest is right.
