### ISSUE TITLE
boost::thread_resource_error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by bbbbyang** [boostorg/beast#1745]
Currently I have a websocket client and make io_context running in boost::thread
```
void websockets::Client<MsgBaseRcv, MsgUtilsRcv, MsgBaseSend, MsgUtilsSend>::
start()
{
    if( !_isStarted )
    {
        _isStarted = true;

        DBG_DETAIL( _dbg, "Attempting connection to " << _serverAddress << ":" << _serverPort );
        _session.reset();
        _session.reset( new ClientSession<MsgBaseRcv, MsgUtilsRcv, MsgBaseSend, MsgUtilsSend>(
                _ioc, _sslContext, this, _serverAddress, _serverPort ) );
        _session->run();

        boost::thread run_thread([&] {
            _ioc.run();
        } );
    }
}
```

In the destructor I call _ioc.stop to hope to end this boost:thread
```
websockets::Client<MsgBaseRcv, MsgUtilsRcv, MsgBaseSend, MsgUtilsSend>::
~Client()
{
    _ioc.stop();
}
```

In my main task, I have a timer. Every 10 seconds this timer will call restart function if the client can not connect with server
```
void  restart()
{
    _client->stop();
    _client.reset(new websockets::Client<MsgBaseRcv, MsgUtilsRcv, MsgBaseSend, MsgUtilsSend>(
            Ip, Port, this ) );
    setTlsCert();
    _client->start();
}
```

I just made this running all night. After around 6 hour. this happened 3 times in my over night testing. It will throw a boost::thread_resource_error: Resource temporarily unavailable and restarted the task again. I think it is running thread not end properly but im not 100% sure. How can I make sure that the ioc thread terminated when destructor get called

**Comment by vinniefalco** [comment]
no idea. try using `std::thread`?

**Comment by bbbbyang** [comment]
I dont want _ioc.run() block my task. I want to make it running in a separate thread. Any suggestion?

**Comment by bbbbyang** [comment]
And I noticed that every 10 secs will throw away old object and make a new one which will ask a new thread is a bad idea. I should call ioc stop, restart, run for this feature, right?

**Comment by vinniefalco** [comment]
You gotta know how to use asio

**Comment by bbbbyang** [comment]
Can you give me more specific hint where should I start to learn about asio

**Comment by vinniefalco** [comment]
I would do an internet search and try to find the stuff that is out there, I don't have any links handy sorry. Maybe look at the asio examples?
