### ISSUE TITLE
issue using http::request<http::buffer_body> with http::async_write

### ISSUE THREAD

**Issue by haashirashraf** [boostorg/beast#1748]
Firstly thanks a lot guys, its probably something simple but when using beast 1.70.0 I initialise the buffer_body with a char* to an array and initialise its size to the number of bytes in the array (I am sure that this array is initialised) when I attempt to write this http::request<http::buffer_body> using http::async_write to a beast::ssl_stream I get the error need buffer in my on_write handler, why is this?

**Comment by vinniefalco** [comment]
What do the docs say about this?

**Comment by haashirashraf** [comment]
The docs say that all members of http::buffer_body::value_type must be initialised, I didn't mention the bool more value which defaults to true, so that is to say this should be set to false?

I see the need buffer error is raised when the data member of the buffer body is a nullptr, I'll try again and set this to false!

Actually I think this will work because I recall seeing (nil) when printing the bodies of my keep alive requests which initialised data to nullptr and prior to doing this seeing the need buffer error!

**Comment by haashirashraf** [comment]
That fixed it! Thanks a lot Vinny!
