### ISSUE TITLE
What version of boost is required ?

### ISSUE THREAD

**Issue by McSwan** [boostorg/beast#1758]
I have a current project that uses boost 1.69 - is that good enough to do websocket client and server connections ? Or is it worthwhile upgrading to 1.71?

**Comment by vinniefalco** [comment]
1.69 should work, but every new version of Boost contains bug fixes and improvements to Beast, so if you want the "best" version, you should use the latest.

**Comment by McSwan** [comment]
Hi Vinnie, I'm using the example from 1.66 and they work well.  I changed the "onread" function so it constantly calls itself. I create the connection, then  use the same connection to constantly read from the same source (should be faster than constantly re establishing a new connection)  . Would the connection eventually time out if there is no traffic? Or if there is constant traffic would it stay open indefinitely?
`void
    on_read(
            boost::system::error_code ec,
            std::size_t bytes_transferred)
    {
        boost::ignore_unused(bytes_transferred);

        if(ec)
            return fail(ec, "read");

        if (!closeConnection ) {
            // Read a message into our buffer
            ws_.async_read(
                    buffer_,
                    std::bind(
                            &Session::on_read,
                            shared_from_this(),
                            std::placeholders::_1,
                            std::placeholders::_2));

            std::cout << boost::beast::buffers(buffer_.data()) << std::endl;
        }
        else
        {
            // Close the WebSocket connection
            ws_.async_close(websocket::close_code::normal,
                            std::bind(
                                    &Session::on_close,
                                    shared_from_this(),
                                    std::placeholders::_1));
        }
    }`

ps Congrats on getting beast into boost!

**Comment by vinniefalco** [comment]
1.71 has timeouts:
https://www.boost.org/doc/libs/1_71_0/libs/beast/doc/html/beast/using_io/timeouts.html

**Comment by McSwan** [comment]
Cheers - I'll check that out - thanks!
