### ISSUE TITLE
How to issue multiple GET requests on a single connection

### ISSUE THREAD

**Issue by Xeverous** [boostorg/beast#1763]
Hey, I have a specific use case and would like to optimize my project towards it (networking takes majority of the time):

- the progam rarely needs to download data but when it needs it's the longest task
- when the program needs to download, it needs to perform multiple HTTP GET requests against the same host (only target URL differs)
- AFAIK, if the server is HTTP 1.1 it is possible to issue multiple requests on a single connection avoiding the need for multiple handshakes and name resolutions
- I have no idea whether/how spawning multiple io_contexts or worker threads affects the overall speed. I issue ~20 requests at most.
- I want to support HTTPS, but apparently the only thing to make it work is proper `ssl::context` construction

I'm currently getting the same error as in #821

my code: https://github.com/Xeverous/filter_spirit/blob/feature-poe-ninja/src/lib/fs/network/http.cpp

**Comment by vinniefalco** [comment]
Well just keep the connection open and issue another read?

**Comment by Xeverous** [comment]
That's exactly what I though to do but apparently I either did something wrong or it's more complicated.

**Comment by vinniefalco** [comment]
Have you tried the **advanced-server** example? It keeps the connection open and allows multiple requests.

**Comment by Xeverous** [comment]
I'm not issuing requests towards my own server - I'm implementing only a client. The only things that I spotted were:

- other examples use different streams - not sure what's the impact
- server example has `keep_alive(true)` - I added this to my request but it did not help

**Comment by vinniefalco** [comment]
Is the server closing the connection on you? What do the headers in the server's response look like?

**Comment by Xeverous** [comment]
```
GET /itemdata HTTP/1.1
Host: api.poe.watch
User-Agent: Boost.Beast/248

HTTP/1.1 200 OK
Date: Sat, 09 Nov 2019 22:44:42 GMT
Server: Apache/2.4.29 (Ubuntu)
Cache-Control: max-age=60
Expires: Sat, 09 Nov 2019 22:45:12 GMT
Access-Control-Allow-Origin: *
Age: 29
X-Cache: HIT from api.poe.watch
Content-Length: 4722679
Content-Type: application/json

GET /compact?league=Standard HTTP/1.1
Host: api.poe.watch
User-Agent: Boost.Beast/248

HTTP/1.1 200 OK
Date: Sat, 09 Nov 2019 22:44:42 GMT
Server: Apache/2.4.29 (Ubuntu)
Cache-Control: max-age=60
Expires: Sat, 09 Nov 2019 22:45:42 GMT
Access-Control-Allow-Origin: *
X-Cache: MISS from api.poe.watch
Transfer-Encoding: chunked
Content-Type: application/json

GET /itemdata HTTP/1.1
Host: api.poe.watch
User-Agent: Boost.Beast/248
(now error - protocol is shutdown)
```

Ok, it looks like I actually do download multiple files correctly but my logic in using requests is flawed - the 3rd request is redundant and it's the same as the 1st.

**Comment by vinniefalco** [comment]
Seems like things are working :)

**Comment by Xeverous** [comment]
Ok, now downloading works - it was a purely off-by-one logic bug caused by missing `return` under an `if` statement.

I'm getting `"could not shutdown the connection: stream truncated"` when closing the connection. Reading #38, looks like this could be a problem with the server I'm issuing requests to.

**Comment by vinniefalco** [comment]
Yeah that happens

**Comment by Xeverous** [comment]
Should I just ignore this error? Is there a need to report this to the server owner?

**Comment by vinniefalco** [comment]
You can ignore it, see:
http://stackoverflow.com/questions/25587403/boost-asio-ssl-async-shutdown-always-finishes-with-an-error

**Comment by Xeverous** [comment]
Ok, everything now works. Thanks for fast responses.
