### ISSUE TITLE
How to get the full chunked data from http response in synchronous mode?

### ISSUE THREAD

**Issue by zaley2000** [boostorg/beast#1765]
In synchronous mode ,I want to get the full chunked data from http response . Is there a related example? My boost  version is 1.71.

      .......
       beast::http::write(stream, req);
       beast::flat_buffer buffer;
       beast::http::response<beast::http::dynamic_body> res;					
	int rt = beast::http::read(stream, buffer, res);
       bool chunked = res.chunked();
	if (chunked)
	{
          // ?????
       }

**Comment by vinniefalco** [comment]
Beast removes any chunked-encoding for you. Your code above will read the complete body into the message. I would suggest you use `beast::http::string_body` instead of `dynamic_body`, it will be easier for you to access the contents.

**Comment by zaley2000** [comment]
Oh, I have get the chunked data like this

	beast::flat_buffer buffer;
	beast::http::response<beast::http::dynamic_body> res;					 
	int rt = beast::http::read(stream, buffer, res);
	bool chunked = res.chunked();
	int nS = res.body().size();
	auto bd = res.body().data();
     //std::string line = buffers_to_string( bd) ;
	for (auto const buffer : beast::buffers_range_ref(bd))
		method->responseBody.append(static_cast<char const*>(buffer.data()), buffer.size());

**Comment by vinniefalco** [comment]
"chunked" has nothing to do with that. A `dynamic_body` uses the `dynamic_buffer` container, which is similar to a deque. It can have more than one buffer. If you instead use `http::string_body`, all your data will be in one buffer and you will not need to make a copy, as you are doing.

**Comment by vinniefalco** [comment]
This will fix itself with Boost.URL
