### ISSUE TITLE
What is the correct way of using async_connect

### ISSUE THREAD

**Issue by tty2099** [boostorg/beast#1768]
### Steps necessary to reproduce the problem
 one server and one client in the same class as member variables, they are follow official websocket async examples. The program run the server part first and then waiting for client of the server to be connected. when the client connected, this program will connect to another server.

I use the same io_context for both part. When I connect to another server first, and then start the server in the same class, then everything sames OK. But I start the server first and then start the client connection to another server, it crashes. The debugger reports that the value of write.pending is true, which value should be false, so assert condition is not satisfied.

### All relevant compiler information

I test my program in Windows and Linux,      on base_stream.hpp:433, crash on the line  , pg1_(impl_->write.pending)

I can't post my source here, because it is private and is not allowed to publish anywhere

**Comment by leleftheriades** [comment]
you are not allowed a second write on the same socket before the first one finishes

**Comment by tty2099** [comment]
No second write on the same socket(client part), only another socket have a lot of writes(server part)

**Comment by leleftheriades** [comment]
server part has one socket for accepting, and one socket per accepted connection correct?

**Comment by tty2099** [comment]
Yes, just as the examples do, https://www.boost.org/doc/libs/1_71_0/libs/beast/doc/html/beast/examples.html.

The crash is from client part

**Comment by tty2099** [comment]
I will upload a simplified version of my code tonight or tomorrow morning.

**Comment by tty2099** [comment]
I simplified my code, the crash disappear, so I should check my code again and again.

**Comment by tty2099** [comment]
I take a mistake on program logic that triggers unnecessary reconnnection to another server.
