### ISSUE TITLE
Server redirect example

### ISSUE THREAD

**Issue by benstadin** [boostorg/beast#1771]
I'm serving a simple static page which implicitely loads an index.html when the base url is entered in the browser (/appresource/a will return ./appresource/a/index.html). I'm looking for a server side redirect example, because obviously the relative files referred within index.html will have the wrong request target (linked image.png in HTML will have target ./appresource/image.png instead of ./appresource/a/image.png).

What's the best way to do a server side redirect?

**Comment by vinniefalco** [comment]
> What's the best way to do a server side redirect?

Build the HTTP response with the correct header and body, and write it?

**Comment by benstadin** [comment]
Sorry, it was obvious in the end.

**Comment by vinniefalco** [comment]
Often, simply asking the question answers it.
