### ISSUE TITLE
Reusing websocket instance after previous connection broke

### ISSUE THREAD

**Issue by abhiarora4** [boostorg/beast#1778]
I am strugging to find a way to reuse the websocket instance after internet was abrupted. Even if I call 

            if (pWebStream_->is_open()) {
                // if (pWebStream_->next_layer().next_layer().is_open());
                pWebStream_->close(websocket::close_reason());

                pWebStream_->next_layer().shutdown();
                    pWebStream_->lowest_layer().close();
                // pWebStream_->next_layer().shutdown;
            }

before reconnecting, it throws exceptions like "stream truncated" and "protocol is shutdown". 

I need to know how to close and create a new SSL session.

Please help!

**Comment by vinniefalco** [comment]
Store the stream in a `boost::optional` or `std::optional` and re-construct it in place when you want to use it again.

**Comment by abhiarora4** [comment]
I read your answer in another issue. How can I change the ssl stream of a websocket. Please help me with some code?

**Comment by vinniefalco** [comment]
You can't change the stream. Just destroy the object and create a new one?

**Comment by abhiarora4** [comment]
Yes. I tried that. But it gave me seg fault or various "Invalid Read" message in valgrind. Is there anyway to gracefully delete the websocket instance? Because io_context is still looking for it even if it is deleted.

**Comment by abhiarora4** [comment]
I was trying this to cleanup after a connection disconnect:

            if (pIoc_) {
                pIoc_->reset();
                pIoc_->stop();
                // pIoc_->run();
            }
            if (pWebStream_)
                delete pWebStream_;
            if (pingTimer_)
                delete pingTimer_;

**Comment by abhiarora4** [comment]
Will it work?

    boost::optional<boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>>> socket;

    // Before connecting!
    socket.emplace(io_context);

Please help

**Comment by vinniefalco** [comment]
> Is it what you are suggesting?

Yes but you need the SSL context too, no?

**Comment by abhiarora4** [comment]
Yes! Right. Thanks
I am also mixing sync and sync operations in a single thread. 
Are these a problem?

           // TODO: Send the Message from the vector
            {
                std::lock_guard<std::mutex> msgGaurd(msgMutex_);
                while (!sendMsgQueue_.empty()) {
                    const auto& m = sendMsgQueue_.front();
                    std::cout << "Sending Message: " << m << std::endl;
                    pWebStream_.value().write(boost::asio::buffer(m.toString()));
                    sendMsgQueue_.pop_front();
                    break;
                }
            }
            std::cout << "Runing" << std::endl;
            // Call io_context run_until to process read messages
            pIoc_->run_until(std::chrono::steady_clock::now() +  std::chrono::milliseconds(DEF_IO_CONTEXT_RUN_FREQ_MS));
            std::cout << "Here" << std::endl;
            if (pWebStream_.value().is_open() and !isInactiveFor(DEF_INACT_TIMEOUT_SEC))
                break;
            // TODO: Check here for last activity timestamp
            state_ = State::CLEANUP;
            // Fall Though!

**Comment by vinniefalco** [comment]
> I am also mixing sync and sync operations in a single thread. Are these a problem?

Maybe, depends on how you write the code. But generally, it is not a good idea to mix. Look at the websocket-chat-multi example for how to queue messages.

**Comment by abhiarora4** [comment]
I am getting this:

    : Assertion `ws_.rd_block_.is_locked(this)' failed.

After it retires to connect.

        case State::WEBSOCKET_HANDSHAKE:
        {
            Poco::URI uri(titanURI_);
            std::string hostname = uri.getHost();
            std::string port = std::to_string(uri.getPort());


            // if (pWebStream_->is_open()) {
            //     // if (pWebStream_->next_layer().next_layer().is_open());
            //     pWebStream_->close(websocket::close_reason());

            //     pWebStream_->next_layer().shutdown();
            //         pWebStream_->lowest_layer().close();
            //     // pWebStream_->next_layer().shutdown;
            // }
        
            ssl::context ssl_context{ssl::context::sslv23_client};
            ssl_context.set_options(ssl::context::default_workarounds | ssl::context::no_sslv2 |
                                ssl::context::no_sslv3);
            ssl_context.set_verify_mode(ssl::verify_peer); // client side
            ssl_context.load_verify_file(context_.caBundleFilePath);
            ssl_context.use_certificate_file(context_.devCertiFilePath, ssl::context_base::pem);
            ssl_context.use_private_key_file(context_.devKeyFilePath, ssl::context_base::pem);

            // if (pIoc_ == nullptr)
            // pIoc_ = new boost::asio::io_context;
            // pWebStream_ = new websocket::stream<ssl::stream<tcp::socket>>{*pIoc_, ssl_context};
            // if (pingTimer_ == nullptr)
            // pingTimer_ = new boost::asio::steady_timer(*pIoc_);
            pWebStream_.emplace(*pIoc_, ssl_context);

            tcp::resolver resolver{*pIoc_};
            const auto results = resolver.resolve(hostname, port);
            std::cout << "TCP Connec" << std::endl;
            boost::asio::connect(pWebStream_.value().next_layer().next_layer(), results.begin(), results.end());

            std::cout << "SSL Connec" << std::endl;
            pWebStream_.value().next_layer().handshake(ssl::stream_base::client);
            pWebStream_.value().control_callback(std::bind(&AlarmNetSocket::onControlFrames, this, std::placeholders::_1,
                                                                std::placeholders::_2));
            std::cout << "Websocket Connec" << std::endl;
            pWebStream_.value().handshake_ex(hostname, "/", std::bind(&AlarmNetSocket::append_headers, this, std::placeholders::_1));
            pWebStream_.value().async_read(readBuf_, std::bind(&AlarmNetSocket::onRead, this, 
                            std::placeholders::_1, std::placeholders::_2));
            pingTimer_->expires_after(std::chrono::seconds(5));
            pingTimer_->async_wait(std::bind(&AlarmNetSocket::onPingTimer, this, std::placeholders::_1));
            lastConnTimeStamp_ = std::chrono::steady_clock::now();
            state_ = State::READY;
        }

**Comment by vinniefalco** [comment]
Have you tried compiling and running the websocket examples? Do they work for you? If yes, then I suggest you start with the example which works and modify it slowly to suit your needs. I can't debug your entire program for you. And users of Beast are expected to know how to use asio. If you look at the source code where the assert is happening you should see a comment with some instructions.

**Comment by dgrr** [comment]
Hello,

In case someone faces the same problem: Don't forget to reset the `ssl::context`. I got a lot of segfault for not resetting the ssl::context correctly. If someone has a problem reusing a `ssl::stream`, just try using `std::optional` for the `ssl::context` too.

**Comment by madmongo1** [comment]
@dgrr Generally, you will want only one `ssl::context` per program. Much like the `io_context`, I create it in `main()`, configure it, and pass a reference to it as a dependency for all ssl streams.

If your program both makes outbound connections and accepts inbound connections, there is a strong case for two `ssl::context` per program.

Creating more than one is an unnecessary burden.

**Comment by dgrr** [comment]
@madmongo1 right. So looks like I had another problem I magically solved. I was getting a segfault related with OpenSSL. I temporary fixed it by using a `std::optional` with the `ssl::context`. I really don't know why. I just removed the `optional` and I get no error.

Thanks for clarifying.

**Comment by madmongo1** [comment]
@dgrr Good to hear that all is resolved. 

Are we in a position to close this issue now, or is there anything else I can help you with?

**Comment by dgrr** [comment]
@madmongo1 I just wanted to comment in case someone faces the same issue in the future. (this issue is already closed).

Thanks!
