### ISSUE TITLE
Is the following a safe approach to determine if an HTTP response has a body or not?

### ISSUE THREAD

**Issue by suryakalpo** [boostorg/beast#1779]
```
http::response<http::dynamic_body> res;
boost::beast::flat_buffer buffer;
http::read(stream, buffer, res); // stream is an ssl::stream<tcp::socket> object

auto body_size = get_optional_value_or(res.payload_size(), 0);
if (body_size > 0 )
{
    response_body = boost::beast::buffers_to_string(res.body().data());
}
```

The reason I ask this question is due to the following caveat in the documentation regarding payload_size()

> If there is no body, this will return zero. Otherwise, if the body exists but is not known ahead of time, boost::none is returned (usually indicating that a chunked Transfer-Encoding will be used).

If it is safe, then a follow-up question:
Can http::response::body::data() be used as-is to read an HTTP body that is chunked?

P.S: Apologies for the original post with the default Github template :)

**Comment by vinniefalco** [comment]
Quoting the github issue template is definitely not going to help you determine if the HTTP response has a body :)

**Comment by vinniefalco** [comment]
It is safe.

> Can http::response::body::data() be used as-is to read an HTTP body that is chunked?

Yes. Whether or not the Transfer-Encoding is chunked has no effect on the resulting body, as Beast automatically removes the chunked encoding for you.

**Comment by suryakalpo** [comment]
Excellent! Thank you. I'll close this issue.
