### ISSUE TITLE
Async Websocket in DLL problem

### ISSUE THREAD

**Issue by rraggerr** [boostorg/beast#1794]
Hello, im trying to un-load my DLL which uses async websocket, so im closing the connection and everything is fine, but when im using FreeLibrary , my DLL unloads from my proccess but Beast or websockets "still loaded". When im trying to recompile the DLL, Visual Studio says what something using this file and it cant be overwritten.

You can easily recreate this by compiling this [example](https://github.com/boostorg/beast/blob/develop/example/websocket/client/async/websocket_client_async.cpp) like an dll (just add DllMain thing and FreeLibrary at the end of main thread which you create in DllMain) -> https://pastebin.com/fvwsaa9G

I guess its problem of Boost Asio and Asio ( because i tried to use this [websocket](https://github.com/zaphoyd/websocketpp), but it has same problem)
Compiler : Visual Studio 2019
Beast version : 266

**Comment by vinniefalco** [comment]
Is this relevant? https://stackoverflow.com/questions/43904050/c-sharp-using-freelibrary-to-unload-dynamic-loading-of-c-unmanaged-dll-does-no

**Comment by rraggerr** [comment]
> Is this relevant? https://stackoverflow.com/questions/43904050/c-sharp-using-freelibrary-to-unload-dynamic-loading-of-c-unmanaged-dll-does-no

I do not know much about C#, but looks like yes.

**Comment by vinniefalco** [comment]
Are you using OpenSSL? Is this answer relevant?

> I eventually did find the root cause of this problem. The issue is using the shared dynamically-linked SSL library. Even though I release memory my DLL uses for interface to SSL library, the OS keeps a portion of my DLL locked in memory due to the way the SSL library initializes itself when called. From what I remember with my research, there's no good existing way to correct this other than statically linking the SSL source in my DLL

**Comment by rraggerr** [comment]
> Are you using OpenSSL? Is this answer relevant?
> 
> > I eventually did find the root cause of this problem. The issue is using the shared dynamically-linked SSL library. Even though I release memory my DLL uses for interface to SSL library, the OS keeps a portion of my DLL locked in memory due to the way the SSL library initializes itself when called. From what I remember with my research, there's no good existing way to correct this other than statically linking the SSL source in my DLL

No, i dont use OpenSSL

**Comment by rraggerr** [comment]
So i've updated Boost library to 1.72, now Beast version is 277. Problem still exists.

**Comment by rraggerr** [comment]
nope

**Comment by rraggerr** [comment]
no

**Comment by vinniefalco** [comment]
There isn't much we can do here, treatment of DLLs is outside the scope of Beast. Unless there is an actual bug in Beast, we can't do anything about it, so I'll go ahead and close this issue.
