### ISSUE TITLE
Question: Rest framework on top of Beast

### ISSUE THREAD

**Issue by overthetop** [boostorg/beast#1797]
Hi all. @vinniefalco thank you for that wonderful library. I'm wondering what will be the most popular rest framework on top of beast at the moment? The only one I've found so far is that https://github.com/0xdead4ead/BeastHttp which is way less popular than the beast project itself :(. I'm wondering if exists something simular with better adoption. I'm looking for a popular library that provides ease of development and high performance.

**Comment by vinniefalco** [comment]
What kind of REST? Do you mean JSON-RPC over HTTP? JSON-RPC over WebSocket? Something else? Are you looking for a client or a server?

Perhaps one of these projects will suit your needs:
https://github.com/boostorg/beast/wiki/Companies-and-Individuals-Using-Beast

**Comment by overthetop** [comment]
Hi @vinniefalco I'm looking for a way to quickly build REST APIs. This is the most common way to build a Web API currently. That would be a quick way to handle HTTP GET, POST, DELETE, PUT etc. requests. See this link for a comparison to RPC API https://blog.jscrambler.com/rpc-style-vs-rest-web-apis/
I want to use c++ for building microservices that will be accessible from a web browser over http. This will show off all the benfits of c++ in building modern cloud architectures.

**Comment by vinniefalco** [comment]
That page has a great explanation, thanks! I am not really an expert on these matters.

**Comment by overthetop** [comment]
Thx for the link @vinniefalco Beast can be used to build a REST API but the code is just too verbose and that makes it difficult. Hope that in future a higher level framework on top of beast will emerge and will get wildly adopted in the c++ world. Currently there isn't such a solution and that's really sad because everybody want to build for the web in 2020. Perhaps if such a framework gets into boost, that will surely became main-stream.

**Comment by madmongo1** [comment]
@overthetop watch this space. In the meantime, this may help: https://github.com/LeonineKing1199/foxy

**Comment by kervinpierre** [comment]
for prosperity: https://github.com/expresscpp/expresscpp
