### ISSUE TITLE
[Question] Beast doesn't seem to work for Bria softphone desktop API websocket

### ISSUE THREAD

**Issue by viduranga** [boostorg/beast#1798]
@vinniefalco thanks for the amazing ws library. I've been using this for many projects. However, for a strange reason it doesn't seem to work for the Bria softphone desktop API after their 5.8 update. The socket connection establishes without any issues but when I write to it, it doesn't seem to transfer. When I try to read, it fails with "Error: The WebSocket stream was gracefully closed at both endpoints".
One thing to note that, Bria API accepts connections to any target and if the target is incorrect, this behaviour is desirable I guess. But I'm using the exact same target they provided and also javascript test with same target seems to work just fine.
I'm attaching the test codes for both C++ and Javascript for you to check. I'd be thankful if you can help.

C++:
`

        auto host = "cpclientapi.softphone.com", endpoint = "/counterpath/socketapi/v1", port = "9002";
        net::io_context ioc;
        ssl::context ctx{ssl::context::tls_client};
        websocket::stream<ssl::stream<tcp::socket>> m_websocket{ioc, ctx};

        tcp::resolver resolver{ioc};

        const auto resolved = resolver.resolve(host, port);

        boost::asio::connect(m_websocket.next_layer().next_layer(), resolved.begin(), resolved.end());

        m_websocket.next_layer().handshake(ssl::stream_base::client);
        m_websocket.handshake(host, endpoint);

        std::string request = "GET/bringToFront\n"
                       "User-Agent: TestApp\n"
                       "Transaction-ID: AE26f998027\n"
                       "Content-Type: application/xml\n"
                       "Content-Length: 0";
        m_websocket.write(boost::asio::buffer(request));

        beast::flat_buffer m_resBuffer;
        m_websocket.read(m_resBuffer);

        std::cout << beast::buffers_to_string(m_resBuffer.data()) << std::endl;

        m_websocket.close(websocket::close_code::normal);`

Javascript:
`

    const  ws = new WebSocket("wss://cpclientapi.softphone.com:9002/counterpath/socketapi/v1");

    ws.addEventListener('message', function (event) {
        console.log(event.data);
    });
    
    ws.addEventListener('open', function (event) {
        ws.send("GET/bringToFront\n" +
            "User-Agent: MyApplication\n" +
            "Transaction-ID: AE26f998027\n" +
            "Content-Type: application/xml\n" +
            "Content-Length: 0")
    });`

PS: This is the output I get from BOOST_ASIO_ENABLE_HANDLER_TRACKING, if that helps.

_@asio|1578194069.501070|0|resolver@0x7ffee37681f0.cancel
@asio|1578194069.556133|0|resolver@0x7ffee3769738.cancel
@asio|1578194069.556544|0|socket@0x7fc9a880a260.close
Error: The WebSocket stream was gracefully closed at both endpoints
@asio|1578194069.557341|0|socket@0x7fc9a8008660.close_

**Comment by viduranga** [comment]
Ignore the send message format. Bria uses an HTTP type message format.

**Comment by vinniefalco** [comment]
Try adding
```
m_websocket.binary( true );
```
before sending the message

**Comment by vinniefalco** [comment]
Another thing to try, declare the stream so that compression is disabled:
```
websocket::stream<ssl::stream<tcp::socket>, false> m_websocket{ioc, ctx};
```

**Comment by viduranga** [comment]
Seems to be the same error still :(

**Comment by viduranga** [comment]
This is the request generated by JS btw.

```
GET wss://cpclientapi.softphone.com:9002/counterpath/socketapi/v1 HTTP/1.1
Host: cpclientapi.softphone.com:9002
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
Upgrade: websocket
Origin: http://localhost:63342
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,de;q=0.8
Sec-WebSocket-Key: PwbI9QJULrCE6yuFxztoBw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

**Comment by vinniefalco** [comment]
Hmm No idea. The upgrade request looks fine to me.

**Comment by viduranga** [comment]
Thanks for the quick response anyway @vinniefalco. I'll post here if I found a solution.
BTW, is there a way to log the HTTP requests sent by asio for the websocket handshakes?

**Comment by madmongo1** [comment]
Hi @viduranga It might be worth installing wireshark and comparing the actual network traffic of the two requests. If there are differences, kindly post them here and I'll take a look.
https://www.wireshark.org/

**Comment by viduranga** [comment]
Hi, Thank you @madmongo1 for the support. I don't have much experience in packet monitoring, so would really help me out if you can take a look at these and give me some insights. Thanks.
[packet_dumps.zip](https://github.com/boostorg/beast/files/4024825/packet_dumps.zip)

**Comment by madmongo1** [comment]
Hi @viduranga 

I have created a minimal complete project with the intention of recreating the problem. I don't have access to your server (connection refused).

If you could open a public port to it (or a safe copy of it in a DMZ) and let me know, I'll check my end.

You could also build the example and see whether you still get the problem (if not, your problem is somewhere else in your code).

https://github.com/test-scenarios/beast-softphone-problem

**Comment by madmongo1** [comment]
Hi @viduranga I was tidying up the code a little (even the tiniest of programs can become a time sink...)

I noticed this line:

```
    std::string request = "GET/bringToFront\n"
                          "User-Agent: TestApp\n"
                          "Transaction-ID: AE26f998027\n"
                          "Content-Type: application/xml\n"
                          "Content-Length: 0";
```
The line-endings here do not conform the the http standard, which requires `"\r\n"`

A header block would also require a terminating `"\r\n"`

Would that be relevant?

**Comment by viduranga** [comment]
Hi @madmongo1 
"cpclientapi.softphone.com" actually redirects to 127.0.0.1 which at the end connects to your local Bria Softphone application. Unfortunately you'd need the Bria Softphone application and an asterisk server to get it to work (I can send a simple asterisk docker image if you have the Bria Softphone trial version). 
Regarding the line endings, I actually get the "The WebSocket stream was gracefully closed at both endpoints" exception right when I try to read from the socket. Even when I removed the "write" call, I get the same error.

**Comment by madmongo1** [comment]
@viduranga 

One thing that this code snippet does not do is this:

```
        // Set SNI Hostname (many hosts need this to handshake successfully)
        if(! SSL_set_tlsext_host_name(stream.native_handle(), host))
        {
            beast::error_code ec{static_cast<int>(::ERR_get_error()), net::error::get_ssl_category()};
            throw beast::system_error{ec};
        }
```

If the web server in your docker container is sitting behind a proxy (e.g. ngnix reverse proxy) then the request may well be rejected as the proxy won't know which upstream web server to hand the request to (even if there's only one).

**Comment by viduranga** [comment]
Hi @madmongo1 
The docker container actually contain the asterisk server, but we're trying to connect to the Softphone application. 
Sorry I didn't explain properly before.
There are 3 components.
1. Asterisk server which handles the PABX and do the VOIP. 
2. Bria Softphone application which runs on your computer and connect to the Asterisk server. You can dial calls from this application. Bria Softphone application also creates a background service which you can connect for RPA processes.
3. The program we're trying to write, connects to that local service and automate the softphone application.

**Comment by viduranga** [comment]
"SSL_set_tlsext_host_name(ws.next_layer().native_handle(), host)" also tried out without any luck :(

**Comment by madmongo1** [comment]
Next things to check:

* asterisk logs (turn up the logging level if possible)

* are you comfortable to place a server on an external Internet address for a short while so I can experiment?

**Comment by viduranga** [comment]
Hi @madmongo1 
Yes, I'll forward the ports and let you know because that will be the easiest for you to test.
