### ISSUE TITLE
Statistics socket bandwidth

### ISSUE THREAD

**Issue by midle110** [boostorg/beast#1800]
i can statistics inbound and outbound when i use  tcp::socket,
but i don't know when tcp-ssl or Beast ?

is there any way ?

**Comment by vinniefalco** [comment]
https://www.boost.org/doc/libs/1_72_0/libs/beast/doc/html/beast/using_io/layered_streams/counted_stream_example.html

**Comment by midle110** [comment]
think you very much , it is same to tls-tcp .
👍
