### ISSUE TITLE
refactor cmake file

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1816]
The Beast CMakeLists.txt needs to be updated using one in JSON as a template:
https://github.com/vinniefalco/json/blob/develop/CMakeLists.txt

Don't forget to update the README.md with the necessary lines:
https://github.com/vinniefalco/json/#cmake

**Comment by madmongo1** [comment]
There are some additional operations in the boost beast CMakeLists.txt file.
I'd value a discussion with you prior to proceeding.

**Comment by vinniefalco** [comment]
Can you just briefly enumerate what those operations are?

**Comment by ricejasonf** [comment]
Building tests and examples by default is cumbersome, and everyone has their own one-off way of disabling them that have to be specified.

Also, I noticed you can not build using cmake without OpenSSL:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENSSL_CRYPTO_LIBRARY (ADVANCED)
    linked by target "lib-beast" in directory /usr/local/src/beast-6f57e5934c1f307e4510ee11dd09594526a3f5d0

... (more libraries follow)
```

**Comment by vinniefalco** [comment]
Use bjam

**Comment by vinniefalco** [comment]
I agree this needs to be addressed

**Comment by klemens-morgenstern** [comment]
Same as #2472.

**Comment by vinniefalco** [comment]
@grisumbras needs to do it, or someone needs to make it like the JSON and URL CMLs

**Comment by grisumbras** [comment]
Ok, I'll get to it on Monday.

**Comment by grisumbras** [comment]
What usage variants does Beast support?
1. Standalone build (outside of Boost tree, as a top-level project).
2. Boost build (inside Boost tree, under superproject).
4. Integrated standalone build (as a subdirectory of a user build, not under superpoject, and not as a Boost lib).
5. Integrated boost build (as a subdirectory of a user build, not under superpoject, but as a Boost lib).

Is that all?

**Comment by vinniefalco** [comment]
I'm not sure. I want as few variants as possible. I can only think of 2 that are required. One is the normal in-superproject which is used to build the releases. The other is the author/maintainer workflow. This might even only be one variant. I would like it to be like JSON, URL, and Http-Proto where the lib is its own target, the dependencies are cleanly specified, and so on

**Comment by klemens-morgenstern** [comment]
I don't think anything but (2) make sense tbh, since beast doesn't have a standalone version.

**Comment by grisumbras** [comment]
Oh, I was under impression Beast has a standalone version.
