### ISSUE TITLE
Tls 1.3 client does not report failed handshake when client certificate verification by server failed

### ISSUE THREAD

**Issue by keksmaster** [boostorg/beast#1817]
### Background

We use boost beast, and create both clients and servers. We use them for testing that certain handshakes succeed or fail (depending on the configuration of the beast clients/servers) when connecting to our stack, or for simple requests and the respective responses (that we cannot trigger in our stack directly as a lot of it happens automatically).

Doing so, we noticed a peculiar difference in the boost beast client behaviour, depending solely on whether one uses Tls 1.2 or 1.3.

### Actual Issue

When the server rejects the client's certificate, i.e. the client's certificate verification fails, a boost beast TLSv1.2 client will report an error from the handshake, specifically the errorcode will have the value: '336151608' and corresponding message 'tlsv1 alert internal error'.

In contrast, a boost beast TLSv1.3 client will report no error from the handshake, i.e. an errorcode will have the value '0' and corresponding message 'The operation completed successfully'.

### Version of Beast

We are using boost 1.71.0

### Steps necessary to reproduce the problem

It can be reproduced using boost beast only.
For this, you need a beast client and server running in different threads/processes (when using synchronous calls) or use asynchronous calls.
Configure both to verify their peers.
Configure the beast server to have a verification callback that simply returns false (i.e. the verification of the client's certificate will fail in any case.)
Configure both to use TLSv1.2 or TLSv1.3 respectively.

See attached file (the code is not running as is since you need to configure your keys and certificates)
[TestTlsVerifyIssue.zip](https://github.com/boostorg/beast/files/4102435/TestTlsVerifyIssue.zip)

**Comment by madmongo1** [comment]
Hi @keksmaster , thanks for taking the time to create this issue. 
Big thanks for supplying a test program!

I have taken your test program, modified it a little and built a little repo to attempt to reproduce the issue here: https://github.com/test-scenarios/beast-issue-1817

Building with a c++17 toolchain against the defalt hunter selections for boost version and openssl version, I get the following output:

```
OpenSSL Version: OpenSSL 1.1.1d  10 Sep 2019
Boost Version: 1.71.0

Testing with: SslVersion::TlsV1_2
server:
 handshake returned error code=337092801
error message=no shared cipher
client:
 handshake returned error code=336151568
error message=sslv3 alert handshake failure

Testing with: SslVersion::TlsV1_3
client:
 handshake returned error code=336151598
error message=tlsv1 alert protocol version
server:
 handshake returned error code=337678594
error message=unsupported protocol
```

Are you in a position to compile this program and confirm what output you are seeing please?

**Comment by madmongo1** [comment]
...and now that I've read the instructions and added a certificate/key pair:

```OpenSSL Version: OpenSSL 1.1.1d  10 Sep 2019
Boost Version: 1.71.0

Testing with: SslVersion::TlsV1_2
client:
 handshake returned error code=337047686
error message=certificate verify failed
server:
 handshake returned error code=336151576
error message=tlsv1 alert unknown ca

Testing with: SslVersion::TlsV1_3
client:
 handshake returned error code=337047686
error message=certificate verify failed
server:
 handshake returned error code=336151576
error message=tlsv1 alert unknown ca
```

**Comment by vinniefalco** [comment]
There's no beast involved here though, right?

**Comment by keksmaster** [comment]
> ...and now that I've read the instructions and added a certificate/key pair:
> 
> ```
> OpenSSL Version: OpenSSL 1.1.1d  10 Sep 2019
> Boost Version: 1.71.0
> 
> Testing with: SslVersion::TlsV1_2
> client:
>  handshake returned error code=337047686
> error message=certificate verify failed
> server:
>  handshake returned error code=336151576
> error message=tlsv1 alert unknown ca
> 
> Testing with: SslVersion::TlsV1_3
> client:
>  handshake returned error code=337047686
> error message=certificate verify failed
> server:
>  handshake returned error code=336151576
> error message=tlsv1 alert unknown ca
> ```

Interesting, that is pretty much the output I would have expected.

I will investigate the repo you created

**Comment by madmongo1** [comment]
I’d be fascinated to learn the results. Perhaps an OpenSSL version issue? 
Either way please do come back when you learn more. If there are versions of OpenSSL that do not work, I believe we owe it to our users to tell them.

**Comment by keksmaster** [comment]
> There's no beast involved here though, right?

That is absolutely right. If this issue proves to be an actual issue, it lies in boost/asio.

> I’d be fascinated to learn the results. Perhaps an OpenSSL version issue?
> Either way please do come back when you learn more. If there are versions of OpenSSL that do not work, I believe we owe it to our users to tell them.

I have opened a PR on the test repo you created to make it a minimal working example.

All in all, this issue can be closed as it is not an issue of boost/beast. My bad!
I have opened a corresponding [issue](https://github.com/boostorg/asio/issues/323) in asio.

Thanks for the help!

**Comment by madmongo1** [comment]
with latest changes:

```
OpenSSL Version: OpenSSL 1.1.1d  10 Sep 2019
Boost Version: 1.71.0

Testing with: SslVersion::TlsV1_2
client:
 handshake returned error code=336151608
error message=tlsv1 alert internal error
server:
 handshake returned error code=337100934
error message=certificate verify failed

Testing with: SslVersion::TlsV1_3
client:
 handshake returned error code=0
error message=Success
server:
 handshake returned error code=337100934
error message=certificate verify failed
```

**Comment by vinniefalco** [comment]
> All in all, this issue can be closed as it is not an issue of boost/beast. My bad

No prob, issues in boostorg/asio are typically ignored for years

**Comment by keksmaster** [comment]
> with latest changes:
> 
> ```
> OpenSSL Version: OpenSSL 1.1.1d  10 Sep 2019
> Boost Version: 1.71.0
> 
> Testing with: SslVersion::TlsV1_2
> client:
>  handshake returned error code=336151608
> error message=tlsv1 alert internal error
> server:
>  handshake returned error code=337100934
> error message=certificate verify failed
> 
> Testing with: SslVersion::TlsV1_3
> client:
>  handshake returned error code=0
> error message=Success
> server:
>  handshake returned error code=337100934
> error message=certificate verify failed
> ```

I'm glad to see that you can reproduce the issue
