### ISSUE TITLE
http::basic_fields bug

### ISSUE THREAD

**Issue by brjoha** [boostorg/beast#1828]
Using this sequence of actions...

beast::http::request<beast::http::string_body> req;
req.insert("abc", "1");
req.insert("abc", "2");
req.insert("abc", "3");

...a call to req.count("abc") returns 3 as expected.  If we then do the following...

auto iter = req.find("abc");
req.insert("abc", "4");
req.erase(iter);

...a call to req.count("abc") returns 0 instead of 3.  However, the header was properly updated since printing the request gives...

 HTTP/1.1
abc: 1
abc: 2
abc: 4

**Comment by vinniefalco** [comment]
Could you perhaps submit a pull request that updates the test?
https://github.com/boostorg/beast/blob/c9d5049307925bccaf2f5e57c127db1a1c78e178/test/beast/http/fields.cpp#L402

If not, I can do it.

**Comment by vinniefalco** [comment]
Code for the tests is here
https://github.com/boostorg/beast/blob/c9d5049307925bccaf2f5e57c127db1a1c78e178/test/beast/http/fields.cpp#L402

**Comment by madmongo1** [comment]
Hi @brjoha :

That was a great find. Thank you so much for the helpful steps to reproduce.

As you can see above, I have created a test to prove the bug, and its fix.

Keep them coming!

R
