### ISSUE TITLE
moved-from objects should not be cleared if allocator unequal

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1832]
dynamic buffers like `flat_buffer` should not be clever and clear the moved-from container when the allocator compares unequal.

**Comment by madmongo1** [comment]
This is a question. There may be use cases I'm not aware of.

I'm interested to understand the design rationale behind providing:

`flat_buffer(flat_buffer&&, Allocator const& alloc)` at all.

This can only perform a move if the allocators compare equal, in which case it seems to me that a caller would have nothing to gain by supplying the allocator and an r-value.

I am wondering if we'd lose anything by only providing:

`flat_buffer(flat_buffer const&, Allocator const& alloc)`
`flat_buffer(flat_buffer const&)`
`flat_buffer(flat_buffer &&) noexcept`

**Comment by vinniefalco** [comment]
It comes up in generic contexts. All std containers have allocator-extended move constructors.
