### ISSUE TITLE
Static analysis: exception spec violation in basic_fields::operator=

### ISSUE THREAD

**Issue by michael-baumann** [boostorg/beast#1833]
### Version of Beast

boost 1.71.0 / **266**

Our static analysis tool (coverity) reports the following:

> Uncaught exception (UNCAUGHT_EXCEPT)
> exn_spec_violation: An exception of type std::length_error is thrown but the throw list noexcept doesn't allow it to be thrown.

in:

In: beast/http/impl/fields.hpp:434

```
basic_fields<Allocator>::
operator=(basic_fields&& other) noexcept(
    alloc_traits::propagate_on_container_move_assignment::value)
      -> basic_fields&
```

Calling in beast/http/impl/fields.hpp:443
```
move_assign(basic_fields& other, std::true_type)
```

Calling in beast/http/impl/fields.hpp:1122
```
clear_all();
```

Calling in beast/http/impl/fields.hpp:1102
```
realloc_string(string_view& dest, string_view s)
```

Calling in beast/http/impl/fields.hpp:1040
```
a.allocate(s.size());
```

which throws std::length_error in case requested size exceeds max_size()

### All relevant compiler information

Xcode10.2.1 on MacOS, libc++

(see also
https://github.com/llvm-mirror/libcxx/blob/master/include/memory line 1850)

I am not familiar enough with these internals, so unsure whether its a false positive or some adaption is necessary, please have look.

**Comment by madmongo1** [comment]
Hi @michael-baumann ,

Thanks for bringing this to our attention.

I will investigate with haste.

**Comment by vinniefalco** [comment]
I believe this was fixed in a recent commit?

**Comment by madmongo1** [comment]
So do i
