### ISSUE TITLE
Is it possible to get the entire raw HTTP request or response?

### ISSUE THREAD

**Issue by cpp19** [boostorg/beast#1842]
Hi,

I am looking at the Beast library and I would like to know if it's possible to get the entire raw HTTP request or response.

I see that `message.hpp` provides functions to access the individual fields and the body. Is the raw buffer stored too? Or do we need to reconstruct it programmatically?

Browsing the code, I found `boost::beast::http::request_serializer` but I wasn't able to write the code to convert a request or response to a C-style buffer.

Any help would be greatly appreciated.
Thank you
C

**Comment by vinniefalco** [comment]
Use https://www.boost.org/doc/libs/1_72_0/libs/beast/doc/html/beast/ref/boost__beast__http__operator_lt__lt_/overload5.html

**Comment by cpp19** [comment]
Thank you. It worked!
