### ISSUE TITLE
help Link in the README direct to obsolete content

### ISSUE THREAD

**Issue by GPierre-Antoine** [boostorg/beast#1844]
Some links in the readme are dead :
- [Best Kept Secrets of Peer Code Review (pdf)](https://smartbear.com/SmartBear/media/pdfs/best-kept-secrets-of-peer-code-review.pdf)
- [The link to 11 Best Practices for Peer Code Review](http://support.smartbear.com/support/media/resources/cc/11_Best_Practices_for_Peer_Code_Review.pdf)
- [C++ Coding Standards (Sutter & Andrescu)](https://doc.lagout.org/programmation/C/CPP101.pdf)

**Comment by vinniefalco** [comment]
sad. we should just remove them.

**Comment by madmongo1** [comment]
I have found replacement links for the first two and have modified the link to C++ Coding Standards so that it points to the book on the publisher's website.
