### ISSUE TITLE
Using BoostBeast with OpenMP crashes Clang

### ISSUE THREAD

**Issue by planetmarshall** [boostorg/beast#1848]
Clang crashes when compiling a program using Boost.Beast with OpenMP. I realize that this may or may not be a bug with Boost.Build (Clang shouldn't really crash even if the input is invalid). I have also logged a bug with [LLVM Bugzilla](https://bugs.llvm.org/show_bug.cgi?id=44914)

### Version of Beast

1.72.0

### Steps necessary to reproduce the problem

Minimal program provided here - 

https://github.com/planetmarshall/boost_beast_openmp

TL;DR, compile a program using `Boost.Beast` with `-fopenmp` and compile it with clang.

### Expected Results:

Something like
```
Thread Number: 5
Thread Number: 0
Thread Number: 9
Thread Number: 2
...etc...
```

### Actual Results

Clang crashes while generating code for `boost::beast::http::detail::is_token_char` in `boost/beast/http/detail/rfc7230.ipp` [clang_crash.txt](https://github.com/boostorg/beast/files/4214592/clang_crash.txt)

### Workaround

Compiles successfully with GCC 8.3

### All relevant compiler information

* Ubuntu 18.04 LTS
* Clang 9
* Boost 1.72.0

**Comment by planetmarshall** [comment]
For the record, I only came across this because my openmp flags were propagating through my codebase due to me not using CMake properly. I don't actually *need* to use OpenMP with Boost Beast, but thought it was worth logging.

**Comment by madmongo1** [comment]
Thanks for logging this @planetmarshall.

Kudos for providing an MVCE!

**Comment by planetmarshall** [comment]
Just tested on Clang 11 and it compiles fine.

**Comment by planetmarshall** [comment]
I'm pretty sure this is a Clang issue and nothing to do with Boost Beast per se, so will close. You can even crash the compiler on Compiler Explorer by adding `-fopenmp` to the compiler options if you are so inclined :) https://godbolt.org/z/yPkWYt

**Comment by vinniefalco** [comment]
nice trick
