### ISSUE TITLE
Combined HTTP and HTTPS client

### ISSUE THREAD

**Issue by Tectu** [boostorg/beast#1849]
I'd like to write an HTTP client class on top of `boost.beast` which will provide the user with an interface such as `my_client::synchronous_request(...)`.
For this, I've been studying the examples & documentation. The two HTTP client examples (SSL & non-SSL) examples have been very helpful for this.

My client class should be able to deal with both SSL and non-SSL connections. To keep things simple, I am trying to figure out whether I can build a client based on the `example/http/client/sync-ssl` that will also be able to handle non-SSL connections.

Is this something that `boost.beast` endorses or do I have to have two internal (private) `my_client::perform_synchronous_request()` functions - one that can handle SSL connections and one that handles non-SSL connections or is `boost.beast` able to handle non-SSL connections although SSL is setup/configured?

**Comment by madmongo1** [comment]
Hi @Tectu, you have a couple of options.

* note that the `next_layer` of an ssl stream is a tcp stream, so you could have a conditional at each stream function initiation, for example:

```
if (ssl_enabled_)
  read(stream, buf, request, ec);
else
  read(stream.next_layer(), buf, request, ec);     
```

* Another option is to have a polymorphic interface to the code that handles transport-related code (read, write, shutdown) and have two models, one ssl and one not

* another option is to write a SynchronousStream type which does one of the above internally. This is the approach I took in a recent project involving beast. However, Vinnie would argue that the polymorphic transport class is preferrable. I would post the example code, but I wrote a model of AsyncStream which is far more complicated and would probably confuse the issue.

**Comment by madmongo1** [comment]
@vinniefalco Would it be worth discussing whether we could provide a stream type which was upgradeable to ssl and downgradable to tcp?

It may not be the most technically pleasing solution, but our users may appreciate the utility.

**Comment by Tectu** [comment]
@madmongo1 thank you for your quick response. I am fairly new to `boost.beast` so just to be sure that I understand correctly I created this diagram which is how I understand option 2 (the polymorphic class approach). Does this correspond to the intended solution?

![image](https://user-images.githubusercontent.com/1385320/74745277-ef678400-5263-11ea-98d5-d9e44924bf28.png)

**Comment by madmongo1** [comment]
@Tectu that looks reasonable

**Comment by Tectu** [comment]
I'll close this issue once I have it actually working. I think I'm close but I am still running into an issue that is currently unclear to me: https://stackoverflow.com/questions/60302428/boost-beast-combined-http-and-https-client

**Comment by vinniefalco** [comment]
> http::read() returns a bad version

Sounds like you did not perform the TLS handshake, and Beast is trying to interpret the binary TLS handshake data from the peer as an HTTP message (which it isn't). There's no need to reinvent the wheel here, Beast already comes with a few examples of "flex" (i.e. TLS and Plain) support, see:
https://github.com/boostorg/beast/tree/develop/example/advanced/server-flex

**Comment by Tectu** [comment]
> There's no need to reinvent the wheel here, Beast already comes with a few examples of "flex" (i.e. TLS and Plain) support, see:
> https://github.com/boostorg/beast/tree/develop/example/advanced/server-flex

I'm very much against reinventing the wheel - I didn't come across that example as first of all I was looking too much for client examples and also I wasn't aware of the 'flex' term :)

The example looks comparably complex - could you boil it down to a list of "necessary things to take care of" so that I can reference those points to the example and then translate it to my own client code? That would be greatly appreciated.

**Comment by vinniefalco** [comment]
The point of this example is that it uses the Curiously Recurring Template Pattern ("CRTP") so that one base class can work with either TLS or plain connections. The particular stream type is provided by the derived class. It looks complex because it supports both HTTP and WebSocket.

**Comment by Tectu** [comment]
I am looking at the flex examples and I see how CRTP is great here. In fact, the library to which this `boost.beast` based HTTP client should be added makes already heavy use of CRTP.

I don't mind changing my design based on the examples but before that I'd like to understand why my current solution is not working - otherwise I don't learn anything.
I am new to `boost.beast` and I'd greatly appreciate if you could give me a few pointers on what to look out for when trying to debug this. Even if it's just something like _"add this error handler callback to there in order to figure out why the handshake might have failed."_

**Comment by madmongo1** [comment]
Can you send me a link to a minimal computable example of your solution? Maybe I can offer some advice.

**Comment by Tectu** [comment]
Thank you for your efforts, I appreciate it a lot. I've zipped my minimal test case: https://files.simulton.com/s/GSFpnKAEctLyKbn

**Comment by madmongo1** [comment]
He @Tectu just saw this. Taking a look

**Comment by madmongo1** [comment]
I have created a github repo and pushed the corrected code:

https://github.com/test-scenarios/beast-issue-1849

**Comment by Tectu** [comment]
@madmongo1 thank you _very_ much for your help - I appreciate your efforts. I understand now what I did wrong and your further improved example is definitely of great help!
