### ISSUE TITLE
Hash collision on big endian systems in http::detail::field_table

### ISSUE THREAD

**Issue by oliverdaniell** [boostorg/beast#1863]
Boost version 1.70.0

On big endian systems there is a hash collision between the  `Autosubmitted` and `Distribution` fields in http::detail::field_table. The difference in behaviour with little endian systems is caused by reinterpreting the string as an integer at `boost/beast/http/impl/field.ipp` on lines 42, 74 and 75. I believe this can be fixed using 

```
endian::native_to_little_inplace(v);
```

You can reproduce the issue using the following code

```
#include <boost/beast/http/field.hpp>
int main() { boost::beast::http::detail::field_table table; }
```

Output:

```
boost/beast/http/impl/field.ipp:457: boost::beast::http::detail::field_table::field_table(): Assertion map_[j][0] == 0' failed.
```

**Comment by vinniefalco** [comment]
but.. a hash collision should be okay since it compares to make sure there's a match and then moves on to then next entry?

**Comment by oliverdaniell** [comment]
This assertion fires during construction of field_table
```
457: BOOST_ASSERT(map_[j][0] == 0);
```

https://github.com/boostorg/beast/blob/develop/include/boost/beast/http/impl/field.ipp

**Comment by vinniefalco** [comment]
hmm it looks like the invariant is that there are no collisions for field numbers 0..255 (which get put into `map_[][0]` and then there must be no collisions for field numbers 256+ (which go to `map_[][1]`) does this sound right?

**Comment by vinniefalco** [comment]
Can you please submit a pull request, but instead of using `endian::native_to_little_inplace` just put an `inline` function into field.ipp that does the same thing?

**Comment by oliverdaniell** [comment]
> hmm it looks like the invariant is that there are no collisions for field numbers 0..255 (which get put into map_[][0] and then there must be no collisions for field numbers 256+ (which go to map_[][1]) does this sound right?

Yes the hash for the first 256 fields must be unique in order to perform the reverse lookup on line 480

**Comment by vinniefalco** [comment]
Instead of `memcpy` would something like this work
```
            v = p[0] +
                256 * p[1] +
                256 * 256 * p[2] +
                256 * 256 * 256 * p[3];
```

**Comment by oliverdaniell** [comment]
I believe so, I'll add an inline function as the same behaviour is required for lines 74,75

**Comment by vinniefalco** [comment]
Don't worry about the pull request, I am handling it. I realize that there should have been more comments in these functions, because I can barely recognize what it is doing! I will have something for you shortly.

**Comment by oliverdaniell** [comment]
```
    static std::uint32_t little_to_native(unsigned char const* p)
    {
        return  p[0] |
                (p[1] <<  8) |
                (p[2] << 16) |
                (p[3] << 24);
    }
```
```
std::uint32_t v = little_to_native(p);
```

```
Int v1 = little_to_native(reinterpret_cast<unsigned char const*>(p1));
Int v2 = little_to_native(reinterpret_cast<unsigned char const*>(p2));
```

I've added a quick test to my powerpc platform and it looks like this does the job. I'm happy to test the merge request when it's available.

**Comment by vinniefalco** [comment]
Here it is https://github.com/boostorg/beast/pull/1864

**Comment by oliverdaniell** [comment]
Merge request looks good, thanks for the help.
