### ISSUE TITLE
Async websocket client ignores target value

### ISSUE THREAD

**Issue by AnwaPeck** [boostorg/beast#1871]
The async websocket client ALWAYS reaches the root "/" endpoint, regardless of target value "/foo" that I specify.  Do I need to specify this value elsewhere (as well)?

// Perform the websocket handshake
ws_.async_handshake(host_, "/foo",
        beast::bind_front_handler(
                &session::on_handshake,
                shared_from_this()));

**Comment by vinniefalco** [comment]
When you inspect the handshake using wireshark, what is being sent?

**Comment by AnwaPeck** [comment]
Using SSL version... so having difficulty with inspection

**Comment by vinniefalco** [comment]
Use a decorator to get the request message and print it before it is sent:
https://www.boost.org/doc/libs/1_72_0/libs/beast/doc/html/beast/using_websocket/decorator.html

**Comment by AnwaPeck** [comment]
My bad!  'Problem' solved.  Rookie cmake error on my side.  Build appeared to be successful but target executable was not being replaced.  Thanks for the prompt assist. Appreciated.

B.T.W.  I found a decorator in the sample code I was using.. Then while following your instruction to print the message... I realised that I was executing a stale build.

**Comment by vinniefalco** [comment]
Glad it got sorted!
