### ISSUE TITLE
Can you open a Gitter channel?

### ISSUE THREAD

**Issue by patlecat** [boostorg/beast#1891]
Would be nice to have a chat room to exchange with peers. Why not open a Gitter channel for this? I could not find anything on any platform yet. Gitter is close to GitHub so that would be natural choice I think.

[Gitter IM](https://gitter.im/)

**Comment by vinniefalco** [comment]
slack.cppalliance.org `#beast` channel

**Comment by patlecat** [comment]
@vinniefalco Thanks a lot, worked!

**Comment by madmongo1** [comment]
@patlecat is now successfully in communication with us on slack. closing.
