### ISSUE TITLE
custom body writer template constructor and header field

### ISSUE THREAD

**Issue by AlexandreBossard** [boostorg/beast#1900]
using beast 1.71.

Hi, I'm having a hard time to figure out how I can use/set the header field in my custom body writer. the documentation says that "_the writer shall not access the contents of h or v before the first call to init, permitting lazy construction of the message._ " [source](https://www.boost.org/doc/libs/1_71_0/libs/beast/doc/html/beast/concepts/BodyWriter.html). But how am i suppose to store the headers since the type is lost outside of the writer's constructor ?

Technically, I would like to set the content_type for my custom body type but I am bit at a loss of how to do it.

This makes me wonder what the constructor parameters are for or what are you supposed to do with it  ?
```
class json_writer
{
public:
  using const_buffers_type = net::const_buffer;

  template <bool isRequest, typename Fields>
  json_writer(http::header<isRequest, Fields> & h, json_wrapper const& b)
    : body_(b)
  {
    // if (h.find(http::field::content_type) == h.end())
    //   h.set(http::field::content_type, "application/json");
  }
// ....
}
```

**Comment by vinniefalco** [comment]
custom bodies cannot set headers. You need to do this in the calling code.

**Comment by AlexandreBossard** [comment]
Alright then  :/

So, what is the **header** parameter supposed to be used for ?

**Comment by vinniefalco** [comment]
So you can _read_ the header and know what to do

**Comment by terrywh** [comment]
documentation says: "The writer shall not access the contents of h or v before the first call to init, permitting lazy construction of the message." but we cant access header int "init" function, so what to do?

**Comment by vinniefalco** [comment]
It might not work as advertised

**Comment by terrywh** [comment]
> It might not work as advertised
does it mean for now we can't implement a body writer/reader depends on the header?

**Comment by vinniefalco** [comment]
> does it mean for now we can't implement a body writer/reader depends on the header?

Yes it might not be possible.
