### ISSUE TITLE
overload for websocket_stream::async_accept

### ISSUE THREAD

**Issue by reapler** [boostorg/beast#1910]
I would like to propose the following function signature in beast/websocket/stream.hpp for websocket_stream::async_accept:

```cpp
    template<
        class Body, class Allocator,
        BOOST_BEAST_ASYNC_TPARAM1 AcceptHandler =
            net::default_completion_token_t<executor_type>
    >
    BOOST_BEAST_ASYNC_RESULT1(AcceptHandler)
    async_accept(
        http::request<Body,
            http::basic_fields<Allocator>> const& req,
        http::response<Body,
            http::basic_fields<Allocator>> const& res,
        AcceptHandler&& handler =
            net::default_completion_token_t<
                executor_type>{});
```

It would allow to pass a response which can use the user defined allocator.
If there's another way to do this, i would be happy to know about.

**Comment by madmongo1** [comment]
Hi @reapler,

I'll discuss it with Vinnie.

I understand the general motivation. Do you have a specific motivating use case? This would obviously help in prioritisation.

**Comment by reapler** [comment]
Well, it would be a step forward to manage *all* memory in Beast.
If someone wants to build a high level library depending on Beast and would like to improve the performance and reduce / eliminate memory fragmentation issues at all cost, it would be convenient if the memory used by Beast is manageable.

**Comment by reapler** [comment]
i just noticed async_connect would also need this kind of overload for the request

**Comment by vinniefalco** [comment]
Are you doing so many handshakes, that your performance measurements indicate this is a bottleneck?

**Comment by reapler** [comment]
No, i don't think this is a bottleneck :)
The second sentence was more a general statement about the advantages of managed memory.
If you would like, i can also try to make pull request with these changes on async_accept and async_connect.

**Comment by vinniefalco** [comment]
These seems like unnecessary complexity.
