### ISSUE TITLE
Use BOOST_ASIO_COMPLETION_TOKEN_FOR

### ISSUE THREAD

**Issue by Vilsol** [boostorg/beast#1916]
I am trying to create a basic websocket server, everything seemed to be compiling fine, but now I have encountered this error and I have no idea how to solve it:

```
***/beast/websocket/impl/accept.hpp(603): error C2244: 'boost::beast::websocket::stream<NextLayer,deflateSupported>::async_accept': unable to match function definition to an existing declaration
***/beast/websocket/impl/accept.hpp(596): note: see declaration of 'boost::beast::websocket::stream<NextLayer,deflateSupported>::async_accept'
***/beast/websocket/impl/accept.hpp(603): note: definition
***/beast/websocket/impl/accept.hpp(603): note: 'auto boost::beast::websocket::stream<NextLayer,deflateSupported>::async_accept(const ConstBufferSequence &,AcceptHandler &&,std::enable_if<!boost::beast::http::detail::is_header<ConstBufferSequence>::value,void>::type *)'
***/beast/websocket/impl/accept.hpp(603): note: existing declarations
***/beast/websocket/impl/accept.hpp(603): note: 'auto boost::beast::websocket::stream<NextLayer,deflateSupported>::async_accept(const boost::beast::http::message<true,Body,Fields> &,AcceptHandler &&)'
        with
        [
            Fields=boost::beast::http::basic_fields<Allocator>
        ]
***/beast/websocket/impl/accept.hpp(603): note: 'auto boost::beast::websocket::stream<NextLayer,deflateSupported>::async_accept(const ConstBufferSequence &,AcceptHandler &&)'
***/beast/websocket/impl/accept.hpp(603): note: 'auto boost::beast::websocket::stream<NextLayer,deflateSupported>::async_accept(AcceptHandler &&)'
```

I am using this library in conjunction with UE4

**Comment by vinniefalco** [comment]
I have no idea how to solve it either, because you didn't include a snippet of the source code in question.

**Comment by Vilsol** [comment]
The absolute smallest example I could come up with:

```
#include "./Socket.h"

#include "Windows/WindowsHWrapper.h"

THIRD_PARTY_INCLUDES_START
#pragma push_macro("check")
#undef check
#include "Windows/AllowWindowsPlatformTypes.h"
#include "Windows/AllowWindowsPlatformAtomics.h"
#include <boost/beast/websocket.hpp>
#include "Windows/HideWindowsPlatformAtomics.h"
#include "Windows/HideWindowsPlatformTypes.h"
#pragma pop_macro("check")
THIRD_PARTY_INCLUDES_END

namespace SDP {
	namespace Web {
		void handle_socket(boost::beast::http::request<boost::beast::http::string_body> req) {
		}
	}
}
```

It seems that as soon as I add the `#include <boost/beast/websocket.hpp>` it just breaks.

**Comment by vinniefalco** [comment]
Do the beast examples and tests compile for you?

**Comment by Vilsol** [comment]
No, they do not. Which is why I made this issue. But the weird part is that only this one specific function is throwing the error. I am using other boost libraries without any issue, even the beast webserver itself, and it works just fine.

**Comment by vinniefalco** [comment]
I wonder if you have two different versions of Boost installed

**Comment by Vilsol** [comment]
I have had to explicitly specified the include directory and the used lib's. And even ignoring that, I have only installed boost once.

**Comment by manni05** [comment]
I'm gettig similar errors (*) by simply compiling a file with only "#include <boost/beast/core.hpp>" as content. I am using boost 1.73 and VS 2019 Version 16.5.4 with /std:c++-latest. The problem seems to be C++20 coroutine support. The template declarations and definitions differ: the decalartions contain a macro that translates to "::boost::asio::completion_token_for", the definitions don't contain that macro. I startet to insert that macro into the definition and that seems to fix the problem. 


*)
- error C2244: 'boost::beast::basic_stream<Protocol,Executor,RatePolicy>::async_connect': unable to match function definition to an existing declaration
- error C2244: 'boost::beast::buffered_read_stream<Stream,DynamicBuffer>::async_write_some' ...
- error C2244: 'boost::beast::flat_stream<NextLayer>::async_read_some'

**Comment by manni05** [comment]
These changes are fixing my problem:

[beast_async.txt](https://github.com/boostorg/beast/files/4551513/beast_async.txt)

**Comment by vinniefalco** [comment]
Interesting, so `BOOST_ASIO_COMPLETION_TOKEN_FOR` is a new Asio thing?

**Comment by vinniefalco** [comment]
All Beast initiating functions should use the macro `BOOST_ASIO_COMPLETION_TOKEN_FOR` for the completion token. We still need the static_assert on the handler signature for pre-c++20 toolchains.

**Comment by manni05** [comment]
I am not sure whether it has become clear, but I have only included the macros that **where already used** in the function declaration into the implementation. My synchronous code is translated again. I do not know whether the asynchronous functions can actually be used with VS 2019 and /std:c++-latest.

**Comment by madmongo1** [comment]
This COMPLETION_TOKEN_FOR business supercedes our own checks that static_assert token conformance with the CompletionToken NTR.

We could therefore remove our own checks build environments that support concepts.

**Comment by vinniefalco** [comment]
> We could therefore remove our own checks build environments that support concepts.

That doesn't help us because we still need our own checks in all the other environments.
