### ISSUE TITLE
User-Agent HTTP header shouldn't be added if explicitly removed through decorator

### ISSUE THREAD

**Issue by ahmedhat** [boostorg/beast#1935]
### Version of Beast
`Beast version 292`

### Steps necessary to reproduce the problem
```
stream->set_option(websocket::stream_base::decorator(
            [](websocket::request_type &req) {
                req.erase(http::field::user_agent);
            }));
```

This results in the client sending `User-Agent: Boost.Beast/290` along the request.

@vinniefalco defined this behavior caused by https://github.com/boostorg/beast/blob/718aef721a7f966ed37c4be28c5d5d92cd21966f/include/boost/beast/websocket/impl/stream_impl.hpp#L591

which shouldn't be there in the first place as User-Agent HTTP header isn't mandatory.

**Comment by vinniefalco** [comment]
We should just remove the Beast feature that fills in the User-Agent.
