### ISSUE TITLE
#include <boost/type_traits/is_convertible.hpp> instead of <boost/type_traits.hpp>

### ISSUE THREAD

**Issue by Anton-V-K** [boostorg/beast#1940]
There is a fragment in `.../beast/core/buffers_prefix.hpp`:
```
#if BOOST_WORKAROUND(BOOST_MSVC, < 1910)
#include <boost/type_traits.hpp>
#endif
```
Actually only `boost::is_convertible` is used, so the include statement can reference only `boost/type_traits/is_convertible.hpp`:
```
#if BOOST_WORKAROUND(BOOST_MSVC, < 1910)
#include <boost/type_traits/is_convertible.hpp>
#endif
```
Such replacement can reduce dependency and is handy if only subset of boost files is available.

**Comment by madmongo1** [comment]
@Anton-V-K, 
Thanks very much for this. I'll get this into the next release right away.
