### ISSUE TITLE
Allow use of std::shared_ptr

### ISSUE THREAD

**Issue by Anton-V-K** [boostorg/beast#1941]
The library should allow usage of `std::shared_ptr` instead of `boost::shared_ptr` in a way like it is done for `asio` (you can define `BOOST_ASIO_HAS_STD_SHARED_PTR` to switch to `std::shared_ptr`).
The files which have `#include <boost/shared_ptr.hpp>` are:

- `.../beast/websocket/stream.hpp`
- `.../beast/core/basic_stream.hpp`
- `.../beast/_experimental/test/stream.hpp`
- `.../beast/websocket/impl/stream_impl.hpp`

**Comment by vinniefalco** [comment]
The library already "allows" you to use `std::shared_ptr`. Nothing stops you from using `std::shared_ptr` with Beast in your program.

**Comment by Anton-V-K** [comment]
@vinniefalco , you're right.
The issue is mainly for the cases when `boost::shared_ptr` isn't available for compiling `beast`.
Particularly I ran into this issue when trying to import `beast` into the code base, which doesn't use boost-pointers.
Moreover after examining the library code I see that use of `shared_ptr` isn't consistent - in some cases it is from STL, in other cases it is from BOOST.

**Comment by vinniefalco** [comment]
> The issue is mainly for the cases when boost::shared_ptr isn't available for compiling beast

But that's impossible. Beast requires Boost, and Boost has `boost::shared_ptr`. So it will always be available.

**Comment by vinniefalco** [comment]
>  I see that use of shared_ptr isn't consistent

Are you talking about `chunk_encode`? I suppose that could be fixed.

**Comment by vinniefalco** [comment]
Also note that `std::enable_shared_from_this::weak_from_this` is C++17. Beast uses Boost shared pointers because they support `weak_from_this` in C++11. That is why you see the Boost version being used, and also why sometimes the library uses the std version.
