### ISSUE TITLE
Need a class can point to both `websocket::stream<beast::tcp_stream>` and `websocket::stream<beast::ssl_stream<beast::tcp_stream>>`

### ISSUE THREAD

**Issue by nineKnight** [boostorg/beast#1952]
I'm writing a websocket server referring to `websocket_server_coro.cpp` and `websocket_server_coro_ssl.cpp`. I wanna set a flag to switch SSL, but I find no same base class in `websocket::stream<beast::tcp_stream>` and `websocket::stream<beast::ssl_stream<beast::tcp_stream>>`. I don't know if I miss such a class.
Anyone provides clues is welcomed.

**Comment by vinniefalco** [comment]
https://github.com/boostorg/beast/blob/fc7c645f64192976acfb6a88a8fdbd5d92bc44fc/example/advanced/server-flex/advanced_server_flex.cpp#L251

**Comment by nineKnight** [comment]
Wow! It seems this is what I need. Thank you.
However, if I'm using sync APIs, I get no way to use a base-class pointer to manage `websocket::stream<beast::tcp_stream>` or `websocket::stream<beast::ssl_stream<beast::tcp_stream>>`, right?

**Comment by vinniefalco** [comment]
The CRTP technique (Curiously Recurring Template Pattern) works with any API, synchronous or otherwise.

**Comment by nineKnight** [comment]
No. I just want a class like this:
```c++
class Stream {
public:
    void Read(...);
    void Write(...);

    void PostDetectSSL(bool result...) {
        if (result) {
            // TODO: ws_.reset(new websocket::stream<beast::ssl_stream<beast::tcp_stream>>(...));
        } else {
            // TODO: ws_.reset(new websocket::stream<beast::tcp_stream>(...));
        }
    }
protected:
    std::unique_ptr<websocket::stream<beast::base_stream>> ws_;
}
```

**Comment by vinniefalco** [comment]
Okay, then write it

**Comment by nineKnight** [comment]
Mmmm...I find no sush a `beast::base_stream` class and it doesn't exist indeed, right? Could you share your idea why you don't need a sush a `beast::base_stream` class?

**Comment by vinniefalco** [comment]
Because Beast demonstrates how to do it with CRTP, see:
https://github.com/boostorg/beast/blob/fc7c645f64192976acfb6a88a8fdbd5d92bc44fc/example/advanced/server-flex/advanced_server_flex.cpp#L251

**Comment by nineKnight** [comment]
So you mean everyone using `beast` has to force the code to be under the CRTP or rewrite `websocket::stream`.

**Comment by vinniefalco** [comment]
No, I'm saying that if you want to implement your own stream which can work as either an SSL stream or a plain stream, then that's fine, and such a type will work with `websocket::stream` as long as it meets the requirements of _SyncReadStream_ and _SyncWriteStream_ for synchronous operations, and _AsyncReadStream_ and _AsyncWriteStream_ for asynchronous operations. But Beast does not provide such a type.

**Comment by nineKnight** [comment]
Maybe I can try maintaining a `beast::tcp_stream` and keeping the result of `detect_ssl`, and constructing a `websocket::stream` when `read()` or `write`.

**Comment by nineKnight** [comment]
It's annoying that I have to maintain both `websocket::stream<beast::tcp_stream>` and `websocket::stream<beast::ssl_stream<beast::tcp_stream>>` and keeping the result of `detect_ssl` when using `asio::spawn`. If there's a base, the code can be much simpler.

> But Beast does not provide such a type.
That's a pity.

I think SSL is an attachment to stream but beast makes it another stream. I prefer a switch like `set_ssl(...)` which may be more code-friendly.

**Comment by madmongo1** [comment]
This is something we get asked for fairly frequently. It may not be theoretically correct, but I agree that users would find it useful.

**Comment by hjelmeland** [comment]
> It's annoying that I have to maintain both `websocket::stream<beast::tcp_stream>` and `websocket::stream<beast::ssl_stream<beast::tcp_stream>>` and keeping the result of `detect_ssl` when using `asio::spawn`. If there's a base, the code can be much simpler.
> 
> I think SSL is an attachment to stream but beast makes it another stream. I prefer a switch like `set_ssl(...)` which may be more code-friendly.

Late to the party, but I just made such a wrapper class : https://github.com/hjelmeland/BeastTlsOrTcpStream. For those of you that don't mind wasting some memory on SSL when using it in TCP mode, feel free to use it.
