### ISSUE TITLE
Overloading async_send for file_body is broken

### ISSUE THREAD

**Issue by k0zmo** [boostorg/beast#1963]
Current implementation adds an overload for `boost::beast::http::async_write_some` when the Body type is `basic_file_body<file_win32>`.
However, this overload is only picked up by MSVC when `/permissive-` flag is not provided - doesn't matter if 2017 or 2019. Compilers that implements two-phase lookup - that is GCC, Clang and MSVC with `/permissive-` flag don't consider this overload. 

That is because the [function](https://github.com/boostorg/beast/blob/develop/include/boost/beast/http/impl/write.hpp#L202) that is supposed to call our specialized overload or the default one calls it with the qualified name. This, as opposed to [unqualified name lookup](https://en.cppreference.com/w/cpp/language/unqualified_lookup) makes the ADL to only consider functions that are visible from the template definition context. In the latter case it would also consider functions that are visible from template instantiation context. 

Below snippet shows the difference:

```cpp
namespace abc {

template <typename T>
struct serializer {};

template <typename Body>
int async_write_some(serializer<Body>) // primary template
{
    return 1;
}

template <typename Body>
int async_write(serializer<Body> sr) // 1st variant, fully qualified name lookup
{
    return abc::async_write_some(sr);
}

template <typename Body>
int async_write2(serializer<Body> sr) // 2nd variant, unqualified name lookup
{
    return async_write_some(sr);
}

struct body_spec {};

int async_write_some(serializer<body_spec>) // our "specialization" for Body=body_spec
{
    return 2;
}

}

int foo()
{
    abc::serializer<abc::body_spec> sr;
    return abc::async_write(sr); // returns 1
}

int bar()
{
    abc::serializer<abc::body_spec> sr;
    return abc::async_write2(sr); // returns 2
}
```

The quickest fix would be to drop name qualification. Another way would be to introduce the dedicated customization point that different bodies could attach to.

**Comment by madmongo1** [comment]
Hi @k0zmo , Do you have some sample code that demonstrates this problem in pure beast terms, perhaps on https://godbolt.org/ ?

**Comment by k0zmo** [comment]
Beside what I presented I don't have any. I was hoping such distilled snippet would be better than full blown Beast's case. I was trying to add linux_body optimization (`sendfile`) based on #593 and couldn't make it work under GCC and Clang with current machinery.

However, if you need it shown in Beast "realm" simply build any of Beast's examples that use file_body (http/server/fast is my choice) and set a breakpoint [here](https://github.com/boostorg/beast/blob/13a928a872a54f0a90b4a166e0792efeaebf7538/include/boost/beast/http/impl/file_body_win32.hpp#L446). Under MSVC without `/permissive-` flag you should hit the breakpoint during `async_send` when the file is present. With `/permissive-` added this function won't be called and you'll not hit the breakpoint.

**Comment by madmongo1** [comment]
Awesome, thanks for the pointers

**Comment by vinniefalco** [comment]
That whole `sendfile` thing is shaky

**Comment by k0zmo** [comment]
As in the whole concept or particular implementation (Linux)?

**Comment by vinniefalco** [comment]
I thought this was already fixed in develop?

**Comment by madmongo1** [comment]
No, I got to the bottom of it and was then distracted with other things.

**Comment by FastInvite2k2** [comment]
I think sendfile() optimization is irrelevant in 2020 because everyone and his brother uses TLS.

**Comment by k0zmo** [comment]
From my experience TLS is not used everywhere - it is used on network boundary (TLS termination) but it's a bit of an overkill inside private network between (micro)services.

**Comment by madmongo1** [comment]
ping

**Comment by iamhaiwen** [comment]
> 我认为 sendfile（） 优化在 2020 年无关紧要，因为每个人和他的兄弟都使用 TLS。

openssl 3.0 has ssl_sendfile
