### ISSUE TITLE
chat multi example

### ISSUE THREAD

**Issue by smalls12** [boostorg/beast#1969]
Hello,

I'm just getting my head around the multi chat example ( https://github.com/boostorg/beast/tree/develop/example/websocket/server/chat-multi ).

Just looking for some information on the lifetime of the websocket_session. I see that the session is stored under shared_state via `::on_accept()` method and that the destructor will remove in from shared_sate.

My question is more so how the destructor is even called since the shared_state is only storing a raw pointer.

I'm guessing it has something to do with `boost::enable_shared_from_this<websocket_session>`.

Thanks :)

**Comment by vinniefalco** [comment]
Yes the lifetime of the object is extended by binding a shared pointer into the completion handler. This is all explained in my presentation: https://youtu.be/7FQwAjELMek?t=1489

**Comment by smalls12** [comment]
Oh perfect, that was easy to understand.

I guess my follow up is in regards to the multithreaded aspect.

The command line offers a way to bring up more threads for `ioc::run()`, what does beast use these threads for?

I ask since the only synchronization I can find occurs in shared_state. Trying to figure out if those threads can somehow stomp on each other.

**Comment by vinniefalco** [comment]
You're supposed to already understand Asio. Beast uses threads to call `io_context::run` for the same reason that all Asio programs do.

**Comment by smalls12** [comment]
I'll back track here.

I noticed initially that the shared_state object stored raw pointers.
With the use of multiple threads I was wondering if there could be a case where a dangling pointer was left lying around and if the use of a weak_ptr would be preferred.

Looking back now, even with multiple threads calling `::run()` each http session is still protected from concurrency with `::make_strand()`.

The shared_state object is also protected using a mutex.

Just working my way through the understanding of the example, looking for some clarification on my understanding.

I appreciate your time and responses :)

**Comment by vinniefalco** [comment]
Yes everything you say is resonating with me :) Okay, so yeah there's a pointer in there but if you look closely you will note that the pointer is inserted when the session is created, while holding a mutex. And the pointer is removed when the session is destroyed, again while holding the mutex. The pointer is always valid as long as it is in the list.

Yes a `weak_ptr` is an interesting idea but it is not necessary, for the reason stated above. It is provable that the pointer is always valid. But `weak_ptr` has other problems. No hash function is defined for them! Thus they cannot be used in an unordered container.

**Comment by vinniefalco** [comment]
Implementing a container that points to objects which can asynchronously come and go is tricky (and I am very certain that this code is correct).

**Comment by smalls12** [comment]
Ah didn't thoroughly look through the `::send()` function.
You go to the effort making a weak_ptr before sending the message anyways.
I suppose that was the main issue I was thinking about; could we send on a session right after it was closed.
The weak_ptr there would then catch it.

**Comment by vinniefalco** [comment]
> The weak_ptr there would then catch it.

Exactly. There is a window of time when the destructor of the session is invoked, but before the destructor fully executes, where the object is in the list. The rules for `shared_ptr` are such, that if we are in the destructor, then it is guaranteed that `weak_ptr::lock` will fail. Subtle.

**Comment by vinniefalco** [comment]
> You go to the effort making a weak_ptr before sending the message anyways

Yes, for the reasons stated in the comments. I was actually thinking of an improvement:
```
thread_local std::vector<boost::weak_ptr<websocket_session>> v;
v.clear();
```

I added `thread_local`.

**Comment by smalls12** [comment]
> There is a window of time when the destructor of the session is invoked, but before the destructor fully executes, where the object is in the list.

And this would only be an issue if one member in the chat was trying to send a message right when another member disconnected right?

**Comment by vinniefalco** [comment]
> And this would only be an issue if one member in the chat was trying to send a message right when another member disconnected right?

Right, because we release the mutex before we iterate the list of weak pointers.

**Comment by smalls12** [comment]
Okay thanks for humoring me :)

**Comment by vinniefalco** [comment]
Keep an eye out here: https://github.com/vinniefalco/BeastLounge/

**Comment by smalls12** [comment]
Okay, think I will try and build that.

**Comment by vinniefalco** [comment]
> Okay, think I will try and build that.

It is still a work in progress, so it might not work, but it might provide ideas if you look at the sources. I am in the middle of a large refactor.

**Comment by smalls12** [comment]
Another pair of eyes : )

**Comment by vinniefalco** [comment]
The _master_ branch should compile (I'm working in _develop_).
