### ISSUE TITLE
Implement SSE (server Side Event) Server

### ISSUE THREAD

**Issue by neel** [boostorg/beast#1976]
I am trying to implement SSE using beast. But all the overloads on write_async() and write_some_async() takes an http message object. But I need to write raw strings on the Socket. How can I do that ?

**Comment by vinniefalco** [comment]
Use Asio to write raw octets to the socket.

**Comment by madmongo1** [comment]
https://www.boost.org/doc/libs/1_73_0/doc/html/boost_asio/reference/async_write.html
