### ISSUE TITLE
请问，如何提高async_handshake时间

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#1978]
请问，如何提高https证书校验的时间

**Comment by madmongo1** [comment]
Google translates this as: "Excuse me, how to increase the time of https certificate verification"

At the moment, the question is ambiguous.

Does it mean:

1. How do I increase the validity period of an SSL certficate? In this case, the answer is that you cannot. You will need to issue a new certificate.

2. How do I increase the timeout while a client is verifying the certificate? This is difficult to answer here as if depends on the verification mechanism you are using.
