### ISSUE TITLE
beast does not set Connection: keep-alive header.

### ISSUE THREAD

**Issue by ashjas** [boostorg/beast#1979]
When i set the request's Connection header to keep-alive, and inspect the http packets, i dont see it set in the http header.
i set it as:
```req_.set(http::field::connection,		"keep-alive");```

I also tried with ```req_.keep_alive(true);```
but still cant see the header being set.

I am looking for this header:
```Connection: keep-alive```

**Comment by madmongo1** [comment]
I need more information.

Did you set the HTTP version to 1.1 prior to setting keep-alive?

Did you call prepare() on the message before sending it?

**Comment by madmongo1** [comment]
The behaviour you see is intended.

In HTTP/1.1 and above, keep-alive behaviour is the default unless the Connection header includes the word "close".

Beast follows the HTTP RFCs exactly. If your HTTP version is >= 11 (1.1) and you call keep_alive(true), Connection headers containing the word close are simply deleted.

HTTP1.1 is the default in Beast, therefore keep-alive is also the default behaviour.
