### ISSUE TITLE
此库默认的https验证机制 

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#1983]
麻烦问下，此库默认的https验证机制 是什么？

**Comment by madmongo1** [comment]
“ Boost.Beast”将Asio用作其数据传输机制。 Asio可以与许多SSL库一起使用（您需要检查Asio的文档）。验证机制由SSL库确定。

**Comment by madmongo1** [comment]
Question answered. No futher communication. Closing issue.
