### ISSUE TITLE
ssl在高并发压力测试下，证书校验很慢

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#1987]
beast库下的async_handshake此接口，在高并发压力测试下，返回结果很慢

**Comment by madmongo1** [comment]
我没有相同的经验。我在市场数据分发服务器中使用了Boost.Beast。它在高负载下无延迟地处理了88000个并发异步连接。

可能是连接的另一端已关闭，而您看到的是TCP层中的延迟吗？

考虑添加超时（您可以在握手阶段在beast :: basic_stream中使用超时功能）

**Comment by Yinpinghua** [comment]
能给我一个相关的列子嘛？谢谢

**Comment by Yinpinghua** [comment]
ssl这块，底层是同步处理的，还是异步处理的？

**Comment by madmongo1** [comment]
> ssl这块，底层是同步处理的，还是异步处理的？

如果使用“ async_”功能，则异步处理SSL层。如果使用同步版本，则它是同步的。

**Comment by madmongo1** [comment]
> 能给我一个相关的列子嘛？谢谢

https://www.boost.org/doc/libs/1_73_0/libs/beast/doc/html/beast/ref/boost__beast__basic_stream/expires_after.html

**Comment by Yinpinghua** [comment]
那如果用beast :: basic_stream中使用超时功能，那岂不是在长连接下，会到一个时间点会自动关闭哦

**Comment by madmongo1** [comment]
完成websocket或SSL握手后，您可以禁用超时。然后，一旦Websocket处于连接状态，Websocket的ping / pong子状态将控制超时。

**Comment by Yinpinghua** [comment]
禁用超是是那个接口？

**Comment by madmongo1** [comment]
> 禁用超是是那个接口？

boost.org/doc/libs/1_73_0/libs/beast/doc/html/beast/ref/boost__beast__basic_stream/expires_never.html

**Comment by Yinpinghua** [comment]
谢谢，大神

**Comment by madmongo1** [comment]
这是我第一次使用中文进行技术支持。我最近怎么样:-)

**Comment by Yinpinghua** [comment]
中文非常棒。向您多学习学习

**Comment by Yinpinghua** [comment]
麻烦问下，我对beast下的ssl进行压测了，每次每秒2W请求，发现证书校验返回很慢

**Comment by Yinpinghua** [comment]
beast下的ssl的接口 :async_handshake,通常多久才会回调给应用层

**Comment by madmongo1** [comment]
我无法评论SSL响应缓慢的问题。这将取决于您所在区域的系统配置。

我无法就SSL层多久回调一次应用程序给您一个很好的答案。 Asio允许您访问基础SSL会话句柄，因此您可以使用OpenSSL API设置所需的任何行为。

Asio SSL和OpenSSL超出了Beast的范围-我们仅使用Asio提供的流。

**Comment by madmongo1** [comment]
Question answered. Closing issue.
