### ISSUE TITLE
ssl使用async_shutdown接口

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#1988]
麻烦问下,在ssl下调用async_shutdown接口，是否需要调用next_layer 下的socket的shutdown()函数

**Comment by madmongo1** [comment]
如果要关闭连接，则可以不执行SSL关闭。您可以简单地遵循以下顺序：
1. Websocket异步关闭
2.当所有未完成的完成处理程序都完成后，关闭（或删除）整个流。

Asio会确保在底层套接字句柄上调用`close（）`之前，确保底层套接字调用函数`shutdown（）`。

**Comment by madmongo1** [comment]
Question answered.
Closing issue.
You are welcome to ask further questions if you encounter difficulties.
