### ISSUE TITLE
How to get notified of new message automatically

### ISSUE THREAD

**Issue by thomasdao** [boostorg/beast#1990]
Hi, I am implementing Web Socket from client, following the example `websocket_client_async_ssl_system_executor`, and I want to be automatically notified when new message is arrived from the server. I guess this is a common use case, but I search a lot of place and don't know what's the best way to do this.

Currently, in `on_read` method, I am also add a call to `async_read`, so there's always a pending `async_read`. However I am struggling what to do when `read` failed. If I also call `async_read` when the previous `on_read` failed, it sometime ends up in infinite read failure. However if I don't call `async_read` when `on_read` failed, there's no more pending `async_read` and I don't know how to get notified of new message.

```cpp
    void
    on_read(
        beast::error_code ec,
        std::size_t bytes_transferred)
    {
        boost::ignore_unused(bytes_transferred);

        if (ec) {
             /* Should I call async_read when error happens?
            ws_.async_read(
                buffer_,
                beast::bind_front_handler(
                    &session::on_read,
                    shared_from_this()));
           */

            return fail(ec, "read");
        }

        // Get data
        if (ws_.got_text()) {
            auto data = beast::buffers_to_string(buffer_.data());
            if (auto cb = callback.lock()) {
                cb->onMessage(data);
            }
        }

        // Clear the buffer
        buffer_.consume(buffer_.size());
        
        // Keep reading message into our buffer
        ws_.async_read(
            buffer_,
            beast::bind_front_handler(
                &session::on_read,
                shared_from_this()));
    }
```

I am new to Beast so I'm quite sure I have missed something. If there's a proper way to do this in Beast? Is my approach above ok or should I call `async_read` periodically? Thank you.

**Comment by vinniefalco** [comment]
Are you also new to Asio?

**Comment by thomasdao** [comment]
@vinniefalco yes I am new to Asio as well. Thank you for the super quick reply!

**Comment by vinniefalco** [comment]
Are you new to C++?

**Comment by thomasdao** [comment]
@vinniefalco Yes I am new to C++ too. I'm sure this is probably a very beginner question :)

**Comment by vinniefalco** [comment]
Well, to use Beast you are supposed to already know how to use Asio, and you are supposed to already have a firm grasp of C++ including template programming. That said, this example shows how to structure an "asynchronous read loop."
https://github.com/boostorg/beast/blob/6f57e5934c1f307e4510ee11dd09594526a3f5d0/example/websocket/server/async/websocket_server_async.cpp#L107

**Comment by madmongo1** [comment]
hi @thomasdao 

I don't know whether you have any experience with state machines. If so, it might be easier to visualise the use of a beast websocket as a state diagram:

```puml
state WebSocket {

	[*] --> HandShaking
    HandShaking --> Error : error
    HandShaking --> Connected : success
    state Connected {
	    state fork_state <<fork>>
    	[*] --> fork_state
        fork_state --> Reading
        fork_state --> Writing
        fork_state --> Closing
        
        state Reading {
        	[*] --> WaitingRead : : async_read
            WaitingRead --> HandlingFrame : success
            WaitingRead --> [*] : read_error : process_event(error)
            HandlingFrame --> WaitingRead : success
            HandlingFrame --> [*] : error : process_event(error)
            
        }
        
        state Closing {
        	[*] --> Idle
            Idle --> WaitCloseRequest : close
            WaitCloseRequest -> [*] : success
            WaitCloseRequest -> [*] : close_error
        }
        
        state Writing {
      
        	[*] --> WritingIdle
            WritingIdle --> Sending : write : async_write
            Sending : write : queue_pending_write
            Sending --> Sending : success : async_write / pending_write
            Sending --> WritingIdle : success / no_pending_write
            Sending --> [*] : write_error
        }
        
        
        state join_state <<join>>
        Reading --> join_state : read_error
        Writing --> join_state : write_error
        Closing --> join_state
        
        join_state --> Error : read_error
    }
}
```

https://liveuml.com/view/5eeb5851663178088afef6e7

**Comment by vinniefalco** [comment]
If anyone reads this UML stuff and it helps them please let me know here.

**Comment by thomasdao** [comment]
Hi @madmongo1 and @vinniefalco, the UML is very useful, it's easier to understand the flow. It would be more complete if you include `async_resolve`, `async_connect`, `next_layer().async_handshake` and `ws_.async_handshake`. It takes me a bit of time to figure it out (but I'm really beginner) :). 

From the example @vinniefalco mentioned, I figured that in order to get notified when the message arrives, I need to call `do_read` in other callback to create async read loop. This is doable and I can get it working in my app. However coming from web, I wish it can just provide me a ready to use callback (with `onMessage`, `onError`, etc) similar to https://developer.mozilla.org/en-US/docs/Web/API/WebSocket, and not having to mess with the internal of websocket which I'm not really familiar.

Thanks all for your help and thanks for the library!

**Comment by Yinpinghua** [comment]
加了定时器，避免僵尸连接

**Comment by Yinpinghua** [comment]
加个定时器，避免僵尸连接

**Comment by madmongo1** [comment]
Question answered. Closing issue.
