### ISSUE TITLE
how to skip UTF8 validation

### ISSUE THREAD

**Issue by Alchemist2077** [boostorg/beast#1991]
Hello.
  Sometimes,Websocket server send binary data with "text" opcode.
  Can i do something to skip UTF8 validation by utf8_checker?
  I know Server sending binary data with text opcode is a bad bahavior,but is very diffcult to change service bahavior.

**Comment by madmongo1** [comment]
No response to request.
Closing issue.

**Comment by madmongo1** [comment]
Re-opening to provide time for more feedback. @Alchemist2077

**Comment by Alchemist2077** [comment]
Server using openresty/1.15.8.2 ,and openresty native library as websocket server.
Sending text data code looks like:
    `ngx.ctx.svr:send_text(_encrypt_result(retdata))`
  "_encrypt_result" mean encrypt data using sha1. So text data translate to binary data.

 When beast cliant try to recive data from this server using:
```
  ws_.async_read(buffer_, beast::bind_front_handler(&WebsocketSession::on_read,
                                                    shared_from_this()));
```

 I got an error says:
  "The WebSocket frame payload was not valid utf8"

By the way: I have read the RFC 6455 standerd,and i decide to motify openresty server logic to send data with proper opcode.
