### ISSUE TITLE
Right way to download large files using async http ssl

### ISSUE THREAD

**Issue by ManojNisal** [boostorg/beast#1992]
I'm trying to write a program to download multiple files over http ssl asynchronously.
I'm basing this on https://www.boost.org/doc/libs/1_72_0/libs/beast/example/http/client/async-ssl/http_client_async_ssl.cpp.

For smaller files, say up to 10 or 20 MB, the full file is available in http response (string body). But this won't be suitable for large files of size greater than GB or so. The way I'm handling this is by specifying range request for each http request. I'm making multiple such http requests in a single io context.

Now, the problem is, some of the http responses return partial read response and there is no content in body. This happens randomly for any of the http requests within a session. Not sure if there is some problem in the way I'm handling this case.

Here is what I'm doing:

for(until the file read requests cover all the extents of file)
{
   auto session_ptr = make_shared<session>(ioc, ctx);
  session_ptr->SetRange(offset, nBytes); // this sets http range field to value like "bytes=0-1023"
  session_ptr->run(host.c_str(), port, target.c_str(), 11);
}
ioc.run();

Note that this works fine if the number of requests in io context is less, say two or three.

**Comment by madmongo1** [comment]
I'm going to need to see some code. It sounds as if you have a logic error somewhere.

**Comment by ManojNisal** [comment]
I'm reusing the session class from https://www.boost.org/doc/libs/1_72_0/libs/beast/example/http/client/async-ssl/http_client_async_ssl.cpp.

Changes that I have added to session class are:

1.  A method to set range.
`void session::SetRange(uint64_t offset, uint64_t numBytes)
{
    std::stringstream stream;
    stream << "bytes=" << offset << "-" << offset + numBytes - 1;
    range_ = stream.str();
}`


2. in session::run, set the http range field
`if (!range_.empty())
{
        req_.set(http::field::range, range_);
}
`
3. Set the timeout to 1 second instead of 30 secs before calling async_shutdown

In the class which downloads the files,

`
int requestBufferSize = 1024 * 1024 * 2; // 2 MB
string target, host;
ParseURL(item.downloadUrl, host, target); // Splits the download url into host and target

uint64_t numBytesRead = 0;
uint64_t offset = 0;

while (numBytesRead < item.size) // item is of a type that i have defined and stores its size, id, download URL and so on
{
                offset = numBytesRead;
                uint32_t numBytesRequested = requestBufferSize;

                if ((item.size - numBytesRead) < requestBufferSize)
                    numBytesRequested = item.size - numBytesRead;

                auto session_ptr = make_shared<session>(ioc, ctx);
                session_ptr->SetRange(offset, numBytesRequested);

                listExtentRequests.push_back(session_ptr); // this can be ignored, using it to track session requests and extents
                session_ptr->run(host.c_str(), port, target.c_str(), 11);
                numBytesRead += numBytesRequested;
}
ioc.run();
`

This works fine if the number of requests is less.

**Comment by ManojNisal** [comment]
Update:

If i change requestBufferSize(i.e. range requested per request) to 200KB and make 100 concurrent requests in a single io context, things work fine.

**Comment by ManojNisal** [comment]
Any update on this? What could be the reason for partial read response in beast?

**Comment by madmongo1** [comment]
Hi @ManojNisal ,

Is there a specific reproducible bug you’d like to report?

If it’s something that I can prove in a test, it becomes a lot easier to fix and maintain.

**Comment by ManojNisal** [comment]
Hi @madmongo1 ,

If I make multiple async http requests over ssl using beast, to download a large file in chunks, then some of the range requests do not return any data. Instead they return with error code "partial read".

**Comment by madmongo1** [comment]
Do you mean beast::http::error::partial_message or asio::ssl::error::short_read?

Can you show some code?

**Comment by ManojNisal** [comment]
Right, the error is beast::http::error::partial_message.
The code is as mentioned in comment #3 above. It is based on the async https example from the library.

Thanks

**Comment by madmongo1** [comment]
@ManojNisal With respect, the code may be based on a tested example, but it now does something different.
We are generally our own worst code reviewer (including me). 
If you put your code/project in a github repo I will compile it and take a look.
What I will probably do is set breakpoints around the failure and examine what is exactly going on at that point. Then I will write a unit test to ensure that what is happening is what is expected.
This may involve the use of wireshark to capture that actual raw data coming from the server.
This would allow me to express the problem in terms of :
a) a bug in beast, or
b) a programming error

If you could do the above it would be instructive for us both.

**Comment by ManojNisal** [comment]
Hi @madmongo1 ,
I have stripped down the problem into a basic test application with a single source file which is attached here.
It just tries to download a Debian iso in batches of range requests. In the file, I'm trying to make 100 concurrent requests of 2MB each, at a time, until required bytes are downloaded. You can tune the parameters as needed. 
Thanks again for all the help.

[Source.cpp.zip](https://github.com/boostorg/beast/files/4908126/Source.cpp.zip)

**Comment by ManojNisal** [comment]
This looks similar to https://github.com/boostorg/beast/issues/2015

**Comment by madmongo1** [comment]
Keepalive
