### ISSUE TITLE
Boost 1.73.0 compilation errors

### ISSUE THREAD

**Issue by AlexandreGerault** [boostorg/beast#1993]
I am trying to code a C++ server game using Boost.Asio. I also want to support websocket sessions so that I am trying to use Boost.Beast. Then I downloaded the `boost_1_73_0` sources from the boost website and I've built it. It worked fine when I just used Boost.Asio but as soon as I make an include of `<boost/beast/core.hpp>` (I still don't even use the beast stuff) I got errors. I asked  support on some discords and it seems it could either be a problem coming from beast compatibility or a configuration issue (my cmake would be wrongly configured).

### Version of Beast

Looking at the `<boost/beast/version.hpp>` I guess this is 290 (`#define BOOST_BEAST_VERSION 290`). I'm using boost 1.73.

### Steps necessary to reproduce the problem

Start a cmake project that includes boost (`find_package`). Make a class and include `<boost/beast/core.hpp>` using boost 1.73.0. I use GCC 10.1.0.

### All relevant compiler information

A lot of errors like
```
error: no declaration matches ‘auto boost::beast::websocket::stream< <template-parameter-1-1>, <anonymous> 
>::async_accept(AcceptHandler&&)’
```
A full compiled errors list available here: https://gist.github.com/AlexandreGerault/ad851126d49195dade0f083f5beaf39b

Edit: Here is the project I try to use boost.beast https://github.com/AlexandreGerault/werewolf_server/pull/3
But I don't think it is relevant.

**Comment by AlexandreGerault** [comment]
I'm sorry I didn't find the patch on the boost website before... :innocent: 

If someone met the same issue than me: just download boost sources again, then look for patches on boost website. You can then apply the patches and build boost. It should fix all compilation problems.

**Comment by vinniefalco** [comment]
What is the link to the patches?

**Comment by madmongo1** [comment]
https://www.boost.org/patches/
