### ISSUE TITLE
Disconnect flat_stream from ssl_stream

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#1995]
Asio now linearises scatter/gather I/O in `ssl::stream`, so we can simplify our code. And probably deprecate `flat_stream` at some point:

https://github.com/chriskohlhoff/asio/commit/17637a48ccbfa2f63941d8393a7c8316a8df4a79

**Comment by ashtum** [comment]
I think we can safely deprecate Beast's `flat_stream` and `ssl_stream`. Removing `ssl_stream` would break a lot of users' code, so I suggest we remove `flat_stream` and rewrite `ssl_stream` to be a facade of `asio::ssl::stream`, keeping it indefinitely. However, we will rewrite the examples to avoid using it and mark it as deprecated.
