### ISSUE TITLE
Issue in uploading binary content

### ISSUE THREAD

**Issue by GaneshTambat1** [boostorg/beast#2000]
I am trying to upload an image file to Microsoft OneDrive. I am using the Boost Beast library. My code is as follows:

        restoreReq_.method(http::verb::put);
        restoreReq_.version(version);
        restoreReq_.target(target);
        restoreReq_.set(http::field::host, host);
        restoreReq_.set(http::field::user_agent, BOOST_BEAST_VERSION_STRING);        
        
        restoreReq_.set(http::field::authorization, strToken_.c_str());
        restoreReq_.set(beast::http::field::content_type, "application/octet-stream");
                                     
        std::ifstream sourceFile("E:\\Home.gif", std::ifstream::binary | std::ifstream::in);
        std::stringstream buffer;
        buffer << sourceFile.rdbuf();
        std::string fileContent = buffer.str();
        long len = fileContent.length();
        restoreReq_.set(http::field::content_length, len);
        restoreReq_.body() = fileContent.c_str();
        restoreReq_.prepare_payload();

I can see that "restoreReq_.body() = fileContent.c_str();" is not assigning the binary content correctly. It is assigning till it finds the first '\0' and after that, it stops. What is the right way to assign binary content to body()? 

Regards,
GT

**Comment by Eelis** [comment]
Since the body type returned by body() is a template parameter of http::request, I think it depends on the actual type of your restoreReq variable.

**Comment by GaneshTambat1** [comment]
Thanks for the quick reply. I am not able to figure out which body type my http::request should have. Currently, it is set to http::string_body and as you correctly pointed out, this causes the issue with binary data. What is the correct body type for Binary data?

**Comment by Eelis** [comment]
I expect that if you use http::string_body, then you can most likely do `restoreReq_.body() = fileContent;` without the `.c_str()`.

**Comment by vinniefalco** [comment]
or maybe use `http::file_body` since you want to upload a file...

**Comment by GaneshTambat1** [comment]
Thanks guys for quick replies. Suggestion to use "restoreReq_.body() = fileContent; without the .c_str()." solved the issue. I can now upload  different image types e.g. pdf, jpg etc.
