### ISSUE TITLE
Doest write_limit only for TCP?

### ISSUE THREAD

**Issue by GOOD-Stuff** [boostorg/beast#2001]
Hello everyone!

My current Beast version is: `#define BOOST_BEAST_VERSION 290`

Do I understand correctly that `simple_rate_policy::write_limit(std::size_t bytes_per_second)` work only for TCP stream?
Can I use the `beast::basic_stream` as follows:
```C++
boost::beast::basic_stream<boost::asio::ip::udp,
                           boost::asio::executor,
                           boost::beast::simple_rate_policy> stream(ioc);
```
or `beast::basic_stream` (in async way) working only for TCP protocol?

**Comment by vinniefalco** [comment]
Only TCP

**Comment by GOOD-Stuff** [comment]
Ok, thanks.
