### ISSUE TITLE
The WebSocket handshake Connection field is missing the upgrade token

### ISSUE THREAD

**Issue by iraizo** [boostorg/beast#2003]
When reporting a bug please include the following:

### Version of Beast

#define BOOST_BEAST_VERSION 292

### Steps necessary to reproduce the problem
This is what im trying to run
https://github.com/iraizo/webcsgo-radar/blob/master/src/websocketserver/server.cpp

### All relevant compiler information

using Visual studio 2019

The more information you provide the sooner your issue
can get resolved!

**Comment by madmongo1** [comment]
Hi @iraizo , Would you mind including a copy of the response headers you are receiving on the client?

R

**Comment by iraizo** [comment]
> Hi @iraizo , Would you mind including a copy of the response headers you are receiving on the client?
> 
> R

will do, give me a minute

**Comment by iraizo** [comment]
@madmongo1 

<img src="https://jelbrek.icu/kc3854aq.png"></img>

**Comment by vinniefalco** [comment]
Looks like the response indicates an error in the request. Show the response line and body.

**Comment by iraizo** [comment]
> Looks like the response indicates an error in the request. Show the response line and body.

the title is the response

**Comment by madmongo1** [comment]
@iraizo He means please copy/paste the entire HTTP response that was sent back during the websocket handshake.

Something like this:
```
HTTP/1.1 404 Not Found
Content-Type: text/html
Content-Length: 61

<html><head></head><body><h1>404 Not Found</h1></body></html>
```

**Comment by iraizo** [comment]
<img src="https://jelbrek.icu/kc3dib9g.png"></img>

**Comment by madmongo1** [comment]
400 Bad Request says it all. The client has not formed a correct websocket handshake request.

**Comment by polhaghverdian** [comment]
I have the same problem. Works with Firefox, but not Chrome. 

With exact same error message: **The WebSocket handshake Connection field is missing the upgrade token**

Is this really enough? ws.accept(); Or should i add the upgrade token manually? 

Any help will be appreciated!

**Comment by madmongo1** [comment]
@polhaghverdian Are you able to share a minimal web page that I can run in firefox/chrome to replicate the problem locally?

I'd also be interested to see any packets you've been able to collect with wireshark, if avaialble.

**Comment by polhaghverdian** [comment]
@madmongo1  

btw: no error message when i connect using the IP adress instead of using "localhost". But i get another issue instead --> **Error: sslv3 alert certificate unknown**

Do you want me to copy & paste the HTML/JS code here?

**Comment by madmongo1** [comment]
> Do you want me to copy & paste the HTML/JS code here?

If it's short. Otherwise a link to a git repo or gist is preferable.

**Comment by polhaghverdian** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<html>
    <head>
        <title>Web-client</title>
        <link rel="stylesheet" href="/index.css">
    </head>
    <body>
    </body>
    <script type="text/javascript" src="/index.js"></script>
</html>`



`
'use strict';

// websocket connection
var serverConnection = new WebSocket('wss://192.168.1.179:8080');

// When websocket is open
serverConnection.addEventListener('open', function (event) {
      console.log("Socket opened");
      serverConnection.send("hello!");
});

serverConnection.onmessage = function(e){
   var server_message = e.data;
   console.log(server_message);
}`

**Comment by madmongo1** [comment]
Great, thanks.
