### ISSUE TITLE
Boost 1.73.0/Beast 290 fails to compile with C1001 on VS 2017 Pro. with C++17 Win32 Release Config

### ISSUE THREAD

**Issue by hytano** [boostorg/beast#2014]
The error/problem described in the following does _only_ occure for C++17, Win32 Release builds with optimizations /O2 or /Ox!

While investigating a mysterious crash of our application when build and run in Win32 Release configuration we stripped down our code to only include suspicious calls to `beast::http::write`.

After simplifying the code it stops building with an internal compiler error C1001. (see below)

The error is located at `boost/beast/http/impl/serializer.hpp` line 54.

Don't know if this helps or is important: This is the exact place (returning from `serializer::do_visit`) where a breakpoint (assembly `int 3`) gets hit and the original application crashes. Crash also only in Win32 Release /O2 *and* C++17.

It looks like a problem of the compiler. But we would be happy to find a work around.

### Environment

Visual Studio 2017 Professional 15.9.24 on Windows 10

### Version of Beast

Boost.Beast/290
Boost 1.73.0

### Steps necessary to reproduce the problem

The following repository contains the completely stripped down version of our CMake/Conan settings for our project and includes a minimum working code to reproduce. 

[https://github.com/lenian-code/win32_cxx17_boost_beast_crash.git](https://github.com/lenian-code/win32_cxx17_boost_beast_crash.git)

The code producing the compiler error is essentially just this:

```
#include <iostream>
#include <boost/beast.hpp>
#include <boost/asio.hpp>

using namespace std;
int main(int argc, char *argv[])
{
	boost::asio::io_context ioc;
	boost::asio::ip::tcp::resolver resolver(ioc);
	boost::beast::tcp_stream stream(ioc);

	auto const results = resolver.resolve("localhost", "8086");

	stream.connect(results);

	boost::beast::http::request<boost::beast::http::empty_body> req(boost::beast::http::verb::head, "/ping", 11);
	req.set(boost::beast::http::field::host, "localhost");
	req.set(boost::beast::http::field::user_agent, BOOST_BEAST_VERSION_STRING);

	boost::beast::http::write(stream, req);

	boost::beast::http::response_parser<boost::beast::http::empty_body> parser;
	parser.skip(true);

	boost::beast::flat_buffer buffer;
	boost::beast::http::read(stream, buffer, parser);

	auto res = parser.release();
	if (res.result() == boost::beast::http::status::no_content) {
		cout << "no content\n";
	}

	stream.socket().shutdown(boost::asio::ip::tcp::socket::shutdown_both);
	return 0;
}
```

### All relevant compiler information

Visual Studio 2017 Professional
15.9.24

All of the following settings are important for reproduction:

- Win32
- Release
- Optimizations /O2 or /Ox
- C++17

Build results in the following error

C1001 An internal error has occured in the compiler. File: serializer.hpp 54

```
1>------ Build started: Project: c1001_with_beast, Configuration: Release Win32 ------
1>main.cpp
1>c:\.conan\47aec1\1\include\boost\beast\http\impl\serializer.hpp(54): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'd:\agent\_work\2\s\src\vctools\compiler\utc\src\p2\main.c', line 187)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>
```

**Comment by madmongo1** [comment]
Thanks for reporting the error.

This looks suspiciously similar to a problem I reported to Microsoft a few months ago. Their team's response was "won't fix - suggest you upgrade to 2019".

It's late for me but I'll pick up the trail in the morning. I know it sounds draconian, but is upgrading your compiler feasable?

If not, we can perhaps use your bug report to apply some pressure.

R

**Comment by hytano** [comment]
Sadly we cannot upgrade to 2019. We depend on some third party vendors and these guys do not support 2019 for the Win32 systems yet.

The C1001 error is annoying. But the real problem is that we can get it to compile and then the program just crashes when reaching the part of the code where the C1001 is usually coming from. 

Is it necessary/helpful to create a demo where the C1001 disappears but the program crashes? I guess this would be quite some work.

**Comment by madmongo1** [comment]
> Is it necessary/helpful to create a demo where the C1001 disappears but the program crashes? I guess this would be quite some work.

This is certainly what Microsoft will ask for when a bug report is filed. They will want a single source file (which implies pre-processed), exact compiler/linker versions and an exact command line sequence to reproduce.

If you make it hard for them, they are unlikely to follow through.

**Comment by hytano** [comment]
Ok, we stuffed some code into our example until the C1001 internal compiler error disappears. 

The code is in the _build_but_crashes_ branch. [build_but_crashes](https://github.com/lenian-code/win32_cxx17_boost_beast_crash/tree/builds_but_crashes)

Now the program crashes inside of `beast::http::write`. 

Can someone else please confirm the crash in win32 release with optimization on VS 2017 15.9.24?

I just noticed that giving the request a "/" as target results in "invalid pointer exception". Longer targets just crash on our system.

**Comment by madmongo1** [comment]
Awesome, thanks. Will take a look later this afternoon

**Comment by madmongo1** [comment]
:/ can't replicate. Can you send me a simpleton's guide to building, starting from clicking the Windows Start Menu?

**Comment by hytano** [comment]
Do you mean you cannot generate/build, or does it compile and then does not crash?

**Comment by madmongo1** [comment]
I open the VS2017 command prompt (both 32 and 64 bit), run cmake and then cmake --build, run the executable. No crash. Both release and debug.

**Comment by BlueZora** [comment]
Hi, I originally discovered this crash with @hytano (just because I forgot to change to x64 :wink:).
I just downloaded the latest boost 1.73.0 and tried to use those sources instead of the ones from the conan package. I'm still getting the crash in release.
Furthermore i tried to take cmake and its compiler and linker options out of the game and just thought that I would just build the main.cpp from the VS2017 command prompt. This also results in an executable which crashes.
I used the following options and linker options:
```console
cl /EHsc /MD /std:c++17 /O2 /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_WINDOWS" /I D:\downloads/boost_1_73_0 main.cpp /link /LIBPATH:D:\downloads/boost_1_73_0/stage/lib
```

**Comment by hytano** [comment]
I can also reproduce the crash by linking/building against a fresh boost 1.73.0 version (this time no Conan package) as described above.

**Comment by madmongo1** [comment]
Sorry @hytano I can't fix this before the boost 1.74 release. It's going to require a major rewrite to accommodate one faulty compiler.
I got as far as chopping out enough code to allow the compiler to complete without an ICE - which then left me with a linker that sat in an infinite loop consuming 100% of 4 CPUs.

**Comment by BlueZora** [comment]
@madmongo1, thank you for the information and your time and effort to replicate the error.
We just keep our fingers crossed that we are not forced to use Win32 anytime soon.

**Comment by Trigve** [comment]
I've been hit by this bug while upgrading to boost 1.76.0 (VS 2017). Is there any known workaround?

**Comment by k0zmo** [comment]
What you can do is to replace all `boost::beast::http::async_write` calls with your own wrapper functions that have the definitions in separate TU which is compiled with C++14 standard. You most likely need to make these functions noinline (`__declspec(noinline)`) because that's what causes the bad codegen in the end - I believe turning the inlining off with `/Ob0` while still having `/O2` also fixed the issue. You only need to do it when compiling for Win32.

**Comment by Trigve** [comment]
@k0zmo Thanks for the info. In my case, the problem was manifested in websocket's `async_handshake` (not `async_write`). And yes, I've already used workaround as you've posted, but I disabled the optimizations at the end of TU (to be applicable for template functions included).

But in the end I upgraded to VS 2019 (as I was even planning it in near future).

**Comment by madmongo1** [comment]
> What you can do is to replace all `boost::beast::http::async_write` calls with your own wrapper functions that have the definitions in separate TU which is compiled with C++14 standard. You most likely need to make these functions noinline (`__declspec(noinline)`) because that's what causes the bad codegen in the end - I believe turning the inlining off with `/Ob0` while still having `/O2` also fixed the issue. You only need to do it when compiling for Win32.

This is a nice workaround.
