### ISSUE TITLE
Missing TCP connection teardown in Websocket when wrapped in net::ssl::stream

### ISSUE THREAD

**Issue by TheStormN** [boostorg/beast#2023]
### Version of Beast

Boost 1.73.0
BOOST_BEAST_VERSION 290

### Steps necessary to reproduce the problem
When using WWS client + server I noticed that only the net::ssl::stream is shutdown properly by `beast` but the TCP socket is left behind. When using the same scenario without SSL, `beast` takes care of shutting down the TCP socket properly.

I'm not sure if this is an issue or it is intended to work like that, so I've decided to post here. :)

**Comment by vinniefalco** [comment]
Working as designed. Usually the application will destroy the socket object, and this will close the connection.

**Comment by TheStormN** [comment]
@vinniefalco Directly calling `close()/closesocket()` on socket without proper shutdown have different behavior on different platforms.
For example on Windows it will try to do proper shutdown by sending FIN/FIN-ACK/ACK, etc, while on Linux it will directly destroy the socket with RST.

In the Windows case ASIO is using socket linger to avoid blocking on destruction, so basically the OS is spawning a new thread that will continue to manage the socket until it is properly shutdown(which is an overhead). When we do proper shutdown this thread is avoided.

What I'm trying to say is that if you don't care about the socket shutdown, you can pretty much remove the TCP teardown functionality and leave the library use to do it or do it every time when you have a supported stream/nested supported streams.

**Comment by vinniefalco** [comment]
I was not aware of this, it will need some research. @madmongo1

**Comment by madmongo1** [comment]
What behaviour do we want? Tear down the SSL connection but leave the TCP connection up, or tear down both?

**Comment by TheStormN** [comment]
I would say - tear down both.

Currently if it is WS socket, the TCP connection is tear down. If it is WSS socket, only the SSL connection is tear down, which is half of the work, after the SSL is teared down, the TCP layer should be also teared down.

**Comment by madmongo1** [comment]
ping - there is a fix in the works for this.
