### ISSUE TITLE
Is it possible to use Beast without Asio?

### ISSUE THREAD

**Issue by FastInvite2k2** [boostorg/beast#2024]
Can I do the I/O myself and communicate with Beast using memory buffers?

**Comment by vinniefalco** [comment]
For HTTP, yes. See:
https://www.boost.org/doc/libs/1_73_0/libs/beast/doc/html/beast/using_http/buffer_oriented_serializing.html
https://www.boost.org/doc/libs/1_73_0/libs/beast/doc/html/beast/using_http/buffer_oriented_parsing.html

For Websocket, no.
