### ISSUE TITLE
parse request OR response

### ISSUE THREAD

**Issue by dirkvdb** [boostorg/beast#203]
I'm implementing an ssdp server. This means I am receiving both broadcasted http requests or responses on a udp socket. There is no guaranteed ordering. So when I receive data it can either be a  request or a response.

Is it possible to use beast in this fashion? The read calls seem to require that you specify if you are reading a request or a response.

**Comment by vinniefalco** [comment]
Currently there is no way to do that, but it is something I can add in the next big update to the parser.

**Comment by dirkvdb** [comment]
That would be nice! Can you give an expectation of the timeframe of the next big update?

**Comment by vinniefalco** [comment]
6 weeks give or take. For now, you can try something like this:
* Read at least 5 bytes into a `streambuf`
* Check if those bytes match the characters `HTTP/`
* If yes, then its a response, else its a request
Now call `beast::http::read` with the appropriate message type, with the same `streambuf`. Beast will use the bytes already in the streambuf before going to the network to get more.

**Comment by dirkvdb** [comment]
I already have code that uses the node parser, but I'm planning to migrate to beast. So I'll just wait a bit for now. Thanks for the fast response!

**Comment by vinniefalco** [comment]
Just to let you know, that I have not forgotten about this issue. I plan on addressing it as soon as I have finished the refactoring of the HTTP parser and algorithms. Beast will provide this function:
```
/** Return `true` if the input sequence indicates a HTTP request.

    This function will return `true` if the bytes in the input sequence form the
    beginning of an HTTP request, or `false` if the bytes in the input sequence
    form the beginning of an HTTP response.

    When something other than an HTTP request or response is detected in
    the input sequence, the return value will be tribool "indeterminate."

    @par Preconditions

    The function requires that `boost::asio::buffer_size(buffers) >= 5`.
*/
boost::tribool
is_request(ConstBufferSequence const& buffers);
```

**Comment by vinniefalco** [comment]
This should become an example similar to the `detect_ssl` and `async_detect_ssl` example.

**Comment by vinniefalco** [comment]
There is no real use-case for this in an example program so I think we should leave this to another library.

**Comment by dirkvdb** [comment]
> There is no real use-case for this in an example program
What exactly do you mean with this?

**Comment by vinniefalco** [comment]
>What exactly do you mean with this?

I mean that any example program which would use this feature would be completely contrived.

I can help you write the code if you still need this feature though, would you be interested in that? One thing I should point out though, Beast HTTP stream operations don't work on UDP sockets. So I'm not sure how you plan to get around that.

**Comment by dirkvdb** [comment]
I'm using regular asio for receiving the messages, but it would be nice if I could use beast for decoding the http messages. Currently I'm using both beast and also have a copy of the nodejs http parser in my project.
I would like to get rid of the nodejs parser, so it would be nice if I could use the beast parser, but is seems to require the isRequest template argument which I do not know.

**Comment by vinniefalco** [comment]
I explained in an earlier reply how to do this. Check the first 5 characters of the input buffer and see if they match `"HTTP/"`. If yes, then you have a response, pass `isRequest=false`. Otherwise, pass `isRequest=true`. Is this not sufficient? Example:
```
template<class ConstBufferSequence>
boost::tribool
is_request(ConstBufferSequence const& buffers)
{
    if(boost::asio::buffer_size(buffers) < 5)
        return boost::indeterminate;
    char buf[5];
    boost::asio::buffer_copy(boost::asio::buffer(buf), buffers);
    return std::memcmp(buf, "HTTP/", 5) != 0;
}
```
