### ISSUE TITLE
Multi stage writing to beast::ostream(response_.body()) causes random output at the end of the response

### ISSUE THREAD

**Issue by menkaur** [boostorg/beast#2038]
I've found this issue in 
BOOST_BEAST_VERSION 277

I took code from following example: https://www.boost.org/doc/libs/master/libs/beast/example/http/server/small/http_server_small.cpp

instead of directly writing to beast::ostream(response_.body()), I created variable
auto outputStream=beast::ostream(response_.body());
and than proceeded writing to it several distinct times.

As result, http response contained invalid data after html body, probably unused stream buffer

**Comment by vinniefalco** [comment]
Can you show us your exact changes to the code?

**Comment by menkaur** [comment]
I've already changed the code on my end to avoid the bug, but it looks like this now:

````
std::stringstream outputStream;                	
                        
                        outputStream << "<html>"<<std::endl;
                        outputStream << "<head><title>"<< myTitle <<"</title>"<<
                            R"delimiter(<script type="text/javascript">window.setTimeout(function(){ document.location.reload(true); }, 15000);</script>)delimiter"
                            <<"</head>" << std::endl;
                        outputStream << "<body>" << std::endl;

                        if (!data.empty()) 
                        {
                            outputStream << "<table>" << std::endl;

                            //after this, I'm writing table head and than table content, line by line

                            outputStream << "</table>" << std::endl;
                        }
                        else
                        {
                            outputStream << "<h1>Nothing to report yet</h1>"<<std::endl;
                        }
                        outputStream << "</body>" << std::endl;
                        outputStream << "</html>" << std::endl;

                        beast::ostream(response_.body()) << outputStream.str();
````

The way I remember it, the code that produced the bug  didn't have the last line, and instead of `std::stringstream outputStream;` I wrote `auto outputStream=beast::ostream(response_.body());`
