### ISSUE TITLE
how to close websocket from another thread safely

### ISSUE THREAD

**Issue by tesla1060** [boostorg/beast#2040]
Hi,
my websocket is defined as below,

`websocket::stream<ssl::stream<tcp::socket>> ws;`

I have two threads, one has a loop with the websocket `read`,  and send out `ping` periodically,

```
while(true):
    ws.read(buffer, ec);
```

and the second thread that periodically check `pong`, if `pong` is timeout, the second thread will initiate `ws.close(websocket::close_code::normal)`

The problem is sometimes this assertion is trigger in `boost/beast/websocket/impl/read.hpp:1045`

`BOOST_ASSERT(! impl.rd_close);`

This seems to be a problem of closing `ws` from another thread. any suggestion how to close from another thread?

**Comment by vinniefalco** [comment]
Use the asynchronous APIs and make sure that you only access the websocket stream from one thread.
