### ISSUE TITLE
file upload function need help

### ISSUE THREAD

**Issue by iams13** [boostorg/beast#2041]
I try to add simple file upload function:
file:  ./boost_1_73_0/boost/beast/http/impl/basic_parser.ipp
in this position: `case state::start_line:`
added the following code, omit some variable declaration and so on:

		_tmp.assign(p, n);
		split_strings(_tmp, vctstr, "\r\n");
		for (size_t i = 0; i < vctstr.size(); ++i)
		{
			if (vctstr[i].find("HTTP/") != std::string::npos)
			{
				if (strncmp(vctstr[i].c_str(), "POST /xxxUpload", sizeof("POST /xxxUpload") - 1) == 0)
				{
					isupload = true;
				}
				split_strings(vctstr[i], vcttmp, " ");
				_headermap["Url"] = vcttmp[1];
				break;
			}
		}

and in this position: 
template<bool isRequest>
void
basic_parser<isRequest>::
parse_body(char const*& p,
    std::size_t n, error_code& ec)

    if (isupload)
    {
		//I used the coro http server example,the reason for processing uploads here is to write the file first
		using upload protocol rfc1867 processing......
		//my question is: how to call the incoming socket handle to send 
		//an HTTP message,or process HTTP messages as in the example
    }
    else
    {
		n = this->on_body_impl(string_view{ p,
			beast::detail::clamp(len_, n) }, ec);
    }

**Comment by madmongo1** [comment]
I'm wondering whether you'd be better off by splitting the message receive into two calls:
1. read the header with `async_read_header` https://www.boost.org/doc/libs/1_73_0/libs/beast/doc/html/beast/ref/boost__beast__http__async_read_header.html
2. perform logic based on `header.target`
3. read and processs the body (if any) with a sequence of calls to `async_read_some` https://www.boost.org/doc/libs/1_73_0/libs/beast/doc/html/beast/ref/boost__beast__http__async_read_some.html

**Comment by iams13** [comment]
> I'm wondering whether you'd be better off by splitting the message receive into two calls:
> 
> 1. read the header with `async_read_header` https://www.boost.org/doc/libs/1_73_0/libs/beast/doc/html/beast/ref/boost__beast__http__async_read_header.html
> 2. perform logic based on `header.target`
> 3. read and processs the body (if any) with a sequence of calls to `async_read_some` https://www.boost.org/doc/libs/1_73_0/libs/beast/doc/html/beast/ref/boost__beast__http__async_read_some.html

thank you very much for your reply. I will try
