### ISSUE TITLE
is HMAC SHA256 provided by beast?

### ISSUE THREAD

**Issue by niXman** [boostorg/beast#2046]
Hi,

can you tell me please is beast provides an HMAC SHA256 implementation without using third party libraries like openssl?
if yes - can you please point me?

thanks!

**Comment by vinniefalco** [comment]
Beast does not provide SHA256. But you don't need to use OpenSSL, just copy one of the many 3rd party C++ SHA256 libraries. For example, this one comes in a single header file:
https://github.com/okdshin/PicoSHA2

**Comment by niXman** [comment]
got it, thank you!

ps
I just use `beast` in my project and thought that maybe for `HMAC SHA256` I can use something from `beast` instead of `openssl`.

**Comment by niXman** [comment]
i was able to do it using `picohash` project but when I removed `libcrypto` and `libssl` from linker cmdline i faced with unresolved externals to `openssl` because `asio` uses `openssl` internaly =)
will revert.

**Comment by vinniefalco** [comment]
Well, if you are already using OpenSSL (for `asio::ssl::stream`) then there's nothing wrong with using the SHA256 from OpenSSL.

**Comment by niXman** [comment]
right, but I forgot `asio` also uses `openssl`.
