### ISSUE TITLE
Wrong internal streamstate when reusing socket

### ISSUE THREAD

**Issue by LeTobi** [boostorg/beast#2047]
I am working on a websocket library using beast. My intention is to reuse the necessary websocket::stream<> object for multiple connections.

As it seems there is always an error with the internal streamstate at the 3rd connection of a stream. The docs do not state any reset functionality so I assume the streamstate should be reset automatically with a failed connection.

I have created a small example with the scenario I stumbled upon: [LeTobi/beast-issue](https://github.com/LeTobi/beast-issue) (boost version 290)
The error occurs when the connection gets closed by the peer at tcp level without shutdown using tcp::socket::close() after a successful handshake.

I hope that the error is reproducible and it is no side-effect of some network-configuration.

**Comment by madmongo1** [comment]
I'm afraid you can't re-use a websocket stream object, it's internal state is not restartable.

You will need to destroy it and recreate it. You can certainly steal the underlying socket/ssl state out of it first if necessary.

**Comment by LeTobi** [comment]
Oh, I didn't expect that.
Because reusing the stream once seemed to work, I thought it was reset.

Reconstructing the objects will probably work fine.
Anyway, would there be a possibility to take ownership of the next layer? With "steal the underlying socket" do you refer to a intended method?

**Comment by vinniefalco** [comment]
Use `std::move(ws.next_layer())` to construct a new stream

**Comment by LeTobi** [comment]
This will work.
Thank you for the tip!
