### ISSUE TITLE
"wrong version number" error when restarting connection manually

### ISSUE THREAD

**Issue by UndarkAido** [boostorg/beast#2050]
### Version of Beast

1.71

### Steps necessary to reproduce the problem

Program: https://github.com/DiscordPP/echo-bot

Websocket implementation: https://github.com/DiscordPP/websocket-beast/blob/master/discordpp/websocket-beast.hh

The initial websocket connection is successful and reconnects after lost internet are successful but when Discord requests a reconnect and I try to reboot the websocket connection myself I get a "wrong version number" error thrown by the handshake at line 99. I'm guessing I'm shutting something down wrong but I have no idea what. Does anyone know what I'm doing wrong?

**Comment by vinniefalco** [comment]
Generally speaking you can "re-use" a Beast websocket stream. You have to destroy the old one and use a new one. You can store it in a `unique_ptr` or `optional` which lets you safely re-construct in place.

**Comment by UndarkAido** [comment]
My call of `ws_ = std::make_unique<boost::beast::websocket::stream<ssl::stream<tcp::socket>>>(*aioc, ctx);` before I connect not sufficient?

**Comment by vinniefalco** [comment]
I see. Can you please try also logging the value of `ec.category().name()` at the same time you log `ec.message()`? I need to know if this error is coming from OpenSSL.

**Comment by UndarkAido** [comment]
It takes a long time for Discord to send the reconnect event but I'll start that brewing!

**Comment by vinniefalco** [comment]
By the way, you cannot mix synchronous and asynchronous calls - I see you are calling `async_read` in one place and `write` in another. This won't work.

**Comment by UndarkAido** [comment]
Huh, it's been working just fine except for this. I guess I'll need to swap them over next because I need the async read. How to I get the category from a `boost::wrapexcept<boost::system::system_error>`?

**Comment by vinniefalco** [comment]
> How to I get the category from a boost::wrapexcept<boost::system::system_error>?

umm.... if `se` has type boost::system::system_error` then the category name can be obtained with:
```
se.code().category().name()
```

I have never seen `wrapexcept` before. Typically I don't use exceptions in network code. You may find it easier to express your program in terms of the Beast functions and members which use `error_code&`.

**Comment by UndarkAido** [comment]
Calling the handshake function to reconnect as I outline above results in this:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  wrong version number
Aborted (core dumped)
```
So that's where I'm getting the exception from.

**Comment by vinniefalco** [comment]
`asio::ssl::stream` definitely does not allow both synchronous and asynchronous calls concurrently.

**Comment by UndarkAido** [comment]
Oh they aren't concurrent. The synchronus setup leads into the async read and the async read is cancelled before new setup.

**Comment by UndarkAido** [comment]
Oh but my write is synchronus. Huh. Well it works, I can't tell you why. Both the read and the write.

**Comment by UndarkAido** [comment]
The category name is `asio.ssl`

**Comment by vinniefalco** [comment]
Right, so you are misusing the SSL stream. First I advise that you do not mix synchronous and asynchronous. Second make sure that you are not accessing the stream from more than one thread at a time. And third, make sure that you are using the SSL stream correctly.

**Comment by UndarkAido** [comment]
Ok, I'll look at swapped out my synchronous stuff for asynchronous soon. The program is single threaded, so that shouldn't be an issue. What would using the SSL stream incorrectly look like?

**Comment by vinniefalco** [comment]
> What would using the SSL stream incorrectly look like?

Well, now that you know that it is an SSL problem, have you perhaps done an Internet search for "SSL wrong version number?"

**Comment by UndarkAido** [comment]
Ah, will do. I'd done all of my searches for "Boost wrong version number" and those all led back to #1776. I've implemented the changes from there but I'll do some more general searches 👍

**Comment by vinniefalco** [comment]
Try this
https://www.google.com/search?q=ssl+%22wrong+version+number%22&oq=ssl+%22wrong+version+number%22

**Comment by UndarkAido** [comment]
Yeah, that's what I was planning on doing when I've got a chance. Thank you though!

**Comment by madmongo1** [comment]
Hi @UndarkAido , how are you getting on with this?

**Comment by UndarkAido** [comment]
@madmongo1 adding a delay got rid of this specific error, so my library is reconnecting to Discord the first time but then Discord says the session token is invalid for some reason (I may be doing something wrong but it works when disconnected because of losing internet) after which you have to do another reconnect for a fresh session and when it's doing that reconnect it crashes somewhere deep inside asio SSL with the only stack trace on my code going to the asio run command. I've tried installing certify and I've almost made everything async like @vinniefalco said but it still fails in the same deep place. I can get the stack trace in just a few.

I think it has something to do with me not shutting down the web socket connection properly because it happens before I have a chance to make the new HTTP call to Discord for the gateway address.

**Comment by UndarkAido** [comment]
@madmongo1 If you don't mind taking a look I've pushed my changes here: https://github.com/DiscordPP/echo-bot/tree/fix-resume
Typing `~reboot` in chat makes the bot restart the connection and triggers the error.
The README has setup instructions.
And if you need help with anything free to mention me or a @Helper in my support server: https://discord.gg/0usP6xmT4sQ4kIDh

**Comment by UndarkAido** [comment]
Have you been able to find anything @madmongo1?

**Comment by UndarkAido** [comment]
It seems most of my issues hinged on the outstanding `async_read`. I've made it all async now but it *might* work to mix them if the outstanding read was handled correctly. There could be something lower I'm missing; everything in my lib is async now, though. Thank you both!
