### ISSUE TITLE
How to response http range request

### ISSUE THREAD

**Issue by bigvzhang** [boostorg/beast#2051]
### Version of Beast: 189

My server needs to support HTTP range request(as
https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests). But I
don't know how to implement it.  Could you help me to give me a demo?

### Response comparisons
```
// For beast
$ curl -I http://localhost:8090/BOOKS/mp3/NPR/200605/a001.mp3
HTTP/1.1 200 OK
Server: Boost.Beast/189
Content-Type: application/text
Content-Length: 4559516
Connection: close

// For nodejs running koa/koa-static/koa-range
$ curl -I http://localhost:8091/BOOKS/mp3/NPR/200605/a001.mp3
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 4559516
Last-Modified: Fri, 25 May 2007 06:04:37 GMT
Cache-Control: max-age=0
Content-Type: audio/mpeg
Date: Thu, 13 Aug 2020 00:54:15 GMT
Connection: keep-alive
```

**Comment by madmongo1** [comment]
You can check the request for the Accept-Ranges header, perform your range calculations and set the appropriate status can headers in the response:

```
HTTP/1.1 206 Partial Content
Content-Range: bytes 0-1023/146515
Content-Length: 1024
...
(binary content)
```

**Comment by bigvzhang** [comment]
Thanks. Working on it. Is there a function to parse range request? If not, is there a function to get range string?  Please help me to improve the following code:

```
	std::uint64_t  req_range1 = _UI64_MAX; 
	std::uint64_t  req_range2 = _UI64_MAX;

	{
		static std::regex rgx("^Range:\\s*bytes=(\\d+)-(\\d+){0,1}\\s*$");
		std::ostringstream oss; oss << req; std::string request_as_string = oss.str();
		std::cmatch mr;
		if(std::regex_search(request_as_string.c_str(), mr, rgx)){
			req_range1 = atoi(mr[1].str().c_str()); // TODO: implement "a to uint64"
			if(mr[2].matched)
				req_range2 = atoi(mr[2].str().c_str());
			//printf("==***Range request from %s to %s\n", mr[1].str().c_str(), mr[2].str().c_str());
		}
	}
```

**Comment by madmongo1** [comment]
Hi @bigvzhang 

If you can let me have a link to your git repo I’d be happy to offer suggestions or even submit a PR to help out.

**Comment by bigvzhang** [comment]
Great.  Because my current code is a big mess,  I'll take some time to create a project.

**Comment by madmongo1** [comment]
Don’t be proud :) most projects are a big mess.

**Comment by bigvzhang** [comment]
The repository is at https://github.com/bigvzhang/vhttp.  

The file range_file_body.hpp is based on basic_file_body.hpp to support range request. So far, it only supports one part range request. Lines 184~285 in main.cpp, which is based on advanced_server example, are used to parse range request.  The issue is  that req[http::field::content_range] doesn't work and the bad solution to re-scan the whole request content is used.

**Comment by madmongo1** [comment]
Hi @bigvzhang , Sorry I've been busy the last few days. Did you figure this out or would you still like my help?

**Comment by bigvzhang** [comment]
Thanks for your precious time.  Just look into the issue:
```
auto sv_range = req[http::field::content_range];  // BAD
auto cookie = req[http::field::cookie];                   // OK
```
Is there an equivalent function to get the range value?

**Comment by madmongo1** [comment]
When you say "bad" what do you mean? A compilation error?

The field is defined here:
https://github.com/boostorg/beast/blob/201105e66ab738bd8e027cff8c11ddd7cd5c7587/include/boost/beast/http/field.hpp#L97

and tested here:
https://github.com/boostorg/beast/blob/201105e66ab738bd8e027cff8c11ddd7cd5c7587/test/beast/http/field.cpp#L109

**Comment by bigvzhang** [comment]
Thanks for your precious help. I got the problem, field::range should be used because the browser use "Range" but not "Content-Range" to send the request.

**Comment by madmongo1** [comment]
Great news!
:clap:

**Comment by bigvzhang** [comment]
I appreciate your help. Have a good day!
