### ISSUE TITLE
Can't assign http::fields to http::response

### ISSUE THREAD

**Issue by bog-dan-ro** [boostorg/beast#2052]
I want to update the fields of a `http::response` from another `http::fields` object.
The following example doesn't work for me:
```
http:fields fields = {};// some fields
http::response<http::string_body> res;
res = fields; // I got an error here
```
I could set them using
```
static_cast<http::fields&>(res) = fields;
```
but it's ugly ...

**Comment by madmongo1** [comment]
Hmm. Allowing a direct assignment would make code easier to write but harder to read.

Your workaround actually provides the hint that the assignment is partial.

Ugly it might be, but I think also safer.

**Comment by vinniefalco** [comment]
`res.base() = fields` but yes that's a code smell

**Comment by bog-dan-ro** [comment]
> `res.base() = fields` but yes that's a code smell

I tried that as well, but it didn't worked for me.


> Hmm. Allowing a direct assignment would make code easier to write but harder to read.
> ...

I thought that the main reason for `http::response` to inherit `http:fields` was to allow this kind of assignments :)


IMHO either allow `res = fields;` or add a new method to assign the fields e.g. `res.fields(fields);`

**Comment by madmongo1** [comment]
Hi @bog-dan-ro, when you say it didn't work for you, are you able to show the error output?

@vinniefalco how do we feel about extending the interface of http::message to allow something like:

`msg.assign(fs)` where `fs` is anything `fields`-like? 

I am dubious about the advantage.

**Comment by madmongo1** [comment]
I'm going to close this issue as we don't have plans to extend the interface prior to a refactor.
