### ISSUE TITLE
Should new beast::ssl_stream<beast::tcp_stream> be created for every http request for every http request I make in coroutine

### ISSUE THREAD

**Issue by ScottYueqiang** [boostorg/beast#2054]
should new beast::ssl_stream<beast::tcp_stream> be created for every http request I make in coroutine?
what is the best way to deal with beast::ssl_stream<beast::tcp_stream>

**Comment by madmongo1** [comment]
> should new beast::ssl_streambeast::tcp_stream be created for every http request I make

Not if your server supports HTTP1.1 (which it will). You can tell whether to close the connection by examining this property having received the response:

https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/ref/boost__beast__http__message/keep_alive.html

If `keep_alive()` is `true`, then you may keep the connection open and simply issue a new request on it.

> in coroutine?

irrelevant.

> what is the best way to deal with beast::ssl_streambeast::tcp_stream

This question is open-ended. Can you be more specific?

**Comment by ScottYueqiang** [comment]
> > should new beast::ssl_streambeast::tcp_stream be created for every http request I make
> 
> Not if your server supports HTTP1.1 (which it will). You can tell whether to close the connection by examining this property having received the response:
> 
> https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/ref/boost__beast__http__message/keep_alive.html
> 
> If `keep_alive()` is `true`, then you may keep the connection open and simply issue a new request on it.
> 
> > in coroutine?
> 
> irrelevant.
> 
> > what is the best way to deal with beast::ssl_streambeast::tcp_stream
> 
> This question is open-ended. Can you be more specific?
I use the beast/example/http/client/coro-ssl/http_client_coro_ssl.cpp to test.
I will send a lot of requests at the same time, each request starts a coroutine, and asynchronously sends and accepts in the coroutine, will there be data race if the same stream is used; do you need to create a stream in each write?

**Comment by madmongo1** [comment]
Hi @ScottYueqiang ,

As with all asio stream objects, you may make one async write and one async read per stream at a time. If you have a batch of frames to send, you must queue them in your own queue and write them one by one. During the completion handler of one `async_write`, you can discard the data you have sent and then initiate the next `async_write`.

Does this make sense?
