### ISSUE TITLE
Can I use external custom sockets?

### ISSUE THREAD

**Issue by lucaszanella** [boostorg/beast#2055]
Hello, I'd like to know a simple information. Can I use custom sockets with this library? I'm looking for a library which let me pass my own socket implementation (my own object which implements open, connect, send, etc). I dont have time to read each http library one by one to determine this, so could you kindly tell me if this is possible. If not, then is it easy to add such funcitonality on this library?

thank you so much!

**Comment by madmongo1** [comment]
Hi @lucaszanella , this is more an Asio question. However, the answer is yes.

Are you using the async or sync version?

There are a couple of concepts in Asio which I expect you will need to model:

eg:

Synchronous Interface:

* SyncReadStream https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/reference/SyncReadStream.html
* SyncWriteStream https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/reference/SyncWriteStream.html

Asyncronous Interface:

* AsyncReadStream https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/reference/AsyncReadStream.html
* AsyncWriteStream https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/reference/AsyncWriteStream.html

**Comment by vinniefalco** [comment]
For WebSocket the answer is no. But for HTTP you can also use the buffer-oriented APIs (e.g. `parser` and `serializer`) and do the reading and writing yourself.

**Comment by madmongo1** [comment]
Hi @lucaszanella, do you feel the issue is sufficiently answered for me to close it, or is there something more you would like to ask?

**Comment by lucaszanella** [comment]
Hi @madmongo1, do you mean implementing my own `AsyncWriteStream, AsyncReadStream` classes? It's kinda hard to get it right (I already did it before for other project).

Looking at https://github.com/boostorg/beast/blob/develop/example/http/client/async/http_client_async.cpp#L26 I see that I have to implement one of those:

```

namespace beast = boost::beast;         // from <boost/beast.hpp>
namespace http = beast::http;           // from <boost/beast/http.hpp>
namespace net = boost::asio;            // from <boost/asio.hpp>
using tcp = boost::asio::ip::tcp;       // from <boost/asio/ip/tcp.hpp>

```

maybe the tcp one?

Or maybe I need to tweak https://github.com/boostorg/beast/blob/develop/include/boost/beast/http/read.hpp by passing my own templates for 

```
class SyncReadStream,
    class DynamicBuffer
```

and maybe for write.hpp also? 

How would I make beast use my classes then? 

Looks like it's possible but requires reimplementing `AsyncReadStream` and `AsyncWriteStream` which requires a lot of work. Am I right? 

Maybe the sync version is easier, but it follows the same principle I guess

**Comment by lucaszanella** [comment]
@vinniefalco is there an example on how to force beast to use a custom parser? I'm not very familiar with hpp only libraries, I don't see a way to do `using parser = MyCustomParser` etc...

**Comment by vinniefalco** [comment]
Did you have a look here? https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/using_http/custom_parsers.html
