### ISSUE TITLE
关于设置websocket心跳

### ISSUE THREAD

**Issue by Yph0258691** [boostorg/beast#2056]
ws_http_.set_option(
		websocket::stream_base::timeout::suggested(
			beast::role_type::server))
麻烦问下，是不是使用这个函数，就可以实现心跳检测了

**Comment by madmongo1** [comment]
是的，当担任服务器角色时，WebSocket将自动启动心跳。 担任客户端角色时，要启动心跳，您必须设置超时值或自己执行心跳。

**Comment by Yph0258691** [comment]
好谢谢啊

**Comment by madmongo1** [comment]
我可以解决这个问题吗？
