### ISSUE TITLE
关于asio如何限制linux虚拟ip的bind

### ISSUE THREAD

**Issue by yph025869** [boostorg/beast#2061]
我的机器有个网卡，还有一个虚拟ip,我想auto end_point = tcp::endpoint(tcp::v4(), enp.port()); 使用这行代码的时候，限制虚拟ip的绑定，麻烦问下，我代码该怎么设置

**Comment by madmongo1** [comment]
我不清楚你在问什么。
是否要绑定到计算机上的所有地址？ 还是要绑定到特定的地址和端口？

**Comment by yph025869** [comment]
绑定，除了特定的地址

**Comment by madmongo1** [comment]
https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/reference/ip__address_v4/any.html

您可以使用它作为地址
