### ISSUE TITLE
buffer_ get send back even if the an error occured

### ISSUE THREAD

**Issue by schorsch1976** [boostorg/beast#2063]
https://github.com/boostorg/beast/blob/201105e66ab738bd8e027cff8c11ddd7cd5c7587/example/advanced/server-flex/advanced_server_flex.cpp#L324

buffer_ get send back even if the an error occured. 

Instead of
```
        if(ec)
            fail(ec, "read");
```

it should be 
```
        if(ec)
            return fail(ec, "read");
```

**Comment by madmongo1** [comment]
Thanks for this. Great catch!

If you'd like your name on beast, feel free to send in a PR.

If not, I'm happy to fix it.
