### ISSUE TITLE
Assert on zero-sized read operation from beast::tcp_stream while using beast::ssl_stream

### ISSUE THREAD

**Issue by villytiger** [boostorg/beast#2065]
Boost asio may run read operation with zero-sized buffer in some cases [1] even when it is write operation on a higher level. It works for asio::ip::tcp::socket since zero-sized read operation is in fact a no-op [2]. But I get assertion failure using beast::tcp_stream in the same case:
```
boost/beast/core/detail/stream_base.hpp:80: boost::beast::detail::stream_base::pending_guard::pending_guard(bool&): Assertion `! b_' failed.
```

### Version of Beast

Beast version: 300
Boost version: 1.74.0

### Steps necessary to reproduce the problem

```cpp
#include <boost/beast.hpp>
#include <boost/beast/ssl.hpp>

namespace asio = boost::asio;
namespace beast = boost::beast;

int main() {
        asio::io_context ioContext;
        asio::ssl::context sslContext(asio::ssl::context::tlsv12_client);
#ifdef FAIL
        beast::ssl_stream<beast::tcp_stream> sslStream(ioContext, sslContext);
#else
        beast::ssl_stream<asio::ip::tcp::socket> sslStream(ioContext, sslContext);
#endif

        sslStream.next_layer().connect({ asio::ip::make_address_v4("173.194.222.113"), 443});
        sslStream.handshake(asio::ssl::stream_base::client);

        std::array<char, 1024> buffer;
        sslStream.async_read_some(asio::buffer(buffer), [](auto ec, auto size) {});

        sslStream.async_write_some(asio::buffer("", 0), [](auto ec, auto size) {});

        ioContext.run();
}
```

[1]: https://github.com/boostorg/asio/blob/boost-1.74.0/include/boost/asio/ssl/detail/io.hpp#L233
[2]: https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/reference/AsyncReadStream.html

**Comment by madmongo1** [comment]
Oh! Great catch.
I’ll check it out.

**Comment by madmongo1** [comment]
Hmm. I can't reproduce it. Is the above example the exact code to produce a problem?

**Comment by villytiger** [comment]
Did you compile it with `-DFAIL`? I made two branches to demonstrate that it works for Asio stream. I should have made the Beast branch the default.

**Comment by madmongo1** [comment]
OK, I have it reproduced. Working on it.
