### ISSUE TITLE
advanced_server_flex example questions

### ISSUE THREAD

**Issue by iburyl** [boostorg/beast#2077]
1) class queue
```
        template<bool isRequest, class Body, class Fields>
        void
        operator()(http::message<isRequest, Body, Fields>&& msg)
```
Is it correct that in the context of the queue, isRequest shall always be `false`?

2) class http_session

`on_read()` function has only one path for error code checking, but within the logic of this example, timeout is also a valid path and correct way to behave in this case is to just return. Is it correct?

```
        // This means they closed the connection
        if(ec == http::error::end_of_stream)
            return derived().do_eof();

        // ~Timeout path~
        if(ec == beast::condition::timeout)
        {
            // do_eof() is not applicable here - we already dropped this connection
            return;
        }

        if(ec)
            return fail(ec, "read");
```

**Comment by madmongo1** [comment]
Q1: In this case, yes. The queue is probably over-engineered for this example as it is designed to queue any kind of message.

Q2: you could certainly add another path for handling timeouts. Unlike the queue, the example is taking a simple approach to error handling.

**Comment by vinniefalco** [comment]
>  it is designed to queue any kind of message.
Yes precisely

**Comment by iburyl** [comment]
Thanks. I'll close the issue, but timeout branch in example will likely help with understanding of correct execution flow.
