### ISSUE TITLE
关于get请求时，获取请求参数的问题

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#2079]
麻烦问下，beast库里面有没有提供一个接口是：获取请求参数的接口，比如：target=/login?user_name=yinpinghua&age=12,然后我想获取user_name age的值

**Comment by madmongo1** [comment]
不，野兽是一个低级的HTTP协议库。

有许多用于解析URI的库。

我们正在开发一个boost.url库，但尚未准备好发布。

我过去使用的一个库是：https://github.com/uriparser/uriparser

-------------------------------------------------------------

No, beast is a low level HTTP protocol library.

There are a number of libraries for parsing URIs.

We have a boost.url library under development, but it is not yet ready for release.

One library I have used in the past is: https://github.com/uriparser/uriparser

**Comment by Yinpinghua** [comment]
好，谢谢
