### ISSUE TITLE
Parse Fetch Metadata Request Headers

### ISSUE THREAD

**Issue by bigvzhang** [boostorg/beast#2080]
### Version of 189

How do I parse Fetch Metadata Request Headers?

I added  the following  lines  to the `beast/http/field.hpp`, but I still cannot get its value through `req[http::field::sec_fetch_mode]`
 ```
    sec_fetch_dest,
    sec_fetch_mode,
    sec_fetch_site,
    sec_fetch_user,
```
How should I do?

**Comment by vinniefalco** [comment]
you can't be adding lines to field.hpp. Just use strings as keys, e.g. `req["Sec-Fetch-Dest"]`.

**Comment by bigvzhang** [comment]
Thanks a lot. The problem is fixed. By the way, is it possible to add such fields in the future?

**Comment by vinniefalco** [comment]
> is it possible to add such fields in the future?

Yes, it is. They are added here:
https://github.com/boostorg/beast/blob/4eb7d06d5d5b2b73c681f1a161cc50be697e8197/tools/field.txt

And then this script is used to generate the source code snippets:
https://github.com/boostorg/beast/blob/4eb7d06d5d5b2b73c681f1a161cc50be697e8197/tools/make_field.sh

**Comment by bigvzhang** [comment]
It's fine. Thanks a lot!
