### ISSUE TITLE
关于beast::http::async_read_some 设置问题

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#2084]
麻烦问下：
beast::http::async_read_some此接口，如果设置大于512个字节读取

**Comment by Yinpinghua** [comment]
底层代码看到，是默认是512个字节读取，有没有办法设置，大于512个字节读取

**Comment by madmongo1** [comment]
内部异步操作尝试读取65536字节的块以提高效率。 因此，它将过度读取多余的字节并将其存储在动态缓冲区中，以准备下一次调用async_read_some。

-----------------------------------------------------

The internal asynchronous operation attempts to read in blocks of 65536 bytes for efficiency. For this reason it will over-read and store the excess bytes in the dynamic buffer ready for the next call to async_read_some.

**Comment by Yinpinghua** [comment]
好，明白了，谢谢您啊
