### ISSUE TITLE
string_param API change results in crash passing literal 0

### ISSUE THREAD

**Issue by ecatmur** [boostorg/beast#2085]
Since #1956 1.74.0:
```
#include <boost/beast.hpp>
int main() {
    boost::beast::http::response<boost::beast::http::string_body> res;
    res.set(boost::beast::http::field::content_length, 0);
}
```

Expected: fails to compile
Actual: compiles, crashes with segmentation fault (null dereference).

https://godbolt.org/z/7G1qqv (middle pane is Boost 1.73, right pane is Boost 1.74).

For us, this only broke a test, but other people might be passing literal 0 as a field value in production code. I'd suggest adding
```
void ${function-name}(field name, std::nullptr_t) = delete;
```
alongside each place `string_param` was changed to `string_view` in 14c3d50b570b1d7bf32453f38be77c759007fdb0.

**Comment by madmongo1** [comment]
The road to Hell is paved with good intentions. Thanks for letting us know.

**Comment by vinniefalco** [comment]
> void ${function-name}(field name, std::nullptr_t) = delete;
Hmm... good idea.
