### ISSUE TITLE
关于使用buffer_body解析器时，出现beast::http::error::need_buffer错误的提问

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#2088]
麻烦问下，我在使用buffer_body解析器时,先读头部，然后循环读取body,会提示beast::http::error::need_buffer的错误，但我的代码能够实现功能

**Comment by madmongo1** [comment]
对不起，我听不懂。

---------------------------

Sorry I don't understand.

**Comment by Yinpinghua** [comment]
我的意思，beast::http::error::need_buffer 这个错误，是不是不用管的？

**Comment by madmongo1** [comment]
If you have no more buffer to offer,  then beast::http::error::need_buffer is an error. If you are able to respond to it and provide more buffer, it is a signal.

-----------------------------------------------------------------------------------------------

如果没有更多缓冲区可提供，那么beast :: http :: error :: need_buffer就是一个错误。 如果您能够响应它并提供更多的缓冲区，那是一个信号。
