### ISSUE TITLE
is it possible to provide async_write_read function for convenience

### ISSUE THREAD

**Issue by yaozongyou** [boostorg/beast#2092]
hi, is it possible to provide a composed operation async_write_read function for convenience. this function receives a request message as a parameter, internally, it async_write this message, and async_read response message.  Combine these into a single composed operation, it will be very convenient for common usage.

Thanks~

**Comment by madmongo1** [comment]
This is beyond the scope of beast, as the exact implementation will depend on the details of how the request should be checked and the response formed.

**Comment by madmongo1** [comment]
However, it would be fairly easy to write a composed operation to do this. We often get requests to also produce a "server framework", along the lines of nodejs express. This is also beyond the scope of beast, but could for the basis of another library that depends on beast.

**Comment by yaozongyou** [comment]
got it, thanks your kind reply.
