### ISSUE TITLE
AddressSanitizer shows heap-buffer-overflow on geting reason().data() from the http response object.

### ISSUE THREAD

**Issue by ashjas** [boostorg/beast#2094]
Beast version 1.71

We are using beast in our application for REST communication.
When we run our application with AddressSanitizer integrated, we get  a heap-buffer-overflow at the 2nd line
shown below.

We are using the following http response object
```boost::optional<http::response_parser<http::string_body>> m_res;```
After we get the data back, we return the data back to the caller, one of which is where we 
copy the status message from the response object like this:
```respPtr->setStatusMessage(m_res.get().get().reason().data());```

any idea why could this could end up in  heap-buffer-overflow error?

**Comment by madmongo1** [comment]
Please bear in mind that the return type of `reason()` is a `string_view` and is therefore not guaranteed to be null-terminated.

I suspect your use of `reason().data()` is a logic error.
