### ISSUE TITLE
How to read cookie/headers from handshake in pure websocket server?

### ISSUE THREAD

**Issue by yuntonyx** [boostorg/beast#2095]
Hey all,

I am trying to read cookies from the handshake http request in this example: 
https://www.boost.org/doc/libs/1_74_0/libs/beast/example/websocket/server/async-ssl/websocket_server_async_ssl.cpp

I tried the following:
```
boost::beast::http::request<boost::beast::http::empty_body> req;
ws_.async_accept(
            req,
            beast::bind_front_handler(
                &session::on_accept,
                shared_from_this()));
```

but after changing the code, I am getting the error `The WebSocket handshake method was not GET`

Is it possible to read header values / cookies without making the server dual protocols?

Thank you

**Comment by madmongo1** [comment]
You need to use overload 3 of websocket::stream::async_accept.

https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/async_accept/overload3.html

You pass it a reference to the originating request so it can continue the upgrade rather than waiting for a new GET request.

**Comment by yuntonyx** [comment]
Where can I get the originating request? 

right now in the example overload 1 of websocket::stream::async_accept is called in on_handshake, and on_handshake is called through 
```
ws_.next_layer().async_handshake(
            ssl::stream_base::server,
            beast::bind_front_handler(
                &session::on_handshake,
                shared_from_this()));
```

After reading both documentations on async_handshake and async_accept, I don't see a way to get a `boost::beast::http::request`? Can you please point me in the right direction?

**Comment by vinniefalco** [comment]
> Can you please point me in the right direction?

Yes: https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/using_websocket/handshaking.html#beast.using_websocket.handshaking.inspecting_http_requests

**Comment by yuntonyx** [comment]
> https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/using_websocket/handshaking.html#beast.using_websocket.handshaking.inspecting_http_requests

Thanks! So is this the only way to get the header of the websocket handshake request (by implementing dual protocol)? Because I do not want to handle any other http requests.
