### ISSUE TITLE
Why do we need semicolon before cookie string

### ISSUE THREAD

**Issue by yuntonyx** [boostorg/beast#2096]
As I was trying to parse cookies in beast. I used the reference here: https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/ref/boost__beast__http__param_list.html
```c++
for(auto const& param : boost::beast::http::param_list{";level=9;no_context_takeover;bits=15"})
{
        std::cout << ";" << param.first;
        if(! param.second.empty())
            std::cout << "=" << param.second;
        std::cout << "\n";
}
```
It seems that param_list assumes that each cookie value should start with a semicolon. However, this is not the case when browsers send the actual cookies. Therefore the following code produces no output (taken from https://github.com/boostorg/beast/issues/1425#issuecomment-459985055) :
```c++
for (auto param : boost::beast::http::param_list(m_req[boost::beast::http::field::cookie])) {
     std::cout << "Cookie '" << param.first << "' has value '" << param.second << "'\n";
}
```

but the following code prints out the cookies correctly:
```c++
for (auto param : boost::beast::http::param_list(";" + m_req[boost::beast::http::field::cookie].to_string())) {
     std::cout << "Cookie '" << param.first << "' has value '" << param.second << "'\n";
}
```

I am wondering why this is the intended behavior?

**Comment by madmongo1** [comment]
Beast is a low level library and makes no attempt to parse the cookie headers. param_list is not intended for this.

**Comment by AeroStun** [comment]
Would Beast welcome cookie parsing primitives? I have a design and implementation from a couple months ago lying around; still completely missing serializing tho

**Comment by Tectu** [comment]
> Would Beast welcome cookie parsing primitives? I have a design and implementation from a couple months ago lying around; still completely missing serializing tho

Any chance that you can make it available through posting it as a gist, blog post, repository or something? Would be really interested to give it a look to see how much work it would save me :)

**Comment by madmongo1** [comment]
I think quite a few of our users would welcome this, as to whether it's something that beast should be proividing is probably a question for @vinniefalco

**Comment by AeroStun** [comment]
I have [this](https://github.com/AeroStun/beast/commits/cookies) lying around my account; spent my whole last August on it; IIRC it works.
