### ISSUE TITLE
关于http2.0 beast库什么时候支持

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#2097]
麻烦，问下beast库什么时候支持http2.0协议

**Comment by kervinpierre** [comment]
我不相信有任何即时计划

**Comment by zhuxiaoguang** [comment]
短期内还没有支持的打算

**Comment by vinniefalco** [comment]
HTTP/2, HTTP/3, SPDY, QUIC are never going to be in Beast.

**Comment by nqf** [comment]
https://github.com/fantasy-peak/simple_http#
