### ISSUE TITLE
Crashing in engine.ipp

### ISSUE THREAD

**Issue by Raj123456788** [boostorg/beast#2103]
Don't get any info but this:
<img width="1177" alt="Screen Shot 2020-10-14 at 4 13 00 PM" src="https://user-images.githubusercontent.com/16295521/96055202-4a279e80-0e38-11eb-94ec-065f93779367.png">

Let me know if anything is wrong with my string data.

**Comment by madmongo1** [comment]
This kind of thing is normally because the object containing your ssl stream has been deleted.

**Comment by Raj123456788** [comment]
@madmongo1 : Thanks.  I have below code 
                            res1.body() = data;
                            res1.prepare_payload();
                            res1.keep_alive(req.keep_alive());
                            return (send(std::move(res1)));
By the time the data is sent over the ssl res1 changes. is there a way I can handle this since data is coming at a fast pace.

**Comment by madmongo1** [comment]
You could use the async_ interface as per the examples?
https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/examples.html#beast.examples.servers

**Comment by madmongo1** [comment]
Activity on this issue seems to have trailed off so I'll close it for now. If you're still having problems, by all means open another issue. It's helpful if you can post a small, complete program on github that demonstrates the issue so I can debug it locally.
