### ISSUE TITLE
How to access response status code from a response_parser?

### ISSUE THREAD

**Issue by rhegner** [boostorg/beast#2110]
I'm using `http::async_read_header` to read only the header of the response into a `http::response_parser<http::empty_body>`. I'm able to access all the headers but I couldn't figure out how to access the response status code.

**Comment by madmongo1** [comment]
Hi @rhegner ,

The response_parser has the method `get()` which can be used to access the embedded reponse.

```
void test(http::response_parser<http::empty_body> const& p)
{
    auto& msg = p.get();

    // text reason for failure
    boost::beast::string_view reason = msg.reason();

    // status code enum
    http::status result = msg.result();

    // statis code as integer
    int result_int = msg.result_int();
}
```

**Comment by madmongo1** [comment]
Vinnie mentioned that there is a comprehensive email/mime library here:
http://www.codesink.org/mimetic_mime_library.html#docs

It might be worth a look if you're under time pressure.

**Comment by rhegner** [comment]
`p.get().result_int()` did the trick, thank you!
