### ISSUE TITLE
beast::basic_stream does not have an assignement operator

### ISSUE THREAD

**Issue by AlexandreBossard** [boostorg/beast#2120]
### Version of Beast
boost 1.73 - not really relevant

### Steps necessary to reproduce the problem
The following code does not compile on msvc 19
```
#include <future>
#include <boost/beast/core/tcp_stream.hpp>
struct S
{
    boost::beast::tcp_stream stream;
    S() : stream(boost::asio::system_executor()) 
    {}
  S(S&& s) : stream(std::move(s.stream)) {}
};
int main()
{
    std::promise<S> p;
    p.set_value(S());
    auto f = p.get_future();
}
```
https://godbolt.org/z/fxYehz

This arise when I wrote a composed operation and use it with `net::use_future`, the `self.complete(ec, std::move(obj))` failed to comiple with MSVC.

MSVC`s `std::future` implementation requires a default constructible object and an assignment operator (copy or move). `beast::basic_stream` fails to provide that, but `asio::basic_stream_socket` seems ok.

It is surprising to have a movable constructor but not a move assignment constructor.

**Comment by kervinpierre** [comment]
https://developercommunity.visualstudio.com/content/problem/123622/stdasyncs-stdfuture-doesnt-support-types-that-are.html
