### ISSUE TITLE
C4003: not enough arguments for function-like macro invocation 'max' in boost version 1.72.0

### ISSUE THREAD

**Issue by DV-Developer** [boostorg/beast#2134]
Updated to version 1.72.0 and am  getting the warning indicated in the title along with associated errors for the file: file_stdio.ipp. The call std::numeric_limits<long>::max() is missing parenthesis to prevent windef.h max macro insertion.

Full warning and errors:
boost.1.72.0.0\lib\native\include\boost\beast\core\impl\file_stdio.ipp(244,71): warning C4003: not enough arguments for function-like macro invocation 'max'
boost.1.72.0.0\lib\native\include\boost\beast\core\impl\file_stdio.ipp(244,71): error C2589: '(': illegal token on right side of '::'
boost.1.72.0.0\lib\native\include\boost\beast\core\impl\file_stdio.ipp(244,7): error C2062: type 'unknown-type' unexpected
boost.1.72.0.0\lib\native\include\boost\beast\core\impl\file_stdio.ipp(244): error C2144: syntax error: 'unknown-type' should be preceded by '('
boost.1.72.0.0\lib\native\include\boost\beast\core\impl\file_stdio.ipp(244,77): error C2059: syntax error: ')'
boost.1.72.0.0\lib\native\include\boost\beast\core\impl\file_stdio.ipp(245,5): error C2143: syntax error: missing ';' before '{'

**Comment by vinniefalco** [comment]
is this fixed in the latest Boost?

**Comment by madmongo1** [comment]
I seem to remember fixing a problem like this.

**Comment by DV-Developer** [comment]
It was logged as a problem and reported fixed for 1.73 in issue 1980 I believe. I’m not seeing 1.73 using Nuget through VS though. So I’m using 1.72.

 

Thanks,

Chris
