### ISSUE TITLE
Build error on ARM64-Release

### ISSUE THREAD

**Issue by thorichelli** [boostorg/beast#2136]
### Version of Beast
v124
### Version of Boost
1.65

### Steps necessary to reproduce the problem

just including the header is enough:

`#include <boost/beast.hpp>`

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'__cpuid': identifier not found (compiling source file sources\test.cpp)	Lib	c:\src\beast\include\boost\beast\core\detail\cpu_info.hpp	49	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol jump_fcontext  libboost_coroutine-vc140-mt-1_65.lib(coroutine_context.obj)	

### All relevant compiler information
msvc 140 ARM64 Release

It cannot find __cpuid on ARM64, how can I make it find? Why do I need cpu_info, can I skip it for a basic query operation?

**Comment by madmongo1** [comment]
looking around the internet, it seems we need to include <intrin.h> on windows
https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=msvc-160

**Comment by eata7** [comment]
I guess no

**Comment by vinniefalco** [comment]
I believe this was fixed in a later version of Beast
