### ISSUE TITLE
built-in timer for async_read() and async_write()

### ISSUE THREAD

**Issue by mirkub** [boostorg/beast#2137]
### Version of Beast
300

### Steps necessary to reproduce the problem
We are implement a http client which is setting up timeout for both read and write:

```
stream_.expires_after(connection_timeout_);
http::async_read(stream_, buffer_, resp, beast::bind_front_handler(&session::on_read, shared_from_this()));

....

stream_.expires_after(connection_timeout_);
http::async_write(stream_, req_, beast::bind_front_handler(&session::on_write, shared_from_this()));
```

But the program crashes in beast/core/impl/basic_stream.hpp:
```
723     if(! impl_->write.pending)
724         BOOST_VERIFY(
725             impl_->write.timer.expires_after(
726                 expiry_time) == 0);
```

So I assume we can't mix the timeout for both read and write. How can this be sorted - i.e. how can we implement independent timeouts for read and write calls?

**Comment by madmongo1** [comment]
It looks like you have a race condition in your calling code.
The timeout works as you expect.
Remember that no asio stream is thread-safe.

**Comment by vinniefalco** [comment]
If you change your program to be single-threaded, what happens?

**Comment by mirkub** [comment]
Moving all the logic to the ioc thread seems to have fixed the problem.
Thanks for help.
