### ISSUE TITLE
what exactly means "outstanding operation"

### ISSUE THREAD

**Issue by JindrichD** [boostorg/beast#2138]
### Version of Beast
300

hi, i see randomly that assert in basic_stream.hpp goes off - there is a comment next to the assert:
```
// If assert goes off, it means that there are
// already read or write (or connect) operations
// outstanding, so there is nothing to apply
// the expiration time to!
//
BOOST_ASSERT(
    ! impl_->read.pending ||
    ! impl_->write.pending);
```
so my question is when the operation is outstaning? i know this is somehow connected with calling stream.expires_after() but i can't figure out when this happens. what is the call sequence of async_write()s and async_read()s and expires_after()s to cause that?

EDIT:
hm...from time to time the program also crashes few lines after above on 
`BOOST_VERIFY(impl_->write.timer.expires_at(expiry_time) == 0);`
what are the reasons why the expires_at fails?

**Comment by madmongo1** [comment]
This error is the code politely telling you that you have broken the fundamental rule of Asio. You must never have more that one asynchronous write in progress at a time on a given stream.
You must wait for the completion handler of the previous write to be invoked before you initiate the next asynchronous write.

**Comment by JindrichD** [comment]
ok, ta. yea i know that rule - however i was pretty sure that that i did not break the rule....well...obviously not...

**Comment by vinniefalco** [comment]
You need to call `expires_after` _before_ the read or write it applies to, not after.
