### ISSUE TITLE
Could not build on android studio

### ISSUE THREAD

**Issue by RealMG** [boostorg/beast#2142]
### Version of Beast

#define BEAST_VERSION 290

### Steps necessary to reproduce the problem

Add the beast to a native jni project on android studio, but when compile, got a pre-compile version error

#elif defined(__GNUC__)
# if((__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) < 40801)
#  error Beast requires C++11: gcc version 4.8 or later needed
# endif

### All relevant compiler information
I set the c++ to 17.
I use the latest ndk version 22, and it uses the clang by default, I checked the clang version was 11.0.5, so I thought beast would be compiled correctly.

**Comment by RealMG** [comment]
I have a step forward on this issue.
I found a compile option for clang : -fgnuc-version
in android ndk, the default __GNUC__ is  4.2.1 even the clang version is pretty new, so I set the -fgnuc-version to a newer version.
the pre-compile error is gone but got some compile error. 

so is the beast library NOT supported on android?

**Comment by madmongo1** [comment]
I would like to help solve this. 

however I am unfamiliar with Android studio.
Would you be able to provide a very simple, complete project for me in GitHub so that I can reproduce and solve for you as soon as possible?

Also, simple instructions on how to install and use android studio would be a great help.

**Comment by RealMG** [comment]
Thanks for replying.
In fact, the compile error could be removed by the compile option which I mentioned.
The Beast headers could be compiled correctly, and the other errors are generated by my code. working on that.
So currently the result is the Beast could be compiled on android studio, but I could not tell if it is workable.
Thanks.

**Comment by madmongo1** [comment]
phew!

Thanks for letting us know.
