### ISSUE TITLE
Beast samples for secured websocket are not proper

### ISSUE THREAD

**Issue by TsvetanBogoev** [boostorg/beast#2151]
BOOST_BEAST_VERSION 189

In _websocket_client_async_ssl.cpp_ a root certificate is added to the context 

`load_root_certificates(ctx);`

 but this certificate is not used and in this sample peer certificate will not be validated without a call to set_verify_mode 

```
// Verify the remote server's certificate
ctx.set_verify_mode(ssl::verify_peer);
```

which is missing. In other samples like http_client_async_ssl.cpp the call is present

**Comment by madmongo1** [comment]
Thanks for reporting. 
You are correct.
