### ISSUE TITLE
Error in large file downloads with flat_buffer

### ISSUE THREAD

**Issue by bulbaasd** [boostorg/beast#2155]
Hello, 
I tried this example ( https://www.boost.org/doc/libs/1_75_0/libs/beast/example/http/client/sync/http_client_sync.cpp) to download a large file ( ~ 400+MB ).

This is what I noticed:
I get a partial message error when trying to use a flat_buffer.
I get rid of the error when trying to use a multi_buffer with maximum body limit.
Would like to know, why I observe this behaviour. Is it a bug with flat_buffer?
Note: I would not doubt the server implementation, as the behaviour is noticed only with asio, and not curl/wget.

**Comment by madmongo1** [comment]
Can you share the url so I can replicate the test?

**Comment by madmongo1** [comment]
I have run this test locally, using a node http server and a 500MB file.
The program ran to completion.
Are you able to share any more information?

**Comment by bulbaasd** [comment]
I'm sorry. I was working with a very old version of boost.
Everything seems to work fine with the newest version.
