### ISSUE TITLE
Why not implement sending a ping of advanced_server_flex?

### ISSUE THREAD

**Issue by dkd1111** [boostorg/beast#2161]
version: boost 1.74.0 / BOOST_BEAST_VERSION 300

- boost 1.67 : https://www.boost.org/doc/libs/1_67_0/libs/beast/example/advanced/server-flex/advanced_server_flex.cpp
I can check sending a ping code.

-  boost 1.70 : https://www.boost.org/doc/libs/1_70_0/libs/beast/example/advanced/server-flex/advanced_server_flex.cpp
No implement of sending a ping.

Is there special reasons for disappear of the codes? or just do it myself on version 1.70?

**Comment by vinniefalco** [comment]
The websocket implementation sends pings automatically if you configure it. See: 
https://www.boost.org/doc/libs/1_75_0/libs/beast/doc/html/beast/using_websocket/timeouts.html

**Comment by dkd1111** [comment]
thanks!!
