### ISSUE TITLE
WebSocket OnRead getting error code 2 (system lib) occasionally. 

### ISSUE THREAD

**Issue by ErikSod** [boostorg/beast#2168]
Version of Beast: 1.73. 
Compiler CoreXT 16.8.

I'm using SSL websocket ( boost::beast::websocket::stream<boost::beast::ssl_stream<boost::beast::tcp_stream>> _webSocket) as a client to connect to a server endpoint and running into some occasional problems with OnRead. Most times it will work fine, but occasionally it will get all the way through the SSL handshake and connection but _webSocket.async_read will return error code 2 (system lib). I didn't see this error code in the websocket errors list so I wasn't sure what it could be caused by. Any ideas what could be happening here?

**Comment by madmongo1** [comment]
Are you on linux or windows?

**Comment by ErikSod** [comment]
Windows.

**Comment by madmongo1** [comment]
1. What do you get if you print everything.message() to the console?

2. are you sure you’re not accessing the websocket on 2 threads? Strange errors are often the result of a data race.

**Comment by ErikSod** [comment]
1. The message() is just "system lib". 
2. That's a good question, let me see if I can force just one thread and see if it repros.

**Comment by mhassanshafiq** [comment]
@ErikSod @madmongo1 was this issue resolved? I am getting this as well, running boost 1.73 on linux

generally observing this when opening a lot of connections.

**Comment by mhassanshafiq** [comment]
@madmongo1 and I can verify the read is happening in a single thread, using strand for all read, write and close functions

**Comment by vinniefalco** [comment]
Where does the string "system lib" come from? Did you check asio sources?

**Comment by mhassanshafiq** [comment]
I am not sure, just printing the `error.message()` where error is passed into the read callback.

Searched the whole boost source, couldn't find this error string anywhere.
@vinniefalco

**Comment by madmongo1** [comment]
At the moment I don’t have a lot to go on. Could you post a short complete program that exhibits the problem?

At the moment I am suspecting a data race or use of freed memory (because that’s what these problems usually are). But without having something to test it’s guesswork.

**Comment by vinniefalco** [comment]
What is `error.category()`?

**Comment by mhassanshafiq** [comment]
error:system lib, category:asio.ssl

@vinniefalco

**Comment by vinniefalco** [comment]
What happens when you use a plain TCP socket instead of an SSL stream?

**Comment by madmongo1** [comment]
FYI, from OpenSSL source:

```
 static ERR_STRING_DATA ERR_str_reasons[]=
 {
 {ERR_R_SYS_LIB              ,"system lib"},
 ```

Typical use in OpenSSL:

```
if (BIO_read_filename(in, file) <= 0) {
 SSLerr(SSL_F_SSL_USE_CERTIFICATE_FILE, ERR_R_SYS_LIB);
 goto end;
```

**Comment by vinniefalco** [comment]
it might be nice to know the actual SSL error instead of just "system lib"

**Comment by mhassanshafiq** [comment]
@vinniefalco tested with simple tcp (instead of ssl) NOT getting the random disconnects with this.

**Comment by madmongo1** [comment]
Hi hate to day it but this kind of intermittent problem is normally due to a race condition or inadvertent undefined behaviour being introduced in the code.

Is the program multi-threaded?

**Comment by mhassanshafiq** [comment]
yes, the code is multi threaded, but all the read write and close operations are posted to the same strand. @madmongo1

**Comment by madmongo1** [comment]
I would bet that if you moved just the comms code into its own single-threaded program you'd see no problems.

Out of interest, can you confirm that the openssl library you are linking to compiled as a multi-threaded library? This is where the error is coming from. It's not originating in Beast or Asio.

**Comment by vinniefalco** [comment]
Try running the I/O context with only one thread, using `ssl::stream`

**Comment by mhassanshafiq** [comment]
@vinniefalco @madmongo1 tried running the code with only single thread in io context. Still got the same result.

**Comment by madmongo1** [comment]
I guess the next step is to isolate the SSL library and test it in isolation. There error you are seeing is originating there.
Can you confirm:
- Which SSL library you are linking to
- Which version
- How it was installed
- What is the underlying OS
etc

**Comment by mhassanshafiq** [comment]
OpenSSL 1.0.2k-fips  26 Jan 2017
install on `CentOS Linux release 7.9.2009 (Core)` using `yum -y install openssl-devel`

**Comment by vinniefalco** [comment]
> 26 Jan 2017

That's pretty old...
