### ISSUE TITLE
How to ignore authentication key when calling with https url?

### ISSUE THREAD

**Issue by leejaenggu** [boostorg/beast#2170]
I am trying to communicate via https URL Post.
However, if you use https, an error appears saying that the host cannot be found.
I think it's a certificate issue.
I want to do something like the -k or --insecure option, which is the certificate override in curl.
What should I do?

**Comment by madmongo1** [comment]
Not a lot of info here, but a common mistake is trying to resolve the entire url.
You can’t do that as beast is a low level library.
You have to connect to the host name/ port section of the url and then issue the request, setting the target field to be the query part of the url
