### ISSUE TITLE
关于使用multipart/form-data请求

### ISSUE THREAD

**Issue by Yinpinghua** [boostorg/beast#2171]
能不能给个multipart/form-data 请求的代码列子

**Comment by madmongo1** [comment]
客户端代码作者负责解码HTTP BODY中的数据。
野兽没有设施来帮助这一点。
我们认为FORM DATA是“应用程序的关注点”

**Comment by Yinpinghua** [comment]
我自己搞定了，谢谢啊

**Comment by Yinpinghua** [comment]
我已解决

**Comment by 1s23** [comment]
> 我已解决

想问下是怎么解决的，可以给个例子吗，感谢

**Comment by vinniefalco** [comment]
http://www.codesink.org/mimetic_mime_library.html
