### ISSUE TITLE
Undefined behavior in parser

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#2172]
Currently the parser exhibits undefined behavior when data is provided but the parser is already "complete." This needs to be fixed. One option is simply to throw an exception. We should check to see if there are any other ways to produce undefined behavior.

**Comment by madmongo1** [comment]
Would it be reasonable to ASSERT this precondition in a debug build and throw in a release build?

**Comment by madmongo1** [comment]
since we already have this code
```
        // If this assert goes off, it means you tried to re-use a
        // parser after it was done reading a message. This is not
        // allowed, you need to create a new parser for each message.
        // The easiest way to do that is to store the parser in
        // an optional object.

        BOOST_ASSERT(! used_);
        if(used_)
        {
            ec = error::stale_parser;
            return;
        }
```

**Comment by madmongo1** [comment]
After some lively discussion in slack, there is not yet complete consensus but there is a 2:1 majority in favour fo the above solution.

I will make this change and re-engage with @genossefloyd to assess impact.

I am reluctant to actuallyt remove the assertion as initially requested as this is clearly an irrecoverable logic error that should be caught during development/testing and never reach production.
