### ISSUE TITLE
HTTP Client Connection Pooling Example

### ISSUE THREAD

**Issue by LukeMauldin** [boostorg/beast#2187]
### Version of Beast

1.74

### Steps necessary to reproduce the problem

I am using boost beast HTTP client to make HTTP and HTTPS requests. Is there an example of how to use boost beast with connection pooling and keep-alive so that if multiple HTTP requests are made to the same URL, then the TCP connections will be reused?
Since beast is a fairly low-level library, I have abstracted it away from my higher level application components.  I would like automated back-ground connection pooling similar to the Go standard's library `net/http` package if that is possible.

### All relevant compiler information

Compiler: MSVC 2019 update 9

**Comment by vinniefalco** [comment]
When I got the notification, I was hoping this would be a pull request with a fully working example of the aforementioned features. But alas, it is only a feature request.

**Comment by madmongo1** [comment]
I wrote a blog on it in the New Year

https://cppalliance.org/richard/2021/01/01/RichardsNewYearUpdate.html
