### ISSUE TITLE
Clarification on Boost websocket.

### ISSUE THREAD

**Issue by edineshkumar** [boostorg/beast#2212]
I am using **Boost** opensource library for creating a websocket in my application. Now my need is, after certain time duration, websocket need to be closed.

**Example:**  After 30 minutes, websocket should gracefully closed at any cost.

Is this possible with Boost library?
If yes, please help me out to configure the websocket's session timeout and achieve my requirements.

Thanks for advance.

**Comment by madmongo1** [comment]
Hi there. You would use an `asio::steady_timer` and initiate an async_wait once the connection was established.
Once the timer times out (completion handler is executed with no error), you would call `async_close` on the websocket. 
Your `async_read` loop should continue until the completion handler indicates an error.
At this point you can destroy your connection object.

**Comment by edineshkumar** [comment]
Thanks for your response.,

Actually in my application already open handler, message handler, close handler and error handler were implemented, which is used it for my application. 

Now I am trying to add additional way to closing the websocket, (i.e.) called as session timeout.

Any example is more helpful for me.

**Comment by madmongo1** [comment]
Can you tell me the rules for your timeout? Is it an inactivity timeout or an overall session lifetime timeout?
I’ll write a small example

**Comment by edineshkumar** [comment]
Overall Session lifetime Timeout .

**Comment by madmongo1** [comment]
ok creating a little project now

**Comment by madmongo1** [comment]
I have added a 30s session timeout to a demo websocket chat server I wrote some time ago.
[https://github.com/test-scenarios/boost_beast_websocket_echo/tree/master/pre-cxx20/echo_server](https://github.com/test-scenarios/boost_beast_websocket_echo/tree/master/pre-cxx20/echo_server)

see connection.hpp and connection.cpp

**Comment by edineshkumar** [comment]
Your example was more useful for my implementation. Very thank you for your responds and quick replay.

Closing the issue.
