### ISSUE TITLE
how to download the bigdata response that type content type is application/octet-stream

### ISSUE THREAD

**Issue by liruisee** [boostorg/beast#2218]
he file is very large and the local memory cannot be fully loaded, so how read it as a iterator.

**Comment by madmongo1** [comment]
First read the header:
https://www.boost.org/doc/libs/1_76_0/libs/beast/doc/html/beast/ref/boost__beast__http__async_read_header.html

And then while `!parser.is_done()`, read section and handle them incrementally:
https://www.boost.org/doc/libs/1_76_0/libs/beast/doc/html/beast/ref/boost__beast__http__async_read_some.html
