### ISSUE TITLE
ASAN traced problem

### ISSUE THREAD

**Issue by GorbachevDaniil** [boostorg/beast#2219]
**Version of Beast**

`BOOST_BEAST_VERSION 306`

**Problem summary**

Hello!

I'm facing problem and have some trace to locate it, but I'm not so deep dived in Beast library, so will really appreciate if you can help me.

Trace that I have from ASAN you can found in attached file. Unfortunately, some of the inputs were cut down.
[log.txt](https://github.com/boostorg/beast/files/6351872/log.txt)

My WssSession class also attached
[wss_session.txt](https://github.com/boostorg/beast/files/6351957/wss_session.txt)

If you need something else I will be glad to provide it.
Look forward to your reply!

Best regards,
Gorbachev Daniil.

**Comment by madmongo1** [comment]
> READ of size 1 at 0x6150002d3a0c thread T1
...
> freed by thread T291 here:

Have you taken steps to guard concurrent access of the websocket?

**Comment by GorbachevDaniil** [comment]
I'm using Websocket only from one thread. I'm creating and destroying it inside thread, so it cannot be accessed in any other place.

**Comment by GorbachevDaniil** [comment]
Maybe I didn't understand you right. Do I need to guard concurrent access to websocket for io context aswell?

**Comment by madmongo1** [comment]
io objects such as sockets, ssl streams and webssocket streams are not thread safe. All intermediate completion handlers must execute on their own implicit or explicit strand.

The io_context is thread safe.

**Comment by GorbachevDaniil** [comment]
Okay thank you
