### ISSUE TITLE
compiler error on dynamic_vector_buffer

### ISSUE THREAD

**Issue by gopalak** [boostorg/beast#2223]
I am trying to yse a dynamic_vector_buffer with an underlying uint8_t vector. (This is a class data member). But when I declare the dynamic_vector_buffer I see the following compiler error.

asio::dynamic_vector_buffer   m_in_db = asio::dynamic_buffer(_in_buf);
and my _in_buf is of type vector<uint8_t>

--- Error I see ---

srvr.cpp:89:35: error: missing template arguments before ‘m_in_db’
     asio::dynamic_vector_buffer   m_in_db =

Also I am not sure on using boost::optional to declare the dynamic_vector_buffer as a data member.
Appreciate the help note @vinniefalco

**Comment by madmongo1** [comment]
This is an asio question.

The error message is telling you that `dynamic_vector_buffer` is a template class, and you have not provided template arguments.

Let's wait until we have solved that, before we talk about the boost::optional question.

**Comment by gopalak** [comment]
Got it. I did fix
asio::dynamic_vector_buffer<uint8_t, std::allocator<uint8_t>>   m_in_db =
    asio::dynamic_buffer(_in_buf);

I would like to have this m_in_db as a data member as I have my handler a bit involved and not easy to put as a lambda

**Comment by madmongo1** [comment]
You'll probably find that you can leave out the `, std::allocator<uint8_t>` part as this is the default.

The asio dynamic buffers are designed to be lightweight, copyable references to an underlying data buffer (e.g. `_in_buf`).

You can create the dynamic_buffer when you need it. You don't need to store it anywhere. The operation that uses it will dynamically update the underlying vector `_in_buf`.

**Comment by gopalak** [comment]
Ahh so if I understand it right - just do an asio::buffer(_in_buf) when I call async_read or async_write ? and the _in_buf will be automatically used as its the underlying storage ?

**Comment by gopalak** [comment]
> You'll probably find that you can leave out the `, std::allocator<uint8_t>` part as this is the default.
> 
> The asio dynamic buffers are designed to be lightweight, copyable references to an underlying data buffer (e.g. `_in_buf`).
> 
> You can create the dynamic_buffer when you need it. You don't need to store it anywhere. The operation that uses it will dynamically update the underlying vector `_in_buf`.

I did leave it and it complained about the template class needing 2 params.

**Comment by madmongo1** [comment]
> Ahh so if I understand it right - just do an asio::buffer(_in_buf) when I call async_read or async_write ? and the _in_buf will be automatically used as its the underlying storage ?

Yes, but only for ASIO async operations. Beast async operations require that you use the Beast dynamic buffers, which are different, and passed by reference.

> I did leave it and it complained about the template class needing 2 params.

My mistake.

**Comment by gopalak** [comment]
> > Ahh so if I understand it right - just do an asio::buffer(_in_buf) when I call async_read or async_write ? and the _in_buf will be automatically used as its the underlying storage ?
> 
> Yes, but only for ASIO async operations. Beast async operations require that you use the Beast dynamic buffers, which are different, and passed by reference.
You mean some thing like beast::multi_buffer ? I really need an under lying uint8_t based storage container in the buffers.
and the dynamic_vector_buffer seems to be a good fit. Doesnt that gel well with beast websocket stream async_read and write calls ?

> 
> > I did leave it and it complained about the template class needing 2 params.
> 
> My mistake.

**Comment by madmongo1** [comment]
Can we consider this issue closed?

**Comment by gopalak** [comment]
Yes thanks for the help. By the way where can I post questions on ssl::context specifically on set_password_callback for private key files ?

**Comment by madmongo1** [comment]
ssl::context is a thin wrapper around OpenSSL.

The OpenSSL documents are a good place to start, and stackoverflow has a good deal on inormation.

You can also join the CppLang slack and see who's online to help you, start in the #beast channel where I live.

https://cppalliance.org/slack/
