### ISSUE TITLE
ref #2231 - use of posix SSIZE_MAX

### ISSUE THREAD

**Issue by madmongo1** [boostorg/beast#2233]
see #2231

POSIX defined SSIZE_MAX but there is no guarantee in C++ that this symbol will be defined (even on a posix build environment) by including `<limits>`.

This is causing a compile error for one of our users.

Poposed fix is to use `std::make_unsigned<std::size_t>` and the corresponding `std::numeric_limits<T>::max()` in place of `ssize_t` and `SSIZE_MAX`.

**Comment by viccpp** [comment]
> Poposed fix is to use `std::make_unsigned<std::size_t>`

`make_signed`?

**Comment by madmongo1** [comment]
Yep :)
