### ISSUE TITLE
 connect: No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by ghost** [boostorg/beast#2248]
Hello to evrey one, i use vpn in my laptop, when i am connect to vpn and i try to sent request to server an get the response i got this message of error:  connect: No connection could be made because the target machine actively refused it. but when i am connect to wifi i recive the reponse from the server. i don t now why.

**Comment by TheStormN** [comment]
I think your issue is nothing related to Beast.

**Comment by Mathieux2** [comment]
Now it s Beast issue, i shoud configure a proxy, but how i dont now

**Comment by TheStormN** [comment]
Beast does not directly support proxies, you will have to implement that yourself.

**Comment by Mathieux2** [comment]
Ok,There is a methode to do our own message of exception, if i do i bad host,because i got message ```No such host is known``` what is the code error of that, i want to exlpain more that error using try and catch

**Comment by TheStormN** [comment]
By viewing your other opened issues I see that you are new to C++, networking, ASIO and Beast. You should start reading the docs, viewing the examples and in general start understanding how the whole machinery is working, before coming here asking generic questions. Perhaps StackOverflow would be a better place for your questions.

If you want to skip some of that learning curve, you should go to a more high level libraries and frameworks. I would recommend the Qt Framework and the provided websocket there - https://doc.qt.io/qt-5/qtwebsockets-examples.html

It does natively support proxies and other high level stuff which you are expecting.
