### ISSUE TITLE
websocket::stream is not compatible with asio::async_write()

### ISSUE THREAD

**Issue by TheStormN** [boostorg/beast#2252]
### Version of Beast
313

### Steps necessary to reproduce the problem
I'm currently developing some generic code which can use any kind of stream as template parameter. My specific case is using `tcp::socket`, `ssl::stream` and `websocket::stream`.

However, it seems that when the `asio::async_write()` free function is used for `websocket::stream` the program fails to compile. However, `asio::async_read()` is compiling fine.

To fix that issue I basically created the following free function
```c++
template <typename StreamType, typename... ArgsType>
constexpr void async_write(websocket::stream<StreamType>& stream, ArgsType&&... args)
{
    stream.async_write(std::forward<ArgsType>(args)...);
}
```

which solves the issue perfectly, but it's weird that I need to do that, given that async_read is working just fine.

EDIT: Here's the error message generated by the compiler:
```
error C2672: 'boost::beast::websocket::stream<boost::asio::ip::tcp::socket,true>::async_write_some': no matching overloaded function found
boost/asio/impl/write.hpp(330): note: while compiling class template member function 'void boost::asio::detail::write_op<AsyncWriteStream,ConstBufferSequence,ConstBufferIterator,CompletionCondition,WriteHandler>::operator ()(const boost::system::error_code &,size_t,int)'
with
[
    AsyncWriteStream=boost::beast::websocket::stream<boost::asio::ip::tcp::socket,true>,
    ConstBufferSequence=std::array<boost::asio::const_buffer,3>,
    ConstBufferIterator=std::_Array_const_iterator<boost::asio::const_buffer,3>,
    CompletionCondition=boost::asio::detail::transfer_all_t,
    WriteHandler=qb::net::AsyncConnection<boost::beast::websocket::stream<boost::asio::ip::tcp::socket,true>>::send::<lambda_a5857e4b406aeb79407b6575053daf19>
]
```

### All relevant compiler information
MSVC 2019 16.10.0

**Comment by madmongo1** [comment]
That is correct. A websocket stream does not model a socket stream. The message boundaries in a websocket specifically delimit variable length messages, whereas the asio socket stream types model a connection with a continuous stream of data with no frame or message boundaries.

**Comment by TheStormN** [comment]
That's fine, but given that my workaround is working fine in such scenarios, perhaps you can add that free function to Beast?
It just needs to be in the `boost::asio` namespace and it will start working.

**Comment by madmongo1** [comment]
I am not at liberty to inject functions into the asio namespace. asio::async_write is not an official _customisation point_.

What I would suggest is that you provide overloads of the name name _in your own project's namespace_ to do what you want.

You will need to provide special handling for the stream type `boost::beast::websocket::stream<T>`.

**Comment by TheStormN** [comment]
Ok, I agree about the customization point. However, I do see that Beast's `websocket::stream` does have an `async_write_some` function which kinds of makes me wonder if it's really impossible to make it compatible stream with ASIO functions.

**Comment by madmongo1** [comment]
beast's async_write_some is there to write multiple parts of a single websocket message, rather than to write some part of a stream.

We have been asked previously for an async_write which would work on a buffers sequence like asio's.

The issue is that it would be ambiguous as to whether eache buffer would be written to a single message, or whether each buffer would form its own distinct message.

The same ambiguity would exist on the read side.

**Comment by TheStormN** [comment]
> The same ambiguity would exist on the read side.

Yes, but `asio::async_read()` does work for `websocket::stream` and thus the confusion rises - why the one would work and the other wont.

IMHO `websocket::stream::async_write_some` should be just a proxy to the next layer and `websocket::stream::async_write()` should take care of writing a whole message.

**Comment by vinniefalco** [comment]
> why the one would work and the other wont.

Coincidence. When I designed `websocket::stream`, I used Asio's interfaces as a guide so that they would be familiar to users.

**Comment by TheStormN** [comment]
Ok, but still, what is the major difference between reading and writing, so that the first can work with the standard interface and the second cannot?

**Comment by vinniefalco** [comment]
> Ok, but still, what is the major difference between reading and writing, so that the first can work with the standard interface and the second cannot?

`async_write_some` has a different signature than what is needed to meet the requirements of _AsyncWriteStream_

https://www.boost.org/doc/libs/1_76_0/doc/html/boost_asio/reference/AsyncWriteStream.html

**Comment by TheStormN** [comment]
Yeah, I can see that from the compiler error. I was asking more of an websocket technical perspective. @madmongo1 already explained what's the technical issue with the writing, but then I would expect the same issue to occur during reading which is not the case.

**Comment by vinniefalco** [comment]
The difference is that when reading, the peer determines the end of the frame. While writing, the application determines the end of the frame. Thus the APIs are not quite symmetric with ASIO's async streams.

**Comment by TheStormN** [comment]
Understood. Ok, thank you for your time(both of you) and the detailed explanations!
