### ISSUE TITLE
[help] Installing beast using git submodules

### ISSUE THREAD

**Issue by Nitwel** [boostorg/beast#2259]
Hi, I'm really new to c++ and trying to install and use beast by adding it to my project as a git submodule.
My problem is that VisualStudio only finds `boost::beast` but not `boost::beast::http` from this example: https://github.com/boostorg/beast/blob/710cc53331f197f6f17e8c38454c09df68e43c03/example/websocket/server/sync/websocket_server_sync.cpp#L16-L29

I've included the hpp files like so:

![grafik](https://user-images.githubusercontent.com/22577866/121884817-ac140d00-cd13-11eb-92cb-beac032bd3d1.png)

where `/libraries/beast` is the beast submodule and same goes for asio and code.

The error VS gives me:
![grafik](https://user-images.githubusercontent.com/22577866/121885081-0614d280-cd14-11eb-9d3b-15d562f939f3.png)

What exactly am I doing wrong that VS does find `boost::beast` but not `boost::beast::http`?

**Comment by madmongo1** [comment]
Boost (including beast) should be installed either the supplied b2 tool.
The Cmake script is there for maintenance use at the moment.
Cmake support for installing boost is in the pipeline but currently not part of the supported user experience.
@pdimov

**Comment by pdimov** [comment]
You haven't included `<boost/beast/http.hpp>`.

**Comment by Nitwel** [comment]
Including `<boost/beast/http.hpp>` still gives an error.

**Comment by klemens-morgenstern** [comment]
@Nitwel we'd need the error to help you. Since it's been over a year, I assume you figured it out by now. If not please reopen the issue.
