### ISSUE TITLE
allow per-message compression option

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#226]
When permessage-deflate is negotiated on a stream, It should be possible to control whether compression is enabled on a per-message basis.

**Comment by JunielKatarn** [comment]
Has this been enabled yet (as of boost 1.68)?
If not, when is message compression used in a Beast WebSocket client?

**Comment by JunielKatarn** [comment]
It certainly does. If I got this correctly, by default, a Beast WS client stream has compression (per-message deflate) enabled, pending other conditions (server negotiation).

Thanks.

**Comment by pscamodio** [comment]
Sorry to resurrect this old issue, but it's still open.
After the three conditions are met the server and client "can" exchange compressed messages. But it seems to be no way to specify, for a specific message if I want to compress it or not.
It seems to me that beast suppose that if permessage_deflate is enabled I want to compress all the messages.
In my case there are some messages that I need to leave uncompressed for speed reason, the time spent in deflate is not acceptable, but I want to compress all the other messages.
I don't see in the write methods any way to specify if that specific message need to be compressed or not.

**Comment by alandefreitas** [comment]
@pscamodio 

From the height of my ignorance, doesn't this work?

```cpp
// Disable compression
websocket::permessage_deflate pmd;
ws.get_options(pmd);
pmd.client_enable = false;
pmd.server_enable = false;
ws.set_options(pmd);
// Use the was stream
ws.read(/* ... */); // or whatever operation
// Enable compression
ws.get_options(pmd);
pmd.client_enable = true;
pmd.server_enable = true;
ws.set_options(pmd);
```

If this does work, then it might not be a huge problem, although this is probably verbose enough to justify some wrapper function.

**Comment by vinniefalco** [comment]
I like your thinking here, but the meaning of "enable" is just that it is allowed as a negotiation option during handshake. Whether or not compression is actually enabled is a property of the stream. See:
https://github.com/boostorg/beast/blob/develop/include/boost/beast/websocket/impl/stream_impl.hpp#L100

**Comment by alandefreitas** [comment]
Yes. I was looking at 

https://github.com/boostorg/beast/blob/00293a6adb5383fe14217a8916dd7ff79a857483/include/boost/beast/websocket/impl/stream_impl.hpp#L227-L228

right now, and trying to find a solution to this issue and https://github.com/boostorg/beast/issues/227.

So this issue is just a matter of agreeing on the API to enable/disable `wr_compress_opt`, while #227 is just a matter of including an extra min size condition at the line above.

**Comment by vinniefalco** [comment]
The minimum size should be configurable, with a reasonable default (see what other libs do, like uWebsockets)
