### ISSUE TITLE
HTTP Response default constructor set status to ok (200)

### ISSUE THREAD

**Issue by GorbachevDaniil** [boostorg/beast#2261]
### Version of Beast 313

Hello! I have small question.
I want to understand why when http response just created it's already has status ok (200)?
I see it's coming from default constructor for message class, but it's not clear behaviour to have 200 for response when no request being sent.

Best regards,
Gorbachev Daniil.

**Comment by vinniefalco** [comment]
Would you prefer the value be uninitialized or undefined?

**Comment by GorbachevDaniil** [comment]
I see that you have unknown in status enums, I think it's best option for this

**Comment by vinniefalco** [comment]
What would `result_int()` return, then? https://www.boost.org/doc/libs/1_76_0/libs/beast/doc/html/beast/ref/boost__beast__http__header/result_int.html

And why would this be better than the current implementation?

**Comment by madmongo1** [comment]
I think the short answer is that when sending a response, 200 OK is the most likely code to be used, so if it makes sense to default it to anything, it would be this.

**Comment by GorbachevDaniil** [comment]
Okay, thank you for your answers! So do I understand right that in most cases server will return 200 and because of it default status is 200? It's looks like an attempt to predicting the future. If status will be unknown as default then it will return 0 and in `result_int()` method till real response was arrived and it's looks fine to me, but of course I could be wrong, because I'm not and expert in beast library.

**Comment by vinniefalco** [comment]
>  It's looks like an attempt to predicting the future

No, the goal of the constructor is to put as many fields as possible into a known, valid state.

**Comment by GorbachevDaniil** [comment]
Okay, thanks.
