### ISSUE TITLE
error in target while parsing headers

### ISSUE THREAD

**Issue by quazeeee** [boostorg/beast#2267]
Hello. I have been using boost::beast for years without flaws, a great project. But now I am facing trouble. I am developing software for windows and copied some part of the old code with the standard beast WebSocket client and server. On the server side, during the accept, I am facing an issue in parse_target method.

parthe_method successfully handles "GET", but pare_target begins work from "HTTP/1.1" and finally fail on "\r\n" after HTTP/1.1 

Can you provide any suggestions? 

Headers from debug:

GET HTTP/1.1
Host: 127.0.0.1:9092
Upgrade: websocket
Connection: upgrade
Sec-WebSocket-Key: zu/EYa2Fgv3M0U5J0ho2Rw==
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol: test_secure

client side code:
wss->async_handshake("127.0.0.1:9092", "/", bind_front ...)

boost beast version: 1.75

**Comment by quazeeee** [comment]
> Hello. I have been using boost::beast for years without flaws, a great project. But now I am facing trouble. I am developing software for windows and copied some part of the old code with the standard beast WebSocket client and server. On the server side, during the accept, I am facing an issue in parse_target method.
> 
> parthe_method successfully handles "GET", but pare_target begins work from "HTTP/1.1" and finally fail on "\r\n" after HTTP/1.1
> 
> Can you provide any suggestions?
> 
> Headers from debug:
> 
> GET HTTP/1.1
> Host: 127.0.0.1:9092
> Upgrade: websocket
> Connection: upgrade
> Sec-WebSocket-Key: zu/EYa2Fgv3M0U5J0ho2Rw==
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Protocol: test_secure
> 
> client side code:
> wss->async_handshake("127.0.0.1:9092", "/", bind_front ...)
> 
> boost beast version: 1.75

**Comment by vinniefalco** [comment]
Glad I could help :)
