### ISSUE TITLE
async_read try_lock assertion failure 

### ISSUE THREAD

**Issue by uvguy** [boostorg/beast#2283]
I have dummy broadcast ws server here, but my first intention is when the server successfully broadcast write data then the server must read client request again. How to avoid soft_mutex try_lock assertion

### Version of Beast

 boost version 1.76 on linux

### Steps necessary to reproduce the problem

I've placed paired client and part of my server code on [my gists](https://gist.github.com/uvguy/0355caabdfc78f5233cb7df79a8a6a03#file-main-cpp-L167)

**Comment by madmongo1** [comment]
The usual reason for this is that you've initiated an async_write before the previous one has completed.

**Comment by uvguy** [comment]
Thanks for your suggestions, but my async_write has already recursively call itself until there are no buffer queue for writing that same as multi_chat example did. Using async_read or posting asio event to trigger server async_read when buffer queue was empty still yield same problem

**Comment by C8LUKA** [comment]
Is that problem done which show in your code @uvguy
