### ISSUE TITLE
Detection of loss of ping/keep-alives

### ISSUE THREAD

**Issue by treyweaver** [boostorg/beast#2284]
I am using version 1.76 on an ARM Cortex processor.  I am running as a client

I have a wss socket established and with wireshark I can see that websocket's ping/keep-alives are working.  Then I disconnect the server from the network to stop the pings.

On the client side I do not see any indication that the link has been lost.  I expected to get an on_read with an error code.

How can I tell if the websocket's ping/keep-alives have been lost?

**Comment by madmongo1** [comment]
By default the client does not initiate pings. The server does. You can enable pings from the client by setting the option on the websocket stream prior to the handshake

**Comment by treyweaver** [comment]
That was not my question.  The server is delivering pings and every thing is running fine.  But for some reason those pings disappear; maybe a cable get cut, a router goes down, someone unplugs a cable.  How does the user of beast know that the server is no longer connected?  My client connection to the server is persistent, so I have to know the connection is lost so I can try to reconnect.

**Comment by madmongo1** [comment]
You client cannot know that the connection has been cut unless it initiates pings.

the server initiated pings tell the server that the connection has been cut.

the lack of pong response to a ping will result in your async_read completing with an error.

**Comment by treyweaver** [comment]
OK that fixed the issue.  I noticed that the client default for keep_alive_pings is "false".  Can I always assume that the websocket server will respond to client pings?

Thanks!

**Comment by madmongo1** [comment]
That is my understanding, yes. Our thinking here is that servers care whether there are zombie clients taking up resources and want to cull them often. Clients tend not to need to do this (although there are exceptons such as yours)
