### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by aaronovz1** [boostorg/beast#2286]
Is there an example of running a websocket server/client capable of IPv4 and IPv6? Is it possible to do a bind-all with IPv6 similar to the `0.0.0.0` address in IPv4?
I tried specifying `tcp::endpoint{boost::asio::ip::tcp::v6(), port}` but I get a `bind: Address already in use` error even with `reuse_address` enabled.

**Comment by vinniefalco** [comment]
No because this is purely an ASIO issue. Check ASIO's examples. Or perhaps look here: https://stackoverflow.com/questions/10286042/using-boost-asio-to-accept-on-ipv6-link-scope-address

**Comment by aaronovz1** [comment]
Turns out the main problem was sysctl configuration on my system had IPv6 disabled. After enabling this a couple minor code changes I was able to get everything working.
