### ISSUE TITLE
async https request (enabling threads)

### ISSUE THREAD

**Issue by paulnegz** [boostorg/beast#2289]
OS: Ubuntu bionic
```
    resolver_.async_resolve(
        host,
        port,
        beast::bind_front_handler(
            &session::on_resolve,
            shared_from_this()));
}
```
using meson build system (https://mesonbuild.com/).
After attaching the header files and libraries, I am unable to make a http request inside https://github.com/openbmc/phosphor-health-monitor/blob/master/healthMonitor.cpp 
![ERROR](https://user-images.githubusercontent.com/37233089/125712789-17cd4d71-0add-48e9-a4ea-1ec455e70226.JPG)

Attached Dependencies: 
![mesonEdit](https://user-images.githubusercontent.com/37233089/125712258-6a48c0c4-7897-4c92-b392-a00dd8a30f17.JPG)

**Comment by madmongo1** [comment]
What steps did you take to prepare your program for multiple threads?
Are you using strands?

**Comment by paulnegz** [comment]
https://github.com/boostorg/beast/tree/develop/example/http/client/async-ssl example uses strands and that the sample code I followed but the error is about threads

**Comment by madmongo1** [comment]
Are you saying that you started with our example and modified it to suit your needs, and it now does not function?

or did you write a new program using our example as a tutorial?

**Comment by paulnegz** [comment]
I copied the example and tried to add it  to a .cpp file(https://github.com/openbmc/phosphor-health-monitor/blob/master/healthMonitor.cpp)

**Comment by madmongo1** [comment]
Ok, probably a good idea to go back to the example, check it’s working, and then make incremental changes until it doesn’t.
Whatever you did last is the problem.
At the moment we don’t have a lot to go on.

**Comment by paulnegz** [comment]
That was my approach and the resolver_.async_resolve function throws an error

**Comment by madmongo1** [comment]
Did you resolve this in the end?
