### ISSUE TITLE
Tooling for HTTP header lists parting

### ISSUE THREAD

**Issue by Tectu** [boostorg/beast#2291]
Does `boost::beast` provide any tooling for parsing HTTP header lists? For example:
```none
Content-Type: multipart/form-data; boundary=something
```
How would one go about retrieving `multipart/form-data` and `boundary=something` as individual items? Does beast provide any tooling for that out of the box?

While we're already at it: Does beast provide any tooling to parse the body of an `multipart/form-data` request? Example request (taken from MDN):
```none
POST /foo HTTP/1.1
Content-Length: 68137
Content-Type: multipart/form-data; boundary=---------------------------974767299852498929531610575

-----------------------------974767299852498929531610575
Content-Disposition: form-data; name="description"

some text
-----------------------------974767299852498929531610575
Content-Disposition: form-data; name="myFile"; filename="foo.txt"
Content-Type: text/plain

(content of the uploaded file foo.txt)
-----------------------------974767299852498929531610575--
```

**Comment by madmongo1** [comment]
Beast is a low level HTTP/websocket library and as such does not offer tools for decoding cookies, mime formats and so on. 
One could envisage a higher level library, built on top of beast that did so.
However, parsing mime documents is fairly trivial.

**Comment by Tectu** [comment]
> One could envisage a higher level library, built on top of beast that did so.

That is what I am working on ->https://github.com/Tectu/malloy
I just don't want to add stuff that is already provided by beast so occasionally I have to drop by here and ask things like that ;-)

**Comment by madmongo1** [comment]
When I get a moment, I intend to create a complimentary library, both on the server and client side.

**Comment by vinniefalco** [comment]
There are some algorithms for parsing such lists, e.g.:
https://github.com/boostorg/beast/blob/710cc53331f197f6f17e8c38454c09df68e43c03/include/boost/beast/http/rfc7230.hpp#L21
