### ISSUE TITLE
Is there any way to use flat_static_buffer's data with zerocopy?

### ISSUE THREAD

**Issue by JaydenFish** [boostorg/beast#2299]
I receive network data with flat_static_buffer or static_buffer. 
Is there any better way than boost::beast::buffers_to_string(static_buffer.data())? Making a string is expensive because of heap allocation.
I'm using boost1.66.

**Comment by madmongo1** [comment]
Since these buffers have a contiguous memory layout it is straightforward to simply get access to the underlying data and view it through (for example) a string_view.

e.g.

    auto mem = mybuff.data();
    auto sv = string_view(reinterpret_cast<const char *>(mem.data()), mem.size());

**Comment by JaydenFish** [comment]
thank you very much!
