### ISSUE TITLE
test/beast/websocket failed against 32 bits compiler (gcc/clang)

### ISSUE THREAD

**Issue by xing1xu** [boostorg/beast#2310]
With 64 mod.

> boost_1_75_0/b2 toolset=clang address-model=64 --abbreviate-paths --disable-icu  --reconfigure -d+1 -d+2 cflags="-std=c++14  "  write

Pass.

With 32 mode.

> boost_1_75_0/b2 toolset=clang address-model=32 --abbreviate-paths --disable-icu  --reconfigure -d+1 -d+2 cflags="-std=c++14  "  write
/bin/sh: line 9: 4003719 Segmentation fault      (core dumped) "../../../../../bin.v2/libs/beast/test/beast/websocket/write.test/clng-lnx-14.0./dbg/adrs-mdl-32/thrdp-pthrd/thrd-mlt/vsblt-hdn/write" > "../../../../../bin.v2/libs/beast/test/beast/websocket/write.test/clng-lnx-14.0./dbg/adrs-mdl-32/thrdp-pthrd/thrd-mlt/vsblt-hdn/write.output" 2>&1 < /dev/null

Failed.

> $cat write.output
> beast.websocket.write
> EXIT STATUS: 139

**Comment by madmongo1** [comment]
Thank you. I will investigate.

**Comment by klemens-morgenstern** [comment]
@xing1xu Can you share some more details about the issue?
