### ISSUE TITLE
buffers_to_string doesn't work, won't compile program

### ISSUE THREAD

**Issue by tech0tron** [boostorg/beast#2316]
PLEASE DON'T FORGET TO "STAR" THIS REPOSITORY :)

If you rather keep your project secret, feel free
to email the author at `<vinnie.falco@gmail.com>`; any
private correspondence is treated as confidential.

When reporting a bug please include the following:

### Version of Beast
313
### Steps necessary to reproduce the problem
`
std::string CodekataConnection::SendMessageAndListen(std::string message)
{
	beast::flat_buffer buffer;
	ws.write(net::buffer(message));
	ws.read(buffer);
    return buffers_to_string(buffer);
}
`

ws is a standard websocket, it is a class member of the CodekataConnection

### All relevant compiler information
MSVC++ on Visual Studio 2019, using Vcpkg to manage all of my dependencies.

These are the errors I am getting:
![image](https://user-images.githubusercontent.com/76018881/134282574-651d1f95-acfc-4e31-98ad-4cd93dde5c41.png)

**Comment by madmongo1** [comment]
Try:

buffers_to_string(buffer.data())
