### ISSUE TITLE
SSL verify callback not being invoked during handshake TLS 1.2

### ISSUE THREAD

**Issue by gopalak** [boostorg/beast#2326]
Beast version 306
I understand this is not a beast specific issue. But my TLS client code has a ssl verify callback set on the SSL context but that never gets invoked. Searching around I find different answers but nothing seems to explain why a callback for cert verification is not being called.

I have set the verify mode to verofy_peer
set the verify call back function as well

Appreciate the help
PS: I know the server I connect to presents a self signed cert

**Comment by gopalak** [comment]
> @chriskohlhoff Any Ideas?

I did post the same in that repo as well. Havent seen reply :(

**Comment by brjoha** [comment]
Perhaps post your code that is constructing the SSL context?

**Comment by klemens-morgenstern** [comment]
@gopalak any luck on providing us with some code?
