### ISSUE TITLE
body limit exceeded

### ISSUE THREAD

**Issue by Moerten** [boostorg/beast#2335]
Hi,

I used a HTTP SSL socket to retrieve binary data (with a string_body). Now I want the receive a zip file and getting always a "body limit exceeded" error. I found out that I should set the parsers "body_limit" function to a bigger value somehow. But I am not using a "response_parser" so far. Maybe you could give an example how to change my code:

Class-Members:
```
boost::beast::flat_buffer m_bufHttpSocket;
boost::beast::http::response<boost::beast::http::string_body> m_oResponse;
shared_ptr<boost::asio::ssl::context> m_pSSLContext;
shared_ptr<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>> m_pHttpSocket;
```
Read-Funktion:
```
http::async_read(
		*m_pHttpSocket,
		m_bufHttpSocket,
		m_oResponse,
		std::bind(
			&base::OnRead,
			this,
			std::placeholders::_1,
			std::placeholders::_2));

```

**Comment by Moerten** [comment]
Do you have an example already?

**Comment by vinniefalco** [comment]
> Do you have an example already?

https://www.boost.org/doc/libs/1_77_0/libs/beast/doc/html/beast/using_http/parser_stream_operations/read_large_response_body.html

**Comment by Moerten** [comment]
This example did not apply to my async http socket well. But I think I got the idea and managed to get it to work now (almost). I do the following:

Class-Members:

```
boost::beast::flat_buffer m_bufHttpSocket;
boost::beast::http::response<boost::beast::http::string_body> m_oResponse;
shared_ptr<boost::beast::http::response_parser<boost::beast::http::string_body>> m_pParser;
shared_ptr<boost::asio::ssl::context> m_pSSLContext;
shared_ptr<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>> m_pHttpSocket;
```

Read-Funktion:
```
        if (m_pParser == nullptr)
	{
                m_pParser = make_shared<http::response_parser<http::string_body>>(std::move(m_oResponse));
               	m_pParser->eager(true);
	        m_pParser->body_limit(std::numeric_limits<std::uint64_t>::max());
        }
	http::async_read(
		*m_pHttpSocket,
		m_bufHttpSocket,
		*m_pParser,
		std::bind(
			&base::OnRead,
			this,
			std::placeholders::_1,
			std::placeholders::_2));
```

Read-Callback:
```
                if ((m_pParser != nullptr) && m_pParser->is_done())
		{
			m_oResponse = m_pParser->release();
			m_pParser.reset();
                         ....
               }
```

I am still a bit confused about e.g. the parsers "content_length" / "content_length_remaining" properties. Also the parser states it "is_done" the "content_length_remaining" value says almost all bytes are missing? But this is obviously wrong.

And the parsers needs a message object for it's constructor which gets moved to the parser. The "m_oResponse" message object is a member of my class. Now it gets moved to the parser. What when for some reasons never "m_oResponse = m_pParser->release()" gets called to move the message object back to my class? Then I guess I would have a broken "m_oResponse" member? How should this be handled?

And more importingly. If I run tha app in release build now it works as expected. But not in debug build. Here I always get a "data truncated" error on first read. No idea why.
