### ISSUE TITLE
Does beast already support HTTP2?

### ISSUE THREAD

**Issue by kqbi** [boostorg/beast#2341]
Does beast already support HTTP2? demo?

**Comment by vinniefalco** [comment]
Nope. And no plans to do so.

**Comment by brjoha** [comment]
I'm using it in a project that supports both HTTP/1.1 and HTTP/2.

When HTTP/2 is negotiated, the nghttp2 lib is used for the session layer but Beast request and response types are still used above that.  I expect to follow the same approach for HTTP/3.
