### ISSUE TITLE
does wss support cdn forwarding

### ISSUE THREAD

**Issue by inaryart** [boostorg/beast#2355]
The wss client of another library I am using cannot be accessed once cdn(cloudflare) is turned on. I want to know whether this library supports cdn

**Comment by madmongo1** [comment]
Cloudflare requires passing a couple of headers I think? Beast can certainly do that.

Can you detail cloudflare's requirements here?

**Comment by inaryart** [comment]
I see that grpc has request header requirements, but the weboscket requirements are not found. I access the cloudflare-protected website via browser f12 and I don’t find anything special. I need to continue to search for information.

https://support.cloudflare.com/hc/en-us/articles/360050483011-Understanding-Cloudflare-gRPC-support

https://support.cloudflare.com/hc/en-us/articles/200169466-Using-Cloudflare-with-WebSockets

**Comment by inaryart** [comment]
give up the use of cdn forwarding to solve this problem.
