### ISSUE TITLE
Problem with Beast and Samsung Internet (websockets, unencrypted)

### ISSUE THREAD

**Issue by johannes1971** [boostorg/beast#2358]
I'm using Beast (from Boost 1.73; Beast 292), in synchronous mode, as a server for websockets (without encryption, just ws://), on Windows. The client application (written in Javascript) can communicate just fine from everything we've tried (Safari, Chrome, Firefox, Edge, etc.), with the exception of "Samsung Internet", apparently the default browser on some Android phones, where Beast complains about bad_method before aborting the connection. While not a major deal (we can tell our users to just use Chrome or Firefox instead), I was still wondering if this is a known problem in either Samsung Internet or Beast, and if there is something we can do to make it work.

Our code is an only mildly adjusted version of the Beast synchronous websocket server example.

**Comment by madmongo1** [comment]
Are you able to post an example of a request header that Beast rejects?
Beast aims to be strictly standards compliant. If the client is sending a malformed request, we may be less forgiving than other libraries.
However, it is possible that we have an error. I'd like to check.

**Comment by johannes1971** [comment]
I can try. What's the best way to obtain such a header?

**Comment by madmongo1** [comment]
```
log_stream << received_request;
```

**Comment by johannes1971** [comment]
> ```
> log_stream << received_request;
> ```

What is received_request in this context? I'm guessing it must be something related to the acceptor?

**Comment by madmongo1** [comment]
> > ```
> > log_stream << received_request;
> > ```
> 
> What is received_request in this context? I'm guessing it must be something related to the acceptor?

It's the request http request you received:

https://www.boost.org/doc/libs/1_78_0/libs/beast/doc/html/beast/ref/boost__beast__http__request.html

https://www.boost.org/doc/libs/1_78_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/async_accept/overload3.html

**Comment by vinniefalco** [comment]
is this resolved?
