### ISSUE TITLE
How do I close a synchronous websocket server?

### ISSUE THREAD

**Issue by johannes1971** [boostorg/beast#2359]
We have a synchronous websocket server, almost exactly the example from the website (https://www.boost.org/doc/libs/develop/libs/beast/example/websocket/server/sync/websocket_server_sync.cpp). Is there a way to close this if the _server_ decides to shut down on its own? Both the acceptor and any open sessions appear to be stuck waiting for something to happen from a remote source. Is there a way to trigger forward motion from another thread, or is that only possible in the async version?

We are currently using Beast 292 from Boost 1.73.

**Comment by madmongo1** [comment]
Short answer is no.
Deciding to shut down the server asynchronously (i.e. while there is a read in progress) starts to argue for an asynchronous server model.

**Comment by johannes1971** [comment]
I don't mind completing any on-going reads, the problem is if it's just sitting there waiting for the next read to occur. There appears to be no way to progress it at that point. 
If this means we need to switch to the asynchronous model, we'll do that. It looked a bit easier like this...

**Comment by madmongo1** [comment]
Using the async model with boost.coroutine or c++20 coroutines is almost as easy as writing inline code.
But writing async code using the continuation passing model isn't that much of a hardship once you get used to it.

**Comment by vinniefalco** [comment]
> It looked a bit easier like this...

Yes, well it is easier because it does less :)

**Comment by vinniefalco** [comment]
If the issue is still unresolved please reopen it or create a new issue, thanks!
