### ISSUE TITLE
Use boost::core::string_view

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#2363]
We need to deprecate `BOOST_BEAST_USE_STD_STRING_VIEW` and change the type to use `boost::core::string_view`

**Comment by vinniefalco** [comment]
isn't this done?

**Comment by sehe** [comment]
@vinniefalco 

Only partially. We [replaced `boost::string_view` with `boost::core::string_view`](https://github.com/boostorg/beast/issues/2417).

I wasn't aware of a desire to also get rid of `BOOST_USE_STD_STRING_VIEW` - for which I never did impact analysis.

Checking back in history suggests that is no longer a realistic desire to support standalone ASIO. Therefore, I so no immediate reason to avoid tie ourselves to Boost Core string_view. In terms of compatibility it is already the Rosetta Stone.

It seems a little impact analysis is all that's needed here.

**Comment by eiderdaus** [comment]
The message `"BOOST_BEAST_USE_STD_STRING_VIEW is deprecated, use BOOST_NO_CXX17_HDR_STRING_VIEW instead"` does not make much sense. Defining or undefining `BOOST_NO_CXX17_HDR_STRING_VIEW` will not bring back `BOOST_BEAST_USE_STD_STRING_VIEW`'s behavior which has been removed obviously. Also it is my understanding whether `BOOST_NO_CXX17_HDR_STRING_VIEW` is defined should be determined by Boost's build system and nothing a user should tamper with. A better message would be `"BOOST_BEAST_USE_STD_STRING_VIEW does not work anymore, stop using it"`.
