### ISSUE TITLE
 how to set up a WebSocket proxy to the VNC server to support noVNC 

### ISSUE THREAD

**Issue by yanzixiang** [boostorg/beast#2371]
https://github.com/novnc/noVNC/blob/master/docs/EMBEDDING.md

**Comment by madmongo1** [comment]
Thanks for the query. Are you able to provide more information on what you are trying to do?
Are you saying that you want to write a websocket proxy?

**Comment by yanzixiang** [comment]
> Are you able to provide more information on what you are trying to do? Are you saying that you want to write a websocket proxy?
I want to use beast to replace websockify, 
https://github.com/novnc/websockify

**Comment by madmongo1** [comment]
OK, this looks reasonably straightforward.
