### ISSUE TITLE
websocket_stream  accept/async_accept have no way to set response fields.

### ISSUE THREAD

**Issue by microcai** [boostorg/beast#2377]
for regular http response, async_write accept a response argument.
for websocket  accept, which in-turn will send a 101 response, have no way to set additional header fileds.

**Comment by vinniefalco** [comment]
https://www.boost.org/doc/libs/1_78_0/libs/beast/doc/html/beast/using_websocket/decorator.html

**Comment by microcai** [comment]
That's too complicated ...
anyway, thanks!
