### ISSUE TITLE
Flawed initialization concept for BodyWriter

### ISSUE THREAD

**Issue by RoiEXLab** [boostorg/beast#2392]
### Version of Beast

1.78.0 (latest)

### The Problem

So I wrote a custom `BodyWriter` that allows to compress data on the fly using the HTTP `Content-Encoding` mechanism. This means the `BodyWriter` has to conditionally set the response headers to `gzip` or `deflate` in this case, based on what the HTTP client actually supports. This is what the current layout currently looks like:

```c++
class custom_body::writer {
  value_type& _value;

 public:
  using const_buffers_type = boost::asio::const_buffer;

  template <bool isRequest, class Fields>
  writer(boost::beast::http::header<isRequest, Fields>& header, value_type& value):  _value{value} {
    if (value.isGzip()) {
      header.insert(field::content_encoding, "gzip");
    } else if (value.isDeflate()) {
      header.insert(field::content_encoding, "deflate");
    }
  }

  void init(boost::system::error_code& ec) noexcept {
    ec = {};
  }

  boost::optional<std::pair<const_buffers_type, bool>> get(boost::system::error_code& ec) {
    // compressing code
  }
};
```

However when I recently stumbled over [the official documentation of `BodyWriter`](https://www.boost.org/doc/libs/1_78_0/libs/beast/doc/html/beast/concepts/BodyWriter.html) it clearly stated that:
> The writer shall not access the contents of h or v before the first call to init, permitting lazy construction of the message. 

For the constructor of the writer class. The only way to be compliant with this requirement is to use type-erasure of some sort (std::any, std::function, etc.)due to the `template <bool isRequest, class Fields>` being used for the header; as it can't be stored as a regular member. This is really inconvenient because the type information is lost. In case the documentation has a legitimate reason for this requirement, a potential solution to this would be to pass the headers to `init` and/or `get` as an argument directly instead of passing it to the constructor.

What are your thoughts on this?

**Comment by vinniefalco** [comment]
Yes I agree the Body concept (plus the reader and writer) have design flaws.

**Comment by RoiEXLab** [comment]
> Yes I agree the Body concept (plus the reader and writer) have design flaws. You are probably better just writing the header using beast, but serializing the body yourself using a buffer-based approach instead of trying to make it work with the Body concept.

Yeah, writing the headers 'by-hand' is what I ended up doing. I'm not exactly sure how you imagine a buffer-base approach. Somehow writing to the stream directly I suppose? I ended up using the `Body` concept just to implement chunked transfer encoding (because the size is unknown) so I don't have to change the code that previously sent a plain string too much.

**Comment by vinniefalco** [comment]
We can't change this for now but I am working on some new concepts in a new library.

**Comment by RoiEXLab** [comment]
@vinniefalco By "new library" do you mean something completely independent of beast or more like beast 2.0?

**Comment by vinniefalco** [comment]
Completely independent of beast

**Comment by RoiEXLab** [comment]
@vinniefalco Thanks for your time and I'm looking forward to it 👍🏼
