### ISSUE TITLE
How to upgrade a SSL based ASIO socket to Beast WebSocket?

### ISSUE THREAD

**Issue by bala-thenightskycoder** [boostorg/beast#2400]
Can you provide me an example code where the async SSL-based ASIO socket is moved to the beast socket to open up the websocket?

**Comment by madmongo1** [comment]
Sure, this is possible with latest asio as asio ssl streams became moveabke in boost 1.68

**Comment by bala-thenightskycoder** [comment]
Any example code? I use boost 1.75. Dman sure this is possible.

**Comment by madmongo1** [comment]
I can knock something up when I get home

**Comment by bala-thenightskycoder** [comment]
Thank you so much:)

**Comment by bala-thenightskycoder** [comment]
One thing I want to mention, I did the handshake using the Boost ASIO library and then moved the socket to Beast. After moving, I just have code to accept() and read() asynchronously.

**Comment by bala-thenightskycoder** [comment]
seems like I am getting uncaught exception when moving the socket:

`class webSocketConnection {
        public:
            using con_handle_t = std::list<std::shared_ptr<Connection>>::iterator;
            boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>> web_socket;
            
            webSocketConnection(    con_handle_t con_handle, 
                                    boost::asio::ssl::context& ssl_context ) :
                                web_socket(std::move(con_handle->get()->ssl_socket.next_layer()), ssl_context) { web_socket.accept(); }
    };
`

`                capegen::webSocketConnection webSocketConnectionObj(con_handle, ssl_context);
`

**Comment by bala-thenightskycoder** [comment]
seems like If I do a handshake using the Boost ASIO and then move the socket to Beast one is not working. 

A simple HTML to test the code:


`<!DOCTYPE HTML>

<html>
   <head>
      
      <script type = "text/javascript">
         function WebSocketTest() {
            
            if ("WebSocket" in window) {
               alert("WebSocket is supported by your Browser!");
               
               // Let us open a web socket
               var ws = new WebSocket("ws://localhost:8082");
				
               ws.onopen = function() {
                  
                  // Web Socket is connected, send data using send()
                  ws.send("Message to send");
                  alert("Message is sent...");
               };
				
               ws.onmessage = function (evt) { 
                  var received_msg = evt.data;
                  alert("Message is received...");
               };
				
               ws.onclose = function() { 
                  
                  // websocket is closed.
                  alert("Connection is closed..."); 
               };
            } else {
              
               // The browser doesn't support WebSocket
               alert("WebSocket NOT supported by your Browser!");
            }
         }
      </script>
		
   </head>
   
   <body>
      <div id = "sse">
         <a href = "javascript:WebSocketTest()">Run WebSocket</a>
      </div>
      
   </body>
</html>`

**Comment by bala-thenightskycoder** [comment]
seems like the boost ASIO handshake is not working if we open up a web socket connection from the client. Below client code I used in browser to test.

<!DOCTYPE HTML>

<html>
   <head>
      
      <script type = "text/javascript">
         function WebSocketTest() {
            
            if ("WebSocket" in window) {
               alert("WebSocket is supported by your Browser!");
               
               // Let us open a web socket
               var ws = new WebSocket("ws://localhost:8082");
				
               ws.onopen = function() {
                  
                  // Web Socket is connected, send data using send()
                  ws.send("Message to send");
                  alert("Message is sent...");
               };
				
               ws.onmessage = function (evt) { 
                  var received_msg = evt.data;
                  alert("Message is received...");
               };
				
               ws.onclose = function() { 
                  
                  // websocket is closed.
                  alert("Connection is closed..."); 
               };
            } else {
              
               // The browser doesn't support WebSocket
               alert("WebSocket NOT supported by your Browser!");
            }
         }
      </script>
		
   </head>
   
   <body>
      <div id = "sse">
         <a href = "javascript:WebSocketTest()">Run WebSocket</a>
      </div>
      
   </body>
</html>

**Comment by bala-thenightskycoder** [comment]
OK. I am confused. I will just wait for your example program.

**Comment by bala-thenightskycoder** [comment]
boost::beast::websocket::stream<boost::asio::ssl::stream<boost::asio::ip::tcp::socket>> web_socket;

Is the above code correct to define a web socket?

How do we move the SSL request and aync_accept on the Beast side?

Drilling down, I believe I face trouble in the moving request, accepting WebSocket connection.

**Comment by vinniefalco** [comment]
Is this resolved?
