### ISSUE TITLE
Boost Beast Http SSL Async Server | Example

### ISSUE THREAD

**Issue by zavoyevatyel** [boostorg/beast#2407]
### Version of Beast

322

### Steps necessary to reproduce the problem

This code shuts down the server 30 seconds after sending the request.:
https://www.boost.org/doc/libs/1_79_0/libs/beast/example/http/server/async-ssl/http_server_async_ssl.cpp

Because this line do it:
beast::get_lowest_layer(stream_).expires_after(std::chrono::seconds(30));

It just needs to close the socket, not server.

### All relevant compiler information

MSVC 2022

**Comment by sehe** [comment]
The quoted code causes a particular connection (`session`) to be closed, not the server. How do you observe the server is shutdown?

**Comment by vinniefalco** [comment]
An unhandled exception would take the server down

**Comment by sehe** [comment]
That's what I was thinking, so I was hoping that requesting more information can help @zavoyevatyel realize the origin of such an exception.

**Comment by zavoyevatyel** [comment]
I just compile the code and make a request from the browser. After 30 seconds the server shuts down. 
I didn't add any code

**Comment by sehe** [comment]
Is there any output? Can you see whether exceptions are thrown by attaching a debugger to the server?

**Comment by vinniefalco** [comment]
have you seen `BOOST_CURRENT_LOCATION`? https://www.boost.org/doc/libs/1_77_0/boost/assert/source_location.hpp

**Comment by zavoyevatyel** [comment]
I found it. I used crt file content but it needs pem files. Thanks for effort
