### ISSUE TITLE
how to get useragent/referer/from fields of websocket 

### ISSUE THREAD

**Issue by RavikumarTulugu** [boostorg/beast#2412]
how to access useragent/referer/from fields on a websocket .

**Comment by madmongo1** [comment]
Use the alternate form of async_accept. You provide a request object, which is filled in during the accept operation.

https://www.boost.org/doc/libs/1_79_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/async_accept/overload3.html

You can get the header fields from there.

**Comment by RavikumarTulugu** [comment]
Thank you for the reply. This is very important for us.

**Comment by RavikumarTulugu** [comment]
it would be great if you can point me to a working code. The req parameter in the async_accept is supposed to be both in out ?? i was giving an empty req uninitialized and my accept started failing. surely, my usage is wrong.  I started seeing this error . 
"The WebSocket handshake method was not GET". i commented out for now and reverted back.

**Comment by sehe** [comment]
I have a complete example here: https://stackoverflow.com/a/71246212/85371

**Comment by RavikumarTulugu** [comment]
Thanks for the code, it worked fine.
