### ISSUE TITLE
session destructor not getting invoked consistently 

### ISSUE THREAD

**Issue by RavikumarTulugu** [boostorg/beast#2413]
we have an async ssl server. every thing works fine. what we are seeing is that there is no consistency on the session destructor getting invoked. it randomly gets invoked. Our session object is pretty huge and it can quickly bring down our server. Wonder any one observed/reported this already . Please advise. 
Thanks

**Comment by madmongo1** [comment]
You have undefined behaviour. Most likely a race condition or something surviving longer than you think holding on to a shared_ptr.

I have limited information as I only have the above paragraph to go on.

My suggesting would be to think about reducing the "pretty huge" session object into more composable pieces.
You may want to look at handler tracking (see boost asio docs) and logging object lifetimes.

**Comment by RavikumarTulugu** [comment]
closing this as not seeing this anymore.
