### ISSUE TITLE
use boost::core::string_view

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#2417]
We should use `boost::core::string_view` instead of `boost::utility::string_view`, because it has better interoperability with `std::string_view`. However, before we make this change public we need to write a short matrix of tests that mix the three principle string views and the standard string `std::string`, `std::string_view`, `boost::utility::string_view`, `boost::core::string_view` in order to understand what compatibility problems users may experience (if any).

**Comment by sehe** [comment]
I've created a whole slew of test-cases to excavate differences between various implementations. These are not up to standard for inclusion, but perhaps someone sees some useful bits?

Goggles advised: https://github.com/sehe/beast/blob/core_string_view/test/beast/core/string.cpp

Note it uses c++17 for brevity - not in the last place to be able to compare with c++17 std::string_view, but liberally using contexpr and traits that are specific to c++17.

**Comment by sehe** [comment]
@vinniefalco Just realized another loose end: despite `std::string_view` compatibility, `core::string_view` still doesn't support some templated free functions, like

 - std::quoted (too bad I guess)
 - asio::buffer
 - asio::const_buffer [demo](https://compiler-explorer.com/z/TxPx4qKv8)

The latter are a shame. They circle back to your discussion about custom buffer types in boost-http somewhat.

**Comment by sehe** [comment]
Status: 

 - IMO This should remain draft until https://github.com/boostorg/core/issues/110 lands, to avoid inconveniencing Beast users with breaking change in their own code using `beast::string_view`

 - @vinniefalco / @pdimov Do you see any mechanism to fix the compatiblity with std::string_view for free function templates (std::quoted, asio::buffer and possible others in thirdparty code)? Perhaps there's already a niebloid like `beast::buffer_bytes` that I'm not aware of for this?

**Comment by pdimov** [comment]
What are we supposed to do about `std::quoted` or `asio::const_buffer`?

**Comment by pdimov** [comment]
It has been merged to master. Next release, well that's another story.

We can't change `std::quoted`, so I'm not sure what we can possibly do about it.

**Comment by vinniefalco** [comment]
What the heck is `std::quoted`

**Comment by pdimov** [comment]
It's a manipulator that quotes strings on op<< and unquotes them on op>>. https://godbolt.org/z/3srYsno9K

**Comment by sehe** [comment]
@pdimov That's awesome. Yeah, I had expected the merge to be visible on boostorg/core#110 but that wasn't a PR in the first place. Are you saying that things that are on master do not /automatically/ get pulled into the superproject next release?

**Comment by pdimov** [comment]
Yes, whatever's on master automatically goes into the next release. But the release itself is months from now.

**Comment by sehe** [comment]
That's fine, the Beast change would be in the same release. As long as they go together or in the right order, I'm not in a hurry.

**Comment by raidenluikang** [comment]
Why not auto detected std::string_view when __cplusplus >= 201703L ?

Or

Standard required [__cpp_lib_string_view >= 201606L]( https://en.cppreference.com/w/cpp/string/basic_string_view )
