### ISSUE TITLE
Boost.org is down. 

### ISSUE THREAD

**Issue by richardbentMicrosoft** [boostorg/beast#2419]
Me and my team is trying to access Boost.org but it looks like the domain has not been renewed.

![53](https://user-images.githubusercontent.com/104841606/166462243-1aed76b4-e5d7-4142-b808-10f681d176a2.PNG)
.

**Comment by sehe** [comment]
Thanks for the report. 

This is being worked on. European VPN might help out for now - I use OpenDNS and Cloudflare 1.1.1.1 and still have access.

**Comment by sehe** [comment]
This should have been sorted out. Flush DNS cache and restart browser. Note that it could take up to 24 hours for DNS updates to replicate world-wide.
