### ISSUE TITLE
Provide type-erased HTTP generation facility

### ISSUE THREAD

**Issue by sehe** [boostorg/beast#2421]
Referring to earlier discussion such as #1139 there is a need for interfaces that do not depend on the static type of the http message object (which is templated).

@vinniefalco made a prototype here: 

> Have a look at these:
> 
> https://github.com/vinniefalco/BeastLounge/blob/44194d746fdb37376ddd998b888389eff7c27ef7/src/http_generator.hpp
> https://github.com/vinniefalco/BeastLounge/blob/44194d746fdb37376ddd998b888389eff7c27ef7/src/buffers_generator.hpp#L128
> 
> Usage:
> 
> https://github.com/vinniefalco/BeastLounge/blob/44194d746fdb37376ddd998b888389eff7c27ef7/src/http_service.cpp#L157
> https://github.com/vinniefalco/BeastLounge/blob/44194d746fdb37376ddd998b888389eff7c27ef7/src/http_connection.cpp#L147
>

**Comment by vinniefalco** [comment]
I love it!

Conflict of interest disclosure: I am the author.

**Comment by sehe** [comment]
Reflecting discussion on cppslack:

 - the generator is intended as an ephemeral type (storage cannot be re-used because of one-time BodyWriter types, e.g.)
 - the samples should be refactored to use the new facility

@vinniefalco New questions:

`http_generator` already exposes `keep_alive` to interrogate the type-erased message. Should serializer features also be exposed (as long as they don't depend on message template parameters). Specifically `limit(size_t)` could be required/useful? Perhaps even `split`/`is_header_done`?

**Comment by sehe** [comment]
Having looked more closely at `limit` I'm going to vote against (it might be more relevant already to tune the `max_buf` parameter).

As for `split`/`is_header_done` I'm also gravitating towards "don't reimplement serializer interface", but maybe I don't understand the `Expect: 100-continue` use-case fully, so I'd like to check.

**Comment by vinniefalco** [comment]
This is starting to sound like more trouble than it is worth. The current examples don't handle 100-continue (or do they?)

**Comment by sehe** [comment]
Indeed ("At least none of the examples require it."). So I'd skip that until maybe someone in the future sells the use-case

**Comment by sehe** [comment]
I think so, except maybe for dreams of better docs surrounding it. I guess that having all the examples use it is the most important kind of documentation, but as an end user I'd love to see the same in the overview documentation.
