### ISSUE TITLE
how to close socket properly on server side ??  

### ISSUE THREAD

**Issue by RavikumarTulugu** [boostorg/beast#2424]
how to properly close connection on server side ?? 
our server is an async ssl server.  our close logic is like below 
on receiving "closed" error in read handler, we post ( boost::asio::post )  an event to the io context and in the post handler we call ws.close(). close throws an exception and the server crashes.  The exception code is 125 ( operation cancelled ) . 

```c++
close(close_reason const& cr)
 {
    static_assert(is_sync_stream<next_layer_type>::value,
         "SyncStream type requirements not met");
     error_code ec;
     close(cr, ec);
     if(ec)
         BOOST_THROW_EXCEPTION(system_error{ec});   <---------- origin of exception. 
 }
```

**Comment by RavikumarTulugu** [comment]
sorry being vague, the error in our case we are relying on  to close the connection is "boost::beast::websocket::error::closed" , in this case the client is a browser tab and the event happens on the close of the tab. our code is in fact based on the example mentioned by you. it is not clear to me as in why close is throwing exception.

**Comment by sehe** [comment]
The example would not try to `close` the websocket after receiving `error::closed` (because of the `fail` in `on_read`).

The server examples all handle `error::closed` without calling `close`, see e.g. https://www.boost.org/doc/libs/master/libs/beast/example/websocket/server/async-ssl/websocket_server_async_ssl.cpp, instead relying on destructors to do the right thing. Same for the chat-multi example.

**Comment by RavikumarTulugu** [comment]
Returning from the read handler will automatically invoke the session destructor unless there are shared pointers floating around . Destructor will automatically close the network connection as well. The documentation and examples floating around are misleading , the latest beast library simplifies lot of things and reduces a lot of code. Our case was that a reference was floating around in a container leading to half closure of the socket.

**Comment by sehe** [comment]
Glad you were able to get it sorted! Of you have suggestions on how to improve the examples (e.g. what specifically was misleading) we'd love to hear.

Even if it is anti-patterns that are floating around in books/other websites, sometimes it can be worth calling it out with a warning in the Beast documentation.

**Comment by RavikumarTulugu** [comment]
https://github.com/boostorg/beast/issues/1127
I was totally misled by the above discussion , I was exactly facing the same issue .  This popped up in my google search. Also the code was pretty old and the api was changed and would not compile with the new library.
