### ISSUE TITLE
Zip64 with zlib

### ISSUE THREAD

**Issue by raumod** [boostorg/beast#2450]
Hello!!

I was wondering if the [zlib](https://github.com/boostorg/beast/tree/develop/include/boost/beast/zlib) library included in this repository supports Zip64??

### Version of Beast
Latest version: [boost-1.79.0](https://github.com/boostorg/beast/releases/tag/boost-1.79.0)

Regards

**Comment by vinniefalco** [comment]
It does not. In fact it doesn't even support zip archives, because the version of zlib in Beast implements the _deflate_ algorithm and not the wrapper that surrounds it. This is the component necessary for compressed websocket messages. I suppose the name zlib is misleading.

**Comment by raumod** [comment]
thanks for your quick reply. I will close this issue 😉
