### ISSUE TITLE
Visual Studio CML instructions are out of date

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#2460]
The README.md does not list the correct instructions for generating a Visual Studio project file. See: https://github.com/boostorg/json/blob/develop/README.md#visual-studio-solution

**Comment by alandefreitas** [comment]
Doesn't CMake already come with a proper toolchain for this generator like any other generator? I've never seen any other boost or non-boost projects with specific instructions for Visual Studio. 

Is there still anything special about Visual Studio? I thought this was just regular CMake usage.

**Comment by vinniefalco** [comment]
No idea but I like having the instructions so I can copy and paste them. Since 2022 is not robust enough we can list 2019. And at some point we will want to modernize the CML for Beast but that can wait.

**Comment by ashtum** [comment]
Addressed in https://github.com/boostorg/beast/pull/2787.
