### ISSUE TITLE
No pong sent when reconnecting

### ISSUE THREAD

**Issue by AdilLayach** [boostorg/beast#2473]
### Version of Beast
1.66

### Steps necessary to reproduce the problem
I'm trying to implement a WebSocket client using boost::beast. The first connection and data exchanges are fine.
And when I close the server and relaunch it again, the connection is properly established again.
However, it is only for a few minutes as the client doesn't reply to Ping requests anymore.

In my Connect function (that I call to connect the first time and reconnect when a disconnection is detected), I properly reset the io_context and the websocket::stream:
```
FContext.restart();
FWebsocket.emplace(FContext);
...
net::connect(FWebsocket->next_layer(), endpoints);
```

What am I missing?

Note: I've also added the Ping mechanism shown in the early advanced-server example as I need it in my client.

### All relevant compiler information
Compiling with cygwin (g++ (GCC) 10.2.0)

**Comment by vinniefalco** [comment]
Are you using synchronous or asynchronous I/O functions?

**Comment by AdilLayach** [comment]
Hello Vinnie,

Thank you for your reply.

I'm using the sync connect/handshake. The others I/O functions (read, write, close, ping) are async.

**Comment by vinniefalco** [comment]
You cannot mix sync and async

**Comment by AdilLayach** [comment]
Hello, 

Thank you for the tip. I thought we could as long as we don't mix them in //.
So I tried to replace my sync connect/handshake with their async version, but I still have the issue.

I'll try to write a minimal code reproducing the issue asap. But if you have any other idea in the meantime let me know

Thank you for the support

**Comment by AdilLayach** [comment]
Yep I take care of this as well
(the minimal code is coming, sorry for the delay)

**Comment by AdilLayach** [comment]
Ok so I built a minimal code and it turns out... the problem is not present
In fact, I was basically blocking the thread handling the IO functions due to some silly line of codes...

Anyway, Thanks Vinnie for the reactivity! Much appreciated!
