### ISSUE TITLE
Add json_body example

### ISSUE THREAD

**Issue by sehe** [boostorg/beast#2474]
We need a json_body sample implementation to elaborate the sketch in https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/using_http/custom_body_types.html#beast.using_http.custom_body_types.value_type

```c++
#include <boost/json/stream_parser.hpp>

struct Body
{
    using value_type = boost::json::value;

    class reader;
    class writer;
};```

**Comment by sehe** [comment]
There's already work going on here https://github.com/boostorg/beast/pull/2381

**Comment by klemens-morgenstern** [comment]
See also #2511. 

Can we close this, so we don't have three places where json_body work happens?

**Comment by sehe** [comment]
@klemens-morgenstern  I guess :) I didn't start the third place, although I like that you named the example folder "body" to allow for the other examples to fit there
