### ISSUE TITLE
g++-4.8 support

### ISSUE THREAD

**Issue by alandefreitas** [boostorg/beast#2481]
The [posix (gcc-4.8, 11, ubuntu-20.04, ubuntu:16.04, g++-4.8, true)](https://github.com/boostorg/beast/runs/7205673790?check_suite_focus=true#logs) workflow has been failing [with](https://github.com/boostorg/beast/runs/7205673790?check_suite_focus=true#step:10:1533):

```console
In file included from ./boost/asio/spawn.hpp:904:0,
                 from libs/beast/test/extras/include/boost/beast/test/yield_to.hpp:15,
                 from libs/beast/test/beast/websocket/test.hpp:20,
                 from libs/beast/test/beast/websocket/accept.cpp:16:
./boost/asio/impl/spawn.hpp: In member function 'virtual void boost::asio::detail::spawned_fiber_thread::resume()':
./boost/asio/impl/spawn.hpp:204:64: error: passing 'boost::asio::detail::spawned_fiber_thread::fiber_type {aka boost::context::fiber}' as 'this' argument of 'boost::context::fiber boost::context::fiber::resume() &&' discards qualifiers [-fpermissive]
     callee_ = BOOST_ASIO_MOVE_CAST(fiber_type)(callee_).resume();
```

I don't know when this error was introduced. It [fails in](https://github.com/boostorg/beast/actions) some recent runs that were only touching the documentation. 

I think I saw in some other library that GCC 4.8 doesn't work well with `&&` `this` qualifiers, which might be the problem.

**Comment by vinniefalco** [comment]
did it ever work?

**Comment by klemens-morgenstern** [comment]
This looks like an asio issue - is it still around with 1.80?

**Comment by klemens-morgenstern** [comment]
The CI passes now with a ubuntu update on develop - is this still an issue?
