### ISSUE TITLE
On websocket close, catch private status code

### ISSUE THREAD

**Issue by jbaumgarten** [boostorg/beast#2485]
Sir, Madam,

I'm using boost library, and beast library for websockets.
I need to catch private status code when the connexion is closed.

I read again and again the headers, but I don't find a way to do it.
Did I miss something?

Yours sincerely,
Julien

**Comment by vinniefalco** [comment]
Call `websocket::stream::reason` after receiving `error::closed` to get the custom code:
https://www.boost.org/doc/libs/1_79_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/reason.html
