### ISSUE TITLE
Not able to include "example/common/root_certificates.hpp"

### ISSUE THREAD

**Issue by dpsingh28** [boostorg/beast#2494]
Hi
I installed Boost 1.80.0 using the following instructions, [https://github.com/boostorg/wiki/wiki/Getting-Started%3A-Overview](https://github.com/boostorg/wiki/wiki/Getting-Started%3A-Overview), but I am not able to include the example root certificates in my node.

I am working on a docker container with following specs:

- Ubuntu 18.04
- C++ 17

I am aiming to setup an SSL websocket connection to query some data from a server. I am following this example: [https://www.boost.org/doc/libs/develop/libs/beast/example/websocket/client/sync-ssl/websocket_client_sync_ssl.cpp](https://www.boost.org/doc/libs/develop/libs/beast/example/websocket/client/sync-ssl/websocket_client_sync_ssl.cpp)

**Things I have tried to resolve my issue:**
- Specify Boost 1.80.0 in the CMakeLists.txt
- export LD_LIBRARY_PATH environment variable to include the boost 1.80.0 installation directory

**ERROR snap**:
![image](https://user-images.githubusercontent.com/93106483/183336733-e4f4ce40-9682-46bc-99a2-e26a3f9ac5d8.png)

Are there any other things I can try?

**Comment by vinniefalco** [comment]
root_certificates.hpp is part of the examples not part of the Beast library. You need to copy the file into your project.

**Comment by dpsingh28** [comment]
Oh ok. Thanks, it worked!
