### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by SC-One** [boostorg/beast#2506]
## Error on handshake (ssl)
I got an error that I really dont know what can i do anymore , Error:
``` handshake: certificate verify failed (SSL routines, tls_process_server_certificate) [asio.ssl:337047686] ```

### Version of Beast : 
_BOOST_BEAST_VERSION 322_

### Steps necessary to reproduce the problem
built on android and work fine with http , just when I wanna use ssl and some custom handshake , I facing mentioned error.
### All relevant compiler information
clang-9
(extra info , android api level 21 , arch abi: x86)

#### Also tried:
- [x] added custom path(pointing to CA folder in android devices) to verify path
- [x] used default verify path
- [x] changed verify method to verify_none , and it worked fine.
- [x] changed verify callback to host_... and rfc28... , and my custom ...
- [x] and some extra trying solutions. 
- [x] used [root_certificate](https://github.com/boostorg/beast/blob/develop/example/common/root_certificates.hpp) too (just for test)

**Comment by madmongo1** [comment]
Do other clients verify successfully? It looks as if the certificate is invalid?

**Comment by SC-One** [comment]
> Do other clients verify successfully? It looks as if the certificate is invalid?

Yeah (this test is on google.com) , I tested on any website and it return **certificate verify failed**

**Comment by SC-One** [comment]
Ok I found it after wasting a lot of  days ... 
file name hashing was different in **android** vs **openssl**. 

@madmongo1 .
