### ISSUE TITLE
web socket async server example is not working

### ISSUE THREAD

**Issue by audi0615** [boostorg/beast#2507]
Hi.

I'm trying to test the web socket async server example, but I got an error on "net::dispatch(...." and the error says "no instance overloading....". my boost library version is 1.78.

I just copied and pasted the example and i have no idea how to fix it. Please help me.

```
    // Get on the correct executor
    void
    run()
    {
        // We need to be executing within a strand to perform async operations
        // on the I/O objects in this session. Although not strictly necessary
        // for single-threaded contexts, this example code is written to be
        // thread-safe by default.
        net::dispatch(ws_.get_executor(),
            beast::bind_front_handler(
                &session::on_run,
                shared_from_this()));
    }
```

**Comment by madmongo1** [comment]
Did you copy/paste the example exactly, or have you modified it since the copy/paste?

Can you show the error message emitted by the compiler please?

**Comment by audi0615** [comment]
dear madmongo1

i just copy/pasted the example and modified nothing.
please refer to following error message.

![2022-08-24_18-29-52](https://user-images.githubusercontent.com/96812644/186384030-0a28b5ec-3497-4caa-a00c-f2ff7bc9f142.png)

**Comment by madmongo1** [comment]
Is this actually failing to compile? The picture is showing an intellisense lookup failure.

**Comment by audi0615** [comment]
Wow. It compiles without problems. but still i get intellisense error. 
Thank you so much madmongo1.

**Comment by klemens-morgenstern** [comment]
Is this still an open issue?
