### ISSUE TITLE
Long compilation time with microsoft compiler (v143)

### ISSUE THREAD

**Issue by stavikpetr** [boostorg/beast#2528]
Hello, so just recently, we adopted beast for websocket client in our codebase. So far so good, it is working quite well, but I noticed that especially SSL async client just takes **_a lot_** of time to compile. In debug mode, one single file takes about 20 seconds to compile, which is about fifth of the whole time of one of our binaries.

Just to confirm that this is not related to our codebase, I took the simple ssl async client from the examples in this repo. For debug, around 21 seconds, for release mode, around 30 seconds, which is quite crazy. (This was also the first time i had to use /bigobj option during compilation)

Anything i can do with that? Or it's just the way it is ? :/

Boost version: 1.78

**Comment by klemens-morgenstern** [comment]
That's just the way it is, as of now, beast makes heavy use on template. I'll leave the issue open,because I want to make some improvements here.

**Comment by stavikpetr** [comment]
Ok thanks for the info.

**Comment by stavikpetr** [comment]
Ok thanks for the info.

**Comment by klemens-morgenstern** [comment]
What completion method are you using, if I may ask? Lambdas as callbacks?

**Comment by stavikpetr** [comment]
Sure, I am using the `beast::bind_front_handler` wrapper everywhere.

**Comment by vinniefalco** [comment]
You need to be careful to structure your source code so that you don't end up including all asio and beast even in the translation units that don't need it. A little bit of type erasing, and some adjustments to your business logic APIs will help.

**Comment by matthias3333** [comment]
Will that be fixed in Beast 2?

**Comment by vinniefalco** [comment]
It will be better yes but openssl and asio are big libraries, they need to be integrated into a project carefully. if you structure things right you can have your own library containing the network code which is built separately and might take a minute to build (but not require changes often) and then the calling code which will be fast to compile and link against the separate network lib.

**Comment by ashtum** [comment]
@stavikpetr Could you please close the issue if your problem has been resolved?
