### ISSUE TITLE
is boost::beast::tcp_stream's expires_after also work for boost::asio::read(boost::beast::tcp_stream)

### ISSUE THREAD

**Issue by xtayaitak** [boostorg/beast#2531]
beast::tcp_stream has async_read_some function buy But has no async_read function.
so I use boost::asio::read for beast::tcp_stream。
I don't know if the timeout and rate limit also work .

**Comment by klemens-morgenstern** [comment]
It works if you use asio::async_read. The sync versions don't support timeouts.
