### ISSUE TITLE
Error: handshake: wrong version number (SSL routines) [asio.ssl:167772427]

### ISSUE THREAD

**Issue by NaliniElangovan** [boostorg/beast#2536]
Hi Team,
Trying to connect the web-socket server by using boost libraries.  

I am facing the error like this, 
Error: handshake: wrong version number (SSL routines) [asio.ssl:167772427] 

Please help me out to solve this problem,

**Comment by vinniefalco** [comment]
Have you seen https://github.com/boostorg/beast/issues/1776 and
https://stackoverflow.com/questions/59157258/boost-asio-ssl-through-proxy-handshake-wrong-version-number ?

**Comment by ashtum** [comment]
@NaliniElangovan Could you please close the issue if your problem has been resolved?
