### ISSUE TITLE
Is boost::beast::tcp_stream's expires_after only work for single chain of asynchronous operations ?

### ISSUE THREAD

**Issue by xtayaitak** [boostorg/beast#2541]
My protocal is full duplex.
So the async write may called before async_read is finished.

can below pseudo-code code's "expires_after" also work correctly?

expires_after(60)
async_read_some(xxx)
expire_afater(20)
async_write(xxx)

**Comment by klemens-morgenstern** [comment]
I don't know what correct means based on your brief description.

**Comment by xtayaitak** [comment]
@klemens-morgenstern 
I'm not sure if expires_after can be called repeatedly.

**Comment by klemens-morgenstern** [comment]
Thanks for the clarification. yes it can.
