### ISSUE TITLE
Websocket TCP packets waiting for ACK before sending.

### ISSUE THREAD

**Issue by AWilco** [boostorg/beast#2545]
This may be more of a "how to use Boost / Beast" rather than "there's a bug in Beast", so if this is O/T I'd be grateful if you could point me in the direction of a better forum. I'm using beast v306 so if upgrading might help I can try that. It may also be a more generic TCP socket question and also O/T.

I'm running a websocket connectiom to a chrome web page. I want to send updates every 50ms but the individual messages are being coalesced and arriving as a batch every 50 or 100ms. Looking at Wireshark output:

![](https://user-images.githubusercontent.com/585380/196401965-69889643-6108-45ee-98fc-2f4385e46d78.png)

My limited understanding of TCP tells me that the websocket server (at 10.55.61.198) is waiting for an ACK from the client. At the highlighted point the delay before the ACK comes back jumps from 50ms to 100ms, and so rather than 1 msg every 50ms it now sends 2 combined into a single TCP packet every 100ms. My understanding of the window parameter is that we should be able to send 4095 bytes before the next ACK?

Is there any boost /tcp configuration I can do to avoid having the messages combined? I have read that this could be due to network congestion, however the nextwork isn't doing a lot at this point. However if I need to look into that further I'd be grateful if you could point me in the right direction.

**Comment by klemens-morgenstern** [comment]
How is this related to beast? is your server written with beast?

**Comment by AWilco** [comment]
Reading through my post above gave me the idea to try sending something from the client in order to force a response and allow the server to send more data. However this hasn't worked out.

![](https://user-images.githubusercontent.com/585380/196412700-4c28b246-0a2e-4135-861b-5419cdfc24c0.png)

What now seems to happen is both sides batch up their messages. After an ACK from the beast server to chrome, everything stops for 90ms. Then we start getting little packets from the client (which should be every 20ms). The first of these contains the ACK for the last payload sent by the server (e.g. recevied packet 1089 contains the ACK for packet 1071 allowing the server to then send more data in packet 1091). Why there is a 90ms gap in communication from the client I don't know as it should have data to send. Again any help or direction to better places much appreciated.

**Comment by AWilco** [comment]
Sorry, yes the server is written in Beast. its written using async\_write but I also tried rewriting with a synchronous write, which didn't have any effect.

**Comment by AWilco** [comment]
Further research suggests this is something to do with Network congestion. The problem goes away if I use a hard-wired connection instead of Wifi. I had hoped TCP\_NODELAY on the socket would help resolve the issue. Whilst it does split the messages up into packets there are still pauses of approx 100ms.

Happy for this to be closed as not a Beast issue, but if anyone knew a good place for me to get further information/help that would be appreciated.

**Comment by gunzino** [comment]
@AWilco 

how do you set TCP_NODELAY on beast?

**Comment by AWilco** [comment]
@gunzino That's probably better than my way. Once I have the tcp socket from the web socket listener, I set the socket option using set\_option() before I construct the websocket using it. I didn't see a way to do it once it was moved into the websocket, but your way I think should be okay.

**Comment by AWilco** [comment]
Closing this as it not a beast issue.
