### ISSUE TITLE
How to correctly immediately close websocket stream

### ISSUE THREAD

**Issue by gunzino** [boostorg/beast#2547]
Hello,

I've managed to implement beast to my software, However I experience some rare crashes due to assertion in stream_base.hpp (line 86) when client lose the network connection. 

My disconnect function looks like this:
```
void ProxyWebsocket::disconnect()
{
    if (m_state == STATE_CLOSING || m_state == STATE_NOT_CONNECTED) {
        return;
    }
    auto self = getThis();
    m_state = STATE_CLOSING;
    boost::beast::get_lowest_layer(*(self->ws_)).close();
    ws_->async_close(boost::beast::websocket::normal, [self](const boost::system::error_code& ec) {
        self->m_state = STATE_NOT_CONNECTED;
    });
}
```

The disconnect function is called by the program when there is 2s timeout. Then it should attempt to establish new connection. After async_close is handled and state is set to STATE_NOT_CONNECTED the object declare new ws_ using std::optional::emplace but in very rare situation it seems like the program is searching for deleted ws_ object. If I'm correct the async_close should ensure that other handlers are gonna be called. Should I use different function to close the stream?

Is there difference between get_lowest_layer(*(self->ws_)).close() and get_lowest_layer(*(self->ws_)).socket().close() ?

Thanks !!

**Comment by klemens-morgenstern** [comment]
Which assertion fires? and why are you calling async_close on the websocket after closing the underlying socket?

**Comment by gunzino** [comment]
The assertion is beast/core/detail/stream_base.hpp line 86. That's good question, probably I wanted to be sure that operation handlers are cancelled so ws_ object could be deleted by std::optional.

**Comment by madmongo1** [comment]
If you're keeping track of the connection state (e.g. m_state), it's likely that there is a design error.
With asio io objects you know you're still connected because your read last succeeded. If that fails, this is your signal that you've transitioned to "not connected" state.

**Comment by gunzino** [comment]
@madmongo1 
Seems that could be the issue, I didn't check the error_code in one of the handlers and just called next async_read_some.
