### ISSUE TITLE
Websockets: How to deal with Flow Control/Backpressure #1159

### ISSUE THREAD

**Issue by echen333** [boostorg/beast#2565]
How do the boost beast websocket handle flow control?

I saw from https://www.boost.org/doc/libs/1_80_0/libs/beast/doc/html/beast/design_choices.html:

> Leave important decisions, such as allocating memory or managing flow control, to the user.

But how does the user actually deal with flow control? As in, if the user is taking a long time to deal with incoming information, the websocket data is then stored in a buffer, but how could the size of this buffer be accessed?

Say this is my on_read function for my websocket.
```
  int count = 0;
  const auto& on_read2 = [&count](boost::json::object& json, size_t val) {
    LOG(INFO) << "Read: \n" << PrettyPrint(json);
    LOG(INFO) << val << "\n";
    if (count <= 5) {
      std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    }
    count++;
  };
```

```
void Sync(const T& on_read){
  stream = std::unique_ptr<
      boost::beast::websocket::stream<boost::beast::ssl_stream<boost::beast::tcp_stream>>>
      secure_websocket_;
  stream->read(buffer_);

}
```

Websocket streams are using the boost beast implementation with TCP.

**Comment by vinniefalco** [comment]
>  if the user is taking a long time to deal with incoming information, the websocket data is then stored in a buffer,

Well no. A Beast Websocket does not buffer incoming data.

**Comment by echen333** [comment]
> Well no. A Beast Websocket does not buffer incoming data.

How is it dealt with then? From my tests, it seemed like you still get older data sent even if you are slow to process.

**Comment by vinniefalco** [comment]
TCP/IP is first in first out, reliable transmission. That means that data is received in exactly the order it is sent, and nothing is lost. You expect websocket and TCP/IP to throw away data if it is not received by the application within a certain amount of time? You have to write code to make that happen if you want that feature.

**Comment by echen333** [comment]
Thanks for the help. Is there a way to see how many requests the application still has left to process?

**Comment by vinniefalco** [comment]
> Is there a way to see how many requests the application still has left to process?

No. I think you might want to learn or brush up a bit on how TCP/IP flow control works. The requests are not "queued up." It is the TCP/IP protocol that slows the rate of transmission when the receiving application is falling behind. This causes the sending application to block (asynchronous requests will take longer to complete). That is what is meant by backpressure.

The book series "TCP/IP Illustrated" is the best reference for getting a deep and comprehensive understanding for how TCP/IP works (it also covers other protocols, which you may choose to ignore if you want).

**Comment by echen333** [comment]
I see, thank you. You're saying the server websocket can tell if the client websocket has read the message?

But how do people normally deal with if the websocket is falling behind? Like if you only want to process the most recent information, and get read of all non-recent information, how would you do that?

Would you need your own setup?

**Comment by vinniefalco** [comment]
> But how do people normally deal with if the websocket is falling behind?

If you want to be able to discard old messages then you need to constantly read and buffer the messages yourself. And then when you process the next buffered message, take the newest one and discard anything that is too old.

**Comment by echen333** [comment]
I see. thanks for the help. 

just wondering, any plans to make an overhead buffer class in boost or is the use case too niche?

**Comment by vinniefalco** [comment]
> any plans to make an overhead buffer class in boost or is the use case too niche

Could be something that appears in a future library (not beast). But that would be years.

**Comment by echen333** [comment]
I noticed that the [boost asio socket](https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/reference/ip__tcp/socket.html) has data members message_peek and message_end_of_record. 

I was wondering if I could those to discard until I get a true from message_end_of_record if it's doing what I think it's doing. 

My only problem right now is having trouble accessing the underlying ip_tcp socket. Currently, I have:
```
std::unique_ptr<
      boost::beast::websocket::stream<boost::beast::ssl_stream<boost::beast::tcp_stream>>>
      secure_websocket_;
  std::unique_ptr<boost::beast::websocket::stream<boost::beast::tcp_stream>> insecure_websocket_;
```

and using 
```
boost::beast::get_lowest_layer(*stream);
```
where stream is one of the two types above. I get something of the type 
```
boost::beast::basic_stream<boost::asio::ip::tcp>
```

Is there any way to get the underlying boost::asio::ip::tcp protocol type?

**Comment by vinniefalco** [comment]
No those are not going to help you

**Comment by klemens-morgenstern** [comment]
`boost::asio::ip::tcp` is the protocol type.

**Comment by ashtum** [comment]
@echen333  Could you please close the issue if your problem has been resolved?
