### ISSUE TITLE
boost(1.81.0)::beast fail to connect to Coinbase's websocket API, ws://ws-feed.pro.coinbase.com/ or wss

### ISSUE THREAD

**Issue by OriKovacsiKatz** [boostorg/beast#2566]
Hi boost developers
I need some advice and help figuring out how to connect to coinbase websocket (I have attempted using 3 client examples):
* my boost libraries was built with cxxstd=2a ,threading-multi,static link, static run-time link
<path to boost source>/boost_1_81_0/libs/beast/example/websocket/client/awaitable/websocket-client-awaitable.cpp
<path to boost source>/boost_1_81_0/libs/beast/example/websocket/client/async-ssl/websocket_client_async_ssl.cpp
<path to boost source>/boost_1_81_0/libs/beast/example/websocket/client/sync-ssl/websocket_client_sync_ssl.cpp

* the launch commandline is:
` ./websocket-client-awaitable ws-feed.pro.coinbase.com 443 '{"type":"subscribe","channels":[{"name":"trade","product_ids":["BTC-USD"]}]}'`
also attempted the subscription json:  `'{"type":"subscribe","channels":[{"name":"ticker","product_ids":["BTC-USD"]}]}'`

Command Terminal (Ubuntu 22.04 x64) shows the error (it fails on handshake process):
`Error: **The WebSocket handshake was declined by the remote peer** [boost.beast.websocket:20 at ./boost/beast/websocket/impl/stream_impl.hpp:656:13 in function 'boost::beast::websocket::stream< <template-parameter-1-1>, <anonymous> >::impl_type::on_response(const response_type&, const sec_ws_key_type&, boost::beast::error_code&)::<lambda(boost::beast::websocket::error)>']`

* I try to trace into the source using gdb (GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1):
`gdb --args ./websocket-client-awaitable ws-feed.pro.coinbase.com 443 '{"type":"subscribe","channels":[{"name":"trade","product_ids":["BTC-USD"]}]}'`

* placing break point on line where error occures:
`(gdb) b ./boost/beast/websocket/impl/stream_impl.hpp:656`
* and back trace to see what is going on:
```
(boost::beast::websocket::error) const (__closure=0x7fffffffc908, e=boost::beast::websocket::error::upgrade_declined) at ./boost/beast/websocket/impl/stream_impl.hpp:656
656	            BOOST_BEAST_ASSIGN_EC(ec, e);
```
 the error code is:
(gdb) p e
$2 = boost::beast::websocket::error::upgrade_declined

(gdb) p ec
$1 = (boost::beast::error_code &) @0x7fffffffcb10: {{d1_ = {val_ = 0, 
      cat_ = 0x0}, 
    d2_ = "\000\000\000\000\377\177\000\000\000\000\000\000\000\000\000"}, 
  lc_flags_ = 0}
(gdb) p e
$2 = boost::beast::websocket::error::upgrade_declined

I turned it in to HRF (format)
1)  on_response (this=0x555555797730, res=..., 
    key=..., ec=...) at ./boost/beast/websocket/impl/stream_impl.hpp:659
2) handshake_op<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> >::operator() (
    this=0x7fffffffd1a0, ec=..., bytes_used=414, cont=true)
    at ./boost/beast/websocket/impl/handshake.hpp:177
3) handshake_op<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> >, void (boost::system::error_code, unsigned long)>::complete(boost::system::error_code, unsigned long) (this=0x7fffffffd138, args#0=..., args#1=414)
    at ./boost/asio/compose.hpp:113
4) handshake_op<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> >, void (boost::system::error_code, unsigned long)>&, boost::system::error_code, unsigned long) (
    this=0x7fffffffd140, self=..., ec=..., bytes_transferred=414)
    at ./boost/beast/http/impl/read.hpp:307
5) handshake_op<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> >, void (boost::system::error_code, unsigned long)>::operator()<boost::system::error_code, unsigned long>(boost::system::error_code&&, unsigned long&&)
    (this=0x7fffffffd138) at ./boost/asio/compose.hpp:107
6) handshake_op<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> >, void (boost::system::error_code, unsigned long)>, void (boost::system::error_code, unsigned long)>::complete(boost::system::error_code, unsigned long) (
    this=0x7fffffffd0c8, args#0=..., args#1=414)
    at ./boost/asio/compose.hpp:113
7) handshake_op<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> >, void (boost::system::error_code, unsigned long)>, void (boost::system::error_code, unsigned long)>&, boost::system::error_code, unsigned long) (this=0x7fffffffd0d0, self=..., 
    ec=..., bytes_transferred=414) at ./boost/beast/http/impl/read.hpp:251
8) handshake_op<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> >, void (boost::system::error_code, unsigned long)>, void (boost::system::error_code, unsigned long)>, boost::asio::use_awaitable_t<--Type <RET> for more, q to quit, c to continue without paging--
boost::asio::any_io_executor>::executor_with_default<boost::asio::any_io_executor>, std::allocator<void> >::complete_now<boost::system::error_code&, unsigned long&>(boost::system::error_code&, unsigned long&) (this=0x7fffffffd0c0)
    at ./boost/beast/core/async_base.hpp:426
9) andshake_op<boost::asio::detail::awaitable_handler<boost::asio::any_io_executor, boost::system::error_code> >, void (boost::system::error_code, unsigned long)>, void (boost::system::error_code, unsigned long)> >::operator()(boost::system::error_code, unsigned long) (this=0x7fffffffd0c0, ec=..., bytes_transferred=414)
    at ./boost/beast/core/impl/basic_stream.hpp:425

* If necessary I can send the complete trace log...

* I googled and found how to get the public part of the certificate:
```
~$ openssl s_client -connect [ws-feed.pro.coinbase.com:443](http://ws-feed.pro.coinbase.com:443/) -tls1_2
CONNECTED(00000003)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "Cloudflare, Inc.", CN = [pro.coinbase.com](http://pro.coinbase.com/)
verify return:1
---
Certificate chain
 0 s:C = US, ST = California, L = San Francisco, O = "Cloudflare, Inc.", CN = [pro.coinbase.com](http://pro.coinbase.com/)
   i:C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3
 1 s:C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3
   i:C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFQTCCBOagAwIBAgIQAwsZ65ykynnsboYy9+uMxzAKBggqhkjOPQQDAjBKMQsw
...... S/hiXlUpW9
kLEGMkU=
-----END CERTIFICATE-----
subject=C = US, ST = California, L = San Francisco, O = "Cloudflare, Inc.", CN = [pro.coinbase.com](http://pro.coinbase.com/)

issuer=C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2794 bytes and written 312 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-ECDSA-CHACHA20-POLY1305
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-CHACHA20-POLY1305
    Session-ID: 4DBF83C88D3DCFF13740C4428DAC970B9B2E01E39C4718D4666DD46CE74D6D9E
    Session-ID-ctx:
    Master-Key: 58F165A17C00478397FBF4EA3B164519C68839B7A80AD3C3FF9A818618B7A4585F937805174A8D6B91F72D3371DB00BB
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - b8 01 f2 b0 2e b8 de 0d-29 39 82 1f fc 93 02 19   ........)9......
    .....
    00b0 - 01 39 9f 2b 3d 08 84 aa-74 d0 b1 2c 9c 10 b3 8c   .9.+=...t..,....

    Start Time: 1668760951
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
closed
```

Can you please help me fix this error and succeed running the example?

Thanks
Ori Kovacsi Katz

**Comment by klemens-morgenstern** [comment]
Please post your issue in a HRF.

**Comment by OriKovacsiKatz** [comment]
Hi Klemens
  I never used HRF, ca you pleas help me do it the first time?

Thanks
Ori

**Comment by klemens-morgenstern** [comment]
HRF = Human readable format. I can't decipher what's going on.

**Comment by OriKovacsiKatz** [comment]
> HRF = Human readable format. I can't decipher what's going on.

I did my best to minimize text. 
Can you please help me fixing this issue

**Comment by ashtum** [comment]
@OriKovacsiKatz Could you please close the issue if your problem has been resolved?
