### ISSUE TITLE
How to "consume" a mutable_buffer

### ISSUE THREAD

**Issue by benstadin** [boostorg/beast#2571]
I want to replace a flat_buffer with a mutable_buffer in order to get access to the read_some interface for controlling my websocket sessions.

How to consume / clear a mutable_buffer? Or must it be recreated? 

And related, how to get a string from a mutable_buffer, since buffers_to_string does not accept a mutable_buffer?

**Comment by vinniefalco** [comment]
`flat_buffer` is not the same as `mutable_buffer`. One is a dynamic buffer the other is like a span.

**Comment by benstadin** [comment]
Thanks. I've adapted my code accordingly.
