### ISSUE TITLE
the ws content apper messy code

### ISSUE THREAD

**Issue by cjdxhjj** [boostorg/beast#2580]
PLEASE DON'T FORGET TO "STAR" THIS REPOSITORY :)

If you rather keep your project secret, feel free
to email the author at `<vinnie.falco@gmail.com>`; any
private correspondence is treated as confidential.

When reporting a bug please include the following:

### Version of Beast
1.80

### Steps necessary to reproduce the problem

i'm chinese, when my ws message contains chinese word, the server decode it as messy code
![image](https://user-images.githubusercontent.com/5616997/206996229-f0cb59bd-3833-4129-a0b6-11049ee7e9f3.png)
![image](https://user-images.githubusercontent.com/5616997/206996388-4344e032-3586-43ea-92cc-bd0318712aea.png)
i'm using the buffers_to_string to decode the message
![image](https://user-images.githubusercontent.com/5616997/206996534-12148bbf-8e55-42d7-a84d-18f583452412.png)

### All relevant compiler information

If you are unable to compile please include the type and
version of compiler you are using as well as all compiler
output including the error message, file, and line numbers
involved.

The more information you provide the sooner your issue
can get resolved!

**Comment by cjdxhjj** [comment]
how can i special the charset to buffers_to_string or how to convert the charset at first

**Comment by klemens-morgenstern** [comment]
Did you check that the logger handles the charset fine? It's all UTF-8?

**Comment by cjdxhjj** [comment]
yes, the logger log other chinese word correct

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/206997630-d642ce73-0683-4b59-af9e-773cc2315a2f.png)

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/206997828-9fe8191c-2002-46a8-939f-dba78419bb9d.png)

**Comment by cjdxhjj** [comment]
my log is a wrapper of boost log

![image](https://user-images.githubusercontent.com/5616997/206999011-b0a10cde-a781-421e-a508-f87a49fd516d.png)

**Comment by klemens-morgenstern** [comment]
What's the file encoding?

**Comment by cjdxhjj** [comment]
utf-8

**Comment by cjdxhjj** [comment]
log file encoding is ansi.

**Comment by cjdxhjj** [comment]
i submit that data to printer, the paper display the chinese words as messy code

**Comment by cjdxhjj** [comment]
when i tried convert the string from utf8 to ansi, the chinese words seems goods, but when i parse that string as json by boost json, the other issure apper, it can't parsed
![image](https://user-images.githubusercontent.com/5616997/207081389-33650458-ad39-45c9-8ab2-1baf960f410a.png)
i call the utf8_to_ansi
![image](https://user-images.githubusercontent.com/5616997/207082027-3e638fc4-fd46-464c-951a-e82896329620.png)
when i call the boost::json::parse, it throw an error
![image](https://user-images.githubusercontent.com/5616997/207082236-22732bb0-e58e-4386-b61f-bebaa864b810.png)
the same value parsed success by java
![image](https://user-images.githubusercontent.com/5616997/207082374-2aa93779-34d1-4264-b120-48288a7e75b3.png)
I have to convert the code a little bit
![image](https://user-images.githubusercontent.com/5616997/207083423-5b43e78d-6997-4b77-b34d-3f81bf9bca27.png)

**Comment by vinniefalco** [comment]
can you make a small self-contained program that reproduces the issue? Perhaps on godbolt.org ?

**Comment by cjdxhjj** [comment]
@vinniefalco the link is https://godbolt.org/z/qqbaxss9G

**Comment by cjdxhjj** [comment]
my ws message payload is flowing:
{"action":6,"data":"[{\"type\":1,\"bold\":true,\"data\":\"11123244256222测试\"},{\"type\":1,\"bold\":true,\"data\":\"https://home.nxin.com\"}]"}

the data is a string and process by handler special by action

when i convert the code at beast read handler, the data seems ok, but i can't parse it by boost json, i have to parse it at first, and convert it step by step.

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/207203008-989f9575-8643-433c-a41f-691dbac1045c.png)

**Comment by vinniefalco** [comment]
"测试" looks like utf-32 and not utf-8. JSON requires utf-8 encoded code points.

**Comment by vinniefalco** [comment]
See: https://godbolt.org/z/zeh64PbPj

**Comment by cjdxhjj** [comment]
@vinniefalco thanks very much, i will have a try convert at send time or binary format

**Comment by cjdxhjj** [comment]
i'm using this code convert the chinese words to utf-8
escape(str).replace(/\%u/g,'/u');
