### ISSUE TITLE
Difference between tcp::socket and beast::tcp_stream

### ISSUE THREAD

**Issue by klemens-morgenstern** [boostorg/beast#2587]
### Discussed in https://github.com/boostorg/beast/discussions/2581

<div type='discussions-op-text'>

<sup>Originally posted by **pfeatherstone** December 13, 2022</sup>
I think `tcp::socket` can have a polymorphic executor too now. Is there a reason to prefer `beast::tcp_stream`?</div>

**Comment by klemens-morgenstern** [comment]
Timeuts  & rate limiting

**Comment by pfeatherstone** [comment]
Also, any reason why github discussions was disabled? It's a good platform to ask Asio and Beast related questions

**Comment by vinniefalco** [comment]
I don't like splitting questions into two separate areas instead of one. Just ask in Issues.
