### ISSUE TITLE
Question: thread safety when socket's default exector is a strand

### ISSUE THREAD

**Issue by pfeatherstone** [boostorg/beast#2588]
I have the following:
```
struct some_listner_object
{
tcp::acceptor acceptor;
...
void do_accept(
  acceptor.async_accept(
                net::make_strand(ioc),
                [self=shared_from_this(), this](beast::error_code ec, tcp::socket socket)
                {
                    if(ec)
                        return;
                    
                    std::make_shared<some_session_object_with_socket>(std::move(socket))->start();

                    do_accept();
                }
  );
};
```

By using `make_strand`, i'm hoping the socket's default executor is a strand. So hopefully, all **async operations** on the socket are by default executed on the strand. Or is it by default all **completion handlers** are executed on the strand?
Basically, if it's the former, then all async operations are then thread safe. If it's the later, then all async operations need to be first `post`ed, unless they are already being called on the strand.

**Comment by klemens-morgenstern** [comment]
That code compiles?

**Comment by pfeatherstone** [comment]
Yep. I have omitted most of the program though. I just wanted to show the crucial bit : `acceptor.async_accept(net::make_strand(ioc), ...)`

**Comment by pfeatherstone** [comment]
Basically, i want to know if a socket's default executor is a strand, then is everything always, automatically thread-safe ? Because all async operations are initiated on that strand and all completion handlers are called on that strand?

**Comment by pfeatherstone** [comment]
If an external thread is calling a function which will call an async function on a socket, then does it have to be posted first to the socket's default executor, i.e. it's strand, or will that async function automatically be initiated on the default executor, i.e. the strand? Do you see what i mean? 
I'm getting confused as to when async reads, writes, accepts, etc, need first to be posted or dispatched if the socket's default executor is a strand.

**Comment by pfeatherstone** [comment]
Ok, another maybe clearer question. Does the executor dictate where the async function is **initiated** or does it only dictate where the completion handler of that sync function is run?

**Comment by criatura2** [comment]
> context
>   An execution context which provides the I/O executor that **the socket will use**, by default, **to dispatch handlers for any asynchronous operations performed on the socket.** 

https://www.boost.org/doc/libs/1_80_0/doc/html/boost_asio/reference/basic_stream_socket/basic_stream_socket/overload2.html

**Comment by pfeatherstone** [comment]
So does that mean i never have to use `dispatch()` or `post` on the strand? I can just use the async functions and everything is always thread safe ?

**Comment by mzimbres** [comment]
https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/reference/ip__tcp/socket.html#boost_asio.reference.ip__tcp.socket.thread_safety

AFAIS, to post across executors you need to dispatch (or post).
