### ISSUE TITLE
Beast "Body limit exceeded" error when response body is large for http::async_read request.

### ISSUE THREAD

**Issue by SRGehani** [boostorg/beast#2589]
Beast Version:
BOOST_BEAST_VERSION 290

Steps necessary to reproduce the problem:
When HTTP response is greater than 8 MB.

I have a "body limit exceeded" error during http::async_read request.

I have seen how to set body_limit using parser as mentioned [here](https://www.boost.org/doc/libs/1_71_0/libs/beast/doc/html/beast/ref/boost__beast__http__parser/body_limit.html), but could you suggest how can it be implemented with http::async_read.

Class members:
boost::beast::ssl_stream<boost::beast::tcp_stream> stream_;
boost::beast::flat_buffer buffer_;
std::shared_ptr< boost::beast::http::response<boost::beast::http::string_body>> resPtr_;

Read function:
    http::async_read(stream_, buffer_, *resPtr_,
        beast::bind_front_handler(
            &http_session::on_read,
            shared_from_this()));

**Comment by vinniefalco** [comment]
> could you suggest how can it be implemented with http::async_read.

It cannot.

**Comment by GaneshTambat1** [comment]
What would be the workaround in such a situation? Especially if moving to another model is not feasible and the rest of the code uses this model.

**Comment by vinniefalco** [comment]
Tell the server to send smaller bodies. But really, you need to refactor your code to pass the parser around. If this is an impossible task you have bigger problems.
