### ISSUE TITLE
Question: strand of a strand?

### ISSUE THREAD

**Issue by pfeatherstone** [boostorg/beast#2591]
What is the behaviour when a strand is created from a strand. I.e.:
```
net::io_context ioc;
auto strand_normal = net::make_strand(ioc);
auto strand_weird   = net::make_strand(strand_normal);
```
?
What's the difference in behaviour when work is bound to either of those strands?
Thanks

**Comment by pfeatherstone** [comment]
Basically if i have the code:
```
acceptor.async_accept(beast::bind_front_handler(&listener::on_accept, shared_from_this()));
...

void on_accept(beast::error_code ec, tcp::socket socket)
{
    std:make_shared<session>(std::move(socket));
}
...
struct session
{
    net::strand<any_io_executor> read_strand;
    net::strand<any_io_executor> write_strand;
    tcp::socket sock;

    session(tcp::socket sock_) 
    : sock{std::move(sock_)), 
      read_strand{sock.get_executor()}, 
      write_strand{sock.get_executor()} {}
};
```
and `acceptor`'s default executor is a strand, then `read_strand` and `write_strand` are strands of strand right?

**Comment by pfeatherstone** [comment]
I mean i could replace 
```
acceptor.async_accept(beast::bind_front_handler(&listener::on_accept, shared_from_this()));
```
with
```
acceptor.async_accept(ioc, beast::bind_front_handler(&listener::on_accept, shared_from_this()));
```
then the new socket's default executor is just plain old `net::io_context` instance. But i want to know what the difference in behaviour is.

**Comment by pfeatherstone** [comment]
If it's the case that creating strands from strands is really not desirable or undefined behaviour (?), then maybe the API should have constraints on what executors you should use. Maybe having a polymorphic executor type is really dangerous. Because `strand<any_io_executor>` could be anything. Maybe being specific about the underlying executor type is preferred.

**Comment by madmongo1** [comment]
Good question. I've never had a satisfactory answer. I would imagine it's similar to taking a lock on two mutexes before executing the completion handler rather than one.

I agree that strands of polymorphic executors are problematic. 

Create your target strand from the ioc and pass it into async_accept.

**Comment by madmongo1** [comment]
You don't need a separate stand for read and write ops. You need one strand per discrete object, such as a connection.

**Comment by madmongo1** [comment]
```
net::io_context ioc;
tcp::acceptor acceptor(net::make_strand(ioc));  // you generally don't need a strand on an acceptor since only one thread will usually accept at once.

acceptor.async_accept(net::make_strand(ioc),   // this will be the connection's strand.
                      beast::bind_front_handler(&listener::on_accept, shared_from_this()));

```

**Comment by pfeatherstone** [comment]
> You don't need a separate stand for read and write ops. You need one strand per discrete object, such as a connection.

Surely it's desirable to have separate read and write strands?

**Comment by madmongo1** [comment]
No. reads and writes on the same object can happen concurrently. But they should happen through the _same_ strand. Because you want them to be processed sequentially by the io object. 

The strand guards your entire connection and any timeouts etc it uses. you use it instead of a mutex to ensure that all operations involving your connection happen sequentially.

**Comment by pfeatherstone** [comment]
Yes i understand what a strand does. But i see no reason why read and write operations can't happen concurrently? All reads should be sequential and all writes should be sequential. But a read and a write can happen at the same time

**Comment by pfeatherstone** [comment]
It's like having a thread that does all the read operations and another thread that does all the write operations. According to BSD sockets docs, that's absolutely fine. Therefore, doing the same thing with Asio should be fine too.

**Comment by pfeatherstone** [comment]
Basically BSD sockets are reentrant.

**Comment by klemens-morgenstern** [comment]
it's not fine if you got something more complex than a socket though like any beast io object.
This is also a question for asio, not beast.

**Comment by pfeatherstone** [comment]
Yes sorry. The asio repo is less responsive. I see asio and beast as the same thing now. Really http and websocket should be merged into asio. Sorry for spamming issues. A discussions tab would be ideal as this isn't an issue at all, it's a bunch of questions. 

I do feel like up to date course material is due. I still see online tutorials from as late as 2020 that start with "use a `asio::io_service`, when this is deprecated. Which makes me think that there is A LOT of material online which is really out of date. It's so easy to use asio incorrectly. In fact, it's probably easier to use it incorrectly than it is to use it correctly. So i feel like i  need to ask questions wherever i can in order to get best usage out of the library.

**Comment by pfeatherstone** [comment]
For example, i feel like making use of the default polymorphic executor is dangerous. From a code readability point of view, it's really not obvious what is running where. I feel like having explicit strands for different things (read, write, callbacks, etc), and using those strands explicitly via `post()` or `bind_executor()` makes it much clearer when reading the code where something is running. I also have a lot of `assert(strand.running_in_this_thread());` throughout my code to catch as many bugs during debug. But i don't see anyone else online promoting this. I tell myself, "maybe I'm doing something wrong". So i feel it best to just ask, even if it's obvious and even if there is something in the docs.

**Comment by madmongo1** [comment]
Every async operation on a beast websocket is a composed operation. Every async step in that operation touches the state of the websocket stream. It would therefore be inappropriate to have two handlers executing concurrently against the same stream.
This is a good general principle to follow with any stream object.

**Comment by pfeatherstone** [comment]
Ok cool. Thank you everyone. Going back to first question. We don't know what a strand of a strand is ?

**Comment by pfeatherstone** [comment]
> Every async operation on a beast websocket is a composed operation. Every async step in that operation touches the state of the websocket stream. It would therefore be inappropriate to have two handlers executing concurrently against the same stream.
> 
> This is a good general principle to follow with any stream object.
> 
>  

In which case Asio and Beast should just enforce this. Like, make it impossible to compile unless you do exactly that.

**Comment by klemens-morgenstern** [comment]
> > Every async operation on a beast websocket is a composed operation. Every async step in that operation touches the state of the websocket stream. It would therefore be inappropriate to have two handlers executing concurrently against the same stream.
> > 
> > This is a good general principle to follow with any stream object.
> > 
> >  
> 
> In which case Asio and Beast should just enforce this. Like, make it impossible to compile unless you do exactly that. 

Would love to, can you tell me how to implement it?

**Comment by pfeatherstone** [comment]
Probably not :) Just an idea. The asio and beast source code looks quite complicated and the original authors would be better suited I think. I do feel like there is an opportunity to make some substantial changes to Asio/Beast to make it safer to use. The networking TS is dead so there is freedom to do what we want...

**Comment by pfeatherstone** [comment]
I'll close the issue as I think I've gone on a massive tangent. Many thanks to everyone

**Comment by pfeatherstone** [comment]
> > > Every async operation on a beast websocket is a composed operation. Every async step in that operation touches the state of the websocket stream. It would therefore be inappropriate to have two handlers executing concurrently against the same stream.
> > > 
> > > This is a good general principle to follow with any stream object.
> > > 
> > >  
> > 
> > In which case Asio and Beast should just enforce this. Like, make it impossible to compile unless you do exactly that. 
> 
> Would love to, can you tell me how to implement it?

How about we make the default executor of a socket a strand, not an any_io_executor ? So it's impossible to construct a socket without giving it a strand. That would be a start

**Comment by sehe** [comment]
@pfeatherstone  that's also a pessimization.

Besides, any_io_executor erases the executor type, which includes the underlying execution context. There's no such thing as a `any_strand` (`strand<io_context::executor_type>` is not the same as `strand<thread_pool::executor_type` etc.) and I'm pretty sure we wouldn't want to make one. It leads to situations where you could easily have multiply-type-erased executors, or multiply strand-wrapped executors, or both.

Imagine constructing from an existing IO object: `mybeast_io_object(obj.get_executor())`; The `obj`'s executor would already be type-erased, so we can't know whether it includes a strand or needs wrapping. Do we blindly wrap it again?

**Comment by pfeatherstone** [comment]
I'm not suggesting we erase the strand. Force it to be strand<io_context::executor_type

**Comment by klemens-morgenstern** [comment]
`any_io_executor` erased the strand though.

**Comment by pfeatherstone** [comment]
Yes but it can also erase anything else. So users can pass in any executor, even if it isn't best practice. I'm saying users should always pass in a strand via make_strand(ioc). So why bother having an erased executor when it will always and should always be the same type

**Comment by pfeatherstone** [comment]
Somewhere above, I was suggestion passing ioc as the executor for the socket type then having two explicit strands, once for read and one for write. Then someone suggested that was a bad idea and should always pass make_strand(ioc) and use that for all handlers. So if that's best practice, why bother having any_io_executor as the default executor of the socket. That seems like a bad idea.

**Comment by pfeatherstone** [comment]
I started using:
```
namespace safe
{
    using tcp_stream = beast::basic_stream<tcp, net::io_context::strand, beast::unlimited_rate_policy>;
    using socket     = net::basic_stream_socket<tcp, net::io_context::strand>;
    using acceptor   = net::basic_socket_acceptor<tcp, net::io_context::strand>;
}
```

But there are too many objects inside asio and beast that use `any_io_executor` as default template parameter which user can't change.
For example `websocket::stream<NextLayer, deflateSupported>` uses `net::steady_timer` but should be `net::basic_waitable_timer<chrono::steady_clock, NextLayer::executor_type` to make this work.
Nearly there though.

**Comment by sehe** [comment]
Yes you can do that. But the library cannot (should not) make that decision. Again, the choice for `strand<io_context::executor_type>` is arbitrary and limiting. But of course you can do that, and that's exactly why you can parameterize the `base_` object types.

In fact this is a standard step when optimizing the performance of Asio code, as the type erasure isn't free.

**Comment by pfeatherstone** [comment]
This also the issue that `boost::asio::ip::tcp` assumes you're using `any_io_executor` and you can't change that

**Comment by pfeatherstone** [comment]
> Yes you can do that. But the library cannot (should not) make that decision. Again, the choice for `strand<io_context::executor_type>` is arbitrary and limiting. But of course you can do that, and that's exactly why you can parameterize the `base_` object types.
> 
> In fact this is a standard step when optimizing the performance of Asio code, as the type erasure isn't free.

Why shouldn't it make that decision if every asio expert says it's a bad idea to not use a strand?

**Comment by sehe** [comment]
Please slow down with the posting, and read more closely. It's not just choosing the strand wrapper. It's also hard coding the underlying context type. That's arbitrary and limiting.

Also, mandating strands may not make sense in the context of, say, a single threaded application.

**Comment by sehe** [comment]
> For example websocket::stream<NextLayer, deflateSupported> uses net::steady_timer but should be net::basic_waitable_timer<chrono::steady_clock, boost::asio::wait_traits<chrono::steady_clock>, NextLayer::executor_type to make this work.

That's a valid enhancement request, please file it.

> boost::asio::ip::tcp assumes you're using any_io_executor 

But it doesn't. It merely provides the protocol, which you can use fine, as you have already just posted.

> and you can't change that

The code you just showed proves otherwise. The only thing you want to avoid is the convenience typedefs (like `tcp::socket`).

**Comment by pfeatherstone** [comment]
> The code you just showed proves otherwise. The only thing you want to avoid is the convenience typedefs (like tcp::socket).

Ah ok, they are just convenience typedefs. They are not used in the internals of the object

**Comment by pfeatherstone** [comment]
> Also, mandating strands may not make sense in the context of, say, a single threaded application

Interesting, do strands incur a runtime cost ?

**Comment by sehe** [comment]
> Interesting, do strands incur a runtime cost ?
Yes, in general.

With the right hinting and compile time flags it **may** be reduced or eliminated in practice, but in principle synchronization is overhead.

**Comment by uohmak4fvpqe** [comment]
> No. reads and writes on the same object can happen concurrently. But they should happen through the _same_ strand. Because you want them to be processed sequentially by the io object.

I don't understand what you mean, this seems contradictory to me. Do they happen concurrently or they have to be sequential in one strand ?
Do you mean the async_* can be concurrent but not the handlers ?

Every async operation on a beast websocket is a composed operation. Every async step in that operation touches the state of the websocket stream. It would therefore be inappropriate to have two handlers executing concurrently against the same stream.
> Would it be reasonnable to call this a design flaw ? Couldn't concurrent handling dramatically accelerate the flux of information ?
