### ISSUE TITLE
Parsing Headers and Getting Cookies

### ISSUE THREAD

**Issue by WarrenN1** [boostorg/beast#2616]
How do I access the headers and get the cookies from an incoming HTTP:Request? So far I am aware that the following can be done:
```
for(auto& h : req.base())
{
    std::cerr << "Header: "<< h.name()<< ", Header Name: " << h.name_string() << ", Value: " << std::string(h.value()) << "\n";
```
But for some headers like:
Content-Type
```
Content-Type: multipart/form-data; boundary=something
```
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

There does not seem to be a built in way to access directives like "boundary=something"
It seems that most headers lack support by beast, but I am wondering if I missed something in the docs?

**Comment by klemens-morgenstern** [comment]
No, it's not supported.
