### ISSUE TITLE
Overall simplification planned?

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [boostorg/beast#2617]
Hi,
I was reading the documentation for Beast and for another library [(uWS](https://github.com/uNetworking/uWebSockets#battery-batteries-included), not to name it).

Beast looks very powerful but it seems many details can be forgotten while using it.
for example [this link,](https://www.boost.org/doc/libs/1_81_0/libs/beast/example/http/client/async-ssl/http_client_async_ssl.cpp) which looks like a bare bone, has:

```
http::async_write(stream_, req_,
            beast::bind_front_handler(
                &session::on_write,
                shared_from_this()));
```
That's a lot of typing. I get the inherent nature of async, but some typing should be removed.

Could it be possible to have something like:

http::async_write(stream_, req_, [](/*arguments*/){
    /* do things...*/      
});

Overall I find Beast very verbose and error prone, (maybe leading to miss some performance optimisations).
Is there a way to make it less so?

**Comment by klemens-morgenstern** [comment]
Yes, by using `asio::awaitable` & C++20 coroutines. Examples are included.

**Comment by vinniefalco** [comment]
> Overall I find Beast very verbose and error prone

Beast is based on Asio so it inherits the same syntax and idioms.

**Comment by LumiereDeLOmbre** [comment]
Ok,
so here [here](https://www.boost.org/doc/libs/1_81_0/libs/beast/example/http/client/awaitable/http_client_awaitable.cpp),

we write `beast::flat_buffer b;` and give it to the method.
Couldn't we have an overload with a static beast::flat_buffer ? Leading to

`co_await http::async_read(stream, res);` ?

**Comment by vinniefalco** [comment]
No. "must be persisted"

**Comment by LumiereDeLOmbre** [comment]
Ok, "pass".
