### ISSUE TITLE
The README says that beast is a header-only library, but cmake then builds liblib-beast.a, etc

### ISSUE THREAD

**Issue by yurivict** [boostorg/beast#2619]

**Comment by ashtum** [comment]
@yurivict Beast is a header-only library, you can include the Beast header and compile your application. However, Beast is designed in a way that separates non-templated implementations into `.ipp` files, enabling you to build them once and reuse them. Simply include `boost/beast/src.hpp` in a separate translation unit and define the [BOOST_BEAST_SEPARATE_COMPILATION](https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/config/configuration_preprocessor_defin.html) macro before including Beast headers to enhance compile time.
