### ISSUE TITLE
It's Safe-Point to refresh the websocket stream in on_close callback

### ISSUE THREAD

**Issue by g302ge** [boostorg/beast#2631]
I have a self-wrapped websocket lib work with beast. like below

```c++

int main() {
     asio::io_context io_context;
     asio::work_guard<> guard(io_context.get_executor);
     auto thread = std::thread([&io_context](){ io_context.run(); });
     std::unique_ptr<beast::websocket::stream> stream = std::make_unique_ptr<>(io_context.get_executor());
     stream.async_write("Some Message");
     stream.async_close([&stream](..){ 
        // refresh the stream 
        // maybe simply using the operator=(std::unique_ptr&&)
     });
     stream.async_write("Some Message");
     thread.join();
}
```

Could tell me, if the refreshing logic in close callback is safe ? In other words, my target is restarting this session in the closed callback

**Comment by klemens-morgenstern** [comment]
In this case yes, because you join before stream goes out of scope after everything is done.

I would however recommend you just use shared_ptr and pass that instead of s reference to avoid a long list of mean bugs.

**Comment by g302ge** [comment]
> In this case yes, because you join before stream goes out of scope after everything is done.
> 
> I would however recommend you just use shared_ptr and pass that instead of s reference to avoid a long list of mean bugs.

In my real code, I have use a callback to callabck on_close which make sure the close in single thread
