### ISSUE TITLE
Clang 16 regression causes compilation error in ssl_stream in C++20 mode

### ISSUE THREAD

**Issue by vient** [boostorg/beast#2648]
Hello, I want to notify you about https://github.com/llvm/llvm-project/issues/60749

This is a problem in Clang itself but they decided that it is not a release blocker. Clang 16 will be released in a week and [provided code](https://godbolt.org/z/nzePcnGjj) is not compiling. Is it possible to change something on Beast side? It seems that the bug requires very specific conditions.

Sorry for inconvenience, we want to switch to LLVM 16 asap and I'm not sure what to do in light of this bug.

**Comment by vient** [comment]
FYI
For our purposes we just made this small patch, after that Beast compiles fine
```diff
diff --git a/boost/beast/ssl/ssl_stream.hpp b/boost/beast/ssl/ssl_stream.hpp
index d7ce7c1..51cc9d0 100644
--- a/boost/beast/ssl/ssl_stream.hpp
+++ b/boost/beast/ssl/ssl_stream.hpp
@@ -673,7 +673,7 @@ public:
         ssl_stream<SyncStream>& stream,
         boost::system::error_code& ec);

-    template<class AsyncStream, BOOST_BEAST_ASYNC_TPARAM1 TeardownHandler>
+    template<class AsyncStream, class TeardownHandler>
     friend
     void
     async_teardown(
@@ -697,7 +697,7 @@ teardown(
 }

 template<class AsyncStream,
-        BOOST_BEAST_ASYNC_TPARAM1 TeardownHandler = net::default_completion_token_t<beast::executor_type<AsyncStream>>>
+        class TeardownHandler = net::default_completion_token_t<beast::executor_type<AsyncStream>>>
 void
 async_teardown(
     boost::beast::role_type role,
 ```
Loosening requirements is not good but Clang bug lies exactly in applying concepts in template list so removing concepts helps. In original issue someone mentioned that you can also move concept to requires clause, like `template<Concept x>` to `template<class x> requires Concept(x)` or something similar, but I did not manage to get working version of this.

**Comment by Tectu** [comment]
Am I correct that this didn't make it into 1.83 despite the assigned milestone?

**Comment by stromnet** [comment]
Archlinux has bumped to clang 16 now, causing this error to pop up on my local development machine.  clang15 package is available in extras, but would be nice to be able to build with clang 16 too.

**Comment by Tectu** [comment]
Similar issue over at FreeBSD and most likely several other places too. I'm not involved in boost development but maybe this would justify a patch release (i.e. boost `1.83.1`)?

**Comment by klemens-morgenstern** [comment]
Yeah, I forgot to merge in time. Issue is fixed in develop. Really sorry about that.

**Comment by Tectu** [comment]
> Yeah, I forgot to merge in time. Issue is fixed in develop. Really sorry about that.

Could you share a link to the particular commit so downstream package maintainers could potentially ship the patch if no `1.83.1` release is planned to address this issue (is there?)?

**Comment by vient** [comment]
https://github.com/boostorg/beast/commit/72c2eeb3980ed0dc530de9241e25b247517de018
