### ISSUE TITLE
library jamfile is non-conforming

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#2649]
The Jamfile for the compiled lib should be in build/Jamfile not the root Jamfile, which probably should be stripped down and/or removed. The library name is "lib-beast" which is also not normal it should be "boost_beast".

**Comment by vinniefalco** [comment]
Also the file test/lib_beast.cpp should be in src/lib_beast.cpp

**Comment by klemens-morgenstern** [comment]
I think that's a bad idea without having openssl.jam work properly. And I can't get this work.

**Comment by klemens-morgenstern** [comment]
I made openssl.jam work. But I will still keep lib_beast and lib_asio where they are (in root). Not exported and used by example & test. Exporting a beast target is a bad idea until we have something similar for asio.
