### ISSUE TITLE
[MSVC][VS2022] read.exe and http_examples.exe hang on VS2022

### ISSUE THREAD

**Issue by QuellaZhang** [boostorg/beast#2653]
Hi All,

We found Boost\libs\beast\test read.exe and http_examples.exe hang on VS2022 when building. This issue can be reproduced stably on VS2022 v17.6.0-pre.2.0.

**Repro steps:**

1. git clone --recurse https://github.com/boostorg/boost F:\gitP\boostorg\boost
2. cd F:\gitP\boostorg\boost
3. .\bootstrap > build0.log
4. .\b2 headers variant=release --build-dir=F:\gitP\boostorg\boost\out\amd64rel address-model=64 > build1.log
5. .\b2 variant=release --build-dir=F:\gitP\boostorg\boost\out\amd64rel address-model=64 > build2.log
6. .\b2 -j16 variant=release -d+2 --build-dir=F:\gitP\boostorg\boost\out\amd64rel libs\beast\test address-model=64 > build3.log

**Results:**
![boost](https://user-images.githubusercontent.com/36754348/225554428-7a5b2d64-9411-4b9a-9b63-cadbed6c8274.png)

**Comment by klemens-morgenstern** [comment]
I'd need some more details, I can't reproduce that.

**Comment by QuellaZhang** [comment]
What kind of information do you need? Below is my OS info. 

A colleague of mine can reproduce the issue on VS2022 Community v17.5.2 with the same commands.

![image](https://user-images.githubusercontent.com/36754348/225831283-f0f07fe9-fc6b-43f9-90eb-b3f219b21ea8.png)

**Comment by vinniefalco** [comment]
Are you using an official release of VS2022 Community or is that a beta?

**Comment by QuellaZhang** [comment]
Release builds, not beta, hang when the executable is run. I have attached linkrepro and exe. You can try the following steps to reproduce:

1. open VS2022 Community v17.5.2 x64 Tools command
2. unzip linkrepro.zip
3. cd linkrepro
4. cl -c read.i -TP /wd4675 /EHs /MD
5. link @link.rsp
6. read.exe
7. it will hang

Attachment:
[linkrepro.zip](https://github.com/boostorg/beast/files/11016274/linkrepro.zip)

**Comment by klemens-morgenstern** [comment]
can you find out where it hangs with a debugger?

**Comment by vinniefalco** [comment]
Scratch that, I was able to reproduce the problem and attach a debugger. This line is hanging, likely due to a change in Asio:
https://github.com/boostorg/beast/blob/3dddb5fecf8ff64bb8b841e7b252ea2b17683030/test/beast/http/read.cpp#L398

We should change that to poll instead. I'm not sure why it succeeds when run from the VS IDE but not from b2.

**Comment by klemens-morgenstern** [comment]
I tried and it still works on VS 2019 - install VS 2022 now.

**Comment by klemens-morgenstern** [comment]
I've written a fix in #2657 - works on my machine. We currently have on CI for that MSVC version, can either of you confirm that this does it?

**Comment by QuellaZhang** [comment]
@klemens-morgenstern, quick fix👍. I verified locally that `read.exe` has run successfully, but `http_examples.exe` still hangs.

**Comment by klemens-morgenstern** [comment]
Ok, let's do that quickfix for the upcoming release and the examples afterwards.

**Comment by klemens-morgenstern** [comment]
Reopened for `http_examples`.
