### ISSUE TITLE
docs: basic_stream::expires_after is confusing

### ISSUE THREAD

**Issue by Spongman** [boostorg/beast#2664]
[basic_stream::expires_after](https://www.boost.org/doc/libs/1_81_0/libs/beast/doc/html/beast/ref/boost__beast__basic_stream/expires_after.html) states:

> Set the timeout for the next logical operation.

The use of the definite article implies the timeout applies to a single operation.

But then it goes on to state:
> The timer applies collectively to any asynchronous reads or writes...

So, which is it? singular or plural?

**Comment by klemens-morgenstern** [comment]
Should be plural. I'll review the details and update the docs.
