### ISSUE TITLE
http_client_async_ssl_system_executor.cpp example compile issues

### ISSUE THREAD

**Issue by jshanaj** [boostorg/beast#2670]
I have tried a few versions of boost with it's included Beast and am having trouble compileing the asyc with system executer.

The errors with 1.76 were excessive centered around the use of placement_new so I switched to 1.82
The problem I see is that the tcp::resolver in this example cannot be constructed with the strand.

VS2019 using V142 toolchain with /permissive and c++latest

Did the example not get migrated or did I miss something obvious.

error C2664: 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp,boost::asio::any_io_executor>::basic_resolver(const boost::asio::any_io_executor &)': cannot convert argument 1 from 'boost::asio::strand<boost::asio::system_executor>' to 'const boost::asio::any_io_executor &'
... Reason: cannot convert from 'boost::asio::strand<boost::asio::system_executor>' to 'const boost::asio::any_io_executor'
... No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
... see declaration of 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp,boost::asio::any_io_executor>::basic_resolver'

I tried changing to io_any_executer but that cascaded to more errors.

**Comment by vinniefalco** [comment]
I would not use the system executor. Does the Beast example compile without changes?

**Comment by jshanaj** [comment]
No, The construction of the resolver gives the error posted.

**Comment by vinniefalco** [comment]
You need to choose the proper type for the resolver. Use a `basic_resolver` and manually enter the correct template parameters to match the type of executor (strand in this case). If you stare at the Asio documentation for long enough, it will become apparent. If this fails, print a copy of the Asio documentation and put it under your pillow at night, and each morning you will know a little bit more. Eventually you will have the answer.

**Comment by jshanaj** [comment]
Thanks. I got sidetracked when the provided example in 2 versions failed to build. Is the System_Executer deprecated in favor of any_io_executer?

**Comment by jshanaj** [comment]
Thanks for that detail. Great explanation. I have been using boost for years, even asio+curl, but have just started looking at Beast for a new project.

**Comment by jshanaj** [comment]
Giving up for now, Too cryptic. I will rewatch the slushie and the CPPCon 2018  videos and play with some minimal examples (i was trying to add to existing project)

**Comment by jshanaj** [comment]
Problem Solved. 
   For those that may encounter this edge case. ASIO will not build if c++latest is selected in Visual Studio 2019/2022 without disabling Concepts.  Beast must have Concepts enabled. Set language to C++20 and remove BOOST_ASIO_DISABLE_CONCEPTS if it is set in a vsprops file :-)

**Comment by vinniefalco** [comment]
Ouch...

**Comment by jshanaj** [comment]
What versions of openssl is Beast compatible with. To remain compatible with current code I am using boost 1.76 and our 1.1.1.k is missing some headers beast is asking for. I updated to openssl 3.1.0 but the Deprecated functions are giving me errors.
