### ISSUE TITLE
unreachable code in asio/buffer.hpp with optimizations

### ISSUE THREAD

**Issue by Dragonexodus** [boostorg/beast#2678]
See References #1582 

@vm2mv wrote:

> boost 1.81 and 1.82
> Visual Studio 2022 17.4.3
> 
>     Disabling inline function expansion (/Ob0) moves the warning from asio to beast:
> 
> boost\beast\core\impl\buffers_cat.hpp(206): warning C4702: unreachable code 
> 
>         template<class I>
>         reference operator()(I)
>         {
> ->          return *self.it_.template get<I::value>();
>         }
> 

I'm using boost-beast in combination with VCPKG.

**Comment by vinniefalco** [comment]
Yeah this has been torturing me for a few years now...

**Comment by Dragonexodus** [comment]
:( Sorry to hear!
Interestingly Version 1.80 and prior are working with VCPKG and static build.
So the questions is.. what changed.
Does this change: https://github.com/ImageEngine/cortex/pull/1217 had a an impact on the compiler behaviour?

**Comment by klemens-morgenstern** [comment]
@Dragonexodus can you check if changing the function in question to 

```cpp
        template<std::size_t I>
        reference operator()(mp11::mp_size_t<I>)
        {
            return *self.it_.template get<I>();
        }
```

Fixes the warning?

**Comment by IamVishalSharma** [comment]
Any update on this .. i am hitting the same issue with Version 1.82 and vc142/143 tool chain Visual Studio 2022 ( 17.6.2)

**Comment by hans-brgs** [comment]
I am experiencing the same issue as described in this thread.

`buffers_cat.hpp(186): warning C4702: unreachable code`

Has anyone else encountered this problem and found a solution or workaround? I'd appreciate any insights or suggestions.

Best,

**Comment by klemens-morgenstern** [comment]
There's a workaround above. I just need confirmation that it solves the problem before merging.
