### ISSUE TITLE
Internal latency measurements

### ISSUE THREAD

**Issue by sfjhkjdsh** [boostorg/beast#2685]
My use case is to measure the latencies for reading WS msg: from network card / Kernel -> `stream::async_read` callback i.e. internal latency. This will allow me to track slow consumer (packet queueing inside kernel) and beast's latency.

One approach can be: As per [kernel](https://www.kernel.org/doc/html/latest/networking/timestamping.html), `SO_TIMESTAMPING` can be used for per byte timestamps. So beast could report timestamps associated with the first and last byte in a WS message.

**Comment by klemens-morgenstern** [comment]
Why can't you just timestamp the call & completion of `async_read` ?

**Comment by sfjhkjdsh** [comment]
there can be times when there's no data on socket, so waiting time will be included as well in the measurement?
