### ISSUE TITLE
Linux connection problems (raspberry pi)

### ISSUE THREAD

**Issue by Moerten** [boostorg/beast#2691]
Hi, I am using my socket classes based on the beast (boost 1.81) one's for linux (raspberry pi) now. Having no problems under windows the same classes are most of the time not working under linux. Then only in rare cases the sockets will connect at all.

One problem seems to be that after a reconnect/restart of the server socket/application the socket thinks it is still in use:
```
acceptor.open(endpoint.protocol());
	acceptor.set_option(boost::asio::ip::tcp::acceptor::reuse_address(true));
	acceptor.set_option(boost::asio::ip::v6_only(false));
	acceptor.bind(endpoint, errorCode);
	if (errorCode)
	{
		if (errorCode.value() == boost::asio::error::address_in_use)
		{
                    ...
```
Why is this the case?
In case the connection does not work I never see the client/server callbacks "on_resolve" and "on_accept" getting called below:
```
// Client...
resolver.async_resolve(
		{ host.c_str(), port.c_str() },
		std::bind(
			&on_resolve,
			this,
			std::placeholders::_1,
			std::placeholders::_2));
```
```
// Server...
acceptor.async_accept(
		socket,
		std::bind(
			&on_accept,
			this,
			std::placeholders::_1));
```
Any ideas what could cause these connection issues? Is there something different for windows/linux?

**Comment by klemens-morgenstern** [comment]
How do you restart the server? Are you sure you kill the previous process properly

**Comment by Moerten** [comment]
The app gets ended normally. I checked with htop the process is not running anymore. But still the socket claims to be in use.

**Comment by omartijn** [comment]
Have you tried `SO_REUSEADDR`?

**Comment by Moerten** [comment]
Thats what calling
```
acceptor.set_option(boost::asio::ip::tcp::acceptor::reuse_address(true));
```
should do if I understand correctly. I think the problem is most probably related to that. It seems linux does not understand that the socket isn't used anymore. Maybe this could be because my shutdown is not working correctly or I read the sockets will stay in TIME_WAIT state for some time after shutdown. Also I am wondering why there is not "SO_REUSEPORT" corresponding "reuse_port" option available.

**Comment by ashtum** [comment]
@Moerten Were you able to successfully resolve the issue?

**Comment by Moerten** [comment]
Yes, it was necessary to call "restart" for the IO service after each run call and not only before each connect. Under windows this wasn't the case. Also I do not know why you do not call yourself restart in the run function if it is required to do so?

**Comment by ashtum** [comment]
@Moerten, Having to call restart on io_context suggests that you might have an open acceptor somewhere in the code.

**Comment by vinniefalco** [comment]
Calling `io_context::restart` is not something to be done casually. Almost no one needs to call this function, and if you do need to call it usually you will have a deep understanding of why.
