### ISSUE TITLE
Synchronous concurrent reads and writes on a websocket?

### ISSUE THREAD

**Issue by lava** [boostorg/beast#2694]
I'd like to use a websocket connection where one thread is continuously reading, and another thread is writing messages (and pings) as they arrive.

As far as I can tell, this is not possible to implement with synchronous operations, since it is not allowed to call the `read()` and `write()` member functions of a stream object concurrently from different threads, and once we're in a synchronous `read()` there's no way to cancel or interrupt it. For `wss` sockets it's also likely to stay that way because the underlying OpenSSL object also doesn't allow concurrent calls to `SSL_read()` and `SSL_write()`. (for plain websockets it seems like the underlying TCP socket should support this, but I can't tell if ASIO and/or beast does)

However all the existing discussion I could find only talks about async reads and writes, so I'd like to sanity check: Is my understanding correct on this?

**Comment by klemens-morgenstern** [comment]
Yes, your understanding is correct.

**Comment by klemens-morgenstern** [comment]
Is this issue still needed?

**Comment by lava** [comment]
No, all good, thanks for the reply.
