### ISSUE TITLE
error boost::beast::http::basic_fields<std::allocator<char> >::value_type::buffer !!

### ISSUE THREAD

**Issue by yasastharinda9511** [boostorg/beast#2696]
Got this error for higher request rates(for lower request rates it's fine)
 boost::beast::http::basic_fields<std::allocator<char> >::value_type::buffer (this=0x7ff86ff8aa68) at /usr/include/boost/beast/http/impl/fields.hpp:287
287	        static_cast<std::size_t>(off_) + len_ + 2};

which occurs when I try to set headers like this req->set(pair_ref.first , beast::string_view(pair_ref.second)); , After commenting this line works fine !!

**Comment by klemens-morgenstern** [comment]
What's pair_ref and are you doing this multi-threaded? Did you run any sanitizer?

**Comment by yasastharinda9511** [comment]
Yeah I'm doing this in multi-threaded environment. Here pair_ref is std::pair<std::string, std::string> (even for the hard coded values this occurs) . no I didn't

**Comment by klemens-morgenstern** [comment]
Are you calling .set from different threads? That would be a race condition and UB.

**Comment by yasastharinda9511** [comment]
Yes I passed the .set to the "boost::asio::post(_io_context.get_executor(), handler)". the matter is if I commented out that line and run for higher request rate works fine. if it is a race condition after the commenting that line also should encounter the same error . but it does not .

**Comment by klemens-morgenstern** [comment]
Well that depends on whether or not your io_context is running on multiple threads, in which case the post would introduce a race condition.

**Comment by ashtum** [comment]
@yasastharinda9511 Is this still open?
