### ISSUE TITLE
My lifetime management is terrible and lazy - Is there a better way?

### ISSUE THREAD

**Issue by systocrat** [boostorg/beast#2697]
Hey everyone,

I have some code that I wrote in the interest of expediency, but I'd like to clean it up and learn in the process.

```
        void stop() {
            if (ws_.is_open()) {
                ws_.async_close(websocket::close_code::normal, [self=shared_from_this()](boost::system::error_code ec) {
                    self->msg_channel_.cancel();
                    self->buffer_.clear();
                    self->resolver_.cancel();

                    self->msg_queue_ = {};
                });
            }

            stopped_ = true;
        }
```

As you can see, in a stop() function that closes my Websocket session, I call async_close witth a lambda that captures the owning classes shared_ptr and does all of its cleanup thereafter.

I'm not the biggest fan of using shared_ptr so frivolously in the first place, and I'm especially not a fan of capturing a shared_ptr in a lambda.

Is there a better way? Should I make the stop function an async operation? What are best practices when thinking about this kind of thing?

**Comment by klemens-morgenstern** [comment]
That really depends on your project and it's code-style. I like to use coroutines to make this stuff async, but your solution seems fine as well. Really hard to say without more info.

**Comment by systocrat** [comment]
Could you give some details I can provide that might be helpful? @klemens-morgenstern

**Comment by klemens-morgenstern** [comment]
How are you working in general? Callbacks? Coros?

**Comment by systocrat** [comment]
@klemens-morgenstern 
Okay, I think I'd like to have all async operations from an objects members be associated with the owning parent objects shared_ptr.

I can write my own completion handler that wraps another one, and holds a shared_ptr to the operation owner in its state- is this a good solution?

**Comment by klemens-morgenstern** [comment]
You don't even need to write that if you're on a recent boost version, you can use [asio::consign](https://www.boost.org/doc/libs/1_82_0/doc/html/boost_asio/reference/consign.html) for that.

**Comment by systocrat** [comment]
Oh, that's perfect, thanks!
