### ISSUE TITLE
questions about handling more than one (nested) websocket connection

### ISSUE THREAD

**Issue by eemincetin** [boostorg/beast#2698]
I've read your async examples, I've created a websocket class that has multiple handlers. Basically I'm listening to coin websockets of a variety of crypto exchange servers. That is okay up to here. But now, I need to connect a websocket and listen for one response. after that response came to me, I'll use that response to connect another websocket, while first websocket is still running (I need to send ping periodically to it, but nothing more than this) and in this new websocket I'll have new handlers and to do somethings.

While connecting coin websockets, I can use an io_context object and my code is stuck in ioc.run(). But now, how to handle a scenario I've just explained. How to build a connection or how to handle more than one connection? I couldn't relate examples with my scenario.

And I'm using async_ssl example to build my all system. I don't really know conceptually what coroutines are. maybe they can help? overall I need to know what should I know/apply to proceed. 

thanks Vinnie for this amazing library

**Comment by klemens-morgenstern** [comment]
`ioc.run()` enters an event loop and will remain there until all the work is finished, which means all connections are closed in your case.

I suspect that you'll want to `asio::post` the second job to the io_context once the connection is accepted. You could also look into coroutines if you want an easier to reason about model.

**Comment by eemincetin** [comment]
thanks for response @klemens-morgenstern , do you have any comment on this @vinniefalco ?

**Comment by ashtum** [comment]
@eemincetin Is this still open?
