### ISSUE TITLE
async-ssl: alert decrypt error 

### ISSUE THREAD

**Issue by definesun** [boostorg/beast#2699]
### Version of Beast
boost_1_71_0

hello, i use async-ssl in my project refer to http_server_async_ssl.cpp example, and https server user self-signed certificate,  bidirectional check between client and server, when config one thread, erverything is ok, but more than one threads, occasionally curl client return curl: (35) OpenSSL/3.1.1: error:02000086:rsa routines::last octet invalid, and server Handshake error with tlsv1 alert decrypt error. I don't know why, can you help me ?

**Comment by klemens-morgenstern** [comment]
That does sound like an invalid certificate.

**Comment by definesun** [comment]
> That does sound like an invalid certificate.

req one by one is ok

**Comment by klemens-morgenstern** [comment]
I don't understand.

**Comment by ashtum** [comment]
@definesun Is this still open?
