### ISSUE TITLE
how to async_write message external?

### ISSUE THREAD

**Issue by clee01** [boostorg/beast#2704]
In [websocket_client_async.cpp](https://github.com/boostorg/beast/blob/develop/example/websocket/client/async/websocket_client_async.cpp)

if i want to call async_write serveral times in main process, how to re-design this example code?

something probably should keep in mind:
* make io_context strand
* ensure session working properly before async_write being invoked
* ...

**Comment by klemens-morgenstern** [comment]
You don't redesign it, you call async_write again from on_write. If you don't like callbacks you can use another completion model.

**Comment by clee01** [comment]
> You don't redesign it, you call async_write again from on_write. If you don't like callbacks you can use another completion model.

but the param `buffer` need to async_write i have no idea in Session, i only know it out of the Session.
so that's my intention to `call async_write serveral times in main process`

**Comment by klemens-morgenstern** [comment]
I don't understand what you want to do.

**Comment by clee01** [comment]
```cpp
class session {};

int main() {
  ...
  // Launch the asynchronous operation
  std::make_shared<session>(ioc)->run(host, port, text);

  // Run the I/O service. The call will return when
  // the socket is closed.
  std::thread th([&]() { ioc.run(); });
  ...

  GetSession()->async_write();
}
```

* GetSession()->async_write();

类似这种处理
