### ISSUE TITLE
No license info for boost/beast/core/detail/work_guard.hpp

### ISSUE THREAD

**Issue by jwakely** [boostorg/beast#2705]
https://github.com/boostorg/beast/blob/develop/include/boost/beast/core/detail/work_guard.hpp has no copyright or license info. I assume it's covered by the usual Boost license, but it would be better to say so in the file.

**Comment by klemens-morgenstern** [comment]
Legally speaking, of course it is based on the license file in the project root. I'll add the license after the 1.83. release is done.

**Comment by jwakely** [comment]
The presence of a license file in the project doesn't imply that all files are covered by that license (e.g. some files in the project are also covered by the Zlib license). And the license is separate from the copyright info, which is also missing.

**Comment by klemens-morgenstern** [comment]
I'd prefer not to, just to keep the release history completely clean.
