### ISSUE TITLE
Single-thread websocket app crashes with `pending_guard` check fails

### ISSUE THREAD

**Issue by zptan** [boostorg/beast#2707]
My project is a client that subscribes (websocket) data from a server, the server pushes data to the client when there is update, and the client will ping the server to keep the connection alive

When testing I got crash by running DEBUG version, but RELEASE version runs well
```
my_proj: /usr/include/boost/beast/core/detail/stream_base.hpp:80: boost::beast::detail::stream_base::pending_guard::pending_guard(bool &): Assertion `! b_' failed.
[1]    3905731 IOT instruction (core dumped)
```

### Version

Beast 300
Boost 1.74

### Steps necessary to reproduce the problem
It is a private project so can not disclose, just show how it works

- `async_write()` only called when sending request to subscribe data
- After subscribe successfully only `async_read()` and `async_ping()` will be called
- No multi-threading
- When connection ends, the caller will re-create a MyClient instance to subscribe data

```cc
class MyClient {
    unsigned ping_interval_;
    uint64_t last_ping_ts_;

    using read_buffer_t = boost::beast::flat_buffer;
    read_buffer_t read_buffer_;
    read_buffer_t response_buffer_;

    std::mutex loop_mtx_;
public:
    ...

    void Loop(const atomic_bool* shutdown) {
        std::unique_lock loop_lock{loop_mtx_, std::try_to_lock};
        if (!loop_lock.owns_lock()) {
            return;
        }

        while (!*shutdown) {
            ws_ = make_unique<...>(io_context_, ssl_context_);
            StartStream(); // Resolve, Connect, Handshake, etc
            io_context_.restart();

            while (!io_context_.stopped() && !*shutdown) {
                boost_error_code_t ec;
                io_context_.run_one(ec);
                if (ec) {
                    break;
                }
            }

            io_context_.stop();
            
            if (!reconnect_ || *shutdown) {
                break;
            }
            std::this_thread::sleep_for(5s);
        }
    }

    void OnHandshake(const boost_error_code_t handshake_ec) {
        return OnStreamStart();
    }

    void OnStreamStart() {
        ReadStream(
            &response_buffer_,
            [this](const boost_error_code_t connection_error, const std::string_view data) {
                OnConnectionResponseRead(connection_error, data);
        });
    }

    void OnConnectionResponseRead(const boost_error_code_t ec, const std::string_view raw_data) {
        Send(request_str_, [this](const boost_error_code_t connection_error, const std::size_t write_size) {
            OnSubscriptionRequestSend(connection_error, write_size);
        });
    }

    void Send(std::string data, auto&& on_write) {
        auto        data_storage = std::make_unique<std::string>(std::move(data));
        const auto& data_to_send = *data_storage;
        ws_->async_write(
            boost::asio::buffer(data_to_send),
            [data_storage = std::move(data_storage),
             on_write     = std::move(on_write)](const auto ec, const auto bytes_transferred) {
                on_write(ec, bytes_transferred);
            });
    }

    void OnSubscriptionRequestSend(const boost_error_code_t ec, const std::size_t bytes_written) {
        ReadStream(
            &response_buffer_,
            [this](const boost_error_code_t connection_error, const std::string_view data) {
                OnSubscriptionResponseRead(connection_error, data);
            });
    }

    void OnSubscriptionResponseRead(const boost_error_code_t ec, const std::string_view data) {
        if (IsSubscriptionOK(data)) {
            ReadStream(&read_buffer_, [this](const boost_error_code_t ec, const std::string_view raw_data) {
                StreamReadStep(ec, raw_data);
            });
            return;
        }

        // LOG error and retry
    }

    void ReadStream(read_buffer_t* read_buffer, auto&& on_read) {
        read_buffer->clear();
        ws_->async_read(
            *read_buffer,
            [on_read = std::move(on_read), read_buffer](const auto ec, const auto /* bytes_transferred */) {
                on_read(ec, std::string_view(static_cast<const char*>(read_buffer->cdata().data()), read_buffer->size()));
        });
    }

    void StreamReadStep(const boost_error_code_t ec, const std::string_view raw_data) {
        OnRead(raw_data);
        ReadStream(
            &read_buffer_,
            [this](const boost_error_code_t err_code, const std::string_view read_raw_data) {
                StreamReadStep(err_code, read_raw_data);
        });
    }

    void OnRead(const std::string_view data) {
        ParseData(data);
        
        // Only ping after data processed
        if (GetCurrentTimestamp() - last_ping_ts_ >= ping_interval_) {
            Ping();
        }
    }

    void Ping() {
        ...
        async_ping(ping_data, [](...){});
        last_ping_ts_ = GetCurrentTimestamp();
    }
};
```

### All relevant compiler information
LLVM 14.0

### More info
I found the [doc](https://www.boost.org/doc/libs/1_74_0/boost/beast/core/detail/stream_base.hpp)
```cc
        explicit
        pending_guard(bool& b)
            : b_(b)
        {
            // If this assert goes off, it means you are attempting
            // to issue two of the same asynchronous I/O operation
            // at the same time, without waiting for the first one
            // to complete. For example, attempting two simultaneous
            // calls to async_read_some. Only one pending call of
            // each I/O type (read and write) is permitted.
            //
            BOOST_ASSERT(! b_);
            b_ = true;
        }
```

So it seems that there are concurent `async_read()`s or `async_write()`s, but I can not find them from the code.

So RELEASE build removes `BOOST_ASSERT(...)`, if concurent `async_read()`s or `async_write()`s cause bug, why only DEBUG build enable the check?

**Comment by klemens-morgenstern** [comment]
I would guess that you're having concurrent ping & read operations going on. You must wait for one to complete before initiating the other.

**Comment by klemens-morgenstern** [comment]
Ok, I guess I was wrong. Can I see more of your impl, i.e. how you call async_read?

**Comment by klemens-morgenstern** [comment]
Who is calling `OnSubscriptionResponseRead` ?

**Comment by klemens-morgenstern** [comment]
I think I found it: you are not waiting for the Ping to complete before initiating another one. Sounds minor, but that could be the issue. can you add code to make sure only one `async_ping` is active at one time?


The `ReadData` doesn't do anything async I assume?

What's the `        // LOG error and retry` in OnSubscriptionResponseRead ? 

Am I getting this right below?

```cpp
    
OnHandshake ->  OnStreamStart

OnStreamStart -> ReadStream >> OnConnectionResponseRead
OnConnectionResponseRead -> Send >> OnSubscriptionRequestSend
OnSubscriptionRequestSend -> ReadStream >> OnSubscriptionResponseRead
OnSubscriptionResponseRead -> ReadStream >> ReadStreamStep (const boost_error_code_t ec, const std::string_view     StreamReadStep -> ReadStream >> StreamReadStep
```

**Comment by klemens-morgenstern** [comment]
Are you running this on a strand or a single thread?

**Comment by klemens-morgenstern** [comment]
I will need a building piece of code that crashes. I can't figure it out by just looking into code snippets.

**Comment by horry-wang** [comment]
using the following C# client code can enable advanced_server_flex.cpp replication
`
using System.Net.Security;
using System.Net.Sockets;
using System.Text;

static async Task RequestAsync(Stream stream)
{
    //string str = "GET /test HTTP/1.1\r\nConnection: Keep-Alive\r\nContent-Length: 0\r\n\r\nGET /trmstatus HTTP/1.1\r\nConnection: Keep-Alive\r\nContent-Length: 0\r\n\r\n";
    string str = "GET /test HTTP/1.1\r\nConnection: Keep-Alive\r\nContent-Length: 0\r\n\r\n";
    var bytes = Encoding.UTF8.GetBytes(str);
    await stream.WriteAsync(bytes);
    var bb = new byte[4096];
    var len = await stream.ReadAsync(bb);
    while (len > 0)
    {
        Console.WriteLine("\r\n===============\r\n");
        Console.WriteLine(Encoding.UTF8.GetString(bb, 0, len));
        len = await stream.ReadAsync(bb);
    }
}

Console.WriteLine("Hello, World!");
TcpClient client = new TcpClient();
client.Connect(System.Net.IPAddress.Parse("127.0.0.1"), 8888);
using SslStream sslStream = new SslStream(client.GetStream(), false);
sslStream.AuthenticateAsClient("gj.gdfsrzcz.xyz");
await RequestAsync(sslStream);
await RequestAsync(sslStream); //there will be problems here
`

**Comment by klemens-morgenstern** [comment]
Glad you found it.
