### ISSUE TITLE
How to stream HTTP response as a `std::basic_istream` (or something like that)

### ISSUE THREAD

**Issue by jviotti** [boostorg/beast#2708]
Hey there! I'm looking for an example on how I can perform an HTTP request, but instead of getting the response as a single `std::string`, get it as it comes as a standard input stream or something like that.

Do you have an examples at hand?

### Version of Beast

I'm on version 347.

**Comment by klemens-morgenstern** [comment]
We do not. You could just use a stringstream to wrap an existing string-body I think.

**Comment by ashtum** [comment]
@jviotti is this still open?

**Comment by jviotti** [comment]
@ashtum , as @klemens-morgenstern mentioned, this is not supported at the moment.

**Comment by ashtum** [comment]
@jviotti You can adapt your own custom type as a message body, here is an example that read and write to/from an `asio::streambuf`: https://godbolt.org/z/hEG6eMq4Y

**Comment by jviotti** [comment]
Interesting. Thanks! I'll close this then!
