### ISSUE TITLE
How does a client ping server proactively and periodically?

### ISSUE THREAD

**Issue by zptan** [boostorg/beast#2711]
My app is a client that subscribes data from a server, the server requires the client to ping periodically (e.g., every 15s), and the ping payload must be in a specific format (so the automatic ping does not work), or the connection will be ended by the server.

A common solution: create a thread that periodically send a ping. But I read some posts and found: _**websocket does not support multi-threading**_.

If the data is pushed frequently by the server, we can ping after reading the data (passive ping), but it is not a general case.

So how does a client do these jobs in a single thread?
- Receive data from the server
- Ping the the server periodically with specific payload

### Version of Beast
Beast 300
Boost 1.74

**Comment by klemens-morgenstern** [comment]
By using the `async_*` APIs. You will find plenty examples in the repository and you should have a look at asio::steady_timer.

**Comment by klemens-morgenstern** [comment]
No they're not thread-safe either. But they're non-blocking so you can have multiple operations going on at the same time.

**Comment by klemens-morgenstern** [comment]
What exactly do you want to do? Trigger a message periodically? Look into asio::steady_timer then. You .async-wait the thing and then trigger what you need to do.
