### ISSUE TITLE
Plans for WebTransport support

### ISSUE THREAD

**Issue by jcelerier** [boostorg/beast#2736]
Hello! 

Are there plans for supporting this new protocol? It has been available for a year and a half-ish in browsers: https://developer.mozilla.org/en-US/docs/Web/API/WebTransport

**Comment by klemens-morgenstern** [comment]
There are not. Beast is in maintenance mode.

**Comment by vinniefalco** [comment]
HTTP/3 lol

**Comment by jcelerier** [comment]
I assume no chance for it in Beast (or anywhere in boost) either?

**Comment by vinniefalco** [comment]
HTTP/3 and SPDY are boondoggles

**Comment by jcelerier** [comment]
I mean maybe but at some point some service is going to expose a WebTransport endpoint only and I'll want to connect to it from C++ code - or conversely, some standard protocol for $whatever will emerge on top of WebTransport which i'll want to provide a performant backend for

**Comment by jcelerier** [comment]
e.g. there's currently standardisation effort towards some new low latency media stack for web browsers, based on WebTransport - and C++ is going to be a major implementation language for this kind of backend (low-latency multimedia processing and streaming)

**Comment by vinniefalco** [comment]
That is very nice but the amount of work to design and implement a conforming library is way beyond my abilities, or desire.
