### ISSUE TITLE
How to use flat_buffer correctly

### ISSUE THREAD

**Issue by romanholidaypancakes** [boostorg/beast#2741]
Currently I'm trying to use the beast asynchronous client, but I'm getting the following problem during testing:
1. `flat_buffer` occasionally causes the program to crash
2. `async_write` occasionally fails to deliver messages to the server

I realized that I may have overlooked something, I am using this example: [websocket_client_async.cpp](https://github.com/boostorg/beast/blob/develop/example/websocket/client/async/websocket_client_async.cpp), here is my simplified code

[example.txt(updated)](https://github.com/boostorg/beast/files/12667465/example.txt)

I tried looking for documentation, but I only found this page [boost__beast__flat_buffer](https://www.boost.org/doc/libs/1_83_0/libs/beast/doc/html/beast/ref/boost__beast__flat_buffer.html) that looked relevant, nothing Any help.

I am using boost 1.83.0.

**Comment by klemens-morgenstern** [comment]
The example you link to doesn't use the buffer simultaneously and only clears it in the write.

Do you have some updated code that doesn't use a shared buffer that I could look at?

**Comment by klemens-morgenstern** [comment]
Where did you upload the code? Maybe create a gist?

**Comment by klemens-morgenstern** [comment]
Your usage of the timer is causing UB, as you may have overlapping reads and writes. For example: you might be in an async_write, the timer triggers and clears the buffer during the write. That would be UB and might lead the your observation.

You have to ensure that only one write & one read are happening at a given time.

I personally like to use coroutines to achieve that. If you're on C++20 you should use asio::awaitable, before you can use asio::spawn with boost.context.

**Comment by klemens-morgenstern** [comment]
You'd need to either us a channel (see asio::experimental::channel) or keep a flag to check if you triggered a read/write already. You can't just randomly trigger writes from multiple places.
