### ISSUE TITLE
Client Async Read/Write example

### ISSUE THREAD

**Issue by rajasurampalli** [boostorg/beast#2746]
Hi,

I have used the same code mentioned in the examples https://www.boost.org/doc/libs/1_83_0/libs/beast/example/http/client/async-ssl/http_client_async_ssl.cpp to perform Async Read/Write operation on client side. 
Unfortunately the beast is throwing the error **The requested address is not valid in its context** in on_connect method. 

However I'm able to resolve it with  the following code snippet(this is sync code)
       
       // The io_context is required for all I/O
        net::io_context ioc;

        // The SSL context is required, and holds certificates
        ssl::context ssl_context(ssl::context::sslv23_client);
 
        // These objects perform our I/O
        tcp::resolver resolver(ioc);
 
        // Look up the domain name
        auto const results = resolver.resolve("mywebsite", "https");

### Version of Beast

1.83

### Steps necessary to reproduce the problem

Copy the code available in https://www.boost.org/doc/libs/1_83_0/libs/beast/example/http/client/async-ssl/http_client_async_ssl.cpp and modify according to your website/apis.

**Comment by klemens-morgenstern** [comment]
How did you invoke the example code? What website did you look up?

**Comment by rajasurampalli** [comment]
its a proprietary website hosted on AWS cloud. I'm able to do synchronous read and write however. 
Wanted to perform an asynchronous read/write.
example: mywebsite.com, api: api/v1/test.
The API information passed to "target".
command line: <host> <port> <target>

**Comment by rajasurampalli** [comment]
I'm sorry I don't have access to the server side code. By the way, I'm able to connect synchronously having an issue during async mode only. So I think it is something to do with the client side.
FYI, the server side code is written in many languages like GoLang, Python, Java etc.

**Comment by ashtum** [comment]
@rajasurampalli It seems the issue is that you are unable to connect to the resolved address. You may want to print the resolved address and check its validity. This is not a Boost.Beast or Boost.Asio issue; you may need to investigate further to understand the reasons for encountering this error: https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2?redirectedfrom=MSDN
