### ISSUE TITLE
One socket connection multiple channel

### ISSUE THREAD

**Issue by ksohan** [boostorg/beast#2753]
Is it possible to create multiple channel in one socket connection so that different request's responses are sent over different channels of the connection. If yes, is there any example of how to do that?

**Comment by ashtum** [comment]
> Is it possible to create multiple channel in one socket connection so that different request's responses are sent over different channels of the connection. If yes, is there any example of how to do that?

Could you please explain what you mean by `multiple channels in one socket`? are you referring to `asio::experimental::channel` ?

**Comment by ksohan** [comment]
I am actually not much familiar `asio::experimental::channel`. So let me explain the scenario, After the client is connected to the server, it subscribes for data. I have two types of data in JSON format which needs to be sent continuously upon subscription.
1. Data1: {"x": 11, "y": 12}
2. Data2: {"x": 100, "z" : 35}

Now these two types of data are being sent over the socket connection and the client has no way to distinguish which data type is the current received data. That's why I was asking about channel so that I can send data1 in one channel and data2 in another channel.

**Comment by fpelliccioni** [comment]
Before diving into potential solutions, could you confirm if you're using TCP sockets or WebSockets for your communication?

As far as I know, in TCP sockets, there's no built-in concept of "channels". Given that you're working with JSON, typically you would need to distinguish between the data types at a higher layer where you parse the JSON.

Once you confirm the type of socket you're using, we can discuss more detailed solutions tailored to your setup.

**Comment by ksohan** [comment]
I am using [this](https://github.com/boostorg/beast/tree/develop/example/websocket/server/chat-multi) example.

**Comment by vinniefalco** [comment]
Add another key/value pair to identify the entity:
```
Data1: { "x": 11, "y": 12, "id" : 1 }
Data2: { "x": 100, "z" : 35, "id" : 2 }
```
