### ISSUE TITLE
Cannot connect to beast based SSL WebSocket server from Windows Chrome WS...

### ISSUE THREAD

**Issue by Honya2000** [boostorg/beast#2772]
Hello,

I'm creating basic SSL WebSocket client / server app.
The source code is basically the same as in beast examples: async-ssl for both client and server.
For the server i'm using CA certificate i obtained recently....

 I could esablish connection and send the data from beast client, Win Firefox, iOS (both Safari and Chrome).
But it doesn't work completely from Windows Google Chrome. 
Chrome WS just reports in the console:
WebSocket connection to 'wss://hon.....org:9090/svc' failed

While server throws error on first read operation:
read: stream truncated

I have spent 2 days trying to make it working with Chrome without success.
Tried all the options on the server side here:
                ssl::context ctx{ ssl::context::tlsv13 };

                ctx.set_default_verify_paths();

                ctx.set_options(
                    boost::asio::ssl::context::default_workarounds |
                    //boost::asio::ssl::context::no_compression |
                    boost::asio::ssl::context::no_sslv2 |
                    boost::asio::ssl::context::no_sslv3 |
                    //boost::asio::ssl::context::no_tlsv1 |
                    boost::asio::ssl::context::verify_none
                    //boost::asio::ssl::context::single_dh_use
                );

Nothing works. 
First read in this sequence just fails with zero size buffer...

                void on_accept(beast::error_code ec)
                {
                    if (ec)
                        return fail(ec, "accept");

                    // Read a message
                    do_read();
                }

                // Read chain
                void do_read()
                {
                    // Read a message into our buffer
                    ws_.async_read(buffer_, beast::bind_front_handler(&wsSession::on_read, shared_from_this()));
                }
Not sure why this read happens at all, since client just fails to connect - it doesn't send anything!
When i debug the server connection from Firefox - first data server gets on read - is what the client actually sent.
But Chrome doesn't sent anything....

My previous SSL WS server based on civetweb lib - is working fine with windows chrome.
But if i'm trying to use websocketpp based server or beast (both are based on the same asio) - it doesn't work with the same truncated stream error.

I got out of ideas.
Any help will be appreciated!

**Comment by ashtum** [comment]
@Honya2000, if I understand correctly, it seems that when you connect using Chrome, the code reaches the `on_accept()` function without encountering any errors. This suggests that both the SSL handshake and Websocket handshake are performed without any issues.
You might be able to obtain more information about the error in the `Network` tab of Chrome DevTools.

**Comment by Honya2000** [comment]
Yes, server got on_accept without errors.
Then first read gives truncated stream error, Second on_read gives operation_aborted.

Looks some http / websocket negotiation just fails, probably headers parsing, not sure.
Pretty sure will get the same error if i would compile websocket example in beast, since i'm using the same code.

Checked Chrome console - it shows request header, but doesn't show Received header (seems nothing was received).
Request header looks like this:

Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,ru;q=0.7,de;q=0.6
Cache-Control: no-cache
Connection: Upgrade
Host: h...org:9090
Origin:
http://h....org:88
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: BjKTdimxZCmtJKTvOQBovw==
Sec-Websocket-Protocol: text
Sec-Websocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by ashtum** [comment]
> Pretty sure will get the same error if i would compile websocket example in beast, since i'm using the same code.

I highly recommend starting with the websocket_server_async_ssl example in the example directory. I'm using Chrome and had no problem connecting to the example server.

**Comment by Honya2000** [comment]
Btw if I remove my SSL cerificate related code, i cannot even connect to the server from Chrome.
Server just throws the error:
handshake: sslv3 alert certificate unknown (SSL routines, ssl3_read_bytes)

So how did you test it with the default example?

**Comment by Honya2000** [comment]
Ok, I replaced OpenSSL for beast to the newest one OpenSSL 3.3 (spent several hours to compile it). Thought probably some old openssl functionality doesn't work properly.
Unfortunately this didn't change anything. Still getting the same error: stream truncated from chrome.

**Comment by ashtum** [comment]
@Honya2000, I have no idea how to replicate the issue. are you suggesting that connecting to `websocket_server_async_ssl` with a connection from Chrome on a Windows machine should give a similar error?

**Comment by Honya2000** [comment]
Yes, as i mentioned yesterday - unmodified example websocket_server_async_ssl - doesn't work with chrome due to ssl certificate issue.
If i'm using my certificate in the example - it gives the same error as in my project with truncated stream.

And it happens only on desktop chrome, both windows and mac (mobile iOS chrome is working).
Even iOS is working which is definitely doesn't accept self signed certificate.

**Comment by Honya2000** [comment]
When i analyze the websocket/read.hpp different functions - i see it reads the first upgrade header from the server. But have no clue why it doesn't send responce to the server, but call on_read callback instead.

Trying to use boost log to log internal events, but cannot compile it due to hundreds boost libs dependencies...

**Comment by Honya2000** [comment]
This is my server: https://honya.myftp.org:9090/

When i enter it from Chrom - i get:
The WebSocket handshake Connection field is missing the upgrade token

**Comment by ashtum** [comment]
> When I enter it from Chrome - I get:
> The WebSocket handshake Connection field is missing the upgrade token

This is expected because the server treats every connection as a WebSocket connection and expects an HTTP upgrade request. I just wanted to see if there is any issue with the certificate.

> This is my server: https://honya.myftp.org:9090/

I can confirm it is impossible to connect from Chrome in windows. Please use the websocket_server_async_ssl example on the server side without any modifications and check if the problem persists.

**Comment by Honya2000** [comment]
Please read my messages above. Yesterday i tried unmodified example and ssl handshake failed because of certificate issues in the example.

With my certificate - i got the same truncated message error.
But it is not my certificate issue because:
1. iOS, Android, and desktop firefox clients are working with my server.
2. Desktop Chrome can connect to my server based on different websocket backend (civetweb) using the same certificate.

All asio based servers are fail to accept connections from Desktop Chrome (tested websocketpp, and beast)

**Comment by ashtum** [comment]
What platform does your server use?
I'm using Linux for running websocket_server_async_ssl example and it works fine when I connect from Chrome in Windows.

**Comment by Honya2000** [comment]
i'm on windows.
Probably this is the issue? beast just doesn't work properly on windows?

**Comment by Honya2000** [comment]
tomorrow will try to adjust chrome security setting to fix certificate issues with unmodified example.
But doubt it will fix anything...

**Comment by ashtum** [comment]
I don't think it is a beast issue, because we run CI in Windows platforms too.
Is it possible for you to test another platform and report the results?
Tomorrow I'll try to replicate the server in a Windows platform.

**Comment by Honya2000** [comment]
It could be beast or asio. If the issue is reproducible in websocketpp i would assume the issue is in asio, since it uses asio only.
Testing on another platform wouldn't be easy right now because i need to install linux on windows machine.
Much easier would be to connect chrome to unmodified async-ssl websocket example.

**Comment by Honya2000** [comment]
Ok, i finally was able to fix chrome issue.
It turned out when i created WebSocket connection in JS code - i specified sub-protocol string "binary" and the client didn't like response from the server and closed connection immediately.
I tried to create WS without the sub-protocol string and magic, everything works!
Sorry for false alarm.
