### ISSUE TITLE
read message error: wrong version number (SSL routines, ssl3_get_record)

### ISSUE THREAD

**Issue by romanholidaypancakes** [boostorg/beast#2774]
### Version of Beast

1.83

### Steps necessary to reproduce the problem
When my client (beast) sends a message to the server, the server can receive the message normally, but when the server replies to the client, the client will read an error:
```
wrong version number (SSL routines, ssl3_get_record)
```
Did I miss something?
The client uses beast, and the server uses other projects.

**Comment by ashtum** [comment]
Could you please provide more information about your code? Are you connecting through a proxy?

**Comment by ashtum** [comment]
In which handler are you getting the error, `on_read` ?

**Comment by ashtum** [comment]
What is your platform and version of OpenSSL?
