### ISSUE TITLE
Discarding request body without needing a temporary buffer

### ISSUE THREAD

**Issue by ecorm** [boostorg/beast#2794]
How can I efficiently discard a request body without needing to use a temporary `string_body` or `vector_body`?

My use case is an HTTP REST server using a configurable map of request-target strings to handler functions. When a request-target is not found in the map, the server should flush the request body and send a 404 response back to the client, while maintaining the persistent (Keep-Alive) HTTP connection. I can flush the request body easily enough via a `string_body` or `vector_body`, but I was wondering how to flush the body bytes without dynamically allocating memory, or using a dedicated static "flush buffer".

I thought of using `empty_body`, but the documentation says:

> ... the parser will fail with the error `http::unexpected_body`

Is my best bet to write a custom Body class for this purpose?

**Comment by ecorm** [comment]
I just realized after asking that I'm using a `http::request_parser<http::string_body>` to perform the initial `http::async_read_header`. I probably can't just use a different `http::request_parser<flush_body>` to read the remainder of the request because there's presumably no way to transfer the parsing state from one parser to another.

I'm also incurring the cost of dynamic allocations via `http::request_parser<http::string_body>` for legitimate request-targets anyway. There's probably no point in avoiding that cost when the request-target is not found.

**Comment by ashtum** [comment]
You can utilize a [http::buffer_body](https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/ref/boost__beast__http__buffer_body.html) that points to a static buffer for that purpose, these examples might help:
https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/more_examples/http_relay.html
https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/using_http/parser_stream_operations/incremental_read.html

**Comment by ecorm** [comment]
> You can utilize a `http::buffer_body`

Yes, I know. I just have to decide if it's better to use one large (1MiB by default) `http::buffer_body` per client session, or use a `string_body` with the assumption that most request bodies will be small. The server is not intended to be used in a large-scale manner, and I don't have much time to perform stress tests, so I have to pick a reasonable approach and live with it.

**Comment by ecorm** [comment]
> I just have to decide if it's better to use one large (1MiB by default) `http::buffer_body` per client session

No, that's not scalable at all, even at the smallish scale I intent to use the server on a Raspberry Pi-like device. Probably better to use `string_body`, watch for `bad_alloc` failures, and do graceful degradation when needed.

**Comment by ecorm** [comment]
I've studied the incremental reading example more closely, and I think I understand things better now. I think what I need is a `parser<basic_dynamic_body<static_buffer>>`, which I can use to incrementally append data to a `std::string` to obtain a contiguous request body. In my use case where the request-target is not found, I still do the incremental reading, but simply ignore the intermediate data.
