### ISSUE TITLE
multiplexing

### ISSUE THREAD

**Issue by djn3m0** [boostorg/beast#2802]
Hi,

I'm trying to manage different connections through one connection. I haven't seen any clear example or document on how to do so. Does Boost Beast support multiplexing?

If yes please provide a clue on how I can achieve it, if not, please tell me if you have any idea how I can achieve this.

Thanks

**Comment by ashtum** [comment]
Do you mean multiplexing in WebSocket? If so, there is no standardized method for multiplexing messages within a single stream. This task is considered a higher-level responsibility for the user. For instance, if you are working with JSON messages, you might structure them as follows:
 ```JSON
{
  "stream_id": "1",
   "payload": "..."
}
```

**Comment by djn3m0** [comment]
Do you know any project that has implemented this?

**Comment by ashtum** [comment]
> Do you know any project that has implemented this?

Not that I'm aware of. but it shouldn't be difficult to implement. what is the message format that you are using?

**Comment by djn3m0** [comment]
I'm trying to write a WebSocket tunnel that can accept multiple TCP connection and send them through WebSocket.

**Comment by ashtum** [comment]
Your message format should be in binary. A straightforward method of multiplexing involves appending a single byte to the start of each message, indicating the stream's state and ID. You may find the followings useful: https://ckousik.github.io/gsoc/2017/06/16/WebSocket-Multiplexer-Overview.html
https://github.com/xtaci/smux
