### ISSUE TITLE
http::async_read hides client disconnection errors

### ISSUE THREAD

**Issue by ecorm** [boostorg/beast#2806]
`http::async_read` does not report client disconnection errors. When a client disconnects before starting to send an HTTP header, `http::async_read` will emit an `http::error::bad_method` error. Because I can't distinguish a disconnection error from a genuine bad HTTP method error, this prevents me from properly logging what happened.

I would expect `http::async_read` to emit the original `boost::asio::error::broken_pipe` or `boost::asio::error::connection_reset` error instead of absorbing it.

The same problem occurs with `http::async_read_header`.

### Version of Beast

` BOOST_BEAST_VERSION 347`

### Steps necessary to reproduce the problem

1. Launch [asynchronous HTTP server example](https://www.boost.org/doc/libs/1_82_0/libs/beast/example/http/server/async/http_server_async.cpp)

2. Start a Telnet session with the server.

3. Terminate the Telnet session via Ctrl-C so that it disconnects from the server.

4. The server prints `read: bad method` instead of `read: Connection reset by peer`.

**Comment by vinniefalco** [comment]
If the underlying socket returns a non-successful error code, this should be propagated to the caller and not returned as a parsing error. This first needs a failing test case.

**Comment by ecorm** [comment]
> This first needs a failing test case.

Was that directed to me, or to the maintainers?

**Comment by vinniefalco** [comment]
> Was that directed to me, or to the maintainers?

I wasn't directing it to anyone just stating a fact for whoever works on this. There is no requirement for the reporter of the problem to first write a test case. Of course, if you provide one we will be happy for the contribution :)

Thanks

**Comment by ecorm** [comment]
I'll wait a while, and if nobody contributes a failing test case, I'll see if I can whip one up to get the ball rolling on this issue.

**Comment by ashtum** [comment]
@ecorm, it seems that when trying to end the Telnet session using Ctrl-C, it writes `^C` characters to the socket. The parser attempts to parse them, resulting in a `bad method` error.

However, using the following method yields the expected result:
> To exit the Telnet session, type Ctrl + ] on your keyboard. This changes the command prompt to show as telnet>. Back in the terminal, type in the word 'close' to close the session.

**Comment by ecorm** [comment]
> @ecorm, it seems that when trying to end the Telnet session using Ctrl-C, it writes ^C characters to the socket. The parser attempts to parse them, resulting in a bad method error.

Ah, that was a blunder on part. Sorry for all the ruckus. Tomorrow, I'll try closing Telnet properly and will confirm that my server receives the expected error code upon disconnection.
