### ISSUE TITLE
Question: Can Beast run on top of Unix domain sockets (aka `local::stream_protocol`)?

### ISSUE THREAD

**Issue by Alexander-Shukaev** [boostorg/beast#2829]
Can Beast run on top of Unix domain sockets (aka `local::stream_protocol`)?

Thanks.

**Comment by ashtum** [comment]
You can pass a different protocol to [beast::basic_stream](https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/ref/boost__beast__basic_stream.html), for example:
```C++
using stream_t = beast::basic_stream<asio::local::stream_protocol>;
```

**Comment by Alexander-Shukaev** [comment]
So does this imply that TCP is not essential for Beast framework (HTTP/websocket in general)?  I am a bit surprised here.

**Comment by ashtum** [comment]
No, there is no coupling to TCP streams, as long as the underlying stream meets the requirements, it can be used for HTTP and WebSocket operations: https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/concepts/streams.html

**Comment by vinniefalco** [comment]
TCP is not essential, but you will need to implement the `teardown` and `async_teardown` customization points for your stream type (Unix domain sockets in this case) when using beast websockets.
