### ISSUE TITLE
Beast Server Unable to Serve JavaScript-Enabled Web Pages/Apps

### ISSUE THREAD

**Issue by vtharmalingam** [boostorg/beast#2833]
### Version of Beast
1.84

### Steps necessary to reproduce the problem
[Advanced, flex (plain + SSL](https://www.boost.org/doc/libs/master/libs/beast/example/http/server/fast/http_server_fast.cpp)

I was able to run the server. It serves a simple HTML that i placed under _doc_root.
But when I put a JS app, this is not serving the page. 

Here is what I did:

1. Pulled this source : [React Sample App](https://github.com/andrewagain/calculator)
2. Did `npm install` and `npm build`. That created build files inside `build` dir
3. Dropped that inside _doc_root

I just get to see this when I opened the browser:

![image](https://github.com/boostorg/beast/assets/7923720/4809deb4-ab3b-4e57-936b-67ba480bf7fe)

Please provide guidance on extending the Beast server to support a JavaScript-rich application (like that one above). I aim to integrate my backend (Beast) with the frontend (React JS) hosted by the same beast server (without having to rely on another WS like Apache or similar). The reason is that as there will be hardly five users who will use the frontend on this server (the front-end necessarily have to be rich enough to support JS), and the rest will use only the the backend (beast WebSocket). 

Thanks for your advice.

Thanks,
Tharma

**Comment by ashtum** [comment]
The HTTP server example functions as a basic static web server and doesn't provide any additional features for the React application. It appears that the index.html has been successfully loaded.
I suspect the problem might lie with the React application. Are you sure that it has been built properly?

**Comment by vtharmalingam** [comment]
Yes, it was built properly. When we do `npm start`, the node is able to deliver the content like this:

![image](https://github.com/boostorg/beast/assets/7923720/7d93a3be-4a46-4dad-a073-20c02bda28a8)

**Comment by ashtum** [comment]
You can check your browser's developer tools to see if any resources fail to load.

**Comment by vtharmalingam** [comment]
Thank you, @ashtum. I am debugging and keep you posted.
