### ISSUE TITLE
Session communication without Mutex?

### ISSUE THREAD

**Issue by vtharmalingam** [boostorg/beast#2858]
1.84

### Older  version 
Concerning session communication (with client), I had developed an app using beast example a few years ago.
Wherein i used "mutex" for guarding the write as well as "vector" for queuing the messages, etc. Here is a snippet of how it is:

```cpp

// a global instance of std::mutex to protect
global variable std::mutex myQueueMutex;


std::vector<std::shared_ptr<const std::string>> queue_;

```
And my write function is like this:

```cpp

void ssl_websocket_session::on_write(beast::error_code ec, std::size_t) 
{ 
    std::lock_guard<std::mutex> guard(myQueueMutex); 
    { 
        //... <you write to your session> 
    } 
    
}


```

### In the latest example,
When I recently studying the latest examples, I found that this part of the code has been migrated, made bit simpler and perhaps sounds more efficient too—without mutex and vector. All managed through "buffer". I am looking for your guidance on whether I can migrate to this one without any drawbacks.

```cpp

// we use the buffer
beast::flat_buffer buffer_;

```

And we use this write function

```cpp

    void
    on_write(
        beast::error_code ec,
        std::size_t bytes_transferred)
    {
        boost::ignore_unused(bytes_transferred);

        if(ec)
            return fail(ec, "write");

        // Clear the buffer
        buffer_.consume(buffer_.size());

        // Do another read
        do_read();
    }

```

Thanks in advance!

Regards,
Tharma

**Comment by vinniefalco** [comment]
The point of the mutex is that foreign threads can concurrently call a "send" function to add the string to a queue. If you want that feature then you have to have the mutex. Alternatively you can call `asio::post` to submit a function object which, when invoked, adds the string to the `vector` without the need for a mutex. But note that `asio::post` uses an internal mutex.

If you are worried about performance, don't be. There is little to no contention for the lock, as the mutex is held for the shortest possible time, and you don't have such a large number of threads trying to queue a string at the same time that the performance would matter.

**Comment by vtharmalingam** [comment]
Very helpful, thank you, @vinniefalco.

**Comment by vtharmalingam** [comment]
Quick follow-up question, @vinniefalco:  Is `std::vector<std::shared_ptr<const std::string>>` the recommended container for the message `queue_` ? Maybe I am missing, in the recent example, `vector` was not found used, but instead some sort of buffer was used?

**Comment by ashtum** [comment]
@vtharmalingam, is this issue still open or has the problem been resolved?
