### ISSUE TITLE
Beast shouldn't have a root Jamfile

### ISSUE THREAD

**Issue by anarthal** [boostorg/beast#2862]
### Version of Beast

develop

### Steps necessary to reproduce the problem

The new Boost superproject has been changed to load all Jamfiles in project roots. This pours test definitions into all Boost, causing failures like https://drone.cpp.al/boostorg/mysql/660/12/3

@grafikrobot should have a PR soon to fix this.

**Comment by ashtum** [comment]
Addressed in #2905.
