### ISSUE TITLE
any_executor_base::destroy_object and any_executor_base::copy_object high CPU usage

### ISSUE THREAD

**Issue by gunzino** [boostorg/beast#2892]
Hello,

### Beast Version: 300

I've developed WebSocket server based on Beast which accepts a lot of messages of small size.  The program needs quite a lot of CPU resources to work, perf shows it's mostly those functions:
boost::asio::execution::detail::any_executor_base::copy_object<boost::asio::io_context::basic_executor_type<std::allocator<void>, 4u> >
boost::asio::execution::detail::any_executor_base::destroy_object<boost::asio::io_context::basic_executor_type<std::allocator<void>, 4u> >

Server has about 250 open connections, accepting about 20 messages/second per connection. Message size between 100-5000 bytes.

Is it indended behavior?

![image](https://github.com/boostorg/beast/assets/6863683/74bbed76-cb41-4af8-9d56-732584b17ebb)

**Comment by ashtum** [comment]
Please make sure you are building the application in release mode. Boost.Beast and Boost.Asio have a lot of indirection and generic functions, which result in a very slow debug executable.

You can eliminate the need for `any_executor` by using a concrete executor type, for example:
```C++
using tcp_stream = beast::basic_stream<
    asio::ip::tcp,
    asio::io_context::executor_type,
    beast::unlimited_rate_policy>;
```
or if you are using a strand:
```C++
using tcp_stream = beast::basic_stream<
    asio::ip::tcp,
    asio::strand<asio::io_context::executor_type>,
    beast::unlimited_rate_policy>;
```

However, given your load (250 connections, 20 req/s each), this seems an unnecessary optimization. What is your total CPU usage for running your application?

**Comment by gunzino** [comment]
@ashtum 
My CPU usage just became 100%, that's how I've noticed it. It's single core cheap VPS but still.

Currently using -Ofast, will try to compile also without debug symbols (-DNDEBUG).

**Comment by ashtum** [comment]
> @ashtum My CPU usage just became 100%, that's how I've noticed it. It's single core cheap VPS but still. Currently using -Ofast, will try to compile also without debug symbols (-DNDEBUG).

100% CPU usage for 5k messages/second is unusual; you can typically expect around 50k on a single core (assuming no other tasks are consuming significant processing power). I believe compiling without debug symbols won't help much. What CPU usage do you observe when running it on your desktop?

> Your code suggestion is not friend with my code.

You need to use concrete executor types for `tcp::acceptor` and `tcp::socket` as well:
```
using acceptor_t = tcp::acceptor::rebind_executor<asio::io_context::executor_type>::other;
using socket_t = tcp::socket::rebind_executor<asio::io_context::executor_type>::other;
```
However, as I mentioned, this change won't make your code significantly faster, expect around a 5% improvement at most.

**Comment by gunzino** [comment]
@ashtum 
I've done some more tests. After I start the app and connections are created (no matter about amount) everything works normally, CPU usage is very low even with 500 connections.

After about 12 hours of running the CPU usage of the executors goes to 100%. Is it possible there is an issue somewhere in my code? In the callback functions?

**Comment by ashtum** [comment]
Are you using a multi-threaded executor? I'm afraid you might have unintentionally created an infinite loop somewhere in your code, probably by not checking the error code of an operation and retrying it.

**Comment by gunzino** [comment]
@ashtum 

Thanks for the fast reply!! That may explain the case...I will let post more info soon
