### ISSUE TITLE
SSL mode not handshake happening 

### ISSUE THREAD

**Issue by EkbalCode** [boostorg/beast#2894]
I am using example/http/client/async-ssl/http_client_async_ssl.cpp 

// The SSL context is required, and holds certificates
    ssl::context ctx{ssl::context::tlsv12_client};

    // This holds the root certificate used for verification
    load_root_certificates(ctx);

    // Verify the remote server's certificate
    ctx.set_verify_mode(ssl::verify_peer);

This code execution not making handshake so in turn I am getting 404 status code .

Kindly help

**Comment by ashtum** [comment]
> This code execution not making handshake so in turn I am getting 404 status code .

The handshake happens in the following line, what is the error message on failure?
```
        // Perform the SSL handshake
        stream_.async_handshake(
            ssl::stream_base::client,
            beast::bind_front_handler(
                &session::on_handshake,
                shared_from_this()));
```

> This code execution not making handshake so in turn I am getting 404 status code .

Do you mean an HTTP 404 error? this shouldn't be related to hanshake process because if the connection fails to perform the handshake correctly it can't make any request at all.
