### ISSUE TITLE
Websocket example

### ISSUE THREAD

**Issue by Dimitrius-dev** [boostorg/beast#2917]
Hello,
Boost=1.84.0, BOOST_BEAST_VERSION=351
I am using boost/beast websocket TLS async client example [link](https://github.com/boostorg/beast/blob/develop/example/websocket/client/async-ssl/websocket_client_async_ssl.cpp). I noticed my connection disconnects sometimes with `stream truncated` and `eof`. What do these errors mean? I checked my internet connection with wireshark and it's fine.

**Comment by ashtum** [comment]
Do they happen at the end of stream? [error::stream_truncated](https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/using_io/ssl_tls_shutdown.html#beast.using_io.ssl_tls_shutdown.error_stream_truncated)

**Comment by Dimitrius-dev** [comment]
No, i get these errors without calling any shutdown or disconnect function. And it shows when use client for high load traffic (high frequency).

**Comment by ashtum** [comment]
Are you sure it’s not the server that dropped the connection? Does this happen with just one specific server?

**Comment by Dimitrius-dev** [comment]
Can connection issues occur while multiply connections use load_certificates function?

**Comment by ashtum** [comment]
Do you mean `load_root_certificates`? it calls [ssl::context::add_certificate_authority](https://www.boost.org/doc/libs/1_86_0/doc/html/boost_asio/reference/ssl__context/add_certificate_authority.html) which is not thread safe.

**Comment by ashtum** [comment]
Do they have their own `ssl::context` too?

**Comment by Dimitrius-dev** [comment]
yes

**Comment by ashtum** [comment]
Have you tried reducing your application to a single connection and a single thread to see if the issue still exists? If possible, test one of the existing examples.
