### ISSUE TITLE
Moving *this before calling get_immediate_executor() causes undefined behavior

### ISSUE THREAD

**Issue by Jackarain** [boostorg/beast#2925]
In the following code, std::move(*this) is used before calling get_immediate_executor(). This can result in undefined behavior, as the this object may become invalid after the move operation.

https://github.com/boostorg/beast/blob/21545dbcaf22d21ba72c0021dae0ee85c7004fc5/include/boost/beast/core/impl/basic_stream.hpp#L328-L330

**Comment by ashtum** [comment]
@Jackarain Thanks for reporting this. I can confirm that this is a bug, as the order of evaluation of function arguments is unspecified and move and happen before dereferencing `this`.

**Comment by Jackarain** [comment]
感谢您的回复，以及迅速的作出修复，感谢

**Comment by vinniefalco** [comment]
Great work, @Jackarain :) thanks.
