### ISSUE TITLE
Investigate proxygen message model

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#340]
Proxygen has a complex message model tailored for specific use cases:
https://github.com/facebook/proxygen/blob/master/proxygen/lib/http/HTTPHeaders.h

It should be possible to write a suitable beast Fields wrapper that transports a `proxygen::HTTPMessage` so it can be packaged into a `beast::message` container.

**Comment by vinniefalco** [comment]
One solution is to use argument dependent lookups as a customization point for serialization, e.g. a call to a non-namespace qualified function, e.g.
```
template<class DynamicBuffer, class Fields>
void
write_fields(DynamicBuffer& buffer, Fields const& f);
```

This can be overloaded for user defined fields types. This doesn't address the handling of the start line or the trailers. But perhaps it can be extended. This solves the problem where proxygen fields use the visitor pattern instead of iterators.

**Comment by vinniefalco** [comment]
There is progress here with **FieldsReader**

**Comment by vinniefalco** [comment]
This no longer seems important, but the HTTP Refactor should review Proxygen's features when redesigning the header container.

**Comment by vinniefalco** [comment]
proxygen's message model sucks :)

**Comment by sehe** [comment]
> proxygen's message model sucks :)

ROFL progressing insight :)
