### ISSUE TITLE
Use BOOST_MSVC

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#371]
Check all use of `_MSC_VER` see if the defects are still present in the minimum required version and if not, remove it.

Otherwise use `BOOST_MSVC`, check the version if possible, use the workaround in the most narrow scope.

>if at all possible, leave some clue as to why that code is there.. ideally a link to a bug report for a workaround

**Comment by glenfe** [comment]
Something like `#if BOOST_WORKAROUND(BOOST_MSVC, < 1910)`  would be ideal.

**Comment by vinniefalco** [comment]
`#if BOOST_WORKAROUND(BOOST_MSVC, < version)`  or if all versions up until the current version exhibit that problem, something like: `#if BOOST_WORKAROUND(BOOST_MSVC, BOOST_TESTED_AT(current))`.    Boost.Config is the better detection mechanism generally

**Comment by vinniefalco** [comment]
What about here
https://github.com/vinniefalco/Beast/blob/master/extras/beast/unit_test/dstream.hpp#L17

**Comment by glenfe** [comment]
Add OutputDebugStringA and OutputDebugStringW to Boost.WinAPI. See https://github.com/boostorg/winapi

**Comment by glenfe** [comment]
And leverage BOOST_WINDOWS detection macro to identify Windows (more so than just MSVC).

**Comment by vinniefalco** [comment]
DONE
