### ISSUE TITLE
support fancy pointers

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#407]
Allocator-aware containers should use `pointer_traits` and this utility (part of Boost now I think)

```
template <class Ptr>
typename pointer_traits<Ptr>::element_type* to_address(Ptr p) noexcept
{
return to_address(p.operator‐>());
}
template <class T>
T* to_address(T* p) noexcept
{
return p;
}
```

**Comment by glenfe** [comment]
`#include <boost/core/pointer_traits.hpp>`

Given a pointer `p` of type `P` you can use the following to get a raw pointer:

`boost::pointer_traits<P>::to_address(p)`

e.g.

```cpp
P pointer = allocator.allocate(size);
new(boost::pointer_traits<P>::to_address(pointer)) T(std::forward<Args>(args)...);
```

**Comment by vinniefalco** [comment]
Don't forget to add a test to make sure it actually works.

**Comment by vinniefalco** [comment]
I would like to make `basic_fields` an ordinary class instead of a class template, and supporting fancy pointers directly would complicate that. No one is asking for fancy pointers, and there is no strong case for the benefits relative to the cost.
