### ISSUE TITLE
Use test allocators for allocator-aware containers

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#411]
Maybe there's some in Boost, but @HowardHinnant has a set of allocators that stresses out containers when used in instantiations. We can use this to check Beast's allocator-aware containers.

**Comment by HowardHinnant** [comment]
They're all somewhere under here in the libc++ repository: https://github.com/llvm-mirror/libcxx/tree/master/test  The exercise the fancy pointer capabilities and everything else.
