### ISSUE TITLE
Review layout of space-critical classes

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#421]
Critical classes like `header`, `message`, `basic_fields` should have their members reviewed to determine if a rearrangement of order results in a space savings.

**Comment by vinniefalco** [comment]
See https://wandbox.org/permlink/7jGi94XsRIxgbCmq

**Comment by glenfe** [comment]
Make the following change to Empty in the unit test empty_base_optimzation_test.cpp and observe which C++ implementations fail to compile it, in various C++ standard modes:

```cpp
struct Empty final {
    operator bool() { return true; }
};
```

**Comment by vinniefalco** [comment]
Done
