### ISSUE TITLE
Tidy up type traits

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#466]
Worth 1k words
![image](https://user-images.githubusercontent.com/1503976/27011403-e9f7b1a2-4e6f-11e7-85e6-e822c52d0e16.png)

**Comment by vinniefalco** [comment]
See:
https://github.com/boostorg/core/commit/6153eebc42b07d80afb9d3f90b959361681cfe06

**Comment by vinniefalco** [comment]
@glenfe How should this look
```
template<class T>
struct is_sync_read_stream<T, detail::void_t<decltype(
    std::declval<std::size_t&>() = std::declval<T>().read_some(
        std::declval<detail::MutableBufferSequence>()),
    std::declval<std::size_t&>() = std::declval<T>().read_some(
        std::declval<detail::MutableBufferSequence>(),
        std::declval<boost::system::error_code&>()),
            (void)0)>> : std::integral_constant<bool,
    has_get_io_service<T>::value
        > {};
```

**Comment by glenfe** [comment]
> See: boostorg/core@6153eeb

Except we're back to the void_t<decltype(expr)> style in Core now. :)

**Comment by vinniefalco** [comment]
What should my example code look like? I se your commit was reverted
