### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#504]
To make sure the **Fields** concept is well specified, there should be a couple of example implementations of **Fields** in the test or example dirs.

**Comment by gyfscx** [comment]
i don't found it, where the file for custom field?thanks a lots.

**Comment by vinniefalco** [comment]
>where the file for custom field?
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/concepts/Fields.html

**Comment by terrywh** [comment]
I'm trying to implement a custom fields container. There is one concept description about `FieldsWriter`:

* `F` denotes a __Fields__ where
      `std::is_same<W, F::reader>::value == true`.

but i don't see any `reader` defined in `http::fields`. Is that a mistake ?

**Comment by vinniefalco** [comment]
> i don't see any reader defined in http::fields

That should say `F::writer`, I'll fix the docs

> i just have to implement a `parser` as well ?

Yes, and you need to derive your parser from `basic_parser` for it to work with the HTTP stream algorithms.

**Comment by vinniefalco** [comment]
Is anyone using this custom Fields feature? I am very likely going to remove it since it hasn't worked out the way I thought it would.

**Comment by feverzsj** [comment]
I tried to derive from http::fields, but the parser only accepts the original fields

**Comment by vinniefalco** [comment]
Yes the parser only uses the original fields

**Comment by vinniefalco** [comment]
Fields concept was a mistake
