### ISSUE TITLE
rfc7230 exists()

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#516]
We might want to rename these to something like `ifound`, `icount`, or `iexists` or otherwise use an identifier that communicates the case-insensitive nature of the comparison.

**Comment by klemens-morgenstern** [comment]
This is a breaking change and the PR is 5 years old, is still open? Or should we just leave it as is?

**Comment by vinniefalco** [comment]
sheeeit... close this stat

**Comment by vinniefalco** [comment]
I don't think its a good idea in the first place I mean `isize()` wtf? That makes no sense
