### ISSUE TITLE
mutable_buffer_body

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#538]
`buffer_body` has a shortcoming, you cannot assign const buffers and use it with a serializer without a `const_cast` (unacceptable in modern code). We could add a `mutable_buffer_body` and change `buffer_body::value_type::data` to `void const*`, and cut out the writer. This highlights a problem with the HTTP relay example though: https://github.com/vinniefalco/Beast/issues/537

See: https://github.com/vinniefalco/Beast/issues/535

**Comment by vinniefalco** [comment]
See https://github.com/vinniefalco/Beast/issues/580

**Comment by klemens-morgenstern** [comment]
I think it would be better to add a `const_buffer_type` now, given the API break in the above proposal.

**Comment by vinniefalco** [comment]
If this can be fixed by adding one line of code (a nested type) great. Otherwise, well... it isn't holding anything up so we can just close it.

**Comment by klemens-morgenstern** [comment]
I'll close it then, user issues should have higher priority.
