### ISSUE TITLE
istream, ostream Stream adapters

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#560]
The documentation suggests that serializing and parsing between ostreams and istreams could be done with stream wrappers, the examples should include both of these and they should be added to the docs.

**Comment by klemens-morgenstern** [comment]
Would this be an io_stream_body? If so example or code?

**Comment by vinniefalco** [comment]
I don't think this is necessary and no it would not be an io_stream_body, this would be an asio SyncReadStream / SyncWriteStream (Which might even already exist).

**Comment by klemens-morgenstern** [comment]
This is sadly not trivial and it's also just useful for a hello world example, so I agree it's not necessary.
