### ISSUE TITLE
Read entire message in http-server-fast

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#574]
http-server-fast would be even faster if it didn't split the read. @chriskohlhoff what do you think?

**Comment by chriskohlhoff** [comment]
Seems reasonable, so I updated my copy with this change (and some other tweaks) here:

https://gist.github.com/chriskohlhoff/b0ba99a54c9ca6fcd5918592902fd434

**Comment by vinniefalco** [comment]
Would you mind if I attach your GitHub id to the commit? Since I am just taking everything you wrote and updating Beast sources with it?

**Comment by vinniefalco** [comment]
Done
