### ISSUE TITLE
http::get_error_category()

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#588]
This needs to be a public interface or else there is no way to check if an error code belongs to http! Same with the other categories.

**Comment by vinniefalco** [comment]
See https://akrzemi1.wordpress.com/2017/08/12/your-own-error-condition/#comment-6954

**Comment by vinniefalco** [comment]
HTTP errors should get the same treatment as WebSocket, by adding an error condition and revising all of the error codes to have more verbose messages.

**Comment by arrtchiu** [comment]
In case someone else runs into this, my workaround for now is this:

```c++
if (ec == boost::beast::http::make_error_code(boost::beast::http::error::body_limit)) {
  // do what you need to do when body-limit is exceeded
}
```

A bit ugly but for only one error (in my case) that's alright and doesn't rely on the `detail` namespace.

**Comment by vinniefalco** [comment]
What's wrong with
```
if (ec == boost::beast::http::error::body_limit)
```
?

**Comment by vinniefalco** [comment]
This issue is not an actual problem. There is no need to retrieve the HTTP error category. However, it would be nice to have error codes mapped to error conditions (in the manner of websocket) and to have more descriptive error codes. This is already in another open issue.

**Comment by arrtchiu** [comment]
> What's wrong with `if (ec == boost::beast::http::error::body_limit)`

Good point, I must've been having a slow brain day!

If I was handling more of these error codes, being able to use a `switch` statement would be useful - something like this:

```c++
if (ec.category() == boost::beast::http::get_error_category()) {
  switch (static_cast<boost::beast::http::error>(ec.value()) {
    //...
  }
}
```

I'm reasonably new to boost/asio so maybe this kind of pattern is frowned upon, though. Open to feedback if you've got the time to spare :)

**Comment by vinniefalco** [comment]
```
if(ec.category() == beast::error_code(static_cast<beast::http::error>(0)).category())
    ...
```
