### ISSUE TITLE
Comparison to Pion

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#602]
>Since the documentation features comparison with other libraries, it may be worth comparing pion (https://github.com/splunk/pion) as well.

**Comment by mika-fischer** [comment]
While you're at it, a comparison to uWebSockets would also be interesting
https://github.com/uNetworking/uWebSockets

**Comment by ksergey** [comment]
Also with libwebsockets

**Comment by vinniefalco** [comment]
LOL come on now guys, do you want me writing code or writing comparisons? :)

**Comment by mika-fischer** [comment]
I would find a comparison to uWebSockets interesting, since it's similar in scope, is modern C++ and claims to be much faster, more memory-efficient and more scalable than beast.

**Comment by vinniefalco** [comment]
Well there's not much to say, uWebSockets is non-Asio and hardly Modern C++. It does achieve better performance and memory usage, although there are questions about whether the benchmarks measure real-world use. As uWebSockets doesn't track any networking standard, I don't feel particularly motivated to form a comparison.

**Comment by vinniefalco** [comment]
I'm going to close this since its a bit out of scope in the near to medium term but we can revisit it later
