### ISSUE TITLE
websocket server ssl example

### ISSUE THREAD

**Issue by nguoithichkhampha** [boostorg/beast#634]
websocket server ssl would be very useful.

**Comment by vinniefalco** [comment]
https://github.com/vinniefalco/Beast/blob/develop/example/server-framework/wss_ports.hpp#L103

I will also add a more simple example soon

**Comment by nguoithichkhampha** [comment]
thanks for your support. anyway, I have an question ?
when I should set auto fragment , when should not. I confuse with this option.

**Comment by vinniefalco** [comment]
It depends on the value you choose for autofragment. 64K isn't going to reduce performance. 1K might. You want autofragment if your messages are big and you need to be responsive to pings.
