### ISSUE TITLE
Head request for large file (10MiB) causes error::body_limit

### ISSUE THREAD

**Issue by dirkvdb** [boostorg/beast#742]
When performing a head request on a large file the error::body_limit error gets triggered. This is probably the logic of a get request that checks if the file fits in the body data structure. But it should not happen for head requests.

### Version of Beast
Current master
d337339c028f247a91a9b2e771e7b31a085496aa

### Steps necessary to reproduce the problem
Perform a head request of a large file

**Comment by ksergey** [comment]
see http://vinniefalco.github.io/beast/beast/ref/beast__http__basic_parser/body_limit.html

**Comment by vinniefalco** [comment]
Beast's HTTP operations are "stateless" with respect to successive messages. So the library has no way to know that you sent a HEAD request, and that the response will not have a body. You have to tell Beast not to expect a body. This is done by calling `basic_parser::skip(true)`:
```
response_parser<string_body> p;

// Tell the parser not to expect a body
p.skip(true);
```

**Comment by vinniefalco** [comment]
Please give **version 106** a try:
https://github.com/boostorg/beast/pull/741

Feel free to leave comments in the Pull Request if you would like to review that code.

Thanks!

**Comment by dirkvdb** [comment]
Ok, thanks. Works fine the skip call.
