### ISSUE TITLE
http_server_fast process request one by one 

### ISSUE THREAD

**Issue by maytrue** [boostorg/beast#749]
I use demo http_server_fast as media server.

Suppose there are two clients. Client one request video file and server return data, Client two need wait for sending complete( server to client one)  , then got data.

How to modify demo to serve multi client simultaneously？

Thanks!

**Comment by vinniefalco** [comment]
What do you mean? Separate connections are processed simultaneously. Why do you think that a client would have to wait for an unrelated connection to finish?

**Comment by maytrue** [comment]
I use argument "0.0.0.0 9000  ./path 3 spin".

Client one send get request to http_server_fast, and http_server_fast send back a large file.
Client two send get request to http_server_fast at the same and client two got connected until all data are sent to client one.

Forgive my bad English!

**Comment by maytrue** [comment]
I am sorry, it is my fault.

I modify 
`   http::async_write(
                          socket_,
                          *file_serializer_,
                          [this](boost::beast::error_code ec)
                          {
                              socket_.shutdown(tcp::socket::shutdown_send, ec);
                              file_serializer_.reset();
                              file_response_.reset();
                              accept();
                          });`

to 
`//        http::write(socket_, *file_serializer_, ec);
//        socket_.shutdown(tcp::socket::shutdown_send, ec);
//        file_serializer_.reset();
//        file_response_.reset();
//        file.close();
//        accept();`

**Comment by vinniefalco** [comment]
Glad you figured it out!
