### ISSUE TITLE
Should messages be EqualityComparable?

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#763]
While writing unit tests I ran into a quality of life issue - messages are not comparable:
```
boost::beast::http::request<boost::beast::http::string_body> sent_request, received_request;
// roundtrip through a custom stream
BOOST_CHECK_EQUAL(sent_request, received_request); // does not compile
```
Is it intended that they are not comparable?

**Comment by vinniefalco** [comment]
Equality comparison opens up a huge can of worms. What if the fields are in different order? What if the field names have a different capitalization? For testing what I do is just convert them to string (e.g. `boost::lexical_cast<std::string>(m)` and compare that way.

**Comment by djarek** [comment]
Okay, haven't thought about that. I guess converting the message into a string should be good enough.
