### ISSUE TITLE
The HTTP sync client example fails if using HTTP 1.0

### ISSUE THREAD

**Issue by sorf** [boostorg/beast#767]
The http_client_sync.cpp example fails with: 
```
Error: end of stream
```
if using HTTP 1.0 instead of 1.1 

### Version of Beast
112

### Steps necessary to reproduce the problem
The code change to expose the problem:
https://github.com/sorf/cpp-libraries-tests/commit/5271a80e7812a2310dd2fa8c2823b08f70636ab8#diff-ec9843e2cca371ed43d59757896fd2a3

### All relevant compiler information

It happens on both Windows (Visual Studio 17 and MinGW gcc 7.1) and on Linux (gcc 7 and clang 3.8).
The test program is run with the suggested parameters:
```
www.example.com 80 /
```

curl shows that www.example.com accepts both HTTP 1.1 and 1.0:

```
>curl -v --http1.0 -o /dev/null www.example.com
<snip>
* Connected to www.example.com (93.184.216.34) port 80 (#0)
> GET / HTTP/1.0
> User-Agent: curl/7.37.0
> Host: www.example.com
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
<snip>
< Content-Length: 1270
< Connection: close
<snip>
```
```
>curl -v --http1.1 -o /dev/null www.example.com
<snip>
* Connected to www.example.com (93.184.216.34) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.0
> Host: www.example.com
> Accept: */*
>
< HTTP/1.1 200 OK
<snip>
< Content-Length: 1270
<snip>
```

**Comment by vinniefalco** [comment]
This is working as designed. `http::write` (and `http::async_write`) will return `http::error::end_of_stream` when the message being sent indicates that the connection should be closed. You need to modify the example thusly:
```
try {
    http::write(socket, req);
}
catch(beast::system_error const& se) {
    if(se.code() != http::error::stream_closed)
        throw;
    socket.shutdown(tcp::socket::shutdown_send);
}
```

**Comment by vinniefalco** [comment]
You could argue that perhaps we should change this behavior. For example, to only happen when writing a response.

**Comment by sorf** [comment]
I think it's fine the way it is even for the request side, now that I know of it.
Maybe a change similar to: https://github.com/sorf/cpp-libraries-tests/commit/0f18c59a002043b7830c66afac6c030697186571 can make its way in the example?

**Comment by vinniefalco** [comment]
Not a bad idea!

**Comment by vinniefalco** [comment]
The client examples can be modified to allow choosing the HTTP version.

**Comment by vinniefalco** [comment]
>I think it's fine the way it is even for the request side, now that I know of it.

Hmm.. no, I don't like it. Because it is confusing to return an error even when the operation is successful. And when using exceptions it breaks the flow of control for nothing. I have made the change, it is in version 124. I like your change with the HTTP version but it would need to be applied to all the clients, can you submit a pull request against 124?

**Comment by sorf** [comment]
> I like your change with the HTTP version but it would need to be applied to all the clients, can you submit a pull request against 124?

Please see pull request #833.
