### ISSUE TITLE
how to post large string body

### ISSUE THREAD

**Issue by haike1363** [boostorg/beast#771]
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::length_error> >'
  what():  field value too large

**Comment by haike1363** [comment]
i can set a large body, but beast can not fit the length automatic?

**Comment by vinniefalco** [comment]
It looks like you are trying to set a header field to a string larger than 64KB - that is too large! Did you mean to set the body instead? Can you provide some example code which demonstrates your problem?

**Comment by haike1363** [comment]
thank you！the problem is that you have indicated
       // request
        const std::string& body = data_points_[done_ % data_points_.size()];
        //req_.set(http::field::body, body); // it is the  problem!!!
        req_.body = body;

**Comment by vinniefalco** [comment]
Glad to hear you got it sorted, thanks!

**Comment by vinniefalco** [comment]
By the way, it looks like you are making a copy of the string. If you know that the string is going to exist, you can use `request<span_body<char>>` instead of `request<string_body>` and make it a non-owning reference.
