### ISSUE TITLE
 Is the minimum required version of cmake really important is 3.5.2?

### ISSUE THREAD

**Issue by d3roch4** [boostorg/beast#811]
In ubuntu 16.04, the default version of cmake is 3.5.1 and the new version of compile the new version of much work.
I've created a fork just to change the `cmake_minimum_required (VERSION 3.5.1)` line and it's working for me.

**Comment by vinniefalco** [comment]
CMake works for you on Ubuntu? Which version of Beast are you using?

**Comment by vinniefalco** [comment]
I can bump it down and see what happens

**Comment by d3roch4** [comment]
Isso use beast Master git in Ubuntu 16.04 with cmake 3.5.1


Em 09/10/2017 17:04, "Vinnie Falco" <notifications@github.com> escreveu:

CMake works for you on Ubuntu? Which version of Beast are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/boostorg/beast/issues/811#issuecomment-335270869>, or mute
the thread

**Comment by vinniefalco** [comment]
Okay, well I pushed a new version that lowers the requirements to 3.5.1 and it seems okay. Does it work for you?

**Comment by d3roch4** [comment]
Yes!
Thank You

2017-10-14 1:21 GMT-03:00 Vinnie Falco <notifications@github.com>:

**Comment by vinniefalco** [comment]
Glad to hear it!

**Comment by vinniefalco** [comment]
Looks like we're set here so I'll go ahead and close the issue, thanks!
