### ISSUE TITLE
LAST CALL FOR CHANGES BEFORE BOOST 1.66.0 !!!!

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#812]
Beast is scheduled for its initial release in Boost 1.66.0. The cutoff for making code changes is October 25th. If anyone has an issue they think needs to be addressed, no matter if it is cosmetic, a bug, something with the documentation, or a feature, then they need to speak up now by opening an issue - I will get to it right away if I can! Otherwise, what we have now at the tip of **master** is what will ship!

**Comment by syedalamabbas** [comment]
Great work! I stumbled upon this after going through other libraries such as Microsoft's cpprestsdk (https://github.com/Microsoft/cpprestsdk), libsourcey( https://sourcey.com/libsourcey/), libwebsockets and websocketapp (https://github.com/zaphoyd/websocketpp). Yours is the best one, I am going to use it in my project, thanks.

Alam

**Comment by generationtech** [comment]
^Ditto. I went through all that stuff too without success before finding Vinnie's work. Beast websockets is a lynchpin for an important project of mine. Kudos to 1.66.0

**Comment by vinniefalco** [comment]
I appreciate the kind words! "libsourcey" that's a new one...and quite a lot of features on that library!

**Comment by daleysoft** [comment]
Thank you for your amazing contribution to the open source community!

**Comment by fcharlie** [comment]
I do not think that beast is suitable for the general environment, Beast is slightly more complex to use, beast should be added to such simple packaging as Golang .NET `HttpClient`, and Golang HttpServer .Net  `KestrelHttpServer`. 

I use C + + to write `Git Smart Http Server`, which require Http Server library and HttpClient library (authentication required). 
After examining most of the C + + HTTP server libraries, I finally had to implement HTTP server myself.
httpclient use cpprestsdk. 
Then I spent a few days using Golang to implement the Git HTTP server (No OpenSource).

This is my Git Server based on .Net(KestrelHttpServer) implementation: https://github.com/fcharlie/Angelo

Does beast plan to enter the C + + standard library? If you want a standard, I suggest that you consider the needs of the average developer.

**Comment by vinniefalco** [comment]
>When will beast be able to implement this function in such a simple way?

This is addressed in the FAQ
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/design_choices/faq.html

**Comment by liuaifu** [comment]
When will release 1.66 beta1?

**Comment by vinniefalco** [comment]
>When will release 1.66 beta1?

@pdimov ?

**Comment by pdimov** [comment]
See the calendar at http://www.boost.org/development/index.html

**Comment by vinniefalco** [comment]
Looks like November 15

**Comment by vinniefalco** [comment]
Boost 1.66.0 is on schedule for December 13th release. It is about to be closed for changes, thanks everyone!
