### ISSUE TITLE
URL path after handshake?

### ISSUE THREAD

**Issue by daleysoft** [boostorg/beast#816]
I'm building a websocket server which handles clients differently based on the URL path supplied by the client during the handshaking process. I've been digging around in stream.hpp for a bit and can't seem to find a way to retrieve the URL path after the handshaking process has completed. Is this not a feature?

Thanks for any help!

**Comment by daleysoft** [comment]
Found it! async_accept_ex

**Comment by vinniefalco** [comment]
Excellent!
