### ISSUE TITLE
[Question] Write: protocol is shutdown

### ISSUE THREAD

**Issue by Randshot** [boostorg/beast#821]
Hello,

I am basing my code on your crawl example: https://github.com/boostorg/beast/blob/develop/example/http/client/crawl/http_crawl.cpp

I tried to convert the code to use https, instead of http, but when I use
```c++
stream_.shutdown(ec);
```
the next request fails with the error: `Write: protocol is shutdown`

And using
```c++
stream_.next_layer().shutdown(boost::asio::socket_base::shutdown_both, ec);
stream_.next_layer().close(ec);
```
results in
```
Read: wrong version number
Read: internal error
Read: internal error
[...]
```

**Comment by vinniefalco** [comment]
Are you calling `ssl::stream::handshake`? Can you post the program?

**Comment by Randshot** [comment]
Yes I am calling handshake().

Anyway, here is the program.
[requester.zip](https://github.com/boostorg/beast/files/1403659/requester.zip)

**Comment by vinniefalco** [comment]
I don't think you can re-use the `ssl::stream`, you have to destroy it and recreate it. You can store the stream in a `boost::optional` and call `optional::emplace` to achieve that.

**Comment by Randshot** [comment]
Ok I will try that.
Where should I call emplace?
Right after shutdown or when I get the next request.

**Comment by vinniefalco** [comment]
Call `emplace` before you establish a new connection

**Comment by Randshot** [comment]
It works now, but it is very slow :/
Anyway thanks for your help :)

**Comment by abhiarora4** [comment]
Can you help me in getting the same thing for boost websocket? I am using 1.68 version.

**Comment by StavrosMar** [comment]
i see some commits , is it fixed now or need to create a new object if i need to reconnect ?

**Comment by ashtum** [comment]
> i see some commits , is it fixed now or need to create a new object if i need to reconnect ?

[websocket::stream::async_close](https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/async_close.html) and [websocket::stream::close](https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/close.html) close the underlying stream once the close procedure is complete. you need to create a new stream.

**Comment by StavrosMar** [comment]
ok thanks, maybe somethiing to add in the future as I wanted to avoid that
