### ISSUE TITLE
asio/associated_allocator.hpp only exists in the standalone Asio version

### ISSUE THREAD

**Issue by theodelrieu** [boostorg/beast#840]
Hi there.

I've tried to build a small example program with the latest master version (127), that simply includes `boost/beast.hpp`:

> fatal error: boost/asio/associated_allocator.hpp: No such file or directory

It seems that this file was added on the standalone Asio repository 3 months ago, but is not in the latest Boost release (1.65.1).

I feel like I've missed something obvious, since nobody reported it before...

**Comment by vinniefalco** [comment]
If you're using the **master** branch of Beast, then you also need to use the **master** branch of all the other Boost libraries. There's no sane way for me to support Boost 1.65.1 anymore, since we are just about to release Boost 1.66.0 (which will include Beast).

**Comment by vinniefalco** [comment]
I have pushed the **v124** tag so you can easily check out the version of Beast which is not updated for Net.TS-flavored Asio: https://github.com/boostorg/beast/tree/v124

**Comment by theodelrieu** [comment]
That makes sense, looking forward to 1.66, meanwhile I'll be using v124. Thanks!
