### ISSUE TITLE
Use beast via CMake

### ISSUE THREAD

**Issue by EdvardD** [boostorg/beast#846]
Is it possible to use beast from my project by CMake command find_package?

**Comment by djarek** [comment]
```
find_package(Boost 1.66 COMPONENTS system REQUIRED)
```

This is sufficient (please note that cmake scripts don't support Boost 1.66 yet and will present a warning:

```
-- clang-format found: /usr/bin/clang-format
CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 106600
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:6 (find_package)


-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   system
*** Finished ***

```

You can safely ignore the warnings.

**Comment by EdvardD** [comment]
I use Boost 1.58 and it's difficult to update it (a lot of services should be updated). Is it possible to use Beast with Boost 1.58?
I find out that Beast was compatible with Boost 1.58 until previous week.

**Comment by vinniefalco** [comment]
If you want to use Beast with Boost 1.58 you should use the **v124** tag: https://github.com/boostorg/beast/tree/v124

**Comment by EdvardD** [comment]
Thanks
