### ISSUE TITLE
No implementation for boost::beast::static_buffer_base::static_buffer_base()

### ISSUE THREAD

**Issue by ksergey** [boostorg/beast#862]
Beast v124

I try to implement own buffer type based on static_buffer_base.
But looks like implementation of static_buffer_base constructor is not exists.

Possible fix (=default)
```c++
protected:
    /** Constructor

        The buffer will be in an undefined state. It is necessary
        for the derived class to call @ref reset in order to
        initialize the object.
    */
    static_buffer_base() = default;
```

**Comment by vinniefalco** [comment]
Yes! Thank you, this will be fixed in 133. I would be interested to hear how your derived class turns out!

**Comment by ksergey** [comment]
Nothing special
```c++
     class flat_buffer final
         : public boost::beast::static_buffer_base
     {
     private:
         std::unique_ptr< char[] > storage_;

     public: 
         flat_buffer(const flat_buffer&) = delete;
         flat_buffer& operator=(const flat_buffer&) = delete;

         explicit flat_buffer(std::size_t capacity)
             : boost::beast::static_buffer_base{0, 0} 
             , storage_(new char[capacity])
         {
             reset(storage_.get(), capacity);
         } 
     };    
```

**Comment by vinniefalco** [comment]
So you are building a circular buffer with dynamic allocation?

**Comment by ksergey** [comment]
Yes. I can't use `static_buffer<...>`, because buffer size (`capacity` in my code) is configurable value.

**Comment by vinniefalco** [comment]
Makes sense. Note that beast has a `flat_buffer`, but it works differently (it is not circular).

**Comment by vinniefalco** [comment]
This should be fixed now, please let me know if it gives you trouble again!
