### ISSUE TITLE
Broken link to documentation in GitHub header

### ISSUE THREAD

**Issue by ldionne** [boostorg/beast#863]
The link to documentation on the GitHub repository header is broken. When I click on http://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast.html, I see:

![screen shot 2017-11-02 at 14 40 03](https://user-images.githubusercontent.com/700834/32351763-c154176c-bfdb-11e7-816c-b92119628fec.png)

**Comment by vinniefalco** [comment]
Where are you getting the link from? All the doc links seem to work for me.

**Comment by ldionne** [comment]
Sorry; from the header there: 
<img width="1060" alt="screen shot 2017-11-02 at 14 57 56" src="https://user-images.githubusercontent.com/700834/32352420-6905b37e-bfde-11e7-8be9-c5edbc6a0bba.png">

**Comment by vinniefalco** [comment]
Excellent, I don't need a new branch to fix that :)

**Comment by vinniefalco** [comment]
Looks like this is fixed so I'll go ahead and close the issue; thanks!
