### ISSUE TITLE
Setting WebSocket User-Agent?

### ISSUE THREAD

**Issue by NuSkooler** [boostorg/beast#878]
This is only a question. Is it possible to get the User-Agent when using WebSocket streams (e.g. `websocket::stream<tcp::socket>`)? Am I missing something here?

**Comment by vinniefalco** [comment]
You can get the User-Agent as a server by reading in the request yourself, inspecting the field, then calling `stream.accept` or `stream.async_accept` and passing the request. You can set the User-Agent as a client by calling `stream.handshake` or `stream.async_handshake` and providing a "decorator." This is explained in the documentation:
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/using_websocket/handshaking_clients.html#beast.using_websocket.handshaking_clients.decorators
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html#beast.using_websocket.handshaking_servers.passing_http_requests

**Comment by NuSkooler** [comment]
@vinniefalco Perfect, thank you!
