### ISSUE TITLE
what's the meaning of ws.text() and ws.get_text()?

### ISSUE THREAD

**Issue by liuaifu** [boostorg/beast#879]
```
ws.read(buffer);
ws.text(ws.got_text());
ws.write(buffer.data());
```
what's the meaning of ws.text() and ws.get_text()?

**Comment by vinniefalco** [comment]
`text()`
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/text/overload1.html

`got_text()`
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/got_text.html
