### ISSUE TITLE
Websocket: MSG_DONTWAIT emulation on `websocket::stream::read`

### ISSUE THREAD

**Issue by mstanichenko** [boostorg/beast#893]
Dear @vinniefalco,

I would like `websocket::stream::read` function call to return immediately if there are no data and block if there are some data to process. In other words, I'd be glad to pass a flag which has the same meaning as `MSG_DONTWAIT` (see [man recv](http://man7.org/linux/man-pages/man2/recv.2.html)). My application is single-threaded and I am not allowed to spawn extra threads.

Would you be so kind as to advice whether I can emulate such a behavior?

Thank you very much in advance.

**Comment by vinniefalco** [comment]
Are you calling `io_service::run()`?

**Comment by vinniefalco** [comment]
It sounds like you want to operate the websocket stream in non-blocking mode.

**Comment by mstanichenko** [comment]
> It sounds like you want to operate the websocket stream in non-blocking mode

My application is single-threaded. I have an external dispatcher which calls my component. Once called, my component is supposed to check the data availability. I cannot block as there are other components to dispatch.

May be I can call `recv` or `read` somehow and pass data further `websocket`

**Comment by vinniefalco** [comment]
It is not a supported mode of operation. But you can try setting the socket into non-blocking mode and using beast's synchronous interfaces, and see if it works. You would just have to ignore the "would block" errors and try again later.

**Comment by mstanichenko** [comment]
> But you can try setting the socket into non-blocking mode

Could you please advise how one can assess the underlying socket?

**Comment by vinniefalco** [comment]
>Could you please advise how one can assess the underlying socket?

http://www.boost.org/doc/libs/1_65_1/doc/html/boost_asio/reference/basic_socket/native_non_blocking/overload3.html

**Comment by mstanichenko** [comment]
I took `websocket_client_sync_ssl.cpp` as a baseline.

When I use this
```c++
ws.lowest_layer().native_non_blocking(true, ec);
std::cout << "EC = " << ec << std::endl;
```
I can see the output `EC = system:0` but my process is permanently in `S`-state which means it's blocking.

I also tried

```c++
ws.lowest_layer().non_blocking(true);
```

But I never got data with it

**Comment by vinniefalco** [comment]
I don't think it will work with SSL

**Comment by vinniefalco** [comment]
I'm sorry but this is not a supported mode. I don't see how it could be made to work with SSL.

**Comment by mstanichenko** [comment]
No problem, you did a great job with such a nice library. Much appreciated.

Would you be able to briefly describe what is wrong with a combination of non-blocking mode and SSL? Do you think I could apply simple changes to my local repository to make it work?

**Comment by vinniefalco** [comment]
When you perform a read in OpenSSL, the implementation can perform both reads and writes to fulfill that read. When you attempt an operation on a non-blocking socket that would block, an error is generated (EWOULDBLOCK). In order to make non-blocking work, the OpenSSL code has to detect that error and save its state in such a way that it can be reattempted later. Currently it does not do that, and doing so is non-trivial. For similar reasons the beast websocket code would require significant rewriting to work in non-blocking mode.

**Comment by mstanichenko** [comment]
Dear @vinniefalco, thank you very much for your explanation.

I am not sure that this will be implemented soon but may be at some point if more people want this functionality...

Do you want me to close this issue? Or you prefer to keep it opened as a `feature request`?

**Comment by vinniefalco** [comment]
There's already an issue open for this: https://github.com/boostorg/beast/issues/445

**Comment by mstanichenko** [comment]
I am not that close familiar with `boost` internals (yet) but is that really the case that using `async_read` with `null_buffers` will not spawn another user/kernel thread in the background?

**Comment by vinniefalco** [comment]
it should not spawn another thread

**Comment by mstanichenko** [comment]
Thank you very much @vinniefalco, I am closing this now as a duplicate of #445 
For subsequent queries, a separate issue will be opened.

**Comment by TechnikEmpire** [comment]
What about the underlying socket and the :: available() member method? Also, possibly could use a peek read on the underlying socket? I don't think the latter will interfere with the SSL stream object as the peek flag leaves the bytes untouched on the socket. Not 100 percent sure if that is guaranteed state-independent though.

Here's an example of passing a zero-length buffer to the async read method, which forces immediate completion. Inside the handler, calling :: available () on the underlying socket (choose layer ie. next_layer or lowest_layer properly) where the result of ::available () should return the total number of bytes that can be read in a non-blocking fashion.

Anyway it's almost 5 am and I've been armchair-commenting on your tickets so hopefully I'm not misunderstanding.

**Comment by TechnikEmpire** [comment]
I'm going to have to actually sit down and try building some beast samples. So far I've just been watching so I'm talking from a place of ignorance. I'll get familiar and come back to this.

When you say that SSL stream perform both read and write, can you clarify the meaning and implication? I've seen that reference in other tickets and I'm trying to understand that.

**Comment by vinniefalco** [comment]
> When you say that SSL stream perform both read and write, can you clarify the meaning and implication? 

Sure. An SSL **read** operation will perform reads, but it can also perform a write, as part of the session bookkeeping required by SSL. For example when the local peer does a read, the remote host can request a re-keying. In that case the local peer has to send a nonce. The same goes for SSL **write** operations, sometimes they need to perform reads.

`beast::websocket::stream` functions similarly. For example, when beast tries to read a message from the websocket stream, and it receives a ping frame from the remote host, the implementation will automatically respond with a pong. This of course requires performing a **write**. As you can imagine, if the caller also has a write operation pending, beast has to do some rather complex juggling in its composed operations to make it all work (this is one of the cool features of the library).

**Comment by TechnikEmpire** [comment]
@vinniefalco Thanks for clarifying, makes sense now.
