### ISSUE TITLE
basic_fields class does not check if Allocator supplies fancy pointers

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#896]
basic_fields should contain a static_assert to see if the supplied Allocator uses standard pointer types, because it is likely to break for fancy pointers.

**Comment by vinniefalco** [comment]
`std::is_pointer<typename std::allocator_traits<A>::pointer_type>::value`?

**Comment by djarek** [comment]
Should work (A must be the rebound allocator).

**Comment by vinniefalco** [comment]
What about for all the other classes that use allocators? For example `basic_multi_buffer`?
