### ISSUE TITLE
Assertion failed in websocket/impl/write.ipp line 468

### ISSUE THREAD

**Issue by nguoithichkhampha** [boostorg/beast#904]
### Version of Beast 79
Sometimes I get Assertion failed in websocket/impl/write.ipp line 468
Can you explain some cases make assert failed in this code ? 
Thanks.

**Comment by vinniefalco** [comment]
Yes, there was a bug that got fixed in a later version. Please use version 124:
https://github.com/boostorg/beast/tree/v124

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by vinniefalco** [comment]
It seems this is resolved in the newer version of Beast, so I'll go ahead and close this. If the problem persists feel free to open a new issue, thanks!
