### ISSUE TITLE
Fields can support allocators with fancy pointers

### ISSUE THREAD

**Issue by glenfe** [boostorg/beast#914]
Instead of:
> `static_assert(std::is_pointer<typename std::allocator_traits<Allocator>::pointer>::value, "Allocator must use regular pointers");`

You could:
> `using allocator_type = typename std::conditional<std::is_pointer<typename std::allocator_traits<Allocator>::pointer>::value, Allocator, boost::alignment::aligned_allocator_adaptor<Allocator> >::type;`

Then all those allocators with fancy pointers (like `offset_ptr`) should just work.

**Comment by vinniefalco** [comment]
This needs to be a pull request. And to be legit, it also needs to be added to the unit test or else how will we know if it works? And I'm not sure I want to add the dependency on Boost.Align.

**Comment by vinniefalco** [comment]
When a user complains then we'll implement it
