### ISSUE TITLE
Separate poll() series for handshake and write to perform async ssl request

### ISSUE THREAD

**Issue by nupagadi** [boostorg/beast#926]
I try to use separate `poll()` series for handshake and write to perform async ssl request. As a result a I have successful handshake, then I send data (I can see it via sniffer) and receive no response. Hence, session::on_write isn't called and due to IsInProgress I get an infinite loop.

To make it clearer I simulated the problem at the beast example of async ssl client.
Here is a commit of a branch from v124 
https://github.com/nupagadi/beast/commit/9b6654eff93cecaa69f5ade831660618e0fc4000

What do I do wrong? And how can I perform this?

Thank you!

**Comment by vinniefalco** [comment]
Does the example program work for you without your changes?

**Comment by nupagadi** [comment]
Yes, it works perfectly well.

**Comment by vinniefalco** [comment]
I'm not sure why it doesn't work for you. At first glance, it seems that your code should work. What about if you try this with a regular connection (i.e. no SSL)? Using **http_client_async**?

**Comment by nupagadi** [comment]
It doesn't: 7d8890b6202045faef4be11f3e1cf4d9533ae336
Did you check if it works for you?

**Comment by djarek** [comment]
You should be using `run_one` (or `run()` with a timer) instead of looping), because you're going to take up 100% CPU time doing absolutely nothing, other than bashing against mutexes and atomics within asio.

**Comment by nupagadi** [comment]
That's what I try to simulate here. Busy-wait concept. In the real application there are different objects being "polled" in some way one by one in the single loop.

**Comment by vinniefalco** [comment]
Which Boost.Asio version are you using?

**Comment by nupagadi** [comment]
1.10.8

**Comment by vinniefalco** [comment]
Is that Boost 1.65.1?

**Comment by nupagadi** [comment]
No. Should I obligatory use 1.65.1? 

> To use Boost 1.65.1 and **earlier** with Beast it is necessary to use Beast version 124

**Comment by vinniefalco** [comment]
I'm just collecting information to see if we can figure out why it is not working.

**Comment by vinniefalco** [comment]
Where is this commit? https://github.com/boostorg/beast/commit/7d8890b6202045faef4be11f3e1cf4d9533ae336 Is it in the boostorg/beast repository? Because I can't find it there, and how would you put it there if you have no write access? Which repository contains this commit?

**Comment by nupagadi** [comment]
I forked the official one:
https://github.com/nupagadi/beast/commit/7d8890b6202045faef4be11f3e1cf4d9533ae336

**Comment by nupagadi** [comment]
I'm using 1.63 boost.

**Comment by vinniefalco** [comment]
> nupagadi/beast@7d8890b

*http_client_async* works for me. This was the command line I used:

```
C:\http-client-async www.example.com 80 /index.html
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=604800
Content-Type: text/html
Date: Mon, 11 Dec 2017 15:17:48 GMT
Etag: "359670651"
Expires: Mon, 18 Dec 2017 15:17:48 GMT
Last-Modified: Fri, 09 Aug 2013 23:54:35 GMT
Server: ECS (oxr/83C0)
Vary: Accept-Encoding
X-Cache: HIT
Content-Length: 1270

<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 50px;
        background-color: #fff;
        border-radius: 1em;
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        body {
            background-color: #fff;
        }
        div {
            width: auto;
            margin: 0 auto;
            border-radius: 0;
            padding: 1em;
        }
    }
    </style>
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is established to be used for illustrative examples in documents. You may use this
    domain in examples without prior coordination or asking for permission.</p>
    <p><a href="http://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
```

**Comment by nupagadi** [comment]
You use Windows. May be that is the case?

**Comment by vinniefalco** [comment]
>Which host, port, and target are you using when you invoke the program?

**Comment by nupagadi** [comment]
I tried "example.com 80 /index.html", but no luck.
Btw, I see site response in the sniffer.

**Comment by vinniefalco** [comment]
I'm not sure why it isn't working for you. I doubt it is a problem with Beast though...

**Comment by nupagadi** [comment]
Are absolutely sure it's not an OS-dependent issue?

**Comment by vinniefalco** [comment]
It could be OS-dependent, but Beast contains almost no platform-specific code so it would have to be a bug in Boost.Asio.

**Comment by nupagadi** [comment]
Ok, thank you for your help. You can close the issue, if you want, or I will post a solution or at least the reason later if I manage to find one.

**Comment by vinniefalco** [comment]
Lets leave it open for a little while in case we find out more information. If you could diagnose it, that would be helpful. Does it happen on OS X?

**Comment by nupagadi** [comment]
I don't know. I'm going to check boost 1.65.1 and then may be Windows build.

**Comment by nupagadi** [comment]
Boost 1.65.1 didn't help. My colleagues have the same issue, by the way.

**Comment by nupagadi** [comment]
My apologies, I just used it in the wrong way. It seems one should call `reset()` on `io_service` object after each "`poll()` series". So it was quite strange it worked for you, @vinniefalco.

**Comment by vinniefalco** [comment]
>So it was quite strange it worked for you

Probably because on Windows the operations complete in a single cycle of the reactor. Glad that this got sorted for you!

**Comment by nupagadi** [comment]
Thank you!
