### ISSUE TITLE
Repeated calls to an HTTPS URL.

### ISSUE THREAD

**Issue by cogle** [boostorg/beast#927]
Hello Vinnie I have followed your example code for the [http_client_async_ssl](https://github.com/boostorg/beast/blob/develop/example/http/client/async-ssl/http_client_async_ssl.cpp) and am able to get it to work well. I have a question with regard on how to correctly modify this code to make repeated calls to the same HTTPS url and endpoint. Currently in my code I have something like
```
void HTTPSClient::OnRead(boost::system::error_code ec, std::size_t bytes_transferred, std::shared_ptr<HTTPSQueryStruct> query)
{
  boost::ignore_unused(bytes_transferred);

  if (ec)
    return ::fail(ec, "read");

  // Write the message to standard out
  std::cout << query->res.body() << std::endl;

  //Default Connection Info is a shared_ptr that is stored in the class where host Url is the desired 
  //endpoint and port is 443.
  _resolver.async_resolve(_default_connection_info->host_url.c_str(), _default_connection_info->Port(),
                          std::bind(&HTTPSClient::OnResolve, shared_from_this(),
                                    std::placeholders::_1, std::placeholders::_2, query));
}
```
I am wondering if this is the most performant way to do this I had initially tried replacing the last line in the above code with

```
  http::async_write(query->stream, query->req,
                    std::bind(&HTTPSClient::OnWrite, shared_from_this(), std::placeholders::_2, 
                     std::placeholders::_2, query));
```

However, it seems as if the endpoint would close the connection on me. The majority of my code is the same as yours and wondering what the best practices while simultaneously maintaining good performance for making repeated calls to the same URL(the endpoint is the same too). 

Here is my HTTPSQueryStruct.

```
  struct HTTPSQueryStruct
  {
    HTTPSQueryStruct(std::shared_ptr<boost::asio::io_context> ioc, ssl::context & c) :
                     stream(*ioc, c)
    {
      running.exchange(true, std::memory_order_relaxed);
    }

    std::atomic_bool running;    

    ssl::stream<tcp::socket> stream;
    boost::beast::flat_buffer buffer; 
    http::request<http::empty_body> req;
    http::response<http::string_body> res;
  };
```

In addition the `boost::asio::io_context` is kept running with the following so I am certain that the `boost::asio::io_context` is running for the longevity of the program even if there is no immediate work.
```
_io_context = _init_info->io_context_ptr;
_work_context = std::make_unique<boost::asio::executor_work_guard<boost::asio::io_context::executor_type>>(boost::asio::make_work_guard(*_io_context));
```

Edit: Protocol is  HTTPS/1.1

**Comment by vinniefalco** [comment]
If you want to issue more than one request on the same connection just send another request and then read the response. This is the "keep-alive" mechanism of HTTP/1.1 and it is on by default. If you get a response from the remote host which indicates the connection will be closed after the response is sent there's nothing you do. You can detect this condition by inspecting the return value from a call to `message::keep_alive` on the response object.

**Comment by cogle** [comment]
Ok, cool thanks. Just to clarify when you say 

> send another request

 you mean just simply after everything is read in the `OnRead` just have a call to 
```
http::async_write(query->stream, query->req,
                    std::bind(&HTTPSClient::OnWrite, shared_from_this(), std::placeholders::_1, std::placeholders::_2, query));
```

Which will then resend the request that I desire, as long as the `message::keep_alive`  field is true?

**Comment by vinniefalco** [comment]
Yes. You will need to adjust the `query->req` to reflect the new request. Fields are not automatically cleared after sending. You can use a `boost::optional` for that:
```
boost::optional<http::message<http::string_body>> req;
```
Then call `req.emplace()` to create a new, empty message

**Comment by cogle** [comment]
Will close this once I can get home and try this solution out. 
Thanks for your help.

**Comment by vinniefalco** [comment]
Did it work?

**Comment by cogle** [comment]
Yes it did! Thanks for your help. If you have any minor issues that you think a starter could pick up and work on do not hesitate to ask I would gladly try and help.

**Comment by d3roch4** [comment]
Dont work for me!
Erro: read: end of stream

**Comment by vinniefalco** [comment]
> end of stream

This means that the remote peer closed the connection normally:

https://www.boost.org/doc/libs/1_68_0/libs/beast/doc/html/beast/ref/boost__beast__http__error.html
_"This error is returned when attempting to read HTTP data, and the stream returns the error boost::asio::error::eof before any octets corresponding to a new HTTP message have been received."_

**Comment by d3roch4** [comment]
So I do not know how to solve!

How can I make this check if I can read it?

Call `ioc.reset()` after `ioc.run()` is correct?

**Comment by vinniefalco** [comment]
```
void fail(boost::system::error_code ec, char const* what)
{
    if(ec == boost::beast::http::error::end_of_stream)
        return;
    ...
```

**Comment by d3roch4** [comment]
now on the third call the error is:
write: Broken pipe

but if I always call the `connect` before all the requests always work. Is it necessary to reset the buffer, parser, io_context, or socket between each request?

**Comment by vinniefalco** [comment]
Yes, you have to reset the parser. The easiest way to do that is to store it in a `boost::optional` or `std::optional` and call `emplace` on it each time you want a new one.

**Comment by jayden717** [comment]
> Yes, you have to reset the parser. The easiest way to do that is to store it in a `boost::optional` or `std::optional` and call `emplace` on it each time you want a new one.

hi vinniefalco，i has the same problem, can you show me the code how to do that for d3roch4's demo code? thanks!

**Comment by mitsubishirgb** [comment]
i am trying to make multiple http requests through a single tcp connection using multiple coroutines for each request function which i can write successfully i also configured the (keep-alive) header. tcp is good i checked it from wireshark but for some reason the program stops after receiving the first http response from the server :

`#pragma once

#include <boost/asio.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <boost/beast/ssl.hpp>
#include <boost/beast/version.hpp>
#include <boost/asio/awaitable.hpp>
#include <boost/asio/use_awaitable.hpp>
#include <iostream>
#include <atomic>

using boost::asio::ip::tcp;
namespace asio = boost::asio;
namespace beast = boost::beast;
namespace http = beast::http;

void fail(boost::system::error_code ec, char const* what) {
    if (ec == http::error::end_of_stream) {
        std::cerr << "End of stream" << std::endl;
        return;
    }
    std::cerr << what << ": " << ec.message() << "\n";
}

class HttpClient {
public:
    static std::atomic<size_t> success_count;
    static asio::ssl::context ssl_context;

    HttpClient(asio::io_context& io_context, const std::string& host, const std::string& port)
        : io_context(io_context), resolver(io_context), host(host), port(port) {}

    void set_request(const http::request<http::string_body>& req) {
        this->req = req;
    }

    asio::awaitable<void> request(asio::ssl::stream<tcp::socket>& socket) {
        boost::system::error_code ec;
        co_await send_request(ec, socket);
        if (ec) {
            fail(ec, "send_request");
            co_return;
        }
        co_await receive_response(ec, socket);
        if (ec) {
            fail(ec, "receive_response");
            co_return;
        }
        co_return;
    }

    static asio::ssl::stream<tcp::socket> session(asio::io_context& io_context, const std::string& host, const std::string& port) {
        tcp::resolver resolver(io_context);
        asio::ssl::context ssl_context{ asio::ssl::context_base::sslv23 };
        asio::ssl::stream<tcp::socket> socket(io_context, ssl_context);
        auto endpoints = resolver.resolve(host, port);
        std::cout << "Connecting" << std::endl;
        asio::connect(socket.lowest_layer(), endpoints);
        std::cout << "Handshaking" << std::endl;
        socket.handshake(asio::ssl::stream_base::client);
        return socket;
    }

private:
    asio::awaitable<void> send_request(boost::system::error_code& ec, asio::ssl::stream<tcp::socket>& socket) {
        std::cout << "Writing" << std::endl;
        co_await http::async_write(socket, req, asio::redirect_error(asio::use_awaitable, ec));
    }

    asio::awaitable<void> receive_response(boost::system::error_code& ec, asio::ssl::stream<tcp::socket>& socket) {
        beast::flat_buffer buffer;
        http::response<http::string_body> res;
        std::cout << "Reading response" << std::endl;
        co_await http::async_read(socket, buffer, res, asio::redirect_error(asio::use_awaitable, ec));
        if (!ec) {
            std::cout << (socket.lowest_layer().is_open() ? "Socket is open after reading" : "Socket is closed after reading") << std::endl;
            if (res.result() == http::status::ok) {
                ++success_count;
                std::cout << "Response: " << res.body() << std::endl;
            }
            else {
                std::cerr << "Response returned with status code: " << res.result_int() << '\n';
            }
        }
    }

    asio::io_context& io_context;
    tcp::resolver resolver;
    const std::string& host;
    const std::string& port;
    http::request<http::string_body> req;
};
std::atomic<size_t> HttpClient::success_count{ 0 };`

**Comment by mitsubishirgb** [comment]
source file :
`#include <boost/asio.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <boost/beast/ssl.hpp>
#include <boost/beast/version.hpp>
#include <boost/asio/awaitable.hpp>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/detached.hpp>
#include <boost/asio/use_awaitable.hpp>
#include <boost/asio/spawn.hpp>
#include <iostream>
#include <string>
#include "HttpClient.hpp"

using boost::asio::ip::tcp;
namespace asio = boost::asio;
namespace beast = boost::beast;
namespace http = beast::http;

int main() {
    try {
        const std::string host = "httpbin.org";
        const std::string port = "443"; // HTTPS port
        const std::string target = "/ip";
        const size_t num_requests = 5;

        asio::io_context io_context;

        http::request<http::string_body> req{ http::verb::get, target, 11 };
        req.set(http::field::host, host);
        req.set(http::field::user_agent, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36");
        req.set(http::field::connection, "keep-alive");

        HttpClient client(io_context, host, port);
        client.set_request(req);
        auto socket = HttpClient::session(io_context, host, port);

        for (size_t i = 0; i < num_requests; ++i) {
            asio::co_spawn(io_context, client.request(socket), asio::detached);
        }

        io_context.run();
        std::cout << "Number of successful requests: " << HttpClient::success_count.load() << std::endl;
    }
    catch (const std::exception& e) {
        std::cerr << "Main error: " << e.what() << std::endl;
        return 1;
    }
    return 0;
}`

**Comment by ashtum** [comment]
@mitsubishirgb, you can't call `http::async_write` before the previous call finishes.

Here you are launching multiple concurrent coroutines, with each one trying to call `http::async_write`:
```C++
    for (size_t i = 0; i < num_requests; ++i) {
        asio::co_spawn(io_context, client.request(socket), asio::detached);
    }
```
You must wait until the current `http::async_write` operation completes before initiating another one.

**Comment by mitsubishirgb** [comment]
> @mitsubishirgb, you can't call `http::async_write` before the previous call finishes.
> 
> Here you are launching multiple concurrent coroutines, with each one trying to call `http::async_write`:
> 
> ```c++
>     for (size_t i = 0; i < num_requests; ++i) {
>         asio::co_spawn(io_context, client.request(socket), asio::detached);
>     }
> ```
> 
> You must wait until the current `http::async_write` operation completes before initiating another one.

oh my bad i guess , this worked when i created tcp for each async_write now it makes sense thanks
