### ISSUE TITLE
How to operate the multibuffer?

### ISSUE THREAD

**Issue by lls2wow** [boostorg/beast#936]
Hi @Vinnei Falco,

     I wondered how could I clear the multi buffer in the example websocket-async.cpp . I modified the code based on mine implementation. I read data from server to multi_buffer many times.  I am analog I received the data first  time was  "aaaa",  and second time I received data was "bbbb".

I convert these data to string .
		stringstream ss;
		ss << buffers(buf.data());
        std::string strData = ss.str();
        std::cout<< strData << endl;

First print is   aaaa  .  That`s OK

Second print  is aaaabbbb.  That`s  unexpected.
What I mean, I want to know how to clear the multibuffer after received a data .  Or how to clear the multi buffer data before next async read?  I can`t find the function like clear or other function to do this.

Best regards, 
Lv Linsong

**Comment by vinniefalco** [comment]
```
beast::websocket::stream<boost::asio::ip::tcp::socket> ws{ioc};
...
beast::multi_buffer b;
ws.read(b);
std::cout << beast::buffers_to_string(b.data()) << std::endl;

// Clear the buffer
b.consume(b.size());
```

If you want to get a `std::string`, and you are using the latest Asio (from the boostorg/asio master branch) you can use `boost::asio::dynamic_buffer` to wrap a `std::string` and pass that instead:

```
beast::websocket::stream<boost::asio::ip::tcp::socket> ws{ioc};
...
std::string s;
auto b = boost::asio::dynamic_buffer(s);
ws.read(b);
std::cout << s << std::endl;

// Clear the string
s.clear();
```

**Comment by lls2wow** [comment]
@Vinniefalco,  You are very kind , It works . Thank you very much.

**Comment by vinniefalco** [comment]
Glad to help!

**Comment by vinniefalco** [comment]
It looks like this has been resolved so I'll go ahead and close the issue. If you feel that more explanation is needed feel free to re-open it, or to create a new one - thanks!

**Comment by vinniefalco** [comment]
If `buffer_` is `boost::beast::flat_buffer` then you can write `boost::beast::buffers_front(buffer_).data()` to get a pointer, and `boost::beast::buffers_front(buffer_).size()` to get the size:
https://www.boost.org/doc/libs/1_68_0/libs/beast/doc/html/beast/ref/boost__beast__buffers_front.html

**Comment by Parean** [comment]
@vinniefalco Could you please tell, how can I use the dynamic_string_buffer to read into it several times? 

```
beast::websocket::stream<boost::asio::ip::tcp::socket> ws{ioc};
...
std::string s;
auto b = boost::asio::dynamic_buffer(s);
ws.read(b);
std::cout << s << std::endl;

// Clear the string
s.clear();
```
In this example, If I call s.clear(), the next time I read, the s.size returns 0, although s.data() returns actual data.

**Comment by vinniefalco** [comment]
asio's dynamic buffers dont' work with beast yet.

**Comment by Parean** [comment]
I don't quite understand what it means "they don't work".  Now there is no way to read to the buffer more than once, do you mean this?

**Comment by vinniefalco** [comment]
Yes

**Comment by vinniefalco** [comment]
See:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1100r0.html
