### ISSUE TITLE
Support for std::reference_wrapper in websocket::stream

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#939]
Should `websocket::stream<std::reference_wrapper<Stream>>` be allowed?

**Comment by vinniefalco** [comment]
Nope. Should `asio::ssl::stream<std::reference_wrapper<asio::ip::tcp::socket>>` be alllowed?

This, however, works:
```
websocket::stream<asio::ip::tcp::socket&> ws{ioc};
```

**Comment by vinniefalco** [comment]
I think this is resolved; feel free to re-open if not, thanks.
