### ISSUE TITLE
Provide convenience alias for public type traits

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#941]
A convenience alias should be provided for public traits, similarly to C++14's or ASIO's traits, example:
```cpp
template<typename T>
using get_lowest_layer_t = typename get_lowest_layer<T>::type
```

**Comment by vinniefalco** [comment]
Which of the other public traits need a similar treatment?

**Comment by djarek** [comment]
Seems that `get_lowest_layer` is the only trait this is applicable to, because C++11 doesn't allow variable templates.

**Comment by vinniefalco** [comment]
We should just change the API of `get_lowest_layer` to be the alias. This would be a breaking change. I doubt anyone will be using this obscure type.
