### ISSUE TITLE
Optional SSL

### ISSUE THREAD

**Issue by eirslett** [boostorg/beast#945]
There are separate examples for plaintext and encrypted protocols, for example the websocket client.
How could you write a program that can work both with and without SSL? Imagine you make a program with a boolean configuration parameter `secure` that can be set to `true` or `false`, or maybe derived from a parsed URL like `ws://...` or `wss://...`.

It looks like the type of the websocket objects are different depending on ssl or not - would you have to duplicate a lot of code to make this work? Or write an abstraction layer on top of them?

**Comment by vinniefalco** [comment]
>would you have to duplicate a lot of code to make this work

No, you just need to implement your logic as a class template or function templates. This is demonstrated in the advanced-flex server example:

http://www.boost.org/doc/libs/master/libs/beast/example/advanced/server-flex/advanced_server_flex.cpp

If you have questions about this example feel free to ask them here

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by eirslett** [comment]
Yes, thanks!
