### ISSUE TITLE
Documentation for server framework example?

### ISSUE THREAD

**Issue by DragonOsman** [boostorg/beast#946]
I'm thinking of learning to use Beast for an app I want to write, but it might take me more time than necessary if I also learned ASIO (since I also need to learn that), so I thought I'd just try to learn the server framework on awesome-cpp.  But I can't find any documentation for it, and it's also only a web server framework.  So there are two things I need to ask:
1. Where's the documentation for that example?
2. Would one of the clients that comes with Beast as an example be good to use with the framework?

Thanks in advance for any help.

**Comment by vinniefalco** [comment]
The server-framework was available in an older version of Beast and is no longer supported or recommended. It has been replaced by a vast array of new, smaller examples. All of the clients and servers in the new examples are suitable for use it just depends on what style you want. Pick one of them that meets your needs:

http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/examples.html

**Comment by DragonOsman** [comment]
Ah, okay, thanks for the info.

**Comment by DragonOsman** [comment]
Where can I find documentation on the examples?  If it's okay to ask.

**Comment by vinniefalco** [comment]
Sure, the examples are loaded with comments throughout. If you find a piece of code in the examples that you don't understand just let me know and I'll add some more comments to it.

**Comment by DragonOsman** [comment]
Alright, thanks.  

So can I just take and use a server and client from the examples in a web app?  Or would it be better to write my own after understanding the examples and Beast itself?

**Comment by vinniefalco** [comment]
The examples are written so that they can be used as a starting point for your client or server application.

**Comment by DragonOsman** [comment]
So that means I can just take and use them as is?  Or does it just mean I can use it to understand how to write my own clients and servers to use in an application?

**Comment by vinniefalco** [comment]
>So that means I can just take and use them as is?

You can make a copy of the source file and use that as a starting point.

**Comment by DragonOsman** [comment]
Alright, thanks.

Now this is probably a noob question, but: what exactly is a flex server or client?  

And lastly, which of the HTTP examples supports both the GET and POST verbs, at least?

**Comment by vinniefalco** [comment]
>this is probably a noob question, but: what exactly is a flex server or client?

No, not a noob question. A "flex server" is my own name for a server which can do plain HTTP or handshake using SSL on the same listening port. There's no "flex client."

>which of the HTTP examples supports both the GET and POST verbs, at least?

All the HTTP client and server examples support "GET" and none of them support "POST." Send or receiving a POST request is no different than handling any other message though, so it should not be difficult to implement. If you have a specific question, I can try to answer it.

**Comment by DragonOsman** [comment]
I'm guessing I could easily extend the example server and client I choose to use to also support POST requests.  If so, I'll just have to learn how to use it well enough for that.

Could you maybe include that into the examples in the next release of Beast, if it's not too much trouble (and hopefully that version will also be in Boost later)?  I think people would want that.

**Comment by vinniefalco** [comment]
I mean how hard is it to add

```
if(req.method() == http::verb::post)
{
    // do something
}
```

To this function?
https://github.com/boostorg/beast/blob/617fc428799bf3684c996d500068dbeacd8f5877/example/advanced/server/advanced_server.cpp#L109

>Could you maybe include that into the examples in the next release of Beast

I don't think that belongs in Beast. First of all how would users test it? You can't just easily force your browser to send a POST request to your server. And if you're sending a POST from a client, to which service will you send it to for testing?

Beast is a low-level library and makes certain assumptions about the level of skill required of users. For example, a knowledge of Boost.Asio is required to use Beast.  POST messages are handled the same way as any other message in Beast, there is nothing magical about them other than that they have a different method (`http::method::post` instead of `http::method::get`). You should not need a specific example of handling POST messages in Beast to understand that.

**Comment by DragonOsman** [comment]
Alright, I got it.  

One more thing, though: I've installed OpenSSL headers and .lib files, but I don't know how to use it for HTTPS.  Does the library take care of it after I #include the headers and link in the library files (and define the macro for detecting OpenSSL support)?

**Comment by vinniefalco** [comment]
>Does the library take care of it

No. If you want HTTP/S support in your application, you need to write code for it. This is demonstrated in the example programs which use SSL:

http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/examples.html

**Comment by DragonOsman** [comment]
Well, yes, but I meant was if I have to do anything else other than writing that code.  I need the certificate, right?  What else do I need to do aside from writing the code?

**Comment by vinniefalco** [comment]
Well you have to secure your server...

**Comment by DragonOsman** [comment]
Okay, I get what I need to do for that.  How do I mark this as solved?

**Comment by vinniefalco** [comment]
Press the "Close" button at the bottom
