### ISSUE TITLE
Better documentation for reading websocket requests

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/beast#948]
The documentation for websocket should title this section "Inspecting the Upgrade Request" and include specific language explaining how the user may retrieve and inspect the HTTP upgrade message:

http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/using_websocket/handshaking_servers.html#beast.using_websocket.handshaking_servers.passing_http_requests

**Comment by ashtum** [comment]
Addressed in https://github.com/boostorg/beast/commit/ab9a4c66e0cae58c7ded86224491545f3197cf5b.
