### ISSUE TITLE
Consider "contiguous_only" customization point for basic_parser

### ISSUE THREAD

**Issue by djarek** [boostorg/beast#961]
There are use-cases where a user exclusively uses DynamicBuffers which produce contiguous buffer sequences. Consider allowing a user to select if they want to allow only contiguous buffer sequences, so that they can achieve lower code size and heap memory usage (by conditionally removing the `buf_` and `buf_len_` members from `basic_parser`).

**Comment by vinniefalco** [comment]
idk man you're talking about saving 8 or 16 bytes in the parser.. there are no heap allocations if the input is already contiguous. I'm having a hard time getting excited about saving 16 bytes.

**Comment by djarek** [comment]
The parser itself has to be heap allocated (at least the one supplied with Beast) because it's not movable. Anyway, this isn't a huge issue, because the savings are marginal.

**Comment by vinniefalco** [comment]
Ah, I see what you mean.

**Comment by vinniefalco** [comment]
One way to do this is make the parser *only* accept a contiguous buffer, then put the buffering logic into the stream algorithms using a utility class. A benefit of this approach is the parser could become independent of Asio headers, which some users want.

**Comment by vinniefalco** [comment]
Parser is going to be refactored and won't allow a non-contiguous buffer.
