### ISSUE TITLE
Documentation for the permessage-deflate extension

### ISSUE THREAD

**Issue by liuaifu** [boostorg/beast#962]
I use boost1.66.0 release develop a websocket server program, the data between client and server is json string, i want to compress it and not find example, is beast support this requirement?

**Comment by vinniefalco** [comment]
Do you mean you want to enable the permessage-deflate extension? Use `stream::set_option` for that:
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/set_option.html

By default, streams operating in the server mode have the extension disabled. You can enable it thusly:
```
permessage_deflate opt;
opt.client_enable = true; // for clients
opt.server_enable = true; // for servers
ws.set_option(opt);
```

The documentation could do a better job explaining this.

**Comment by liuaifu** [comment]
Yes, i want to use permessage-deflate extension. But i run wireshark to check, it seems no effects.
`void Client::run()
{
	// Accept the websocket handshake
	ws_.async_accept(
		boost::asio::bind_executor(
			strand_,
			std::bind(
				&Client::on_accept,
				shared_from_this(),
				std::placeholders::_1)));
}

void Client::on_accept(boost::system::error_code ec)
{
	if (ec) {
		printf("%s: %s\n", __FUNCTION__, ec.message().c_str());
		if (ws_.next_layer().is_open())
			ws_.next_layer().cancel();
		return;
	}

	boost::beast::websocket::permessage_deflate opt;
	opt.client_enable = true; // for clients
	opt.server_enable = true; // for servers
	ws_.set_option(opt);
	
	//...
}`

**Comment by liuaifu** [comment]
I move it to the front of ws_.async_accept, now work correctly.

	boost::beast::websocket::permessage_deflate opt;
	opt.client_enable = true; // for clients
	opt.server_enable = true; // for servers
	ws_.set_option(opt);
	ws_.async_accept(
		boost::asio::bind_executor(
			strand_,
			std::bind(
				&Client::on_accept,
				shared_from_this(),
				std::placeholders::_1)));
	//...

@vinniefalco Thank you.

**Comment by vinniefalco** [comment]
Sorry...yes, you have to set the option before performing the handshake. I'm going to go ahead and keep this issue open as a reminder that I need to update the documentation to make this more clear - thanks!

**Comment by lls2wow** [comment]
So the document of permessage-deflate is closed now? 
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/set_option.html
http://www.boost.org/doc/libs/master/libs/beast/doc/html/beast/ref/boost__beast__websocket__permessage_deflate.html

**Comment by vinniefalco** [comment]
I don't understand the question?

**Comment by hoditohod** [comment]
Hi Vinnie,
Once the handshake is complete (and compression is enabled), is it possible to selectively enable compression on each individual message?

**Comment by vinniefalco** [comment]
Compression cannot be selectively enabled and disabled on individual messages yet.

**Comment by hoditohod** [comment]
Thanks!

**Comment by klemens-morgenstern** [comment]
is this resolved?
