### ISSUE TITLE
HTTP: async client and browser behavior for ssl examples

### ISSUE THREAD

**Issue by TurtleWithWheels156** [boostorg/beast#963]
Hi Vinnie,

I'm new to beast and am looking through the different examples; I appreciate the time that went into it and had a question regarding the async server/client examples that use ssl.  I ran the server and tested a request for an html file with the client and got a response with the header and body; it also looks like the server prints out "shutdown: End of file".  However, going through a browser (e.g. Chrome) and trying to request the same page responds with "... didn’t send any data." with the server printing out "handshake: http request".  

It's not a bug or an issue, rather I am currently getting a grasp of the code and was wondering if you knew what might be causing this behavior, thanks.

**Comment by djarek** [comment]
First guess should in this case be that the browser might not like your self-signed certificate.

**Comment by TurtleWithWheels156** [comment]
Oh okay I'll look into that.  Thanks.
