### ISSUE TITLE
Beast / ASIO / Coroutine2

### ISSUE THREAD

**Issue by rberlich** [boostorg/beast#965]
Hi there,

from what I can see, ASIO Coroutine handling (and hence Beast coroutine handling) is not based on Coroutine 2, and its predecessor has been marked deprecated. 

There is not much information to be found regarding if and when ASIO will move to Coroutine 2. As this will have an impact on Beast, do you have any insight in how far this will change the API of ASIO and Beast ?

Thanks and a Happy New Year,
Beet

**Comment by vinniefalco** [comment]
There should be no impact. Programs which use stackful coroutines will not have to change. The deprecation warning will eventually be dealt with in a manner that is transparent.

**Comment by rberlich** [comment]
Thanks a lot!
