### ISSUE TITLE
Question: cancelling a websocket underlying socket a good idea?

### ISSUE THREAD

**Issue by hoditohod** [boostorg/beast#966]
Hi Vinnie, 
This is a just a question not an issue. I have a websocket server where async reads and writes on the socket are concurrently in progress (at most one of each type as the documentation states). When I receive an error in the read handler for example, for some error cases I want to abruptly terminate the websocket session. Is it a good idea to kill the other handler with socket.next_layer().cancel(). Or is there any better way to cancel an async op on a websocket stream which I want to terminate as quickly as possible?

Thanks!

**Comment by vinniefalco** [comment]
`cancel` is what you want

**Comment by hoditohod** [comment]
Dumb question: you mean the next_layer().cancel() on the websocket::stream, right? Because I don't see cancel() on the websocket::stream itself.

**Comment by vinniefalco** [comment]
Correct

**Comment by hoditohod** [comment]
Thank you!

Beast is awesome, keep up the good work! :)
