### ISSUE TITLE
Resetting a parser?

### ISSUE THREAD

**Issue by chrisics** [boostorg/beast#971]
When a server is done processing a request, it wants to parse a new request from the socket. 

We need to provide a new parser for each new request. In asynchronous mode, that means allocating heap memory. 
It would be more convenient to re-use a parser as a member variable and reset it state for new read operation. 

Or did I miss something? Thank you.

    void do_read()
    {
        // Read a new request
        **parser_.reset();**  
 
        http::async_read_header(stream_, buf_, parser_,
                            boost::asio::bind_executor(strand_,
                                                       std::bind(&session::on_read_header,
                                                                 this,
                                                                 std::placeholders::_1,
                                                                 std::placeholders::_2)));
    }

**Comment by vinniefalco** [comment]
Adding `parser::reset` would place unnecessary burdens on the **BodyReader** concept. 

The solution is to store the parser in a `boost::optional` and recreate it using `optional::emplace`.

**Comment by jeremiahar** [comment]
Another option is to manually call the destructor and use placement new. This avoids the overhead of optional when you don't really need it.

```c++
using T = boost::beast::http::request_parser<boost::beast::http::empty_body>;
m_Parser.~T();
new (&m_Parser) T();
```

**Comment by vinniefalco** [comment]
there's no overhead to optional...

**Comment by jeremiahar** [comment]
I was referring to the penalty to the sizeof optional<T> vs T. There has to be at least one extra bool of state to determine whether the T needs to be destructed or not. This can be as high as 8 bytes due to padding (you can check sizeof(void*) vs sizeof(std::optional<void*>).

**Comment by vinniefalco** [comment]
yeah that's true

**Comment by steve-numeus** [comment]
If I am using a `response_parser` with a `string_body`, even if I use an `optional`, it will still heap allocate for the string body, correct?

```c++
beast::flat_buffer _read_buf;
std::optional<http::response_parser<http::string_body>> _parser;
```

In my read function:

```c++
_parser.emplace();
_parser->body_limit(std::numeric_limits<std::size_t>::max());

http::async_read(_stream, _read_buf, *_parser, _read_cb);
```

I will read the entire response in the callback, and therefore on the next read I can reuse whatever internal buffers etc have been allocated in the previous read.

What is the most efficient way to do this, and avoid heap allocations during the read operation (or at least, for reads the same size or smaller than the largest read this far)?

Perhaps a different body type, or a way to pass a buffer to the parser?

**Comment by Spongman** [comment]
also...
```
	std::destroy_at(&parser_);	// c++17
	std::construct_at(&parser_);	// c++20
```
