### ISSUE TITLE
need_eof() bogus?

### ISSUE THREAD

**Issue by chrisics** [boostorg/beast#972]
The implemention for need_eof() seems bogus:
http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/ref/boost__beast__http__message/need_eof.html

A POST should return status 201 Created, and keep the connection open if requested, should it not?  

See https://tools.ietf.org/html/rfc7230#section-6.3

Br,
Chris.

**Comment by vinniefalco** [comment]
From https://tools.ietf.org/html/rfc7230#section-3.3

*"All 1xx (Informational), 204 (No Content), and 304 (Not Modified) responses do not include a message body.  **All other responses do include a message body, although the body might be of zero length.**"*

I believe the server is required to send "Content-Length: 0" when it sends a 201 status response to a POST request.

**Comment by chrisics** [comment]
all right, Thanks.

**Comment by vinniefalco** [comment]
Let's not be too hasty in closing this, I've asked a few questions on StackOverflow to verify

**Comment by vinniefalco** [comment]
Okay, I am convinced that in the absence of "Content-Length: 0" an **eof** is needed.

This implementation always sends "Content-Length: 0" for 201 status responses lacking an entity body:

https://github.com/square/retrofit/issues/1721
