### ISSUE TITLE
terminate called after throwing an instance of 'std::invalid_argument' for http-sync-ssl

### ISSUE THREAD

**Issue by erosh** [boostorg/beast#973]
Hi.
Thank you very much for you great job!

Is it a way to handle such exception?
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  invalid file descriptor: -1
```

It can be easily reproduced by running http_client_sync_ssl.cpp
with wrong(not valid) host value. And this exception unfortunately is not caught.

**Comment by vinniefalco** [comment]
What is the exact command line you are using to invoke the program?

**Comment by erosh** [comment]
Hm. Sorry. I figured out that I had another exception in my code during stack unwinding.
