### ISSUE TITLE
"Stale" warning

### ISSUE THREAD

**Issue by rberlich** [boostorg/beast#974]
Hi there, 

just noted the warning regarding compatibility between current Beast-releases and Boost.ASIO here on Github. It says: 

"This situation is temporary until Boost 1.66.0 is released, where Beast and Asio will work correctly with each other within the monolithic Boost release."

As 1.66 is there, this warning could be amended to something along the lines of "Note that, in order to use current versions of Boost.Beast, you need at least Boost version 1.66 ."

Best Regards,
Beet

**Comment by vinniefalco** [comment]
Ah yes, thanks for pointing that out I will update that right away. It should be fixed in version 153.
