### ISSUE TITLE
gcc warns about const type qualifiers ignored on function return type

### ISSUE THREAD

**Issue by chrisics** [boostorg/beast#981]
In fields.ipp, line 294 and fields.hpp, line 96:  

for instance:
field const name()  

Const does not have an effect on a primitive type as return value. See https://stackoverflow.com/questions/40689158/why-type-qualifiers-ignored-on-function-return-type-only-in-case-of-primitives

**Comment by vinniefalco** [comment]
This is fixed in the tip of develop and master - thanks!
https://github.com/boostorg/beast/blob/develop/include/boost/beast/http/fields.hpp#L104
