### ISSUE TITLE
file_mode::write_new fails on windows

### ISSUE THREAD

**Issue by chrisics** [boostorg/beast#982]
Due to what seems to be compliance issue of the standard c library of Microsoft, 
The call open() of file_stdio, with file_mode "write_new" translates to a call to 

std::fopen (file_name, "wbx");

And this fails with "invalid argument passed to c-function". 

The "x" is not supported: See https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx

(Beast version 144)

**Comment by vinniefalco** [comment]
Can you please submit a pull request with a fix?

**Comment by vinniefalco** [comment]
This should be fixed now
