### ISSUE TITLE
How to set the websocket`s header parameter?

### ISSUE THREAD

**Issue by lls2wow** [boostorg/beast#991]
Hi @vinniefalco ,

      Would you kind tell me how to set  the websocket`s header parameter?

      Like 'headers.put("User-Agent", "Mozilla/5.0 (iPhone; CPU iPhon….0 Mobile/14E304 Safari/602.1");'

**Comment by vinniefalco** [comment]
You want a "request decorator." This is explained here:
http://www.boost.org/doc/libs/1_66_0/libs/beast/doc/html/beast/using_websocket/handshaking_clients.html#beast.using_websocket.handshaking_clients.decorators

**Comment by vinniefalco** [comment]
Has this issue been resolved?

**Comment by lls2wow** [comment]
Yes, Thank you it works well ,sorry to respond lately.@vinniefalco

**Comment by vinniefalco** [comment]
No problem at all, glad it worked for you! I'll go ahead and close this issue now. Feel free to open new ones if you need to.

**Comment by lls2wow** [comment]
This code works OK , but async_handshake_ex can`t compile.

```
	ws_.async_handshake(host, target,
		std::bind(
			&ssl_wssession::on_handshake,
			shared_from_this(),
			std::placeholders::_1));
```

**Comment by vinniefalco** [comment]
Maybe you could please post the compile error?

**Comment by bernardlawes** [comment]
Vinnie, thank you for the great work and documentation.  I have a question about the decorators.  I understand how to handle the other fields like: 
{
   m.insert(http::field::host, my.coolhost.io);
}

But, how would I modify the "GET" field? For example, I want to change 
GET / HTTP/1.1 to ----->  GET /notifier/ws/mesage-received HTTP/1.1

Sorry if this is rudimentary.  I'm a complete noob to all of this.

**Comment by bernardlawes** [comment]
Hi Vinne Falco, sorry if the rudimentary question..   But I am a noob on this.

In your example for using decorators: 
**ws.handshake_ex("localhost", "/",
    [](request_type& m)
    {
        m.insert(http::field::sec_websocket_protocol, "xmpp;ws-chat");
    });**

I am receiving the errors during compile:
(1) syntax error: identifier 'request_type'
(2) 'req' cannot be implicitly captured because no default capture mode has been specified

Do you have a full example of connecting to a websocket after having modified the websocket header parameter?

**Comment by vinniefalco** [comment]
You need to use the correct namespace to access the type: `boost::beast::websocket::request_type`. This is explained in the documentation, and you can see it in the header:
https://github.com/boostorg/beast/blob/develop/include/boost/beast/websocket/stream.hpp#L45

The documentation explains:
_"...Sample code and identifiers appearing in this section is written as if these declarations are in effect:"_
```
#include <boost/beast/websocket.hpp>
using namespace boost::beast::websocket;"
```
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/using_websocket.html

**Comment by bernardlawes** [comment]
Wow! your responsiveness is without reproach.  Thank you..  I'll give it a try and get back to you.

**Comment by bernardlawes** [comment]
Excellent.  It worked.  Thank you..  However, I'm facing another issue...
I want to also include and outside outside parameter in the handshake_ex lambda expression.

		**ws.handshake_ex(wsHost, "/",
			[](request_type& req, std::map<std::string, std::string>& headers)
		{	
			for (auto const &header : headers)
			{
				req.set(header.first, header.second);
				std::cout << header.first << ": " << header.second << std::endl;
			}
		});**

However, in doing so, I receive: **RequestDecorator requirements not me**
