### ISSUE TITLE
SOH in response headers

### ISSUE THREAD

**Issue by RewritableJ** [boostorg/beast#996]
Hello.

When I make request to certain server the response contains some cookie headers. Those headers contain SOH character that is treated as invalid by basic_parser_base causing bad_value error code, though the response is fine.

**Comment by vinniefalco** [comment]
SOH is a control character with the value 0x01? That is an illegal character according to rfc2616 and rfc7230 (the HTTP protocol specifications). If you want to accept such characters as valid HTTP, you need to filter the input before passing it to Beast.
